#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod part_10;
mod part_11;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;
pub use part_08::*;
pub use part_09::*;
pub use part_10::*;
pub use part_11::*;

script_sdk_2::script_module! {
    npcs {
        "#CallGhost" => callghost,
        "#ForeignMerchant1" => foreignmerchant1,
        "#ForeignMerchant2" => foreignmerchant2,
        "#ForeignMerchant3" => foreignmerchant3,
        "#ForeignMerchant4" => foreignmerchant4,
        "#ZGuard" => zguard,
        "#em_end" => em_end,
        "#em_sky_s" => em_sky_s,
        "#treasure" => treasure,
        "#zdan_broad" => zdan_broad,
        "Agent#pc1" => agent_pc1,
        "AideAmi#Aru" => aideami_aru,
        "Archeologist" => archeologist,
        "Belder" => belder,
        "Boat#Aru" => boat_aru,
        "Books#Mona1" => books_mona1,
        "Catfoii" => catfoii,
        "Chief Officer#edq" => chief_officer_edq,
        "Common-Looking Man" => common_looking_man,
        "Creature#Monas" => creature_monas,
        "Dead Crow#Aru" => dead_crow_aru,
        "Dead Man#King" => dead_man_king,
        "Dorian_izlude" => dorian_izlude,
        "Drunkard#Aru" => drunkard_aru,
        "Drunkard#Aru1" => drunkard_aru1,
        "EntranceCheck#1" => entrancecheck_1,
        "EntranceCheck#2" => entrancecheck_2,
        "Event Switch#pc" => event_switch_pc,
        "Female Follower#em" => female_follower_em,
        "Foreign Merchant#aru1" => foreign_merchant_aru1,
        "Foreign Merchant#aru2" => foreign_merchant_aru2,
        "Gooho Ahn" => gooho_ahn,
        "Grass Behind#Aru" => grass_behind_aru,
        "Heap of Earth" => heap_of_earth,
        "Ibrahim" => ibrahim,
        "Inside Island#Aru" => inside_island_aru,
        "Investigator" => investigator,
        "Ishmael#em" => ishmael_em,
        "Jhonnita" => jhonnita,
        "Kimeunbang" => kimeunbang,
        "Larjes#Aru" => larjes_aru,
        "Larjes#Boat1" => larjes_boat1,
        "Larjes#Monastery" => larjes_monastery,
        "Larjes#Monastery2" => larjes_monastery2,
        "Leblo" => leblo,
        "Louis" => louis,
        "Magistrate#Aru" => magistrate_aru,
        "Man from Morocc" => man_from_morocc,
        "Man in Hiding#nd" => man_in_hiding_nd,
        "Man#King" => man_king,
        "Man#zgang" => man_zgang,
        "Martha" => martha,
        "Marybell" => marybell,
        "MealConversation Trigger" => mealconversation_trigger,
        "Moonho Ahn" => moonho_ahn,
        "Muff" => muff,
        "Night#Aru2" => night_aru2,
        "Niren#em_sky" => niren_em_sky,
        "Niren#ss" => niren_ss,
        "Normal-Looking Man" => normal_looking_man,
        "Odd Slab" => odd_slab,
        "Odd Switch#Switch1" => odd_switch_switch1,
        "Odd Switch#Switch2" => odd_switch_switch2,
        "Old Soldier" => old_soldier,
        "Ordinary Man#pc1" => ordinary_man_pc1,
        "Ordinary Man#pc2" => ordinary_man_pc2,
        "Out_from_Monastery" => out_from_monastery,
        "Outside Island#Aru" => outside_island_aru,
        "Pass Out#Aru" => pass_out_aru,
        "Pope#rachel2" => pope_rachel2,
        "Ragged Man#nd" => ragged_man_nd,
        "Rogue Agent" => rogue_agent,
        "Rogue Agent#nd0" => rogue_agent_nd0,
        "Rogue Guild Agent#nd1" => rogue_guild_agent_nd1,
        "Rogue Guild Agent#nd2" => rogue_guild_agent_nd2,
        "Rogue Guild Agent#nd3" => rogue_guild_agent_nd3,
        "Rogue Guild Agent#nd4" => rogue_guild_agent_nd4,
        "Rogue Investigator" => rogue_investigator,
        "Scholar#zgang" => scholar_zgang,
        "Secret Agent#Aru" => secret_agent_aru,
        "Shaman" => shaman,
        "Sippie#ss" => sippie_ss,
        "Small Safe" => small_safe,
        "Soldier#Aru" => soldier_aru,
        "StrangeMachine_izlude" => strangemachine_izlude,
        "Suspicious Man#1" => suspicious_man_1,
        "Suspicious-Looking Man" => suspicious_looking_man,
        "The Wanderer" => the_wanderer,
        "Valdes" => valdes,
        "Waiter#pc" => waiter_pc,
        "Wanted Notice#edq" => wanted_notice_edq,
        "Wola" => wola,
        "Zhed#em_sky" => zhed_em_sky,
        "boss#quests_quests_nameless_1487" => boss,
        "outtoin_01#mo" => outtoin_01_mo,
    }
    events {
        "#CallGhost::OnTouch" => callghost_ontouch,
        "#ForeignMerchant1::OnTouch" => foreignmerchant1_ontouch,
        "#ForeignMerchant2::OnTouch" => foreignmerchant2_ontouch,
        "#ForeignMerchant3::OnTouch" => foreignmerchant3_ontouch,
        "#ForeignMerchant4::OnTouch" => foreignmerchant4_ontouch,
        "#ZGuard::OnDisable" => zguard_ondisable,
        "#ZGuard::OnEnable" => zguard_onenable,
        "#ZGuard::OnInit" => zguard_oninit,
        "#ZGuard::OnMyMobDead" => zguard_onmymobdead,
        "#ZGuard::OnReset" => zguard_onreset,
        "#ZGuard::OnTimer300000" => zguard_ontimer300000,
        "#em_end::OnInit" => em_end_oninit,
        "#em_end::OnTimer10000" => em_end_ontimer10000,
        "#em_end::OnTimer15000" => em_end_ontimer15000,
        "#em_end::OnTimer19000" => em_end_ontimer19000,
        "#em_end::OnTimer23000" => em_end_ontimer23000,
        "#em_end::OnTimer30000" => em_end_ontimer30000,
        "#em_end::OnTimer35000" => em_end_ontimer35000,
        "#em_end::OnTimer4000" => em_end_ontimer4000,
        "#em_end::OnTimer43000" => em_end_ontimer43000,
        "#em_end::OnTimer47000" => em_end_ontimer47000,
        "#em_end::OnTimer53000" => em_end_ontimer53000,
        "#em_end::OnTimer7000" => em_end_ontimer7000,
        "#em_end::OnTouch_" => em_end_ontouch,
        "#em_sky_s::OnTouch" => em_sky_s_ontouch,
        "#zdan_broad::OnDisable" => zdan_broad_ondisable,
        "#zdan_broad::OnEnable" => zdan_broad_onenable,
        "#zdan_broad::OnInit" => zdan_broad_oninit,
        "#zdan_broad::OnTimer11000" => zdan_broad_ontimer11000,
        "#zdan_broad::OnTimer13000" => zdan_broad_ontimer13000,
        "#zdan_broad::OnTimer15000" => zdan_broad_ontimer15000,
        "#zdan_broad::OnTimer18000" => zdan_broad_ontimer18000,
        "#zdan_broad::OnTimer21000" => zdan_broad_ontimer21000,
        "#zdan_broad::OnTimer3000" => zdan_broad_ontimer3000,
        "#zdan_broad::OnTimer300000" => zdan_broad_ontimer300000,
        "#zdan_broad::OnTimer350000" => zdan_broad_ontimer350000,
        "#zdan_broad::OnTimer5000" => zdan_broad_ontimer5000,
        "#zdan_broad::OnTimer7000" => zdan_broad_ontimer7000,
        "#zdan_broad::OnTimer9000" => zdan_broad_ontimer9000,
        "Agent#pc1::OnInit" => agent_pc1_oninit,
        "AideAmi#Aru::OnTouch_" => aideami_aru_ontouch,
        "Belder::OnTouch_" => belder_ontouch,
        "Catfoii::OnInit" => catfoii_oninit,
        "Creature#Monas::OnInit" => creature_monas_oninit,
        "Creature#Monas::OnMyMobDead" => creature_monas_onmymobdead,
        "Creature#Monas::OnTouch" => creature_monas_ontouch,
        "Dead Man#King::OnEnable" => dead_man_king_onenable,
        "Dead Man#King::OnInit" => dead_man_king_oninit,
        "Dead Man#King::OnTimer150000" => dead_man_king_ontimer150000,
        "Dorian_izlude::OnTouch" => dorian_izlude_ontouch,
        "EntranceCheck#1::OnTouch_" => entrancecheck_1_ontouch,
        "EntranceCheck#2::OnTouch_" => entrancecheck_2_ontouch,
        "Event Switch#pc::OnTouch" => event_switch_pc_ontouch,
        "Foreign Merchant#aru1::OnTouch" => foreign_merchant_aru1_ontouch,
        "Foreign Merchant#aru2::OnInit" => foreign_merchant_aru2_oninit,
        "Grass Behind#Aru::OnTouch" => grass_behind_aru_ontouch,
        "Ibrahim::OnTouch" => ibrahim_ontouch,
        "Inside Island#Aru::OnTouch" => inside_island_aru_ontouch,
        "Larjes#Monastery2::OnInit" => larjes_monastery2_oninit,
        "Larjes#Monastery::OnInit" => larjes_monastery_oninit,
        "Louis::OnInit" => louis_oninit,
        "Man#King::OnMyMobDead" => man_king_onmymobdead,
        "Man#King::OnTimer300000" => man_king_ontimer300000,
        "Martha::OnInit" => martha_oninit,
        "MealConversation Trigger::OnTouch" => mealconversation_trigger_ontouch,
        "Night#Aru2::OnTouch" => night_aru2_ontouch,
        "Odd Slab::OnInit" => odd_slab_oninit,
        "Odd Slab::OnTouch" => odd_slab_ontouch,
        "Odd Switch#Switch1::OnInit" => odd_switch_switch1_oninit,
        "Odd Switch#Switch2::OnInit" => odd_switch_switch2_oninit,
        "Out_from_Monastery::OnInit" => out_from_monastery_oninit,
        "Out_from_Monastery::OnTouch" => out_from_monastery_ontouch,
        "Outside Island#Aru::OnTouch" => outside_island_aru_ontouch,
        "Pass Out#Aru::OnTouch" => pass_out_aru_ontouch,
        "Secret Agent#Aru::OnInit" => secret_agent_aru_oninit,
        "Suspicious Man#1::OnInit" => suspicious_man_1_oninit,
        "Suspicious Man#1::OnTimer30000" => suspicious_man_1_ontimer30000,
        "Suspicious Man#1::OnTouch_" => suspicious_man_1_ontouch,
        "The Wanderer::OnEnable" => the_wanderer_onenable,
        "The Wanderer::OnInit" => the_wanderer_oninit,
        "The Wanderer::OnTimer60000" => the_wanderer_ontimer60000,
        "Valdes::OnTouch" => valdes_ontouch,
        "Wanted Notice#edq::OnDisable" => wanted_notice_edq_ondisable,
        "Wanted Notice#edq::OnEnable" => wanted_notice_edq_onenable,
        "Wola::OnTouch" => wola_ontouch,
        "outtoin_01#mo::OnTouch" => outtoin_01_mo_ontouch,
    }
}
