#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;
pub use part_08::*;
pub use part_09::*;

script_sdk_2::script_module! {
    npcs {
        "#DrawerOpener" => draweropener,
        "#Hg_Quest" => hg_quest,
        "#HugelTree" => hugeltree,
        "A Pile of Paper" => a_pile_of_paper,
        "A Spirit#HQuest" => a_spirit_hquest,
        "Alex" => alex,
        "Allen Schuwell" => allen_schuwell,
        "Ashe" => ashe,
        "Ashe#2" => ashe_2,
        "Ashe#3" => ashe_3,
        "Ashe#4" => ashe_4,
        "Ashe#5" => ashe_5,
        "Boatman" => boatman,
        "Boatman#hugel" => boatman_hugel,
        "Bomb Maker" => bomb_maker,
        "Booboo the Cow" => booboo_the_cow,
        "Book" => book,
        "Burupu" => burupu,
        "Burupu's Instructions" => burupu_s_instructions,
        "Cellette Lavit" => cellette_lavit,
        "Clam#C1" => clam_c1,
        "Clam#C2" => clam_c2,
        "Clam#C3" => clam_c3,
        "Clam#C4" => clam_c4,
        "Dono" => dono,
        "El Schatt" => el_schatt,
        "Empty" => empty,
        "Enquro Carson" => enquro_carson,
        "Entrance" => entrance,
        "Erjan" => erjan,
        "Eukran" => eukran,
        "Euslan" => euslan,
        "Girl#Hu" => girl_hu,
        "Girl#hugel" => girl_hugel,
        "Herico" => herico,
        "HiddenActivator#Hugel" => hiddenactivator_hugel,
        "HiddenExplosion" => hiddenexplosion,
        "HiddenHugel" => hiddenhugel,
        "Hit" => hit,
        "HuMSpawner" => humspawner,
        "Julian" => julian,
        "Julian#2" => julian_2,
        "Kurupe" => kurupe,
        "Laura" => laura,
        "Laura#2" => laura_2,
        "Layoma" => layoma,
        "Maewan" => maewan,
        "Makkie" => makkie,
        "Manainne" => manainne,
        "Moks Bugs#Bug1" => moks_bugs_bug1,
        "Moks Bugs#Bug2" => moks_bugs_bug2,
        "Moks Bugs#Bug3" => moks_bugs_bug3,
        "Moks Bugs#Bug4" => moks_bugs_bug4,
        "Moks Mushrooms#Mush1" => moks_mushrooms_mush1,
        "Moks Mushrooms#Mush2" => moks_mushrooms_mush2,
        "Moks Mushrooms#Mush3" => moks_mushrooms_mush3,
        "Morriphen" => morriphen,
        "Neha" => neha,
        "OdinInit" => odininit,
        "Perfitz" => perfitz,
        "Postell Schuwell" => postell_schuwell,
        "Postell Schuwell#D" => postell_schuwell_d,
        "Pub Granny" => pub_granny,
        "Shede" => shede,
        "Sign" => sign,
        "Siria" => siria,
        "Strange Man#Hugel" => strange_man_hugel,
        "Suspicious Barrel" => suspicious_barrel,
        "Torpy" => torpy,
        "Torpy's Mom" => torpy_s_mom,
        "Unethical Machine" => unethical_machine,
        "Upper Drawer#First" => upper_drawer_first,
        "Upper Drawer#Second" => upper_drawer_second,
        "Young Man#Hu_Quest" => young_man_hu_quest,
        "alex#warp" => alex_warp,
        "alex#warp2" => alex_warp2,
        "alex#warp3" => alex_warp3,
        "alex#warp4" => alex_warp4,
        "object#1" => object_1,
        "object#2" => object_2,
        "object#3" => object_3,
        "warpinside#1" => warpinside_1,
        "warpinside#2" => warpinside_2,
        "warpinside#3" => warpinside_3,
        "warpinside#4" => warpinside_4,
        "warpinside#5" => warpinside_5,
    }
    events {
        "#DrawerOpener::OnEnable" => draweropener_onenable,
        "#DrawerOpener::OnInit" => draweropener_oninit,
        "#DrawerOpener::OnTimer1000" => draweropener_ontimer1000,
        "#DrawerOpener::OnTimer4500" => draweropener_ontimer4500,
        "#Hg_Quest::OnTouch" => hg_quest_ontouch,
        "Allen Schuwell::OnTouch_" => allen_schuwell_ontouch,
        "Ashe#3::OnTouch_" => ashe_3_ontouch,
        "Ashe#4::OnTouch_" => ashe_4_ontouch,
        "Ashe#5::OnTouch_" => ashe_5_ontouch,
        "Burupu::OnTouch_" => burupu_ontouch,
        "Clam#C1::OnTimer20000" => clam_c1_ontimer20000,
        "Clam#C2::OnTimer20000" => clam_c2_ontimer20000,
        "Clam#C3::OnTimer20000" => clam_c3_ontimer20000,
        "Clam#C4::OnTimer20000" => clam_c4_ontimer20000,
        "Empty::OnTouch_" => empty_ontouch,
        "Entrance::OnTouch_" => entrance_ontouch,
        "HiddenActivator#Hugel::OnInit" => hiddenactivator_hugel_oninit,
        "HiddenActivator#Hugel::OnTimer180000" => hiddenactivator_hugel_ontimer180000,
        "HiddenActivator#Hugel::OnTouch" => hiddenactivator_hugel_ontouch,
        "HiddenExplosion::OnInit" => hiddenexplosion_oninit,
        "HiddenExplosion::OnTouch" => hiddenexplosion_ontouch,
        "HiddenHugel::OnTouch" => hiddenhugel_ontouch,
        "HuMSpawner::OnMonster" => humspawner_onmonster,
        "HuMSpawner::OnMonsterDead" => humspawner_onmonsterdead,
        "HuMSpawner::OnTimer60000" => humspawner_ontimer60000,
        "Kurupe::OnTouch_" => kurupe_ontouch,
        "Moks Bugs#Bug1::OnTimer20000" => moks_bugs_bug1_ontimer20000,
        "Moks Bugs#Bug2::OnTimer20000" => moks_bugs_bug2_ontimer20000,
        "Moks Bugs#Bug3::OnTimer20000" => moks_bugs_bug3_ontimer20000,
        "Moks Bugs#Bug4::OnTimer20000" => moks_bugs_bug4_ontimer20000,
        "Moks Mushrooms#Mush1::OnTimer20000" => moks_mushrooms_mush1_ontimer20000,
        "Moks Mushrooms#Mush2::OnTimer20000" => moks_mushrooms_mush2_ontimer20000,
        "Moks Mushrooms#Mush3::OnTimer20000" => moks_mushrooms_mush3_ontimer20000,
        "OdinInit::OnInit" => odininit_oninit,
        "OdinInit::OnTimer100000" => odininit_ontimer100000,
        "Postell Schuwell#D::OnEnable" => postell_schuwell_d_onenable,
        "Postell Schuwell#D::OnInit" => postell_schuwell_d_oninit,
        "Postell Schuwell#D::OnTimer100000" => postell_schuwell_d_ontimer100000,
        "Strange Man#Hugel::OnEnable" => strange_man_hugel_onenable,
        "Strange Man#Hugel::OnInit" => strange_man_hugel_oninit,
        "Strange Man#Hugel::OnTimer60000" => strange_man_hugel_ontimer60000,
        "Upper Drawer#First::OnTouch_" => upper_drawer_first_ontouch,
        "Upper Drawer#Second::OnInit" => upper_drawer_second_oninit,
        "Upper Drawer#Second::OnTouch_" => upper_drawer_second_ontouch,
        "alex#warp2::OnTouch_" => alex_warp2_ontouch,
        "alex#warp3::OnTouch_" => alex_warp3_ontouch,
        "alex#warp4::OnTouch_" => alex_warp4_ontouch,
        "alex#warp::OnTouch_" => alex_warp_ontouch,
        "object#1::OnTouch_" => object_1_ontouch,
        "object#2::OnTouch_" => object_2_ontouch,
        "object#3::OnTouch_" => object_3_ontouch,
        "warpinside#1::OnEnter" => warpinside_1_onenter,
        "warpinside#1::OnInit" => warpinside_1_oninit,
        "warpinside#1::OnTouch_" => warpinside_1_ontouch,
        "warpinside#2::OnEnter" => warpinside_2_onenter,
        "warpinside#2::OnInit" => warpinside_2_oninit,
        "warpinside#2::OnTouch_" => warpinside_2_ontouch,
        "warpinside#3::OnEnter" => warpinside_3_onenter,
        "warpinside#3::OnInit" => warpinside_3_oninit,
        "warpinside#3::OnTouch_" => warpinside_3_ontouch,
        "warpinside#4::OnEnter" => warpinside_4_onenter,
        "warpinside#4::OnInit" => warpinside_4_oninit,
        "warpinside#4::OnTouch_" => warpinside_4_ontouch,
        "warpinside#5::OnEnter" => warpinside_5_onenter,
        "warpinside#5::OnInit" => warpinside_5_oninit,
        "warpinside#5::OnTouch_" => warpinside_5_ontouch,
    }
}
