pub mod cool_event_corp;
pub mod dts_warper;
pub mod kafras;

script_sdk_2::script_module! {
    npcs {
        "Cool Event Corp Staff" => cool_event_corp::cool_event_corp_staff,
        "Cool Event Corp. Staff" => cool_event_corp::cool_event_corp_staff_l184,
        "Cool Event Corp. Staff#kafras_cool_event_corp_191" => cool_event_corp::cool_event_corp_staff_l191,
        "Cool Event Corp. Staff#kafras_cool_event_corp_198" => cool_event_corp::cool_event_corp_staff_l198,
        "Cool Event Staff" => dts_warper::cool_event_staff,
        "Kafra" => kafras::kafra,
        "Kafra Employee#ein1" => kafras::kafra_employee_ein1,
        "Kafra Employee#ein2" => kafras::kafra_employee_ein2,
        "Kafra Employee#ein3" => kafras::kafra_employee_ein3,
        "Kafra Employee#kafras_kafras_115" => kafras::kafra_employee,
        "Kafra Employee#kafras_kafras_130" => kafras::kafra_employee_l130,
        "Kafra Employee#kafras_kafras_143" => kafras::kafra_employee_l143,
        "Kafra Employee#kafras_kafras_160" => kafras::kafra_employee_l160,
        "Kafra Employee#kafras_kafras_190" => kafras::kafra_employee_l190,
        "Kafra Employee#kafras_kafras_203" => kafras::kafra_employee_l203,
        "Kafra Employee#kafras_kafras_217" => kafras::kafra_employee_l217,
        "Kafra Employee#kafras_kafras_233" => kafras::kafra_employee_l233,
        "Kafra Employee#kafras_kafras_248" => kafras::kafra_employee_l248,
        "Kafra Employee#kafras_kafras_261" => kafras::kafra_employee_l261,
        "Kafra Employee#kafras_kafras_274" => kafras::kafra_employee_l274,
        "Kafra Employee#kafras_kafras_289" => kafras::kafra_employee_l289,
        "Kafra Employee#kafras_kafras_305" => kafras::kafra_employee_l305,
        "Kafra Employee#kafras_kafras_318" => kafras::kafra_employee_l318,
        "Kafra Employee#kafras_kafras_331" => kafras::kafra_employee_l331,
        "Kafra Employee#kafras_kafras_346" => kafras::kafra_employee_l346,
        "Kafra Employee#kafras_kafras_360" => kafras::kafra_employee_l360,
        "Kafra Employee#kafras_kafras_377" => kafras::kafra_employee_l377,
        "Kafra Employee#kafras_kafras_391" => kafras::kafra_employee_l391,
        "Kafra Employee#kafras_kafras_426" => kafras::kafra_employee_l426,
        "Kafra Employee#kafras_kafras_435" => kafras::kafra_employee_l435,
        "Kafra Employee#kafras_kafras_450" => kafras::kafra_employee_l450,
        "Kafra Employee#kafras_kafras_507" => kafras::kafra_employee_l507,
        "Kafra Employee#kafras_kafras_522" => kafras::kafra_employee_l522,
        "Kafra Employee#kafras_kafras_535" => kafras::kafra_employee_l535,
        "Kafra Employee#kafras_kafras_547" => kafras::kafra_employee_l547,
        "Kafra Employee#kafras_kafras_561" => kafras::kafra_employee_l561,
        "Kafra Employee#kafras_kafras_576" => kafras::kafra_employee_l576,
        "Kafra Employee#kafras_kafras_592" => kafras::kafra_employee_l592,
        "Kafra Employee#kafras_kafras_601" => kafras::kafra_employee_l601,
        "Kafra Employee#kafras_kafras_620" => kafras::kafra_employee_l620,
        "Kafra Employee#kafras_kafras_635" => kafras::kafra_employee_l635,
        "Kafra Employee#kafras_kafras_649" => kafras::kafra_employee_l649,
        "Kafra Employee#kafras_kafras_664" => kafras::kafra_employee_l664,
        "Kafra Employee#kafras_kafras_678" => kafras::kafra_employee_l678,
        "Kafra Employee#kafras_kafras_693" => kafras::kafra_employee_l693,
        "Kafra Service" => kafras::kafra_service,
        "Kafra Voting Staff#alb" => dts_warper::kafra_voting_staff_alb,
        "Kafra Voting Staff#alde" => dts_warper::kafra_voting_staff_alde,
        "Kafra Voting Staff#gef" => dts_warper::kafra_voting_staff_gef,
        "Kafra Voting Staff#lght" => dts_warper::kafra_voting_staff_lght,
        "Kafra Voting Staff#moc" => dts_warper::kafra_voting_staff_moc,
        "Kafra Voting Staff#pay" => dts_warper::kafra_voting_staff_pay,
        "Kafra Voting Staff#prt" => dts_warper::kafra_voting_staff_prt,
        "Kafra Voting Staff#yuno" => dts_warper::kafra_voting_staff_yuno,
        "Scrutiny Association#5" => dts_warper::scrutiny_association_5,
        "Scrutiny Association#6" => dts_warper::scrutiny_association_6,
        "Scrutiny Association#7" => dts_warper::scrutiny_association_7,
        "Vote Timer#ein" => dts_warper::vote_timer_ein,
        "Vote Timer2#ein" => dts_warper::vote_timer2_ein,
        "Vote Timer3#ein" => dts_warper::vote_timer3_ein,
        "Vote Timer4#ein" => dts_warper::vote_timer4_ein,
        "kaf_izlude" => kafras::kaf_izlude,
    }
    events {
        "Scrutiny Association#5::OnEnable" => dts_warper::scrutiny_association_5_onenable,
        "Scrutiny Association#5::OnInit" => dts_warper::scrutiny_association_5_oninit,
        "Scrutiny Association#5::OnTimer7200000" => dts_warper::scrutiny_association_5_ontimer7200000,
        "Scrutiny Association#6::OnEnable" => dts_warper::scrutiny_association_6_onenable,
        "Scrutiny Association#6::OnTimer1000" => dts_warper::scrutiny_association_6_ontimer1000,
        "Scrutiny Association#6::OnTimer10000" => dts_warper::scrutiny_association_6_ontimer10000,
        "Scrutiny Association#6::OnTimer15000" => dts_warper::scrutiny_association_6_ontimer15000,
        "Scrutiny Association#6::OnTimer5000" => dts_warper::scrutiny_association_6_ontimer5000,
        "Scrutiny Association#7::OnEnable" => dts_warper::scrutiny_association_7_onenable,
        "Scrutiny Association#7::OnTimer1000" => dts_warper::scrutiny_association_7_ontimer1000,
        "Scrutiny Association#7::OnTimer10000" => dts_warper::scrutiny_association_7_ontimer10000,
        "Scrutiny Association#7::OnTimer15000" => dts_warper::scrutiny_association_7_ontimer15000,
        "Scrutiny Association#7::OnTimer5000" => dts_warper::scrutiny_association_7_ontimer5000,
        "Vote Timer#ein::OnEnable" => dts_warper::vote_timer_ein_onenable,
        "Vote Timer#ein::OnInit" => dts_warper::vote_timer_ein_oninit,
        "Vote Timer#ein::OnTimer60000" => dts_warper::vote_timer_ein_ontimer60000,
        "Vote Timer2#ein::OnEnable" => dts_warper::vote_timer2_ein_onenable,
        "Vote Timer2#ein::OnTimer60000" => dts_warper::vote_timer2_ein_ontimer60000,
        "Vote Timer3#ein::OnEnable" => dts_warper::vote_timer3_ein_onenable,
        "Vote Timer3#ein::OnTimer60000" => dts_warper::vote_timer3_ein_ontimer60000,
        "Vote Timer4#ein::OnEnable" => dts_warper::vote_timer4_ein_onenable,
        "Vote Timer4#ein::OnTimer60000" => dts_warper::vote_timer4_ein_ontimer60000,
    }
}
