// Generated by tools/scripts-import/convert_sdk2.py from npc/events/xmas.txt. Hand-maintained from here on: edit this file directly.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

#[derive(Clone, Copy, Debug)]
enum FatherChristmasStep {
    Start,
    LStart,
    M0,
    M1,
    LNotEnuf,
    MEnd,
    OnInit,
}

fn father_christmas_run(ctx: &Ctx, mut step: FatherChristmasStep, args: Vec<Val>) -> Result<Val, Stop> {
    'machine: loop {
        match step {
            FatherChristmasStep::Start => {
                ctx.mes("[Santa Claus]")?;
                if ctx.var("xmas_npc").get()? == 0 {
                    ctx.var("xmas_npc").set(Val::from(1))?;
                }
                if (ctx.var("#event_xmas").get()?.number()? > 0 && ctx.var("#event_xmas").get()?.number()? < 30) {
                    step = FatherChristmasStep::LStart;
                    continue 'machine;
                }
                ctx.mes("Merry Christmas!")?;
                if (ctx.var("Class").get()? == 0 || ctx.var("#event_xmas").get()?.number()? >= 30) {
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                ctx.mes("I have a gift for you! Ho Ho Ho!")?;
                ctx.call(
                    Function::GetItem,
                    vec![ctx.call(Function::Rand, vec![Val::from(664), Val::from(667)])?, Val::from(1)],
                )?;
                ctx.var("#event_xmas").set((ctx.var("#event_xmas").get()? + Val::from(1)))?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            FatherChristmasStep::LStart => {
                ctx.lines(args!["I'm having a bit of a problem...", "Do you care to listen?"])?;
                ctx.next()?;
                let choice = runtime::select(ctx, &["Listen to Santa Claus.", "Give Santa Claus proof.", "Cancel."])?;
                ctx.var("@menu").set(choice)?;
                match choice {
                    1 => {
                        step = FatherChristmasStep::M0;
                        continue 'machine;
                    }
                    2 => {
                        step = FatherChristmasStep::M1;
                        continue 'machine;
                    }
                    3 => {
                        step = FatherChristmasStep::MEnd;
                        continue 'machine;
                    }
                    _ => return Err(Stop::Error("Invalid menu selection".into())),
                }
                step = FatherChristmasStep::M0;
                continue 'machine;
            }
            FatherChristmasStep::M0 => {
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "My problem is this.",
                        "There seems to be a man out there",
                        "that is impersonating me and spreading",
                        "terror throughout the land."
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "Like the Grinch of legend, he's taking",
                        "all the childrens' toys and keeping them",
                        "for himself."
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "I'm too busy here creating my batch of ",
                        "toys for next year, so I can't go",
                        "out and find him myself.",
                        "So I would like you to go out and",
                        "Destroy this man for me."
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "He has in his posession one of my",
                        "magic sacks, however, so he will",
                        "escape into it to another place each",
                        "time you attack him."
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "However,",
                        "In his haste, he tends to drop things.",
                        "If by chance he drops one of his Stockings",
                        "With Holes that he uses to steal the",
                        "poor childrens' toys, pick it up."
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "If you collect 3 of these, I will give",
                        "you a prototype mystery box that",
                        "I've been keeping around the",
                        "lab. It spits out random presents",
                        "and saves me a ton of work."
                    ],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            FatherChristmasStep::M1 => {
                ctx.mes("[Santa Claus]")?;
                if ctx.call(Function::CountItem, vec![Val::from(7034)])?.number()? < 3 {
                    step = FatherChristmasStep::LNotEnuf;
                    continue 'machine;
                }
                ctx.call(Function::DelItem, vec![Val::from(7034), Val::from(3)])?;
                ctx.lines(args![
                    "Seems you've been doing a",
                    "good job of taking down those",
                    "fake Santas. Keep it up!"
                ])?;
                ctx.next()?;
                ctx.call(Function::GetItem, vec![Val::from(644), Val::from(1)])?;
                ctx.var("#event_xmas").set((ctx.var("#event_xmas").get()? + Val::from(1)))?;
                ctx.lines_as(
                    "Santa Claus",
                    args![
                        "There's your reward.",
                        "If you get 3 more, I'll give you another.",
                        "Hope you get a good item."
                    ],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            FatherChristmasStep::LNotEnuf => {
                ctx.lines(args![
                    "You don't have enough socks as proof.",
                    "Go take down those evil Santas",
                    "and get more for me and I'll reward you."
                ])?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            FatherChristmasStep::MEnd => {
                ctx.lines_as(
                    "Santa Claus",
                    args!["I see. Well, at the very least", "we shall meet again on Christmas morning."],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            FatherChristmasStep::OnInit => {
                ctx.call(Function::DisableNpc, vec![Val::from("Santa Claus")])?;
                return Err(Stop::End);
            }
        }
    }
}

pub fn father_christmas(ctx: &Ctx) -> Script {
    father_christmas_run(ctx, FatherChristmasStep::Start, Vec::new()).map(|_| ())
}

pub fn father_christmas_oninit(ctx: &Ctx) -> Script {
    father_christmas_run(ctx, FatherChristmasStep::OnInit, Vec::new()).map(|_| ())
}
