[workspace]
resolver = "2"
members = [
    "server",
    "tools",
    "lib/database",
    "lib/script-sdk",
    "lib/script-runtime"
]

exclude = ["scripts"]

[profile.dev]
opt-level = 0
incremental = true

[profile.release.package."configuration"]
opt-level = 0
[profile.release.package."packets"]
opt-level = 0
[profile.release.package."tools"]
opt-level = 0

[workspace.dependencies]
bitcode = { version = "0.5.1", features = ["serde", "derive"] }
byteorder = "1.5.0"
lazy_static  = "1.4.0"
hashbrown = "0.14"
base64 = { version = "0.21.7", features = [] }
sha1 = "0.10"
fastmurmur3 = "0.2.0"
regex-lite = "0.1.6"
tokio = { version = "1.33.0", features = ["full", "tracing"] }
axum = { version = "0.8", default-features = false, features = ["http1", "json", "query", "tokio", "ws"] }
futures = "0.3"
wasmtime = { version = "43.0.2", default-features = false, features = ["async", "cranelift", "runtime", "std", "wat", "anyhow"] }
sled = "0.34.7"
dashmap = "6.1.0"
parking_lot = "0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["chrono", "fmt"] }
rand = "0.8"
fastrand = "2.0.1"
flate2 = "1.0.28"
md5 = "0.7.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", features = ["raw_value"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
json-flat-parser = "0.1.0"
