pub mod umbala;
pub mod veins;
pub mod yuno;

script_sdk_2::script_module! {
    npcs {
        "#jump" => umbala::jump,
        "Airship Representative" => yuno::airship_representative,
        "Bertan#um" => umbala::bertan_um,
        "Bungee Jump" => umbala::bungee_jump,
        "Freidrich#juno" => yuno::freidrich_juno,
        "Haith#um" => umbala::haith_um,
        "Iriya#um" => umbala::iriya_um,
        "Juno Artisan#juno" => yuno::juno_artisan_juno,
        "Juno Despot#juno" => yuno::juno_despot_juno,
        "Juno Fighter#juno" => yuno::juno_fighter_juno,
        "Juno Granny#juno" => yuno::juno_granny_juno,
        "Juno Sage#juno" => yuno::juno_sage_juno,
        "JunoSoldier1" => yuno::junosoldier1,
        "JunoSoldier2" => yuno::junosoldier2,
        "JunoSoldier3" => yuno::junosoldier3,
        "JunoSoldier4" => yuno::junosoldier4,
        "JunoSoldier5" => yuno::junosoldier5,
        "JunoSoldier6" => yuno::junosoldier6,
        "JunoSoldier7" => yuno::junosoldier7,
        "Kid#ve1" => veins::kid_ve1,
        "Kid#ve2" => veins::kid_ve2,
        "Kid#ve3" => veins::kid_ve3,
        "Kid#ve4" => veins::kid_ve4,
        "Kid#ve5" => veins::kid_ve5,
        "Kid#ve6" => veins::kid_ve6,
        "La Ed#um" => umbala::la_ed_um,
        "Niels#um" => umbala::niels_um,
        "Old Lady#ve2" => veins::old_lady_ve2,
        "Old Lady#ve3" => veins::old_lady_ve3,
        "Old Man#ve1" => veins::old_man_ve1,
        "Old Man#ve2" => veins::old_man_ve2,
        "Old Man#ve3" => veins::old_man_ve3,
        "Old Man#ve4" => veins::old_man_ve4,
        "Old Man#ve5" => veins::old_man_ve5,
        "Old lady#ve1" => veins::old_lady_ve1,
        "Pasto#um" => umbala::pasto_um,
        "Prisoner#ve1" => veins::prisoner_ve1,
        "Towner#ve1" => veins::towner_ve1,
        "Towner#ve10" => veins::towner_ve10,
        "Towner#ve11" => veins::towner_ve11,
        "Towner#ve12" => veins::towner_ve12,
        "Towner#ve13" => veins::towner_ve13,
        "Towner#ve14" => veins::towner_ve14,
        "Towner#ve15" => veins::towner_ve15,
        "Towner#ve16" => veins::towner_ve16,
        "Towner#ve17" => veins::towner_ve17,
        "Towner#ve18" => veins::towner_ve18,
        "Towner#ve19" => veins::towner_ve19,
        "Towner#ve2" => veins::towner_ve2,
        "Towner#ve20" => veins::towner_ve20,
        "Towner#ve21" => veins::towner_ve21,
        "Towner#ve22" => veins::towner_ve22,
        "Towner#ve23" => veins::towner_ve23,
        "Towner#ve24" => veins::towner_ve24,
        "Towner#ve25" => veins::towner_ve25,
        "Towner#ve26" => veins::towner_ve26,
        "Towner#ve27" => veins::towner_ve27,
        "Towner#ve28" => veins::towner_ve28,
        "Towner#ve29" => veins::towner_ve29,
        "Towner#ve3" => veins::towner_ve3,
        "Towner#ve4" => veins::towner_ve4,
        "Towner#ve5" => veins::towner_ve5,
        "Towner#ve6" => veins::towner_ve6,
        "Towner#ve7" => veins::towner_ve7,
        "Towner#ve8" => veins::towner_ve8,
        "Towner#ve9" => veins::towner_ve9,
        "Utan Kid#1" => umbala::utan_kid_1,
        "Utan Kid#2" => umbala::utan_kid_2,
        "Utan Kid#3" => umbala::utan_kid_3,
        "Utan Kid#um" => umbala::utan_kid_um,
        "Utan Man#1" => umbala::utan_man_1,
        "Utan Man#2" => umbala::utan_man_2,
        "Utan Man#3" => umbala::utan_man_3,
        "Utan Man#5" => umbala::utan_man_5,
        "Utan villager#um" => umbala::utan_villager_um,
        "Ward#ve1" => veins::ward_ve1,
        "Ward#ve2" => veins::ward_ve2,
        "Yuwooki#um" => umbala::yuwooki_um,
    }
    events {
        "#jump::OnTouch_" => umbala::jump_ontouch,
        "Bungee Jump::OnTouch_" => umbala::bungee_jump_ontouch,
    }
}
