#!/usr/bin/env python3
"""Generates lib/script-sdk-2/src/bonus_names.rs from the bonus operations the scripts call.

One enum variant per distinct bonus name, per function: `Bonus` (`bonus`), `Bonus2` (`bonus2`) and `Bonus3`
(`bonus3`). Names are matched without regard to case, as the server does, and each variant keeps the spelling used
most often. The auto-spell forms of `bonus3`..`bonus5` are hand-written in `bonus.rs`, so they are left out here.
"""

import argparse
import collections
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts"
OUTPUT = ROOT / "lib/script-sdk-2/src/bonus_names.rs"
CALL = re.compile(r"Function::(Bonus[2-5]?)\s*,\s*vec!\[")
AUTO_SPELL = re.compile(r"^bautospell", re.IGNORECASE)


def top_level_arguments(text: str, start: int) -> list[str]:
    depth, index, arguments, current, in_string = 1, start, [], "", False
    while index < len(text):
        character = text[index]
        if character == '"' and (index == 0 or text[index - 1] != "\\"):
            in_string = not in_string
        if not in_string:
            if character in "([{":
                depth += 1
            elif character in ")]}":
                depth -= 1
                if depth == 0:
                    if current.strip():
                        arguments.append(current.strip())
                    return arguments
            elif character == "," and depth == 1:
                arguments.append(current.strip())
                current = ""
                index += 1
                continue
        current += character
        index += 1
    return arguments


def collect() -> dict[str, collections.Counter]:
    """Function name -> Counter of (spelling, value count) for each bonus name."""
    found: dict[str, collections.Counter] = {}
    for path in SCRIPTS.rglob("*.rs"):
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in CALL.finditer(text):
            arguments = top_level_arguments(text, match.end())
            if not arguments:
                continue
            name = re.search(r'constant\("([^"]+)"\)', arguments[0])
            if not name:
                continue
            found.setdefault(match.group(1), collections.Counter())[(name.group(1), len(arguments) - 1)] += 1
    return found


def canonical_spellings(counter: collections.Counter) -> dict[str, tuple[str, set[int]]]:
    """Lowercased name -> (most used spelling, the value counts seen for it)."""
    spellings: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    arities: dict[str, set[int]] = collections.defaultdict(set)
    for (spelling, arity), count in counter.items():
        spellings[spelling.lower()][spelling] += count
        arities[spelling.lower()].add(arity)
    return {key: (spellings[key].most_common(1)[0][0], arities[key]) for key in sorted(spellings)}


def variant(name: str) -> str:
    stripped = name[1:] if name[:1] in ("b", "B") else name
    return stripped[:1].upper() + stripped[1:]


def render(found: dict[str, collections.Counter], warnings: list[str]) -> str:
    lines = [
        "//! Bonus operations the scripts use, one variant per rathena name.",
        "//!",
        "//! Generated by `tools/scripts-import/gen_sdk2_bonus.py` from the scripts. Do not edit by hand.",
        "",
    ]

    names = canonical_spellings(found.get("Bonus", collections.Counter()))
    lines += [
        "/// `bonus`: a stat or flag. Flag names take no value and are written without one.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum Bonus {",
    ]
    for key, (spelling, arities) in names.items():
        if arities - {0, 1}:
            warnings.append(f"bonus {spelling}: unexpected value counts {sorted(arities)}")
        flag = 0 in arities
        if flag and 1 in arities:
            warnings.append(f"bonus {spelling}: called as a flag and with a value; the flag form is generated and the value is dropped")
        lines.append(f"    {variant(spelling)}{'' if flag else '(i32)'},")
    lines += ["}", "", "impl Bonus {", "    pub(crate) fn parts(self) -> (&'static str, Option<i32>) {", "        match self {"]
    for key, (spelling, arities) in names.items():
        if 0 in arities:
            lines.append(f"            Bonus::{variant(spelling)} => (\"{spelling}\", None),")
        else:
            lines.append(f"            Bonus::{variant(spelling)}(value) => (\"{spelling}\", Some(value)),")
    lines += ["        }", "    }", "}", ""]

    for function, enum_name, value_count, doc in (
        ("Bonus2", "Bonus2", 2, "`bonus2`: a key (a constant or number, such as a race or effect) and a value."),
        ("Bonus3", "Bonus3", 3, "`bonus3`: three values. The auto-spell forms are in `bonus.rs`."),
    ):
        names = {key: value for key, value in canonical_spellings(found.get(function, collections.Counter())).items()
                 if not AUTO_SPELL.match(value[0])}
        lines += [
            f"/// {doc}",
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
            f"pub enum {enum_name} {{",
        ]
        for key, (spelling, arities) in names.items():
            if arities != {value_count}:
                warnings.append(f"{function} {spelling}: unexpected value counts {sorted(arities)}")
            fields = ", ".join(["i32"] * value_count)
            lines.append(f"    {variant(spelling)}({fields}),")
        fields_pattern = ", ".join(f"v{index}" for index in range(value_count))
        values = ", ".join(f"v{index}" for index in range(value_count))
        lines += [
            "}",
            "",
            f"impl {enum_name} {{",
            f"    pub(crate) fn parts(self) -> (&'static str, [i32; {value_count}]) {{",
            "        match self {",
        ]
        for key, (spelling, _) in names.items():
            lines.append(f"            {enum_name}::{variant(spelling)}({fields_pattern}) => (\"{spelling}\", [{values}]),")
        lines += ["        }", "    }", "}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated file is out of date instead of writing it")
    args = parser.parse_args()

    warnings: list[str] = []
    rendered = render(collect(), warnings)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"{OUTPUT} is out of date; run gen_sdk2_bonus.py")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    for warning in warnings:
        print(f"warning: {warning}")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
