#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "Arena Assistant" => arena_assistant,
        "Gloomy Wizard" => gloomy_wizard,
        "Room of Earth" => room_of_earth,
        "Room of Earth#Door" => room_of_earth_door,
        "Room of Earth#Failed" => room_of_earth_failed,
        "Room of Fire" => room_of_fire,
        "Room of Fire#Door" => room_of_fire_door,
        "Room of Fire#Failed" => room_of_fire_failed,
        "Room of Water" => room_of_water,
        "Room of Water#Door" => room_of_water_door,
        "Room of Water#Failed" => room_of_water_failed,
        "Test Helper#wiz" => test_helper_wiz,
        "White Dog#wiz" => white_dog_wiz,
        "Wizard Guildsman" => wizard_guildsman,
    }
    events {
        "Arena Assistant::OnInit" => arena_assistant_oninit,
        "Arena Assistant::OnStart" => arena_assistant_onstart,
        "Arena Assistant::OnStartArena" => arena_assistant_onstartarena,
        "Room of Earth#Door::OnDisable" => room_of_earth_door_ondisable,
        "Room of Earth#Door::OnEnable" => room_of_earth_door_onenable,
        "Room of Earth#Door::OnInit" => room_of_earth_door_oninit,
        "Room of Earth#Door::OnMyMobDead" => room_of_earth_door_onmymobdead,
        "Room of Earth#Door::OnTimer1000" => room_of_earth_door_ontimer1000,
        "Room of Earth#Door::OnTimer30000" => room_of_earth_door_ontimer30000,
        "Room of Earth#Door::OnTimer50000" => room_of_earth_door_ontimer50000,
        "Room of Earth#Door::OnTimer60000" => room_of_earth_door_ontimer60000,
        "Room of Earth#Door::OnTimer61000" => room_of_earth_door_ontimer61000,
        "Room of Earth#Door::OnTimer62000" => room_of_earth_door_ontimer62000,
        "Room of Earth#Door::OnTimer63000" => room_of_earth_door_ontimer63000,
        "Room of Earth#Failed::OnInit" => room_of_earth_failed_oninit,
        "Room of Earth#Failed::OnTouch_" => room_of_earth_failed_ontouch,
        "Room of Earth::OnDisable" => room_of_earth_ondisable,
        "Room of Earth::OnEnable" => room_of_earth_onenable,
        "Room of Earth::OnInit" => room_of_earth_oninit,
        "Room of Earth::OnMyMobDead" => room_of_earth_onmymobdead,
        "Room of Earth::OnTimer1000" => room_of_earth_ontimer1000,
        "Room of Earth::OnTimer123000" => room_of_earth_ontimer123000,
        "Room of Earth::OnTimer153000" => room_of_earth_ontimer153000,
        "Room of Earth::OnTimer173000" => room_of_earth_ontimer173000,
        "Room of Earth::OnTimer183000" => room_of_earth_ontimer183000,
        "Room of Earth::OnTimer184000" => room_of_earth_ontimer184000,
        "Room of Earth::OnTimer185000" => room_of_earth_ontimer185000,
        "Room of Earth::OnTimer186000" => room_of_earth_ontimer186000,
        "Room of Earth::OnTimer2000" => room_of_earth_ontimer2000,
        "Room of Earth::OnTimer3000" => room_of_earth_ontimer3000,
        "Room of Earth::OnTimer33000" => room_of_earth_ontimer33000,
        "Room of Earth::OnTimer63000" => room_of_earth_ontimer63000,
        "Room of Earth::OnTimer93000" => room_of_earth_ontimer93000,
        "Room of Fire#Door::OnDisable" => room_of_fire_door_ondisable,
        "Room of Fire#Door::OnEnable" => room_of_fire_door_onenable,
        "Room of Fire#Door::OnInit" => room_of_fire_door_oninit,
        "Room of Fire#Door::OnMyMobDead" => room_of_fire_door_onmymobdead,
        "Room of Fire#Door::OnTimer1000" => room_of_fire_door_ontimer1000,
        "Room of Fire#Door::OnTimer110000" => room_of_fire_door_ontimer110000,
        "Room of Fire#Door::OnTimer120000" => room_of_fire_door_ontimer120000,
        "Room of Fire#Door::OnTimer121000" => room_of_fire_door_ontimer121000,
        "Room of Fire#Door::OnTimer122000" => room_of_fire_door_ontimer122000,
        "Room of Fire#Door::OnTimer123000" => room_of_fire_door_ontimer123000,
        "Room of Fire#Door::OnTimer30000" => room_of_fire_door_ontimer30000,
        "Room of Fire#Door::OnTimer60000" => room_of_fire_door_ontimer60000,
        "Room of Fire#Door::OnTimer90000" => room_of_fire_door_ontimer90000,
        "Room of Fire#Failed::OnInit" => room_of_fire_failed_oninit,
        "Room of Fire#Failed::OnTouch_" => room_of_fire_failed_ontouch,
        "Room of Fire::OnDisable" => room_of_fire_ondisable,
        "Room of Fire::OnEnable" => room_of_fire_onenable,
        "Room of Fire::OnInit" => room_of_fire_oninit,
        "Room of Fire::OnMyMobDead" => room_of_fire_onmymobdead,
        "Room of Fire::OnTimer1000" => room_of_fire_ontimer1000,
        "Room of Fire::OnTimer123000" => room_of_fire_ontimer123000,
        "Room of Fire::OnTimer153000" => room_of_fire_ontimer153000,
        "Room of Fire::OnTimer173000" => room_of_fire_ontimer173000,
        "Room of Fire::OnTimer183000" => room_of_fire_ontimer183000,
        "Room of Fire::OnTimer184000" => room_of_fire_ontimer184000,
        "Room of Fire::OnTimer185000" => room_of_fire_ontimer185000,
        "Room of Fire::OnTimer186000" => room_of_fire_ontimer186000,
        "Room of Fire::OnTimer2000" => room_of_fire_ontimer2000,
        "Room of Fire::OnTimer3000" => room_of_fire_ontimer3000,
        "Room of Fire::OnTimer33000" => room_of_fire_ontimer33000,
        "Room of Fire::OnTimer63000" => room_of_fire_ontimer63000,
        "Room of Fire::OnTimer93000" => room_of_fire_ontimer93000,
        "Room of Water#Door::OnDisable" => room_of_water_door_ondisable,
        "Room of Water#Door::OnEnable" => room_of_water_door_onenable,
        "Room of Water#Door::OnInit" => room_of_water_door_oninit,
        "Room of Water#Door::OnMyMobDead" => room_of_water_door_onmymobdead,
        "Room of Water#Door::OnTimer1000" => room_of_water_door_ontimer1000,
        "Room of Water#Door::OnTimer30000" => room_of_water_door_ontimer30000,
        "Room of Water#Door::OnTimer50000" => room_of_water_door_ontimer50000,
        "Room of Water#Door::OnTimer60000" => room_of_water_door_ontimer60000,
        "Room of Water#Door::OnTimer61000" => room_of_water_door_ontimer61000,
        "Room of Water#Door::OnTimer62000" => room_of_water_door_ontimer62000,
        "Room of Water#Door::OnTimer63000" => room_of_water_door_ontimer63000,
        "Room of Water#Failed::OnInit" => room_of_water_failed_oninit,
        "Room of Water#Failed::OnTouch_" => room_of_water_failed_ontouch,
        "Room of Water::OnDisable" => room_of_water_ondisable,
        "Room of Water::OnEnable" => room_of_water_onenable,
        "Room of Water::OnInit" => room_of_water_oninit,
        "Room of Water::OnMyMobDead" => room_of_water_onmymobdead,
        "Room of Water::OnTimer1000" => room_of_water_ontimer1000,
        "Room of Water::OnTimer123000" => room_of_water_ontimer123000,
        "Room of Water::OnTimer153000" => room_of_water_ontimer153000,
        "Room of Water::OnTimer173000" => room_of_water_ontimer173000,
        "Room of Water::OnTimer183000" => room_of_water_ontimer183000,
        "Room of Water::OnTimer184000" => room_of_water_ontimer184000,
        "Room of Water::OnTimer185000" => room_of_water_ontimer185000,
        "Room of Water::OnTimer186000" => room_of_water_ontimer186000,
        "Room of Water::OnTimer2000" => room_of_water_ontimer2000,
        "Room of Water::OnTimer3000" => room_of_water_ontimer3000,
        "Room of Water::OnTimer33000" => room_of_water_ontimer33000,
        "Room of Water::OnTimer63000" => room_of_water_ontimer63000,
        "Room of Water::OnTimer93000" => room_of_water_ontimer93000,
        "Test Helper#wiz::OnDisable" => test_helper_wiz_ondisable,
        "Test Helper#wiz::OnEnable" => test_helper_wiz_onenable,
        "Test Helper#wiz::OnInit" => test_helper_wiz_oninit,
        "Test Helper#wiz::OnTimer2000" => test_helper_wiz_ontimer2000,
        "Test Helper#wiz::OnTimer4000" => test_helper_wiz_ontimer4000,
        "Test Helper#wiz::OnTimer5000" => test_helper_wiz_ontimer5000,
        "Test Helper#wiz::OnTimer7000" => test_helper_wiz_ontimer7000,
        "Test Helper#wiz::OnTimer9000" => test_helper_wiz_ontimer9000,
    }
}
