#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod part_10;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;
pub use part_08::*;
pub use part_09::*;
pub use part_10::*;

script_sdk_2::script_module! {
    npcs {
        "#Crayu" => crayu,
        "#Cursed Soul" => cursed_soul,
        "#Switch" => switch,
        "#Valkyrie Warp" => valkyrie_warp,
        "#kidniff" => kidniff,
        "#mazewarp" => mazewarp,
        "#movesign" => movesign,
        "#music" => music,
        "#skill" => skill,
        "#witch" => witch,
        "Aaron#sign" => aaron_sign,
        "Alchemist#sign" => alchemist_sign,
        "Annoyed Man" => annoyed_man,
        "Archeologist#sign" => archeologist_sign,
        "CallMonster#serin" => callmonster_serin,
        "CallMonster#witch" => callmonster_witch,
        "Cute Girl" => cute_girl,
        "Daewoon#sign" => daewoon_sign,
        "Dark Lord#serin" => dark_lord_serin,
        "Depressing Man" => depressing_man,
        "Emergency Exit" => emergency_exit,
        "Examiner#sd" => examiner_sd,
        "Examiner#sign" => examiner_sign,
        "Fastidious Old Man" => fastidious_old_man,
        "Fastidious-Looking Guy" => fastidious_looking_guy,
        "Flaming Spirit Man" => flaming_spirit_man,
        "Fountain#s" => fountain_s,
        "Fountain#sign" => fountain_sign,
        "Geffenia Warp" => geffenia_warp,
        "Gordon#sign" => gordon_sign,
        "Guard#s10" => guard_s10,
        "Hagin#sign" => hagin_sign,
        "Jesqurienne#sign" => jesqurienne_sign,
        "Knight#ss" => knight_ss,
        "Lonely-looking Woman" => lonely_looking_woman,
        "Mad Man#s" => mad_man_s,
        "Maid#a1" => maid_a1,
        "Maid#a2" => maid_a2,
        "Maid#b1" => maid_b1,
        "Maid#b2" => maid_b2,
        "Maid#c1" => maid_c1,
        "Maid#c2" => maid_c2,
        "Maid#d1" => maid_d1,
        "Maid#d2" => maid_d2,
        "Maid#e1" => maid_e1,
        "Maid#e2" => maid_e2,
        "Maid#f1" => maid_f1,
        "Maid#f2" => maid_f2,
        "Maid#s10" => maid_s10,
        "Maid#sign" => maid_sign,
        "Maid#sign2" => maid_sign2,
        "Monograph#sign" => monograph_sign,
        "Mysterious Energy#1" => mysterious_energy_1,
        "Mysterious Energy#2" => mysterious_energy_2,
        "Mysterious Energy#3" => mysterious_energy_3,
        "Mysterious Energy#4" => mysterious_energy_4,
        "Mysterious Energy#5" => mysterious_energy_5,
        "Mysterious Energy#6" => mysterious_energy_6,
        "Mysterious Energy#7" => mysterious_energy_7,
        "Mysterious Energy#8" => mysterious_energy_8,
        "Native#_s" => native_s,
        "Piru Piru#sign" => piru_piru_sign,
        "Pleasant-Featured Lady#s" => pleasant_featured_lady_s,
        "Pleur#sign" => pleur_sign,
        "Pleur#warp" => pleur_warp,
        "Poor-looking Merchant" => poor_looking_merchant,
        "Queen of the Dead" => queen_of_the_dead,
        "Refined Steward" => refined_steward,
        "Rogue#sign" => rogue_sign,
        "Serin#dummy" => serin_dummy,
        "Serin#serin" => serin_serin,
        "Serin#witch" => serin_witch,
        "Sign#quests_the_sign_quest_35" => sign,
        "Sir Jore#sign" => sir_jore_sign,
        "Soldier#s11_" => soldier_s11,
        "Standby Room#sign" => standby_room_sign,
        "Starter#serin" => starter_serin,
        "Starter#witch" => starter_witch,
        "Steward#sign" => steward_sign,
        "Strange Guy#sign" => strange_guy_sign,
        "Timer#serin" => timer_serin,
        "Timer#witch" => timer_witch,
        "Valkyrie#sign" => valkyrie_sign,
        "Warp#serin" => warp_serin,
        "Warp#witch" => warp_witch,
        "Wealthy-looking Merchant" => wealthy_looking_merchant,
        "Witch#s" => witch_s,
        "Young Man#sign" => young_man_sign,
        "s_dance#cen" => s_dance_cen,
        "s_dance#down" => s_dance_down,
        "s_dance#left" => s_dance_left,
        "s_dance#right" => s_dance_right,
        "s_dance#up" => s_dance_up,
        "s_dance_timer" => s_dance_timer,
        "sign_w6" => sign_w6,
    }
    events {
        "#Crayu::OnTouch_" => crayu_ontouch,
        "#Cursed Soul::OnMyMobDead" => cursed_soul_onmymobdead,
        "#Cursed Soul::OnTouch_" => cursed_soul_ontouch,
        "#Valkyrie Warp::OnTouch_" => valkyrie_warp_ontouch,
        "#kidniff::OnTouch_" => kidniff_ontouch,
        "#mazewarp::OnTouch_" => mazewarp_ontouch,
        "#movesign::OnTouch_" => movesign_ontouch,
        "#music::OnTouch_" => music_ontouch,
        "#skill::OnDisable" => skill_ondisable,
        "#skill::OnEnable" => skill_onenable,
        "#skill::OnMyMobDead" => skill_onmymobdead,
        "#witch::OnTouch_" => witch_ontouch,
        "Aaron#sign::OnSmile" => aaron_sign_onsmile,
        "CallMonster#serin::OnMyMobDead" => callmonster_serin_onmymobdead,
        "CallMonster#serin::OnReset" => callmonster_serin_onreset,
        "CallMonster#serin::Oncall" => callmonster_serin_oncall,
        "CallMonster#witch::OnMyMobDead" => callmonster_witch_onmymobdead,
        "CallMonster#witch::OnReset" => callmonster_witch_onreset,
        "CallMonster#witch::Oncall" => callmonster_witch_oncall,
        "Dark Lord#serin::OnDisable" => dark_lord_serin_ondisable,
        "Dark Lord#serin::OnEnable" => dark_lord_serin_onenable,
        "Dark Lord#serin::OnInit" => dark_lord_serin_oninit,
        "Examiner#sd::OnDisable" => examiner_sd_ondisable,
        "Examiner#sd::OnInit" => examiner_sd_oninit,
        "Examiner#sd::OnTouch_" => examiner_sd_ontouch,
        "Examiner#sd::OnUp" => examiner_sd_onup,
        "Geffenia Warp::OnDisable" => geffenia_warp_ondisable,
        "Geffenia Warp::OnEnable" => geffenia_warp_onenable,
        "Geffenia Warp::OnInit" => geffenia_warp_oninit,
        "Geffenia Warp::OnTimer10000" => geffenia_warp_ontimer10000,
        "Geffenia Warp::OnTimer20000" => geffenia_warp_ontimer20000,
        "Geffenia Warp::OnTimer30000" => geffenia_warp_ontimer30000,
        "Geffenia Warp::OnTimer40000" => geffenia_warp_ontimer40000,
        "Geffenia Warp::OnTimer45000" => geffenia_warp_ontimer45000,
        "Geffenia Warp::OnTouch_" => geffenia_warp_ontouch,
        "Jesqurienne#sign::OnHo" => jesqurienne_sign_onho,
        "Jesqurienne#sign::OnOmg" => jesqurienne_sign_onomg,
        "Pleur#sign::OnGasp" => pleur_sign_ongasp,
        "Pleur#sign::OnHo" => pleur_sign_onho,
        "Pleur#sign::OnKis2" => pleur_sign_onkis2,
        "Pleur#sign::OnOmg" => pleur_sign_onomg,
        "Serin#dummy::OnDisable" => serin_dummy_ondisable,
        "Serin#dummy::OnEnable" => serin_dummy_onenable,
        "Serin#dummy::OnInit" => serin_dummy_oninit,
        "Serin#dummy::OnStart" => serin_dummy_onstart,
        "Serin#dummy::OnTimer13000" => serin_dummy_ontimer13000,
        "Serin#dummy::OnTimer3000" => serin_dummy_ontimer3000,
        "Serin#dummy::OnTimer6000" => serin_dummy_ontimer6000,
        "Serin#dummy::OnTimer9000" => serin_dummy_ontimer9000,
        "Serin#serin::OnDisable" => serin_serin_ondisable,
        "Serin#serin::OnEnable" => serin_serin_onenable,
        "Serin#witch::OnDisable" => serin_witch_ondisable,
        "Serin#witch::OnEnable" => serin_witch_onenable,
        "Sign#quests_the_sign_quest_35::OnInit" => sign_oninit,
        "Sir Jore#sign::OnTouch_" => sir_jore_sign_ontouch,
        "Standby Room#sign::OnInit" => standby_room_sign_oninit,
        "Standby Room#sign::OnReset" => standby_room_sign_onreset,
        "Standby Room#sign::OnStartArena" => standby_room_sign_onstartarena,
        "Starter#serin::OnEnable" => starter_serin_onenable,
        "Starter#serin::OnTouch_" => starter_serin_ontouch,
        "Starter#witch::OnEnable" => starter_witch_onenable,
        "Starter#witch::OnTouch_" => starter_witch_ontouch,
        "Timer#serin::OnStart" => timer_serin_onstart,
        "Timer#serin::OnTimer600000" => timer_serin_ontimer600000,
        "Timer#serin::OnTimer620000" => timer_serin_ontimer620000,
        "Timer#witch::OnStart" => timer_witch_onstart,
        "Timer#witch::OnTimer600000" => timer_witch_ontimer600000,
        "Timer#witch::OnTimer620000" => timer_witch_ontimer620000,
        "Warp#serin::OnDisable" => warp_serin_ondisable,
        "Warp#serin::OnEnable" => warp_serin_onenable,
        "Warp#serin::OnInit" => warp_serin_oninit,
        "Warp#serin::OnTouch_" => warp_serin_ontouch,
        "Warp#witch::OnDisable" => warp_witch_ondisable,
        "Warp#witch::OnEnable" => warp_witch_onenable,
        "Warp#witch::OnInit" => warp_witch_oninit,
        "Warp#witch::OnTouch_" => warp_witch_ontouch,
        "s_dance#cen::OnDisable" => s_dance_cen_ondisable,
        "s_dance#cen::OnEnable" => s_dance_cen_onenable,
        "s_dance#cen::OnInit" => s_dance_cen_oninit,
        "s_dance#cen::OnReset" => s_dance_cen_onreset,
        "s_dance#cen::OnTouch_" => s_dance_cen_ontouch,
        "s_dance#cen::OnUp" => s_dance_cen_onup,
        "s_dance#down::OnDisable" => s_dance_down_ondisable,
        "s_dance#down::OnEnable" => s_dance_down_onenable,
        "s_dance#down::OnInit" => s_dance_down_oninit,
        "s_dance#down::OnReset" => s_dance_down_onreset,
        "s_dance#down::OnTouch_" => s_dance_down_ontouch,
        "s_dance#down::OnUp" => s_dance_down_onup,
        "s_dance#left::OnDisable" => s_dance_left_ondisable,
        "s_dance#left::OnEnable" => s_dance_left_onenable,
        "s_dance#left::OnInit" => s_dance_left_oninit,
        "s_dance#left::OnReset" => s_dance_left_onreset,
        "s_dance#left::OnTouch_" => s_dance_left_ontouch,
        "s_dance#left::OnUp" => s_dance_left_onup,
        "s_dance#right::OnDisable" => s_dance_right_ondisable,
        "s_dance#right::OnEnable" => s_dance_right_onenable,
        "s_dance#right::OnInit" => s_dance_right_oninit,
        "s_dance#right::OnReset" => s_dance_right_onreset,
        "s_dance#right::OnTouch_" => s_dance_right_ontouch,
        "s_dance#right::OnUp" => s_dance_right_onup,
        "s_dance#up::OnDisable" => s_dance_up_ondisable,
        "s_dance#up::OnEnable" => s_dance_up_onenable,
        "s_dance#up::OnInit" => s_dance_up_oninit,
        "s_dance#up::OnReset" => s_dance_up_onreset,
        "s_dance#up::OnTouch_" => s_dance_up_ontouch,
        "s_dance#up::OnUp" => s_dance_up_onup,
        "s_dance_timer::OnButton_Off" => s_dance_timer_onbutton_off,
        "s_dance_timer::OnDisable" => s_dance_timer_ondisable,
        "s_dance_timer::OnDisableAll" => s_dance_timer_ondisableall,
        "s_dance_timer::OnEnable" => s_dance_timer_onenable,
        "s_dance_timer::OnTimer11000" => s_dance_timer_ontimer11000,
        "s_dance_timer::OnTimer13000" => s_dance_timer_ontimer13000,
        "s_dance_timer::OnTimer18000" => s_dance_timer_ontimer18000,
        "s_dance_timer::OnTimer2000" => s_dance_timer_ontimer2000,
        "s_dance_timer::OnTimer21000" => s_dance_timer_ontimer21000,
        "s_dance_timer::OnTimer24000" => s_dance_timer_ontimer24000,
        "s_dance_timer::OnTimer30000" => s_dance_timer_ontimer30000,
        "s_dance_timer::OnTimer34000" => s_dance_timer_ontimer34000,
        "s_dance_timer::OnTimer38000" => s_dance_timer_ontimer38000,
        "s_dance_timer::OnTimer4000" => s_dance_timer_ontimer4000,
        "s_dance_timer::OnTimer44000" => s_dance_timer_ontimer44000,
        "s_dance_timer::OnTimer6000" => s_dance_timer_ontimer6000,
        "s_dance_timer::OnTimer8000" => s_dance_timer_ontimer8000,
        "sign_w6::OnTouch_" => sign_w6_ontouch,
    }
}
