#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "Aide Arioss#edq" => aide_arioss_edq,
        "Assistant Naomi#edq" => assistant_naomi_edq,
        "Commander Lebiordirr#edq" => commander_lebiordirr_edq,
        "Grumbling Soldier#edq" => grumbling_soldier_edq,
        "Historian Magnifier#edq" => historian_magnifier_edq,
        "Laphine Prisoner#edq" => laphine_prisoner_edq,
        "Manuk Guard#1_edq" => manuk_guard_1_edq,
        "Manuk Guard#2_edq" => manuk_guard_2_edq,
        "Murdered Yggdrasilid#1F" => murdered_yggdrasilid_1f,
        "Neat Etorr#edq" => neat_etorr_edq,
        "Nidhoggur Manager" => nidhoggur_manager,
        "Purification Admin#nyd2" => purification_admin_nyd2,
        "Purification Stone#nyd2" => purification_stone_nyd2,
        "Sighing Soldier#edq" => sighing_soldier_edq,
        "Splendide Guard#1_edq" => splendide_guard_1_edq,
        "Splendide Guard#2_edq" => splendide_guard_2_edq,
        "World Tree Yggdrasil#2F" => world_tree_yggdrasil_2f,
        "Yggdrasil Gatekeeper" => yggdrasil_gatekeeper,
        "ins_nyd1_spawn_mobs" => ins_nyd1_spawn_mobs,
        "ins_nyd2_spawn_mobs" => ins_nyd2_spawn_mobs,
        "ins_nyd_1f_timer" => ins_nyd_1f_timer,
        "nyd_2f_boss_enter" => nyd_2f_boss_enter,
        "nyd_2f_boss_enter_call" => nyd_2f_boss_enter_call,
        "nyd_2f_boss_enter_logic" => nyd_2f_boss_enter_logic,
        "nyd_2f_ddr_control" => nyd_2f_ddr_control,
        "nyd_2f_enter" => nyd_2f_enter,
        "nyd_2f_enter_broad" => nyd_2f_enter_broad,
        "nyd_2f_red" => nyd_2f_red,
        "nyd_2f_red_c" => nyd_2f_red_c,
        "nyd_2f_red_warp1" => nyd_2f_red_warp1,
        "nyd_call_mon_1" => nyd_call_mon_1,
        "nyd_to2f_warp" => nyd_to2f_warp,
        "trap#edq2" => trap_edq2,
        "trap#s_edq" => trap_s_edq,
    }
    events {
        "Murdered Yggdrasilid#1F::OnInstanceInit" => murdered_yggdrasilid_1f_oninstanceinit,
        "Murdered Yggdrasilid#1F::OnTouch" => murdered_yggdrasilid_1f_ontouch,
        "Purification Stone#nyd2::OnDisable" => purification_stone_nyd2_ondisable,
        "Purification Stone#nyd2::OnEnable" => purification_stone_nyd2_onenable,
        "Purification Stone#nyd2::OnInit" => purification_stone_nyd2_oninit,
        "Purification Stone#nyd2::OnTimer1000" => purification_stone_nyd2_ontimer1000,
        "Purification Stone#nyd2::OnTimer1740000" => purification_stone_nyd2_ontimer1740000,
        "Purification Stone#nyd2::OnTimer1800000" => purification_stone_nyd2_ontimer1800000,
        "World Tree Yggdrasil#2F::OnDisable" => world_tree_yggdrasil_2f_ondisable,
        "World Tree Yggdrasil#2F::OnEnable" => world_tree_yggdrasil_2f_onenable,
        "World Tree Yggdrasil#2F::OnInstanceInit" => world_tree_yggdrasil_2f_oninstanceinit,
        "Yggdrasil Gatekeeper::OnTouch_" => yggdrasil_gatekeeper_ontouch,
        "ins_nyd1_spawn_mobs::OnInstanceInit" => ins_nyd1_spawn_mobs_oninstanceinit,
        "ins_nyd1_spawn_mobs::OnMyAquaDead" => ins_nyd1_spawn_mobs_onmyaquadead,
        "ins_nyd1_spawn_mobs::OnMyPhyDead" => ins_nyd1_spawn_mobs_onmyphydead,
        "ins_nyd1_spawn_mobs::OnMyPingDead" => ins_nyd1_spawn_mobs_onmypingdead,
        "ins_nyd1_spawn_mobs::OnMyRhynDead" => ins_nyd1_spawn_mobs_onmyrhyndead,
        "ins_nyd1_spawn_mobs::OnMyTreeDead" => ins_nyd1_spawn_mobs_onmytreedead,
        "ins_nyd2_spawn_mobs::OnInstanceInit" => ins_nyd2_spawn_mobs_oninstanceinit,
        "ins_nyd2_spawn_mobs::OnMyDarkshaDead" => ins_nyd2_spawn_mobs_onmydarkshadead,
        "ins_nyd2_spawn_mobs::OnMyPhyDead" => ins_nyd2_spawn_mobs_onmyphydead,
        "ins_nyd2_spawn_mobs::OnMyPingDead" => ins_nyd2_spawn_mobs_onmypingdead,
        "ins_nyd2_spawn_mobs::OnMyRhynDead" => ins_nyd2_spawn_mobs_onmyrhyndead,
        "ins_nyd_1f_timer::OnDisable" => ins_nyd_1f_timer_ondisable,
        "ins_nyd_1f_timer::OnEnable" => ins_nyd_1f_timer_onenable,
        "ins_nyd_1f_timer::OnInstanceInit" => ins_nyd_1f_timer_oninstanceinit,
        "ins_nyd_1f_timer::OnTimer1200000" => ins_nyd_1f_timer_ontimer1200000,
        "ins_nyd_1f_timer::OnTimer1500000" => ins_nyd_1f_timer_ontimer1500000,
        "ins_nyd_1f_timer::OnTimer1800000" => ins_nyd_1f_timer_ontimer1800000,
        "ins_nyd_1f_timer::OnTimer1830000" => ins_nyd_1f_timer_ontimer1830000,
        "ins_nyd_1f_timer::OnTimer1850000" => ins_nyd_1f_timer_ontimer1850000,
        "ins_nyd_1f_timer::OnTimer900000" => ins_nyd_1f_timer_ontimer900000,
        "nyd_2f_boss_enter::OnTouch" => nyd_2f_boss_enter_ontouch,
        "nyd_2f_boss_enter_call::OnDisable" => nyd_2f_boss_enter_call_ondisable,
        "nyd_2f_boss_enter_call::OnEnable" => nyd_2f_boss_enter_call_onenable,
        "nyd_2f_boss_enter_call::OnInstanceInit" => nyd_2f_boss_enter_call_oninstanceinit,
        "nyd_2f_boss_enter_call::OnMyMobDead" => nyd_2f_boss_enter_call_onmymobdead,
        "nyd_2f_boss_enter_call::OnTimer180000" => nyd_2f_boss_enter_call_ontimer180000,
        "nyd_2f_boss_enter_call::OnWarpColor" => nyd_2f_boss_enter_call_onwarpcolor,
        "nyd_2f_boss_enter_logic::OnDisable" => nyd_2f_boss_enter_logic_ondisable,
        "nyd_2f_boss_enter_logic::OnEnable" => nyd_2f_boss_enter_logic_onenable,
        "nyd_2f_boss_enter_logic::OnInstanceInit" => nyd_2f_boss_enter_logic_oninstanceinit,
        "nyd_2f_boss_enter_logic::OnTimer180000" => nyd_2f_boss_enter_logic_ontimer180000,
        "nyd_2f_ddr_control::OnTouch" => nyd_2f_ddr_control_ontouch,
        "nyd_2f_enter::OnTouch_" => nyd_2f_enter_ontouch,
        "nyd_2f_enter_broad::OnDisable" => nyd_2f_enter_broad_ondisable,
        "nyd_2f_enter_broad::OnEnable" => nyd_2f_enter_broad_onenable,
        "nyd_2f_enter_broad::OnInstanceInit" => nyd_2f_enter_broad_oninstanceinit,
        "nyd_2f_enter_broad::OnTimer12000" => nyd_2f_enter_broad_ontimer12000,
        "nyd_2f_enter_broad::OnTimer15000" => nyd_2f_enter_broad_ontimer15000,
        "nyd_2f_enter_broad::OnTimer18000" => nyd_2f_enter_broad_ontimer18000,
        "nyd_2f_red::OnDisable" => nyd_2f_red_ondisable,
        "nyd_2f_red::OnEnable" => nyd_2f_red_onenable,
        "nyd_2f_red::OnInstanceInit" => nyd_2f_red_oninstanceinit,
        "nyd_2f_red::OnTimer10000" => nyd_2f_red_ontimer10000,
        "nyd_2f_red::OnTouch" => nyd_2f_red_ontouch,
        "nyd_2f_red_c::OnDisable" => nyd_2f_red_c_ondisable,
        "nyd_2f_red_c::OnEnable" => nyd_2f_red_c_onenable,
        "nyd_2f_red_c::OnInstanceInit" => nyd_2f_red_c_oninstanceinit,
        "nyd_2f_red_c::OnMyMobDead" => nyd_2f_red_c_onmymobdead,
        "nyd_2f_red_c::OnTimer180000" => nyd_2f_red_c_ontimer180000,
        "nyd_2f_red_warp1::OnDisable" => nyd_2f_red_warp1_ondisable,
        "nyd_2f_red_warp1::OnEnable" => nyd_2f_red_warp1_onenable,
        "nyd_2f_red_warp1::OnInstanceInit" => nyd_2f_red_warp1_oninstanceinit,
        "nyd_2f_red_warp1::OnTouch" => nyd_2f_red_warp1_ontouch,
        "nyd_call_mon_1::OnDisable" => nyd_call_mon_1_ondisable,
        "nyd_call_mon_1::OnEnable" => nyd_call_mon_1_onenable,
        "nyd_call_mon_1::OnInstanceInit" => nyd_call_mon_1_oninstanceinit,
        "nyd_call_mon_1::OnMyMobDead" => nyd_call_mon_1_onmymobdead,
        "nyd_to2f_warp::OnDisable" => nyd_to2f_warp_ondisable,
        "nyd_to2f_warp::OnEnable" => nyd_to2f_warp_onenable,
        "nyd_to2f_warp::OnInstanceInit" => nyd_to2f_warp_oninstanceinit,
        "nyd_to2f_warp::OnTouch" => nyd_to2f_warp_ontouch,
        "trap#edq2::OnTouch_" => trap_edq2_ontouch,
        "trap#s_edq::OnTouch_" => trap_s_edq_ontouch,
    }
}
