#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "#arn_timer_pt" => arn_timer_pt,
        "Helper#party" => helper_party,
        "Ponox" => ponox,
        "Slipslowrun#party" => slipslowrun_party,
        "Staff#party-1" => staff_party_1,
        "Staff#party-2" => staff_party_2,
        "alloff#pt" => alloff_pt,
        "arena_out" => arena_out,
        "arena_p" => arena_p,
        "arn_warp_pt" => arn_warp_pt,
        "cast#pt" => cast_pt,
        "force_01mob#party" => force_01mob_party,
        "force_01start#party" => force_01start_party,
        "force_02mob#party" => force_02mob_party,
        "force_02start#party" => force_02start_party,
        "force_03mob#party" => force_03mob_party,
        "force_03start#party" => force_03start_party,
        "force_04mob#party" => force_04mob_party,
        "force_04start#party" => force_04start_party,
        "force_05mob#party" => force_05mob_party,
        "force_05start#party" => force_05start_party,
        "force_06mob#party" => force_06mob_party,
        "force_06start#party" => force_06start_party,
        "force_07mob#party" => force_07mob_party,
        "force_07start#party" => force_07start_party,
        "force_08mob#party" => force_08mob_party,
        "force_08start#party" => force_08start_party,
        "force_09_exit" => force_09_exit,
        "force_09mob#party" => force_09mob_party,
        "force_09start#party" => force_09start_party,
        "force_10mob-1#party" => force_10mob_1_party,
        "force_10mob-2#party" => force_10mob_2_party,
        "force_10start#party" => force_10start_party,
        "force_exit#party" => force_exit_party,
        "force_exitmob#party" => force_exitmob_party,
        "toarena#party" => toarena_party,
        "toout#party" => toout_party,
    }
    events {
        "#arn_timer_pt::OnEnter" => arn_timer_pt_onenter,
        "#arn_timer_pt::OnStop" => arn_timer_pt_onstop,
        "#arn_timer_pt::OnTimer2000" => arn_timer_pt_ontimer2000,
        "#arn_timer_pt::OnTimer3000" => arn_timer_pt_ontimer3000,
        "#arn_timer_pt::OnTimer4000" => arn_timer_pt_ontimer4000,
        "#arn_timer_pt::OnTimer60000" => arn_timer_pt_ontimer60000,
        "Helper#party::OnEnter" => helper_party_onenter,
        "Helper#party::OnInit" => helper_party_oninit,
        "Helper#party::OnStop" => helper_party_onstop,
        "Ponox::OnInit" => ponox_oninit,
        "Ponox::OnStart" => ponox_onstart,
        "Ponox::OnStartArena" => ponox_onstartarena,
        "Slipslowrun#party::On01_End" => slipslowrun_party_on01_end,
        "Slipslowrun#party::On02_End" => slipslowrun_party_on02_end,
        "Slipslowrun#party::On03_End" => slipslowrun_party_on03_end,
        "Slipslowrun#party::On04_End1" => slipslowrun_party_on04_end1,
        "Slipslowrun#party::On04_End2" => slipslowrun_party_on04_end2,
        "Slipslowrun#party::On04_Start" => slipslowrun_party_on04_start,
        "Slipslowrun#party::On05_End1" => slipslowrun_party_on05_end1,
        "Slipslowrun#party::On05_End2" => slipslowrun_party_on05_end2,
        "Slipslowrun#party::On06_End" => slipslowrun_party_on06_end,
        "Slipslowrun#party::On07_End" => slipslowrun_party_on07_end,
        "Slipslowrun#party::On08_End" => slipslowrun_party_on08_end,
        "Slipslowrun#party::On09_End" => slipslowrun_party_on09_end,
        "Slipslowrun#party::On10_End" => slipslowrun_party_on10_end,
        "Slipslowrun#party::OnFail" => slipslowrun_party_onfail,
        "Slipslowrun#party::OnStart" => slipslowrun_party_onstart,
        "Slipslowrun#party::OnTimer120000" => slipslowrun_party_ontimer120000,
        "Slipslowrun#party::OnTimer180000" => slipslowrun_party_ontimer180000,
        "Slipslowrun#party::OnTimer2000" => slipslowrun_party_ontimer2000,
        "Slipslowrun#party::OnTimer240000" => slipslowrun_party_ontimer240000,
        "Slipslowrun#party::OnTimer3000" => slipslowrun_party_ontimer3000,
        "Slipslowrun#party::OnTimer300000" => slipslowrun_party_ontimer300000,
        "Slipslowrun#party::OnTimer360000" => slipslowrun_party_ontimer360000,
        "Slipslowrun#party::OnTimer4000" => slipslowrun_party_ontimer4000,
        "Slipslowrun#party::OnTimer420000" => slipslowrun_party_ontimer420000,
        "Slipslowrun#party::OnTimer480000" => slipslowrun_party_ontimer480000,
        "Slipslowrun#party::OnTimer5000" => slipslowrun_party_ontimer5000,
        "Slipslowrun#party::OnTimer540000" => slipslowrun_party_ontimer540000,
        "Slipslowrun#party::OnTimer60000" => slipslowrun_party_ontimer60000,
        "Slipslowrun#party::OnTimer600000" => slipslowrun_party_ontimer600000,
        "Slipslowrun#party::OnTimer605000" => slipslowrun_party_ontimer605000,
        "Slipslowrun#party::OnTimer606000" => slipslowrun_party_ontimer606000,
        "Slipslowrun#party::OnTimer607000" => slipslowrun_party_ontimer607000,
        "Slipslowrun#party::OnTimer608000" => slipslowrun_party_ontimer608000,
        "Slipslowrun#party::OnTimer609000" => slipslowrun_party_ontimer609000,
        "Slipslowrun#party::OnTimer610000" => slipslowrun_party_ontimer610000,
        "Slipslowrun#party::OnTimer611000" => slipslowrun_party_ontimer611000,
        "Slipslowrun#party::OnTimer612000" => slipslowrun_party_ontimer612000,
        "Slipslowrun#party::OnTimer613000" => slipslowrun_party_ontimer613000,
        "Slipslowrun#party::OnTimer614000" => slipslowrun_party_ontimer614000,
        "Slipslowrun#party::OnTimerOff" => slipslowrun_party_ontimeroff,
        "alloff#pt::OnEnable" => alloff_pt_onenable,
        "alloff#pt::OnInit" => alloff_pt_oninit,
        "arena_out::OnTouch_" => arena_out_ontouch,
        "arena_p::On04_Start" => arena_p_on04_start,
        "arena_p::On06_Start" => arena_p_on06_start,
        "arena_p::On07_Start" => arena_p_on07_start,
        "arena_p::On08_Start" => arena_p_on08_start,
        "arena_p::On09_Start" => arena_p_on09_start,
        "arena_p::On10_Start" => arena_p_on10_start,
        "arena_p::OnExit" => arena_p_onexit,
        "arena_p::OnReset" => arena_p_onreset,
        "arena_p::OnStart" => arena_p_onstart,
        "arn_warp_pt::OnOut" => arn_warp_pt_onout,
        "cast#pt::OnNomal1" => cast_pt_onnomal1,
        "cast#pt::OnNomal2" => cast_pt_onnomal2,
        "cast#pt::OnTimeOver1" => cast_pt_ontimeover1,
        "cast#pt::OnTimeOver2" => cast_pt_ontimeover2,
        "force_01mob#party::OnEnable" => force_01mob_party_onenable,
        "force_01mob#party::OnMyMobDead" => force_01mob_party_onmymobdead,
        "force_01mob#party::OnReset" => force_01mob_party_onreset,
        "force_01start#party::OnTouch_" => force_01start_party_ontouch,
        "force_02mob#party::OnEnable" => force_02mob_party_onenable,
        "force_02mob#party::OnMyMobDead" => force_02mob_party_onmymobdead,
        "force_02mob#party::OnReset" => force_02mob_party_onreset,
        "force_02start#party::OnTouch_" => force_02start_party_ontouch,
        "force_03mob#party::OnEnable" => force_03mob_party_onenable,
        "force_03mob#party::OnMyMobDead" => force_03mob_party_onmymobdead,
        "force_03mob#party::OnReset" => force_03mob_party_onreset,
        "force_03start#party::OnTouch_" => force_03start_party_ontouch,
        "force_04mob#party::OnEnable" => force_04mob_party_onenable,
        "force_04mob#party::OnMyMobDead" => force_04mob_party_onmymobdead,
        "force_04mob#party::OnReset" => force_04mob_party_onreset,
        "force_04start#party::OnTouch_" => force_04start_party_ontouch,
        "force_05mob#party::OnEnable" => force_05mob_party_onenable,
        "force_05mob#party::OnMyMobDead" => force_05mob_party_onmymobdead,
        "force_05mob#party::OnReset" => force_05mob_party_onreset,
        "force_05start#party::OnTouch_" => force_05start_party_ontouch,
        "force_06mob#party::OnEnable" => force_06mob_party_onenable,
        "force_06mob#party::OnMyMobDead" => force_06mob_party_onmymobdead,
        "force_06mob#party::OnReset" => force_06mob_party_onreset,
        "force_06start#party::OnTouch_" => force_06start_party_ontouch,
        "force_07mob#party::OnEnable" => force_07mob_party_onenable,
        "force_07mob#party::OnMyMobDead" => force_07mob_party_onmymobdead,
        "force_07mob#party::OnReset" => force_07mob_party_onreset,
        "force_07start#party::OnTouch_" => force_07start_party_ontouch,
        "force_08mob#party::OnEnable" => force_08mob_party_onenable,
        "force_08mob#party::OnMyMobDead" => force_08mob_party_onmymobdead,
        "force_08mob#party::OnReset" => force_08mob_party_onreset,
        "force_08start#party::OnTouch_" => force_08start_party_ontouch,
        "force_09_exit::OnTouch_" => force_09_exit_ontouch,
        "force_09mob#party::OnEnable" => force_09mob_party_onenable,
        "force_09mob#party::OnMyMobDead" => force_09mob_party_onmymobdead,
        "force_09mob#party::OnReset" => force_09mob_party_onreset,
        "force_09start#party::OnTouch_" => force_09start_party_ontouch,
        "force_10mob-1#party::OnEnable" => force_10mob_1_party_onenable,
        "force_10mob-1#party::OnMyMobDead" => force_10mob_1_party_onmymobdead,
        "force_10mob-1#party::OnReset" => force_10mob_1_party_onreset,
        "force_10mob-2#party::OnEnable" => force_10mob_2_party_onenable,
        "force_10mob-2#party::OnMyMobDead" => force_10mob_2_party_onmymobdead,
        "force_10mob-2#party::OnReset" => force_10mob_2_party_onreset,
        "force_10start#party::OnTouch_" => force_10start_party_ontouch,
        "force_exit#party::OnTouch_" => force_exit_party_ontouch,
        "force_exitmob#party::OnEnable" => force_exitmob_party_onenable,
        "force_exitmob#party::OnMyMobDead" => force_exitmob_party_onmymobdead,
        "force_exitmob#party::OnReset" => force_exitmob_party_onreset,
        "toarena#party::OnEnter" => toarena_party_onenter,
        "toarena#party::OnInit" => toarena_party_oninit,
        "toarena#party::OnTouch_" => toarena_party_ontouch,
        "toout#party::OnEnter" => toout_party_onenter,
        "toout#party::OnInit" => toout_party_oninit,
        "toout#party::OnStop" => toout_party_onstop,
        "toout#party::OnTimer" => toout_party_ontimer,
        "toout#party::OnTimer60000" => toout_party_ontimer60000,
        "toout#party::OnTimer70000" => toout_party_ontimer70000,
        "toout#party::OnTouch_" => toout_party_ontouch,
    }
}
