#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;

pub use part_01::*;
pub use part_02::*;

script_sdk_2::script_module! {
    npcs {
        "Baphomet#prst" => baphomet_prst,
        "Dark Lord#prst" => dark_lord_prst,
        "Deviruchi#prst" => deviruchi_prst,
        "Doppelganger#prst" => doppelganger_prst,
        "High Bishop#prst" => high_bishop_prst,
        "Mummy1_1" => mummy1_1,
        "Mummy2_1" => mummy2_1,
        "Mummy3_1" => mummy3_1,
        "Mummy_Generator" => mummy_generator,
        "Peter S. Alberto" => peter_s_alberto,
        "Peter S. Alberto#2" => peter_s_alberto_2,
        "Sister Cecilia" => sister_cecilia,
        "Z_C#prst" => z_c_prst,
        "Zombie Info" => zombie_info,
        "Zombie1_1" => zombie1_1,
        "Zombie2_1" => zombie2_1,
        "Zombie3_1" => zombie3_1,
        "Zombie4_1" => zombie4_1,
        "Zombie5_1" => zombie5_1,
        "Zombie_Generator#prst" => zombie_generator_prst,
        "prst1_1" => prst1_1,
        "prst2_1" => prst2_1,
        "prst3_1" => prst3_1,
    }
    events {
        "Baphomet#prst::OnTouch_" => baphomet_prst_ontouch,
        "Dark Lord#prst::OnTouch_" => dark_lord_prst_ontouch,
        "Deviruchi#prst::OnTouch_" => deviruchi_prst_ontouch,
        "Doppelganger#prst::OnTouch_" => doppelganger_prst_ontouch,
        "Mummy1_1::OnDisable" => mummy1_1_ondisable,
        "Mummy1_1::OnEnable" => mummy1_1_onenable,
        "Mummy1_1::OnInit" => mummy1_1_oninit,
        "Mummy1_1::OnTouch_" => mummy1_1_ontouch,
        "Mummy2_1::OnDisable" => mummy2_1_ondisable,
        "Mummy2_1::OnEnable" => mummy2_1_onenable,
        "Mummy2_1::OnInit" => mummy2_1_oninit,
        "Mummy2_1::OnTouch_" => mummy2_1_ontouch,
        "Mummy3_1::OnDisable" => mummy3_1_ondisable,
        "Mummy3_1::OnEnable" => mummy3_1_onenable,
        "Mummy3_1::OnInit" => mummy3_1_oninit,
        "Mummy3_1::OnTouch_" => mummy3_1_ontouch,
        "Mummy_Generator::OnDisable" => mummy_generator_ondisable,
        "Mummy_Generator::OnEnable" => mummy_generator_onenable,
        "Mummy_Generator::OnInit" => mummy_generator_oninit,
        "Mummy_Generator::Onm1" => mummy_generator_onm1,
        "Mummy_Generator::Onm2" => mummy_generator_onm2,
        "Mummy_Generator::Onm3" => mummy_generator_onm3,
        "Peter S. Alberto#2::OnDisable" => peter_s_alberto_2_ondisable,
        "Peter S. Alberto#2::OnEnable" => peter_s_alberto_2_onenable,
        "Peter S. Alberto#2::OnInit" => peter_s_alberto_2_oninit,
        "Peter S. Alberto::OnDisable" => peter_s_alberto_ondisable,
        "Peter S. Alberto::OnEnable" => peter_s_alberto_onenable,
        "Z_C#prst::OnMyMobDead" => z_c_prst_onmymobdead,
        "Zombie Info::OnTouch_" => zombie_info_ontouch,
        "Zombie1_1::OnDisable" => zombie1_1_ondisable,
        "Zombie1_1::OnEnable" => zombie1_1_onenable,
        "Zombie1_1::OnInit" => zombie1_1_oninit,
        "Zombie1_1::OnTouch_" => zombie1_1_ontouch,
        "Zombie2_1::OnDisable" => zombie2_1_ondisable,
        "Zombie2_1::OnEnable" => zombie2_1_onenable,
        "Zombie2_1::OnInit" => zombie2_1_oninit,
        "Zombie2_1::OnTouch_" => zombie2_1_ontouch,
        "Zombie3_1::OnDisable" => zombie3_1_ondisable,
        "Zombie3_1::OnEnable" => zombie3_1_onenable,
        "Zombie3_1::OnInit" => zombie3_1_oninit,
        "Zombie3_1::OnTouch_" => zombie3_1_ontouch,
        "Zombie4_1::OnDisable" => zombie4_1_ondisable,
        "Zombie4_1::OnEnable" => zombie4_1_onenable,
        "Zombie4_1::OnInit" => zombie4_1_oninit,
        "Zombie4_1::OnTouch_" => zombie4_1_ontouch,
        "Zombie5_1::OnDisable" => zombie5_1_ondisable,
        "Zombie5_1::OnEnable" => zombie5_1_onenable,
        "Zombie5_1::OnInit" => zombie5_1_oninit,
        "Zombie5_1::OnTouch_" => zombie5_1_ontouch,
        "Zombie_Generator#prst::OnDisable" => zombie_generator_prst_ondisable,
        "Zombie_Generator#prst::OnEnable" => zombie_generator_prst_onenable,
        "Zombie_Generator#prst::OnInit" => zombie_generator_prst_oninit,
        "Zombie_Generator#prst::OnTimer300000" => zombie_generator_prst_ontimer300000,
        "Zombie_Generator#prst::OnTimer300500" => zombie_generator_prst_ontimer300500,
        "Zombie_Generator#prst::OnTimer301500" => zombie_generator_prst_ontimer301500,
        "Zombie_Generator#prst::OnTimer302000" => zombie_generator_prst_ontimer302000,
        "Zombie_Generator#prst::Onm1" => zombie_generator_prst_onm1,
        "Zombie_Generator#prst::Onm2" => zombie_generator_prst_onm2,
        "Zombie_Generator#prst::Onm3" => zombie_generator_prst_onm3,
        "Zombie_Generator#prst::Onm4" => zombie_generator_prst_onm4,
        "Zombie_Generator#prst::Onm5" => zombie_generator_prst_onm5,
        "prst1_1::OnTouch_" => prst1_1_ontouch,
        "prst2_1::OnTouch_" => prst2_1_ontouch,
        "prst3_1::OnTouch_" => prst3_1_ontouch,
    }
}
