pub mod arena_point;
pub mod arena_room;

script_sdk_2::script_module! {
    npcs {
        "#arena_1039" => arena_room::arena_1039,
        "Arena Manager#arena" => arena_room::arena_manager_arena,
        "Arena Point Manager" => arena_point::arena_point_manager,
        "Arena Record Staff" => arena_room::arena_record_staff,
        "Givu#arena" => arena_room::givu_arena,
        "Helper Ben" => arena_room::helper_ben,
        "Helper Epin" => arena_room::helper_epin,
        "Helper Lonik" => arena_room::helper_lonik,
        "Helper Lunic" => arena_room::helper_lunic,
        "Helper Pat" => arena_room::helper_pat,
        "Helper Vicious" => arena_room::helper_vicious,
        "Live Broadcast#arena" => arena_room::live_broadcast_arena,
        "Picture Manager#arena" => arena_room::picture_manager_arena,
        "Reward Manager#arena" => arena_room::reward_manager_arena,
        "Teleporter#arena" => arena_room::teleporter_arena,
        "Vendigos" => arena_room::vendigos,
        "npctime#arena" => arena_room::npctime_arena,
    }
    events {
        "#arena_1039::OnBest" => arena_room::arena_1039_onbest,
        "#arena_1039::OnHeart" => arena_room::arena_1039_onheart,
        "#arena_1039::OnInit" => arena_room::arena_1039_oninit,
        "#arena_1039::OnKik" => arena_room::arena_1039_onkik,
        "#arena_1039::OnKis" => arena_room::arena_1039_onkis,
        "#arena_1039::OnOmg" => arena_room::arena_1039_onomg,
        "#arena_1039::OnSci" => arena_room::arena_1039_onsci,
        "Vendigos::OnLineRec_50" => arena_room::vendigos_onlinerec_50,
        "Vendigos::OnLineRec_60" => arena_room::vendigos_onlinerec_60,
        "Vendigos::OnLineRec_70" => arena_room::vendigos_onlinerec_70,
        "Vendigos::OnLineRec_80" => arena_room::vendigos_onlinerec_80,
        "Vendigos::OnLineRec_pt" => arena_room::vendigos_onlinerec_pt,
        "npctime#arena::OnStart" => arena_room::npctime_arena_onstart,
        "npctime#arena::OnStop" => arena_room::npctime_arena_onstop,
        "npctime#arena::OnTimer10000" => arena_room::npctime_arena_ontimer10000,
        "npctime#arena::OnTimer15000" => arena_room::npctime_arena_ontimer15000,
        "npctime#arena::OnTimer17000" => arena_room::npctime_arena_ontimer17000,
        "npctime#arena::OnTimer18000" => arena_room::npctime_arena_ontimer18000,
        "npctime#arena::OnTimer19000" => arena_room::npctime_arena_ontimer19000,
        "npctime#arena::OnTimer2000" => arena_room::npctime_arena_ontimer2000,
        "npctime#arena::OnTimer20000" => arena_room::npctime_arena_ontimer20000,
        "npctime#arena::OnTimer25000" => arena_room::npctime_arena_ontimer25000,
        "npctime#arena::OnTimer27000" => arena_room::npctime_arena_ontimer27000,
        "npctime#arena::OnTimer28000" => arena_room::npctime_arena_ontimer28000,
        "npctime#arena::OnTimer29000" => arena_room::npctime_arena_ontimer29000,
        "npctime#arena::OnTimer30000" => arena_room::npctime_arena_ontimer30000,
        "npctime#arena::OnTimer35000" => arena_room::npctime_arena_ontimer35000,
        "npctime#arena::OnTimer37000" => arena_room::npctime_arena_ontimer37000,
        "npctime#arena::OnTimer38000" => arena_room::npctime_arena_ontimer38000,
        "npctime#arena::OnTimer39000" => arena_room::npctime_arena_ontimer39000,
        "npctime#arena::OnTimer40000" => arena_room::npctime_arena_ontimer40000,
        "npctime#arena::OnTimer45000" => arena_room::npctime_arena_ontimer45000,
        "npctime#arena::OnTimer47000" => arena_room::npctime_arena_ontimer47000,
        "npctime#arena::OnTimer48000" => arena_room::npctime_arena_ontimer48000,
        "npctime#arena::OnTimer49000" => arena_room::npctime_arena_ontimer49000,
        "npctime#arena::OnTimer5000" => arena_room::npctime_arena_ontimer5000,
        "npctime#arena::OnTimer50000" => arena_room::npctime_arena_ontimer50000,
        "npctime#arena::OnTimer55000" => arena_room::npctime_arena_ontimer55000,
        "npctime#arena::OnTimer57000" => arena_room::npctime_arena_ontimer57000,
        "npctime#arena::OnTimer58000" => arena_room::npctime_arena_ontimer58000,
        "npctime#arena::OnTimer59000" => arena_room::npctime_arena_ontimer59000,
        "npctime#arena::OnTimer60000" => arena_room::npctime_arena_ontimer60000,
        "npctime#arena::OnTimer62000" => arena_room::npctime_arena_ontimer62000,
        "npctime#arena::OnTimer7000" => arena_room::npctime_arena_ontimer7000,
        "npctime#arena::OnTimer8000" => arena_room::npctime_arena_ontimer8000,
        "npctime#arena::OnTimer9000" => arena_room::npctime_arena_ontimer9000,
    }
}
