pub mod airships;
pub mod einbroch;
pub mod hugel;
pub mod izlude;
pub mod lighthalzen;
pub mod rachel;
pub mod yuno;

script_sdk_2::script_module! {
    npcs {
        "#AirshipWarp-1" => airships::airshipwarp_1,
        "#AirshipWarp-3" => airships::airshipwarp_3,
        "Aanos#01airplane" => airships::aanos_01airplane,
        "Airport Staff#airport1a" => einbroch::airport_staff_airport1a,
        "Airport Staff#lhz_air1a" => lighthalzen::airport_staff_lhz_air1a,
        "Airport Staff#y_air1a" => yuno::airport_staff_y_air1a,
        "Airship Crew#ein-1" => airships::airship_crew_ein_1,
        "Airship Staff#airplane" => airships::airship_staff_airplane,
        "Airship Staff#airplane01" => airships::airship_staff_airplane01,
        "Airship Staff#ein01" => einbroch::airship_staff_ein01,
        "Airship Staff#yuno01" => yuno::airship_staff_yuno01,
        "Airship Staff#yuno02" => yuno::airship_staff_yuno02,
        "Airship_Staff_izlude" => izlude::airship_staff_izlude,
        "Apple Merchant#air01" => airships::apple_merchant_air01,
        "Apple Merchant#airplane" => airships::apple_merchant_airplane,
        "Arrival Staff#airport2a" => einbroch::arrival_staff_airport2a,
        "Arrival Staff#lhz_air2a" => lighthalzen::arrival_staff_lhz_air2a,
        "Arrival Staff#y_air2a" => yuno::arrival_staff_y_air2a,
        "Clarice" => airships::clarice,
        "Dianne#01airplane_01" => airships::dianne_01airplane_01,
        "Domestic Boarding" => yuno::domestic_boarding,
        "Domestic_Airship" => airships::domestic_airship,
        "Exit#airplane1a" => airships::exit_airplane1a,
        "Exit#airplane_011a" => airships::exit_airplane_011a,
        "International Boarding" => yuno::international_boarding,
        "International_Airship" => airships::international_airship,
        "Maelin#01airplane" => airships::maelin_01airplane,
        "Mendel#01airplane_01" => airships::mendel_01airplane_01,
        "Nils#ein" => airships::nils_ein,
        "Pilot#airplane" => airships::pilot_airplane,
        "Pilot#airplane_01" => airships::pilot_airplane_01,
        "Swordsman Shimizu#air_01" => airships::swordsman_shimizu_air_01,
        "Umbala Kid#ein_p" => airships::umbala_kid_ein_p,
        "Umbala Lady#ein_p" => airships::umbala_lady_ein_p,
        "Umbala Man#ein_p" => airships::umbala_man_ein_p,
        "Zerta#01airplane" => airships::zerta_01airplane,
        "toairplane#hugel" => hugel::toairplane_hugel,
        "toairplane#rachel" => rachel::toairplane_rachel,
    }
    events {
        "#AirshipWarp-1::OnHide" => airships::airshipwarp_1_onhide,
        "#AirshipWarp-1::OnInit" => airships::airshipwarp_1_oninit,
        "#AirshipWarp-1::OnTouch_" => airships::airshipwarp_1_ontouch,
        "#AirshipWarp-1::OnUnhide" => airships::airshipwarp_1_onunhide,
        "#AirshipWarp-3::OnHide" => airships::airshipwarp_3_onhide,
        "#AirshipWarp-3::OnInit" => airships::airshipwarp_3_oninit,
        "#AirshipWarp-3::OnTouch_" => airships::airshipwarp_3_ontouch,
        "#AirshipWarp-3::OnUnhide" => airships::airshipwarp_3_onunhide,
        "Dianne#01airplane_01::OnTouch_" => airships::dianne_01airplane_01_ontouch,
        "Domestic_Airship::OnInit" => airships::domestic_airship_oninit,
        "Domestic_Airship::OnTimer100000" => airships::domestic_airship_ontimer100000,
        "Domestic_Airship::OnTimer130000" => airships::domestic_airship_ontimer130000,
        "Domestic_Airship::OnTimer140000" => airships::domestic_airship_ontimer140000,
        "Domestic_Airship::OnTimer150000" => airships::domestic_airship_ontimer150000,
        "Domestic_Airship::OnTimer160000" => airships::domestic_airship_ontimer160000,
        "Domestic_Airship::OnTimer180000" => airships::domestic_airship_ontimer180000,
        "Domestic_Airship::OnTimer20000" => airships::domestic_airship_ontimer20000,
        "Domestic_Airship::OnTimer210000" => airships::domestic_airship_ontimer210000,
        "Domestic_Airship::OnTimer220000" => airships::domestic_airship_ontimer220000,
        "Domestic_Airship::OnTimer230000" => airships::domestic_airship_ontimer230000,
        "Domestic_Airship::OnTimer240000" => airships::domestic_airship_ontimer240000,
        "Domestic_Airship::OnTimer260000" => airships::domestic_airship_ontimer260000,
        "Domestic_Airship::OnTimer290000" => airships::domestic_airship_ontimer290000,
        "Domestic_Airship::OnTimer300000" => airships::domestic_airship_ontimer300000,
        "Domestic_Airship::OnTimer310000" => airships::domestic_airship_ontimer310000,
        "Domestic_Airship::OnTimer320000" => airships::domestic_airship_ontimer320000,
        "Domestic_Airship::OnTimer340000" => airships::domestic_airship_ontimer340000,
        "Domestic_Airship::OnTimer370000" => airships::domestic_airship_ontimer370000,
        "Domestic_Airship::OnTimer380000" => airships::domestic_airship_ontimer380000,
        "Domestic_Airship::OnTimer390000" => airships::domestic_airship_ontimer390000,
        "Domestic_Airship::OnTimer400000" => airships::domestic_airship_ontimer400000,
        "Domestic_Airship::OnTimer420000" => airships::domestic_airship_ontimer420000,
        "Domestic_Airship::OnTimer450000" => airships::domestic_airship_ontimer450000,
        "Domestic_Airship::OnTimer460000" => airships::domestic_airship_ontimer460000,
        "Domestic_Airship::OnTimer470000" => airships::domestic_airship_ontimer470000,
        "Domestic_Airship::OnTimer480000" => airships::domestic_airship_ontimer480000,
        "Domestic_Airship::OnTimer50000" => airships::domestic_airship_ontimer50000,
        "Domestic_Airship::OnTimer60000" => airships::domestic_airship_ontimer60000,
        "Domestic_Airship::OnTimer70000" => airships::domestic_airship_ontimer70000,
        "Domestic_Airship::OnTimer80000" => airships::domestic_airship_ontimer80000,
        "International_Airship::OnEnable" => airships::international_airship_onenable,
        "International_Airship::OnInit" => airships::international_airship_oninit,
        "International_Airship::OnTimer105000" => airships::international_airship_ontimer105000,
        "International_Airship::OnTimer130000" => airships::international_airship_ontimer130000,
        "International_Airship::OnTimer140000" => airships::international_airship_ontimer140000,
        "International_Airship::OnTimer150000" => airships::international_airship_ontimer150000,
        "International_Airship::OnTimer160000" => airships::international_airship_ontimer160000,
        "International_Airship::OnTimer185000" => airships::international_airship_ontimer185000,
        "International_Airship::OnTimer210000" => airships::international_airship_ontimer210000,
        "International_Airship::OnTimer220000" => airships::international_airship_ontimer220000,
        "International_Airship::OnTimer230000" => airships::international_airship_ontimer230000,
        "International_Airship::OnTimer240000" => airships::international_airship_ontimer240000,
        "International_Airship::OnTimer25000" => airships::international_airship_ontimer25000,
        "International_Airship::OnTimer50000" => airships::international_airship_ontimer50000,
        "International_Airship::OnTimer60000" => airships::international_airship_ontimer60000,
        "International_Airship::OnTimer70000" => airships::international_airship_ontimer70000,
        "International_Airship::OnTimer80000" => airships::international_airship_ontimer80000,
        "toairplane#hugel::OnTouch" => hugel::toairplane_hugel_ontouch,
        "toairplane#rachel::OnTouch" => rachel::toairplane_rachel_ontouch,
    }
}
