// Generated by tools/scripts-import/convert_sdk2.py from npc/quests/seals/god_weapon_creation.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn grunburti_1_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_gid = Val::from(0);
    ctx.lines_as(
        "Dwarf Grunburti",
        args!["A human?!", "This land is full", "of your kind. What", "brings you here?"],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Dwarf Grunburti",
        args![
            "Living in Midgard and away from",
            "my home town is painful enough, let alone facing a whiny human. Leave me alone!"
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from(
                "Ask him about Dwarves.:Ask him what he is doing.:Request weapon creation.:Cancel.",
            )],
        )?);
        let mut matched1 = false;
        let no_case1 = !subject1.loosely_equals(&Val::from(1))
            && !subject1.loosely_equals(&Val::from(2))
            && !subject1.loosely_equals(&Val::from(3))
            && !subject1.loosely_equals(&Val::from(4));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "What's to know about Dwarves?",
                    "We're the toughest race. After all, we can live anywhere, no matter",
                    "how harsh the environment may be."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "I doubt your feeble mind can comprehend the how unendurable",
                    "it must be for you to live in my homeland, but you can try.",
                    "Try to imagine."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args!["Most of the knowledge and skills that you humans are so proud of were probably handed down from Dwarves."],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "This is especially true in the",
                    "case of smithing. Even the tools and weapons of the gods were made by my ancestors. You know that?"
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "We have the greatest knowlege and skills, but have accepted our fate to live in the cold, barren lands of the Giants."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Did you just ask what I am doing here? Mwahahaha! Waiting for any humans stupid enough to come",
                    "here so I can kick their ass!"
                ],
            )?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["Oh don't worry. I'd only humiliate myself by fighting with a weakling like you. Humans are so fragile, but they stubbornly cling to their arrogance and fight amongst", "each other."])?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["As a race, your people are just hopeless. I wouldn't even share the same continent with a human! But alas, I have no choice."])?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["The path to my hometown", "disappeared after the war 1,000 years ago. Somehow, I can no longer find the way through the Yggdrasil Tree that will take me back..."])?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "I'm stuck here in Midgard.",
                    "At least I was fortunate enough to find this cave. We Dwarves are most cozy living underground, after all."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            l_gid = ctx.call(Function::GetCharacterId, vec![Val::from(2)])?;
            if (((runtime::op(&ctx.var("$god1").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true()
                || runtime::op(&ctx.var("$god2").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                || runtime::op(&ctx.var("$god3").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                || runtime::op(&ctx.var("$god4").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
            {
                if ((((runtime::op(&ctx.var("$god1").get()?, ">=", &ctx.var("$@god_check1").get()?)?.is_true()
                    && runtime::op(&ctx.var("$god2").get()?, ">=", &ctx.var("$@god_check1").get()?)?.is_true())
                    && runtime::op(&ctx.var("$god3").get()?, ">=", &ctx.var("$@god_check1").get()?)?.is_true())
                    && runtime::op(&ctx.var("$god4").get()?, ">=", &ctx.var("$@god_check1").get()?)?.is_true())
                    && ctx
                        .call(
                            Function::GetGuildInfo,
                            vec![ctx.call(Function::GetCharacterId, vec![Val::from(2)])?, Val::from(2)],
                        )?
                        .loosely_equals(&Val::from(1)))
                {
                    ctx.lines_as(
                        "Dwarf Grunburti",
                        args![
                            "Hmm...",
                            "I'll need some things to make a weapon for you. What exactly were you interested in having?"
                        ],
                    )?;
                    ctx.next()?;
                    'b2: {
                        let subject2 = Val::from(runtime::select_values(
                            ctx,
                            &[Val::from("Brisingamen:Megingjard:Sleipnir:Mjolnir")],
                        )?);
                        let mut matched2 = false;
                        let no_case2 = !subject2.loosely_equals(&Val::from(1))
                            && !subject2.loosely_equals(&Val::from(2))
                            && !subject2.loosely_equals(&Val::from(3))
                            && !subject2.loosely_equals(&Val::from(4));
                        if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                            matched2 = true;
                        }
                        if matched2 {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "I will need...",
                                    "^0000FF4 Freya's Jewel",
                                    "4 Silver Ornament",
                                    "3 Snow Crystal",
                                    "3 Ripple",
                                    "3 Drifting Air",
                                    "2 Sapphire",
                                    "3 Pearl",
                                    "10 Opal",
                                    "5 Cursed Ruby",
                                    "20 Gold^000000",
                                    "1 Necklace^000000..."
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["However, the time for me to create this Brisingamen has not yet come. You'll have to wait until the seals are released. Mwahahaha!"])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                            matched2 = true;
                        }
                        if matched2 {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "I will need...",
                                    "^0000FF1 Gleipnir",
                                    "20 Gold",
                                    "10 Sapphire",
                                    "10 Oridecon",
                                    "1 Belt^000000"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["However, the seals on Megingjard have not yet been released. Until then, you'll have to wait! Bwahahaha!"])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                            matched2 = true;
                        }
                        if matched2 {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "I will need...",
                                    "^0000FF3 Wheel of the Unknown",
                                    "5 Feather of Angel Wing",
                                    "3 Sprit of Fish",
                                    "4 Amblem of the Sun God",
                                    "3 Breath of Spirit",
                                    "20 Gold",
                                    "10 Elunium",
                                    "1 Slotted Boots^000000"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["But even so, I can't create Sleipnir until the seals have been broken. Otherwise, you're out of luck, human. Hahaha~!"])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched2 && subject2.loosely_equals(&Val::from(4)) {
                            matched2 = true;
                        }
                        if matched2 {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "I will need...",
                                    "^0000FF2 Thor's Gauntlets",
                                    "4 Iron Maiden",
                                    "5 Wrath of Valkyrie",
                                    "5 Omen of Tempest",
                                    "5 Billow",
                                    "20 Oridecon",
                                    "5 Elunium",
                                    "40 Gold",
                                    "1 Stunner^000000"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["But I can't even create a replica of Mjolnir if the seals are still in place. Until they're released, you'll just have to wait. Bwahaha!"])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                    }
                }
                ctx.lines_as(
                    "Dwarf Grunburti",
                    args!["We Dwarves have too much pride to demonstrate our skills in front of a lowly human!"],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Dwarf Grunburti",
                    args!["Stop bothering me and get out of here! Go play with some monsters, you simple minded fool!"],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            if ctx
                .call(
                    Function::GetGuildInfo,
                    vec![ctx.call(Function::GetCharacterId, vec![Val::from(2)])?, Val::from(2)],
                )?
                .loosely_equals(&Val::from(0))
            {
                ctx.lines_as(
                    "Dwarf Grunburti",
                    args![
                        "I'll only present",
                        "my magnificent skills",
                        "to a human of incredibly",
                        "high standing!"
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Dwarf Grunburti",
                    args![
                        "Although I hate",
                        "most humans, I have",
                        "no choice but to respect the ones chosen by destiny. Go and bring your ^0000FFguildmaster^000000!"
                    ],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            ctx.lines_as(
                "Dwarf Grunburti",
                args!["Although it is very humiliating to present my valuable skills to a human being..."],
            )?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["All the seals have been released, and he who holds the Emperium is chosen by destiny. I have no choice but to respect you."])?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["First of all, I shall confirm whether or not you have brought all the necessary materials to forge a godly item! I hate it when humans come here without any purpose!"])?;
            ctx.next()?;
            if ((((((((((ctx.call(Function::CountItem, vec![Val::from(7073)])?.number()? > 3
                && ctx.call(Function::CountItem, vec![Val::from(7077)])?.number()? > 3)
                && ctx.call(Function::CountItem, vec![Val::from(7088)])?.number()? > 2)
                && ctx.call(Function::CountItem, vec![Val::from(7090)])?.number()? > 2)
                && ctx.call(Function::CountItem, vec![Val::from(7092)])?.number()? > 2)
                && ctx.call(Function::CountItem, vec![Val::from(726)])?.number()? > 1)
                && ctx.call(Function::CountItem, vec![Val::from(722)])?.number()? > 2)
                && ctx.call(Function::CountItem, vec![Val::from(727)])?.number()? > 9)
                && ctx.call(Function::CountItem, vec![Val::from(724)])?.number()? > 4)
                && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 19)
                && ctx.call(Function::CountItem, vec![Val::from(2603)])?.number()? > 0)
            {
                ctx.lines_as(
                    "Dwarf Grunburti",
                    args!["Hmm...", "I guess you", "want to have", "^0000FFBrisingamen^000000!"],
                )?;
                ctx.next()?;
            } else {
                if ((((ctx.call(Function::CountItem, vec![Val::from(7058)])?.number()? > 0
                    && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 19)
                    && ctx.call(Function::CountItem, vec![Val::from(726)])?.number()? > 9)
                    && ctx.call(Function::CountItem, vec![Val::from(984)])?.number()? > 9)
                    && ctx.call(Function::CountItem, vec![Val::from(2627)])?.number()? > 0)
                {
                    ctx.lines_as(
                        "Dwarf Grunburti",
                        args!["Hmm...", "I guess you", "want to have", "^0000FFMegingjard^000000!"],
                    )?;
                    ctx.next()?;
                } else {
                    if (((((((ctx.call(Function::CountItem, vec![Val::from(7076)])?.number()? > 2
                        && ctx.call(Function::CountItem, vec![Val::from(7079)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(7083)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(7086)])?.number()? > 3)
                        && ctx.call(Function::CountItem, vec![Val::from(7087)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 19)
                        && ctx.call(Function::CountItem, vec![Val::from(985)])?.number()? > 9)
                        && ctx.call(Function::CountItem, vec![Val::from(2406)])?.number()? > 0)
                    {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args!["Hmm...", "I guess you", "want to have", "^0000FFSleipnir^000000!"],
                        )?;
                        ctx.next()?;
                    } else {
                        if ((((((((ctx.call(Function::CountItem, vec![Val::from(7074)])?.number()? > 1
                            && ctx.call(Function::CountItem, vec![Val::from(7075)])?.number()? > 3)
                            && ctx.call(Function::CountItem, vec![Val::from(7078)])?.number()? > 4)
                            && ctx.call(Function::CountItem, vec![Val::from(7089)])?.number()? > 4)
                            && ctx.call(Function::CountItem, vec![Val::from(7091)])?.number()? > 4)
                            && ctx.call(Function::CountItem, vec![Val::from(984)])?.number()? > 19)
                            && ctx.call(Function::CountItem, vec![Val::from(985)])?.number()? > 4)
                            && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 39)
                            && ctx.call(Function::CountItem, vec![Val::from(1522)])?.number()? > 0)
                        {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args!["Hmm...", "I guess you", "want to have", "^0000FFMjolnir^000000!"],
                            )?;
                            ctx.next()?;
                        } else {
                            ctx.lines_as("Dwarf Grunburti", args!["...", "......"])?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["...", "......", "........."])?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["...", "......", ".........", "............."])?;
                            ctx.next()?;
                            ctx.lines_as("Dwarf Grunburti", args!["How dare you come here unprepared?! Did you forget what you needed to bring? Listen carefully this time!"])?;
                            ctx.next()?;
                            'b3: {
                                let subject3 = Val::from(runtime::select_values(
                                    ctx,
                                    &[Val::from("Brisingamen:Megingjard:Sleipnir:Mjolnir")],
                                )?);
                                let mut matched3 = false;
                                let no_case3 = !subject3.loosely_equals(&Val::from(1))
                                    && !subject3.loosely_equals(&Val::from(2))
                                    && !subject3.loosely_equals(&Val::from(3))
                                    && !subject3.loosely_equals(&Val::from(4));
                                if !matched3 && subject3.loosely_equals(&Val::from(1)) {
                                    matched3 = true;
                                }
                                if matched3 {
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "I will need...",
                                            "^0000FF4 Freya's Jewel",
                                            "4 Silver Ornament",
                                            "3 Snow Crystal",
                                            "3 Ripple",
                                            "3 Drifting Air",
                                            "2 Sapphire",
                                            "3 Pearl",
                                            "10 Opal",
                                            "5 Cursed Ruby",
                                            "20 Gold^000000",
                                            "1 Necklace^000000..."
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "Hmmm, but now",
                                            "that the seals have",
                                            "been released, you must hurry before another human can claim",
                                            "one of the godly items..."
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args!["Hurry...!", "Once I forge", "Brisingamen,", "the seals will", "activate again!"],
                                    )?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                                if !matched3 && subject3.loosely_equals(&Val::from(2)) {
                                    matched3 = true;
                                }
                                if matched3 {
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "I will need...",
                                            "^0000FF1 Gleipnir",
                                            "20 Gold",
                                            "10 Sapphire",
                                            "10 Oridecon",
                                            "1 Belt^000000"
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "Hmmm, but now",
                                            "that the seals have",
                                            "been released, you must hurry before another human can claim",
                                            "one of the godly items..."
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args!["Hurry...!", "Once I forge", "Megingjard,", "the seals will", "activate again!"],
                                    )?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                                if !matched3 && subject3.loosely_equals(&Val::from(3)) {
                                    matched3 = true;
                                }
                                if matched3 {
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "I will need...",
                                            "^0000FF3 Wheel of the Unknown",
                                            "5 Feather of Angel Wing",
                                            "3 Sprit of Fish",
                                            "4 Amblem of the Sun God",
                                            "3 Breath of Spirit",
                                            "20 Gold",
                                            "10 Elunium",
                                            "1 Slotted Boots^000000"
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "Hmmm, but now",
                                            "that the seals have",
                                            "been released, you must hurry before another human can claim",
                                            "one of the godly items..."
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args!["Hurry...!", "Once I forge", "Sleipnir,", "the seals will", "activate again!"],
                                    )?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                                if !matched3 && subject3.loosely_equals(&Val::from(4)) {
                                    matched3 = true;
                                }
                                if matched3 {
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "I will need...",
                                            "^0000FF2 Thor's Gauntlets",
                                            "4 Iron Maiden",
                                            "5 Wrath of Valkyrie",
                                            "5 Omen of Tempest",
                                            "5 Billow",
                                            "20 Oridecon",
                                            "5 Elunium",
                                            "40 Gold"
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args![
                                            "Hmmm, but now",
                                            "that the seals have",
                                            "been released, you must hurry before another human can claim",
                                            "one of the godly items..."
                                        ],
                                    )?;
                                    ctx.next()?;
                                    ctx.lines_as(
                                        "Dwarf Grunburti",
                                        args!["Hurry...!", "Once I forge", "the Mjolnir,", "the seals will", "activate again!"],
                                    )?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                            }
                        }
                    }
                }
            }
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Hmpf.",
                    "I can't get any work done in here. Come with me to the ^0000FFunderground laboratory^000000 as my guest, human."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["Now hurry up! ^0000FFOnly one of each godly item^000000 will be given to the humans ^FF0000right after all the seals are released^000000!"])?;
            ctx.close_window()?;
            ctx.call(Function::Warp, vec![Val::from("que_god01"), Val::from(214), Val::from(63)])?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(4)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Dwarf Grunburti",
                args!["Muhahahahahaha!", "Out of my sight,", "you dirty, filthy", "human...!"],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn grunburti_1(ctx: &Ctx) -> Script {
    grunburti_1_body(ctx, Vec::new()).map(|_| ())
}

fn god_hopewarp1_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    return Err(Stop::End);
}

pub fn god_hopewarp1(ctx: &Ctx) -> Script {
    god_hopewarp1_body(ctx, Vec::new()).map(|_| ())
}

fn god_hopewarp1_oninit_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(
        Function::WaitingRoom,
        vec![
            Val::from("Laboratory Entrance"),
            Val::from(2),
            Val::from("#god_hopewarp1::OnStartArena"),
            Val::from(1),
        ],
    )?;
    ctx.call(Function::EnableWaitingRoomEvent, vec![])?;
    return Err(Stop::End);
}

pub fn god_hopewarp1_oninit(ctx: &Ctx) -> Script {
    god_hopewarp1_oninit_body(ctx, Vec::new()).map(|_| ())
}

fn god_hopewarp1_onstartarena_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(
        Function::WarpWaitingPc,
        vec![Val::from("que_god01"), Val::from(155), Val::from(63)],
    )?;
    ctx.call(Function::DoNpcEvent, vec![Val::from("Grunburti#god::OnEnable")])?;
    ctx.call(Function::DisableWaitingRoomEvent, vec![])?;
    return Err(Stop::End);
}

pub fn god_hopewarp1_onstartarena(ctx: &Ctx) -> Script {
    god_hopewarp1_onstartarena_body(ctx, Vec::new()).map(|_| ())
}

fn god_hopewarp1_onreset_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(Function::EnableWaitingRoomEvent, vec![])?;
    return Err(Stop::End);
}

pub fn god_hopewarp1_onreset(ctx: &Ctx) -> Script {
    god_hopewarp1_onreset_body(ctx, Vec::new()).map(|_| ())
}

fn que_godnpc1_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.lines_as(
        "Entrance Notice",
        args!["Only the most", "worthy of humans", "will possess the", "power of the gods."],
    )?;
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn que_godnpc1(ctx: &Ctx) -> Script {
    que_godnpc1_body(ctx, Vec::new()).map(|_| ())
}

fn grunburti_god_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_gid = Val::from(0);
    if (((runtime::op(&ctx.var("$god1").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true()
        || runtime::op(&ctx.var("$god2").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
        || runtime::op(&ctx.var("$god3").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
        || runtime::op(&ctx.var("$god4").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
    {
        ctx.lines_as(
            "Dwarf Grunburti",
            args![
                "One of the godly",
                "items has been created,",
                "and the seals have been",
                "restored. You'll have to",
                "wait until they're all",
                "released again...!"
            ],
        )?;
        ctx.next()?;
        ctx.lines_as(
            "Dwarf Grunburti",
            args!["Bwahahahahahahaa!", "Even though you're", "just a human, I feel", "pity for you~"],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    l_gid = ctx.call(Function::GetCharacterId, vec![Val::from(2)])?;
    if ctx
        .call(
            Function::GetGuildInfo,
            vec![ctx.call(Function::GetCharacterId, vec![Val::from(2)])?, Val::from(2)],
        )?
        .loosely_equals(&Val::from(0))
    {
        ctx.lines_as("Dwarf Grunburti", args!["How in the...", "Get out of here!"])?;
        ctx.next()?;
        ctx.lines_as(
            "Dwarf Grunburti",
            args![
                "How did one of you",
                "stupid humans get in",
                "here?! Only those who",
                "hold the Emperium can",
                "even think of entering",
                "this place...!"
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as("Dwarf Grunburti", args!["It's incredibly", "humiliating to do work for a human. But since destiny has chosen you as the bearer of an Emperium, I have no choice but to oblige your requests."])?;
    ctx.next()?;
    ctx.lines_as("Dwarf Grunburti", args!["We only have", "^FF000010 minutes^000000 to recreate one godly treasure. After that, the seals will restore themselves and I won't be able to create anything until they're released again..."])?;
    ctx.next()?;
    ctx.lines_as(
        "Dwarf Grunburti",
        args![
            "^FF0000Don't be too slow^000000,",
            "otherwise ^FF0000I will give",
            "the chance to another",
            "human^000000 right away!"
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Dwarf Grunburti",
        args!["Now...!", "Choose the item", "you wish for me", "to create!"],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from("Brisingamen:Megingjard:Sleipnir:Mjolnir")],
        )?);
        let mut matched1 = false;
        let no_case1 = !subject1.loosely_equals(&Val::from(1))
            && !subject1.loosely_equals(&Val::from(2))
            && !subject1.loosely_equals(&Val::from(3))
            && !subject1.loosely_equals(&Val::from(4));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "B-Brisingamen?!",
                    "I've never expected",
                    "such insolence...!",
                    "This necklace will never have any meaning in my eyes unless it's worn by the goddess Freya."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "But who am I to judge your worthiness? These treasures",
                    "select their owners with their own will. Let's see if Brisingamen will find you worthy!"
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Once again, I need following materials in order to reproduce",
                    "this godly treasure..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "^0000FF4 Freya's Jewel",
                    "4 Silver Ornament",
                    "3 Snow Crystal",
                    "3 Ripple",
                    "3 Drifting Air",
                    "2 Sapphire",
                    "3 Pearl",
                    "10 Opal",
                    "5 Cursed Ruby",
                    "20 Gold",
                    "1 Necklace^000000"
                ],
            )?;
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(ctx, &[Val::from("Make Brisingamen.:Cancel.")])?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1)) && !subject2.loosely_equals(&Val::from(2));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    if ((((((((((ctx.call(Function::CountItem, vec![Val::from(7073)])?.number()? > 3
                        && ctx.call(Function::CountItem, vec![Val::from(7077)])?.number()? > 3)
                        && ctx.call(Function::CountItem, vec![Val::from(7088)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(7090)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(7092)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(726)])?.number()? > 1)
                        && ctx.call(Function::CountItem, vec![Val::from(722)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(727)])?.number()? > 9)
                        && ctx.call(Function::CountItem, vec![Val::from(724)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 19)
                        && ctx.call(Function::CountItem, vec![Val::from(2603)])?.number()? > 0)
                    {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Never in my wildest",
                                "imaginings have I thought that I'd be crafting this masterpiece for a mere human. Give me a moment."
                            ],
                        )?;
                        ctx.next()?;
                        if (((runtime::op(&ctx.var("$god1").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true()
                            || runtime::op(&ctx.var("$god2").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god3").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god4").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                        {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "But...",
                                    "The seals",
                                    "have just been",
                                    "restored. You'll have to",
                                    "wait until they're all",
                                    "released again...!"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args!["Bwahahahahahahaa!", "Even though you're", "just a human, I feel", "pity for you~"],
                            )?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        ctx.call(Function::DelItem, vec![Val::from(7073), Val::from(4)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7077), Val::from(4)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7088), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7090), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7092), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(726), Val::from(2)])?;
                        ctx.call(Function::DelItem, vec![Val::from(722), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(727), Val::from(10)])?;
                        ctx.call(Function::DelItem, vec![Val::from(724), Val::from(5)])?;
                        ctx.call(Function::DelItem, vec![Val::from(969), Val::from(20)])?;
                        ctx.call(Function::DelItem, vec![Val::from(2603), Val::from(1)])?;
                        ctx.call(Function::GetItem, vec![Val::from(2630), Val::from(1)])?;
                        ctx.var("$god1").set(Val::from(0))?;
                        ctx.var("$god2").set(Val::from(0))?;
                        ctx.var("$god3").set(Val::from(0))?;
                        ctx.var("$god4").set(Val::from(0))?;
                        ctx.call(
                            Function::Announce,
                            vec![
                                ((((Val::from("[Brisingamen] has come into the hands of [")
                                    + ctx.call(Function::StrCharInfo, vec![Val::from(0)])?)
                                    + Val::from("], master of the ["))
                                    + ctx.call(Function::GetGuildInfo, vec![l_gid.clone(), Val::from(0)])?)
                                    + Val::from("] guild.")),
                                ctx.constant("BC_ALL")?,
                            ],
                        )?;
                        ctx.lines_as("Dwarf Grunburti", args!["Ah, just look at this dazzling beauty. No other piece of jewelry complemented Freya as well as Brisingamen."])?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    } else {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Idiot human!",
                                "You didn't bring",
                                "everything I need to",
                                "recreate Brisingamen!",
                                "Hurry...!"
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as(
                        "Dwarf Grunburti",
                        args!["Muhahahaha~", "Somehow, I figured", "you'd back out, human!"],
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as("Dwarf Grunburti", args!["M- Megingjard?!", "The girdle of might?!"])?;
            ctx.next()?;
            ctx.lines_as("Dwarf Grunburti", args!["This belt was worn long ago by Thor, the mightest warrior ever. But since these treasures select their owners, we'll see whether or not it recognizes you as worthy!"])?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Once again, I need following materials in order to reproduce",
                    "this godly treasure..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args!["^0000FF1 Gleipnir", "20 Gold", "10 Sapphire", "10 Oridecon", "1 Belt^000000..."],
            )?;
            ctx.next()?;
            'b3: {
                let subject3 = Val::from(runtime::select_values(ctx, &[Val::from("Make Megingjard.:Cancel.")])?);
                let mut matched3 = false;
                let no_case3 = !subject3.loosely_equals(&Val::from(1)) && !subject3.loosely_equals(&Val::from(2));
                if !matched3 && subject3.loosely_equals(&Val::from(1)) {
                    matched3 = true;
                }
                if matched3 {
                    if ((((ctx.call(Function::CountItem, vec![Val::from(7058)])?.number()? > 0
                        && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 19)
                        && ctx.call(Function::CountItem, vec![Val::from(726)])?.number()? > 9)
                        && ctx.call(Function::CountItem, vec![Val::from(984)])?.number()? > 9)
                        && ctx.call(Function::CountItem, vec![Val::from(2627)])?.number()? > 0)
                    {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Twenty years ago,",
                                "I'd never believe that",
                                "something so powerful and dangerous as Megingjard would end up in the hands of a human..."
                            ],
                        )?;
                        ctx.next()?;
                        if (((runtime::op(&ctx.var("$god1").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true()
                            || runtime::op(&ctx.var("$god2").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god3").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god4").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                        {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "But...",
                                    "The seals",
                                    "have just been",
                                    "restored. You'll have to",
                                    "wait until they're all",
                                    "released again...!"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args!["Bwahahahahahahaa!", "Even though you're", "just a human, I feel", "pity for you~"],
                            )?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        ctx.call(Function::DelItem, vec![Val::from(7058), Val::from(1)])?;
                        ctx.call(Function::DelItem, vec![Val::from(969), Val::from(20)])?;
                        ctx.call(Function::DelItem, vec![Val::from(726), Val::from(10)])?;
                        ctx.call(Function::DelItem, vec![Val::from(984), Val::from(10)])?;
                        ctx.call(Function::DelItem, vec![Val::from(2627), Val::from(1)])?;
                        ctx.call(Function::GetItem, vec![Val::from(2629), Val::from(1)])?;
                        ctx.var("$god1").set(Val::from(0))?;
                        ctx.var("$god2").set(Val::from(0))?;
                        ctx.var("$god3").set(Val::from(0))?;
                        ctx.var("$god4").set(Val::from(0))?;
                        ctx.call(
                            Function::Announce,
                            vec![
                                ((((Val::from("[Megingjard] the godly item has been given to [")
                                    + ctx.call(Function::StrCharInfo, vec![Val::from(0)])?)
                                    + Val::from("], the master of the guild ["))
                                    + ctx.call(Function::GetGuildInfo, vec![l_gid.clone(), Val::from(0)])?)
                                    + Val::from("].")),
                                ctx.constant("BC_ALL")?,
                            ],
                        )?;
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Here...",
                                "Be careful with how",
                                "you use the strength",
                                "of a god. Just a fair",
                                "warning, human..."
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    } else {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Idiot human!",
                                "You didn't bring",
                                "everything I need to",
                                "recreate Megingjard!",
                                "Hurry...!"
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                }
                if !matched3 && subject3.loosely_equals(&Val::from(2)) {
                    matched3 = true;
                }
                if matched3 {
                    ctx.lines_as(
                        "Dwarf Grunburti",
                        args!["Muhahahaha~", "Somehow, I figured", "you'd back out, human!"],
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Sleipnir...",
                    "Now, understand",
                    "that I can't create",
                    "the eight-legged stallion",
                    "of legend. However..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "I can create a pair",
                    "of shoes that will possess the power of Sleipnir. It's a strange, but feasible process..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Once again, I need following materials in order to reproduce",
                    "this godly treasure..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "^0000FF3 Wheel of the Unknown",
                    "5 Feather of Angel Wing",
                    "3 Sprit of Fish",
                    "4 Amblem of the Sun God",
                    "3 Breath of Spirit",
                    "20 Gold",
                    "10 Elunium",
                    "1 Slotted Boots^000000..."
                ],
            )?;
            ctx.next()?;
            'b4: {
                let subject4 = Val::from(runtime::select_values(ctx, &[Val::from("Make Sleipnir.:Cancel.")])?);
                let mut matched4 = false;
                let no_case4 = !subject4.loosely_equals(&Val::from(1)) && !subject4.loosely_equals(&Val::from(2));
                if !matched4 && subject4.loosely_equals(&Val::from(1)) {
                    matched4 = true;
                }
                if matched4 {
                    if (((((((ctx.call(Function::CountItem, vec![Val::from(7076)])?.number()? > 2
                        && ctx.call(Function::CountItem, vec![Val::from(7079)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(7083)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(7086)])?.number()? > 3)
                        && ctx.call(Function::CountItem, vec![Val::from(7087)])?.number()? > 2)
                        && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 19)
                        && ctx.call(Function::CountItem, vec![Val::from(985)])?.number()? > 9)
                        && ctx.call(Function::CountItem, vec![Val::from(2406)])?.number()? > 0)
                    {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "I never believed",
                                "that the speed of",
                                "Sleipnir would be",
                                "used by a human.",
                                "Give me a moment..."
                            ],
                        )?;
                        ctx.next()?;
                        if (((runtime::op(&ctx.var("$god1").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true()
                            || runtime::op(&ctx.var("$god2").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god3").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god4").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                        {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "But...",
                                    "The seals",
                                    "have just been",
                                    "restored. You'll have to",
                                    "wait until they're all",
                                    "released again...!"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args!["Bwahahahahahahaa!", "Even though you're", "just a human, I feel", "pity for you~"],
                            )?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        ctx.call(Function::DelItem, vec![Val::from(7076), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7079), Val::from(5)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7083), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7086), Val::from(4)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7087), Val::from(3)])?;
                        ctx.call(Function::DelItem, vec![Val::from(969), Val::from(20)])?;
                        ctx.call(Function::DelItem, vec![Val::from(985), Val::from(10)])?;
                        ctx.call(Function::DelItem, vec![Val::from(2406), Val::from(1)])?;
                        ctx.call(Function::GetItem, vec![Val::from(2410), Val::from(1)])?;
                        ctx.var("$god1").set(Val::from(0))?;
                        ctx.var("$god2").set(Val::from(0))?;
                        ctx.var("$god3").set(Val::from(0))?;
                        ctx.var("$god4").set(Val::from(0))?;
                        ctx.call(
                            Function::Announce,
                            vec![
                                ((((Val::from("[Sleipnir] the godly item has been given to [")
                                    + ctx.call(Function::StrCharInfo, vec![Val::from(0)])?)
                                    + Val::from("], the master of the guild ["))
                                    + ctx.call(Function::GetGuildInfo, vec![l_gid.clone(), Val::from(0)])?)
                                    + Val::from("].")),
                                ctx.constant("BC_ALL")?,
                            ],
                        )?;
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args!["There...", "Wear these, and", "move with the speed of", "the legendary Sleipnir..."],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    } else {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Idiot human!",
                                "You didn't bring",
                                "everything I need to",
                                "recreate Sleipnir!",
                                "Hurry...!"
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                }
                if !matched4 && subject4.loosely_equals(&Val::from(2)) {
                    matched4 = true;
                }
                if matched4 {
                    ctx.lines_as(
                        "Dwarf Grunburti",
                        args!["Muhahahaha~", "Somehow, I figured", "you'd back out, human!"],
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(4)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "M-M-Mjolnir!?",
                    "Even though the",
                    "moment is at hand,",
                    "I can scarcely believe..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "^333333*Sigh...*^000000",
                    "This is almost a disgrace to gods and the Dwarf race. But perhaps, wielding Mjolnir may be your destiny..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "Once again, I need following materials in order to reproduce",
                    "this godly treasure..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Dwarf Grunburti",
                args![
                    "^0000FF2 Thor's Gauntlets",
                    "4 Iron Maiden",
                    "5 Wrath of Valkyrie",
                    "5 Omen of Tempest",
                    "5 Billow",
                    "20 Oridecon",
                    "5 Elunium",
                    "40 Gold",
                    "1 Stunner^000000..."
                ],
            )?;
            ctx.next()?;
            'b5: {
                let subject5 = Val::from(runtime::select_values(ctx, &[Val::from("Make Mjolnir.:Cancel.")])?);
                let mut matched5 = false;
                let no_case5 = !subject5.loosely_equals(&Val::from(1)) && !subject5.loosely_equals(&Val::from(2));
                if !matched5 && subject5.loosely_equals(&Val::from(1)) {
                    matched5 = true;
                }
                if matched5 {
                    if ((((((((ctx.call(Function::CountItem, vec![Val::from(7074)])?.number()? > 1
                        && ctx.call(Function::CountItem, vec![Val::from(7075)])?.number()? > 3)
                        && ctx.call(Function::CountItem, vec![Val::from(7078)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(7089)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(7091)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(984)])?.number()? > 19)
                        && ctx.call(Function::CountItem, vec![Val::from(985)])?.number()? > 4)
                        && ctx.call(Function::CountItem, vec![Val::from(969)])?.number()? > 39)
                        && ctx.call(Function::CountItem, vec![Val::from(1522)])?.number()? > 0)
                    {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Do not disgrace",
                                "Thor, lord of Thunder,",
                                "or you will regret it.",
                                "Mark my words..."
                            ],
                        )?;
                        ctx.next()?;
                        if (((runtime::op(&ctx.var("$god1").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true()
                            || runtime::op(&ctx.var("$god2").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god3").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                            || runtime::op(&ctx.var("$god4").get()?, "<", &ctx.var("$@god_check2").get()?)?.is_true())
                        {
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args![
                                    "But...",
                                    "The seals",
                                    "have just been",
                                    "restored. You'll have to",
                                    "wait until they're all",
                                    "released again...!"
                                ],
                            )?;
                            ctx.next()?;
                            ctx.lines_as(
                                "Dwarf Grunburti",
                                args!["Bwahahahahahahaa!", "Even though you're", "just a human, I feel", "pity for you~"],
                            )?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        ctx.call(Function::DelItem, vec![Val::from(7074), Val::from(2)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7075), Val::from(4)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7078), Val::from(5)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7089), Val::from(5)])?;
                        ctx.call(Function::DelItem, vec![Val::from(7091), Val::from(5)])?;
                        ctx.call(Function::DelItem, vec![Val::from(984), Val::from(20)])?;
                        ctx.call(Function::DelItem, vec![Val::from(985), Val::from(5)])?;
                        ctx.call(Function::DelItem, vec![Val::from(969), Val::from(40)])?;
                        ctx.call(Function::DelItem, vec![Val::from(1522), Val::from(1)])?;
                        ctx.call(Function::GetItem, vec![Val::from(1530), Val::from(1)])?;
                        ctx.var("$god1").set(Val::from(0))?;
                        ctx.var("$god2").set(Val::from(0))?;
                        ctx.var("$god3").set(Val::from(0))?;
                        ctx.var("$god4").set(Val::from(0))?;
                        ctx.call(
                            Function::Announce,
                            vec![
                                ((((Val::from("[Mjolnir] has been bestowed to [")
                                    + ctx.call(Function::StrCharInfo, vec![Val::from(0)])?)
                                    + Val::from("], the master of the ["))
                                    + ctx.call(Function::GetGuildInfo, vec![l_gid.clone(), Val::from(0)])?)
                                    + Val::from("] guild.")),
                                ctx.constant("BC_ALL")?,
                            ],
                        )?;
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "It's done.",
                                "Take it. How does",
                                "it feel to hold the world's most powerful weapon in your grasp?"
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    } else {
                        ctx.lines_as(
                            "Dwarf Grunburti",
                            args![
                                "Idiot human!",
                                "You didn't bring",
                                "everything I need",
                                "to recreate Mjolnir!",
                                "Hurry...!"
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                }
                if !matched5 && subject5.loosely_equals(&Val::from(2)) {
                    matched5 = true;
                }
                if matched5 {
                    ctx.lines_as(
                        "Dwarf Grunburti",
                        args!["Muhahahaha~", "Somehow, I figured", "you'd back out, human!"],
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
    }
    return Err(Stop::End);
}

pub fn grunburti_god(ctx: &Ctx) -> Script {
    grunburti_god_body(ctx, Vec::new()).map(|_| ())
}

fn grunburti_god_onenable_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(Function::InitNpcTimer, vec![])?;
    return Err(Stop::End);
}

pub fn grunburti_god_onenable(ctx: &Ctx) -> Script {
    grunburti_god_onenable_body(ctx, Vec::new()).map(|_| ())
}

fn grunburti_god_ontimer10000_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(
        Function::MapAnnounce,
        vec![
            Val::from("que_god01"),
            Val::from("Remember that you only have 10 minutes for this! Hurry up!"),
            ctx.constant("BC_MAP")?,
        ],
    )?;
    return Err(Stop::End);
}

pub fn grunburti_god_ontimer10000(ctx: &Ctx) -> Script {
    grunburti_god_ontimer10000_body(ctx, Vec::new()).map(|_| ())
}

fn grunburti_god_ontimer610000_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(
        Function::MapAnnounce,
        vec![
            Val::from("que_god01"),
            Val::from("You're too slow! I'm going to give another human a chance! Next!"),
            ctx.constant("BC_MAP")?,
        ],
    )?;
    return Err(Stop::End);
}

pub fn grunburti_god_ontimer610000(ctx: &Ctx) -> Script {
    grunburti_god_ontimer610000_body(ctx, Vec::new()).map(|_| ())
}

fn grunburti_god_ontimer612000_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(Function::DoNpcEvent, vec![Val::from("god_wep_warpmaster::OnEnable")])?;
    return Err(Stop::End);
}

pub fn grunburti_god_ontimer612000(ctx: &Ctx) -> Script {
    grunburti_god_ontimer612000_body(ctx, Vec::new()).map(|_| ())
}

fn grunburti_god_ontimer615000_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.call(Function::DoNpcEvent, vec![Val::from("god_wep_warpmaster::OnDisable")])?;
    ctx.call(Function::DoNpcEvent, vec![Val::from("#god_hopewarp1::OnReset")])?;
    ctx.call(Function::StopNpcTimer, vec![])?;
    return Err(Stop::End);
}

pub fn grunburti_god_ontimer615000(ctx: &Ctx) -> Script {
    grunburti_god_ontimer615000_body(ctx, Vec::new()).map(|_| ())
}

#[derive(Clone, Copy, Debug)]
enum GodWepWarpmasterStep {
    Start,
    OnEnable,
    OnDisable,
}

fn god_wep_warpmaster_run(ctx: &Ctx, mut step: GodWepWarpmasterStep, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_i = Val::from(0);
    'machine: loop {
        match step {
            GodWepWarpmasterStep::Start => {
                step = GodWepWarpmasterStep::OnEnable;
                continue 'machine;
            }
            GodWepWarpmasterStep::OnEnable => {
                l_i = Val::from(1);
                'l1: loop {
                    if !(l_i.clone().number()? <= 6) {
                        break 'l1;
                    }
                    'b1: {
                        ctx.call(Function::EnableNpc, vec![(Val::from("god_failwarp#") + l_i.clone())])?;
                    }
                    l_i = (l_i.clone() + Val::from(1));
                }
                return Err(Stop::End);
            }
            GodWepWarpmasterStep::OnDisable => {
                l_i = Val::from(1);
                'l2: loop {
                    if !(l_i.clone().number()? <= 6) {
                        break 'l2;
                    }
                    'b2: {
                        ctx.call(Function::DisableNpc, vec![(Val::from("god_failwarp#") + l_i.clone())])?;
                    }
                    l_i = (l_i.clone() + Val::from(1));
                }
                return Err(Stop::End);
            }
        }
    }
}

pub fn god_wep_warpmaster(ctx: &Ctx) -> Script {
    god_wep_warpmaster_run(ctx, GodWepWarpmasterStep::Start, Vec::new()).map(|_| ())
}

pub fn god_wep_warpmaster_onenable(ctx: &Ctx) -> Script {
    god_wep_warpmaster_run(ctx, GodWepWarpmasterStep::OnEnable, Vec::new()).map(|_| ())
}

pub fn god_wep_warpmaster_ondisable(ctx: &Ctx) -> Script {
    god_wep_warpmaster_run(ctx, GodWepWarpmasterStep::OnDisable, Vec::new()).map(|_| ())
}

#[derive(Clone, Copy, Debug)]
enum GodFailwarp1Step {
    Start,
    OnInit,
    OnTouch,
}

fn god_failwarp_1_run(ctx: &Ctx, mut step: GodFailwarp1Step, args: Vec<Val>) -> Result<Val, Stop> {
    'machine: loop {
        match step {
            GodFailwarp1Step::Start => {
                step = GodFailwarp1Step::OnInit;
                continue 'machine;
            }
            GodFailwarp1Step::OnInit => {
                ctx.call(Function::DisableNpc, vec![])?;
                return Err(Stop::End);
            }
            GodFailwarp1Step::OnTouch => {
                ctx.call(Function::Warp, vec![Val::from("prontera"), Val::from(156), Val::from(324)])?;
                return Err(Stop::End);
            }
        }
    }
}

pub fn god_failwarp_1(ctx: &Ctx) -> Script {
    god_failwarp_1_run(ctx, GodFailwarp1Step::Start, Vec::new()).map(|_| ())
}

pub fn god_failwarp_1_oninit(ctx: &Ctx) -> Script {
    god_failwarp_1_run(ctx, GodFailwarp1Step::OnInit, Vec::new()).map(|_| ())
}

pub fn god_failwarp_1_ontouch(ctx: &Ctx) -> Script {
    god_failwarp_1_run(ctx, GodFailwarp1Step::OnTouch, Vec::new()).map(|_| ())
}

fn godly_item_quests_god_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_i = Val::from(0);
    shared::other_gm_npcs::f_gm_npc(ctx, vec![])?;
    ctx.lines_as(
        "Use in case of emergency",
        args!["Please enter password.", "If you wish to cancel, please enter 0."],
    )?;
    ctx.next()?;
    l_i = shared::other_gm_npcs::f_gm_npc(ctx, vec![Val::from(1854), Val::from(0), Val::from(0), Val::from(4000)])?;
    if l_i.clone() == -2 {
        ctx.lines_as("Use in case of emergency", args!["Password is incorrect."])?;
        ctx.close_window()?;
        return Err(Stop::End);
    } else {
        if l_i.clone() == -1 {
            ctx.lines_as("Use in case of emergency", args!["You have canceled your request."])?;
            ctx.close_window()?;
            return Err(Stop::End);
        } else {
            if l_i.clone() == 0 {
                ctx.close_window()?;
                return Err(Stop::End);
            } else {
                ctx.lines_as("Use in case of emergency", args!["What services would you like to use?"])?;
                ctx.next()?;
                'b1: {
                    let subject1 = Val::from(runtime::select_values(
                        ctx,
                        &[Val::from("Turn off Warps.:Reset Timer.:Reset chat room.")],
                    )?);
                    let mut matched1 = false;
                    let no_case1 = !subject1.loosely_equals(&Val::from(1))
                        && !subject1.loosely_equals(&Val::from(2))
                        && !subject1.loosely_equals(&Val::from(3));
                    if !matched1 && subject1.loosely_equals(&Val::from(1)) {
                        matched1 = true;
                    }
                    if matched1 {
                        ctx.lines_as("Use in case of emergency", args!["Press the 'Next' button to turn off warps."])?;
                        ctx.next()?;
                        ctx.call(Function::DoNpcEvent, vec![Val::from("god_wep_warpmaster::OnDisable")])?;
                        ctx.lines_as("Use in case of emergency", args!["You have successfully turned off warps."])?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                    if !matched1 && subject1.loosely_equals(&Val::from(2)) {
                        matched1 = true;
                    }
                    if matched1 {
                        ctx.lines_as("Use in case of emergency", args!["Press the 'Next' button to reset timer."])?;
                        ctx.next()?;
                        ctx.call(Function::DoNpcEvent, vec![Val::from("Grunburti#god::OnEnable")])?;
                        ctx.lines_as("Use in case of emergency", args!["You have successfully reset timer."])?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                    if !matched1 && subject1.loosely_equals(&Val::from(3)) {
                        matched1 = true;
                    }
                    if matched1 {
                        ctx.lines_as(
                            "Use in case of emergency",
                            args!["Please press the 'Next' button to reset the arena chat room in que_god01."],
                        )?;
                        ctx.next()?;
                        ctx.call(Function::DoNpcEvent, vec![Val::from("#god_hopewarp1::OnReset")])?;
                        ctx.lines_as(
                            "Use in case of emergency",
                            args!["You have successfully reset the arena chat room (Laboratory Entrance 1/2)."],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                }
            }
        }
    }
    Ok(Val::from(0))
}

pub fn godly_item_quests_god(ctx: &Ctx) -> Script {
    godly_item_quests_god_body(ctx, Vec::new()).map(|_| ())
}
