#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;

script_sdk_2::script_module! {
    npcs {
        "#cave_vos" => cave_vos,
        "#ice_4f_1" => ice_4f_1,
        "#ice_4f_2" => ice_4f_2,
        "#ice_4f_3" => ice_4f_3,
        "#ice_4f_4" => ice_4f_4,
        "#ice_sec" => ice_sec,
        "#rachel33" => rachel33,
        "#raevent1" => raevent1,
        "#ratrace1" => ratrace1,
        "Blazing Fire#ice1" => blazing_fire_ice1,
        "Blazing Fire#ice2" => blazing_fire_ice2,
        "Blazing Fire#ice3" => blazing_fire_ice3,
        "Blazing Fire#ice4" => blazing_fire_ice4,
        "Bloody Spot" => bloody_spot,
        "Book#ra_in" => book_ra_in,
        "Female Follower#1rachel" => female_follower_1rachel,
        "Grandma#rachel" => grandma_rachel,
        "Hamion#aru" => hamion_aru,
        "High Priest Zhed#rachel" => high_priest_zhed_rachel,
        "High Priestess Niren#r2" => high_priestess_niren_r2,
        "High Priestess Niren#ra" => high_priestess_niren_ra,
        "Idle Merchant#ra_in01" => idle_merchant_ra_in01,
        "Idle Merchant#ra_in01_2" => idle_merchant_ra_in01_2,
        "Jenny#ra_in01" => jenny_ra_in01,
        "Katinshuell" => katinshuell,
        "Kid#1rachel" => kid_1rachel,
        "Kid#2rachel" => kid_2rachel,
        "Kid#Candy Addict" => kid_candy_addict,
        "Kid#ra_in01" => kid_ra_in01,
        "Lachellen" => lachellen,
        "Logan#ra_in01" => logan_ra_in01,
        "Male Follower#1rachel" => male_follower_1rachel,
        "Man Stuck in Ice#cave" => man_stuck_in_ice_cave,
        "Manson#ra_in01" => manson_ra_in01,
        "Mohadian" => mohadian,
        "Mr. Shendar" => mr_shendar,
        "Nemma#ra_temple" => nemma_ra_temple,
        "Panno#rachel" => panno_rachel,
        "Pope#rachel" => pope_rachel,
        "Pope's Office Guard#rac" => pope_s_office_guard_rac,
        "Priest#1rachel" => priest_1rachel,
        "Priestess#1rachel" => priestess_1rachel,
        "Quest Temple Exit#ra_tem" => quest_temple_exit_ra_tem,
        "Seeking Follower#rachel" => seeking_follower_rachel,
        "Sincere Follower Urstia" => sincere_follower_urstia,
        "Suspicious Man#ra_in01" => suspicious_man_ra_in01,
        "Temple Entrance#ra_tem" => temple_entrance_ra_tem,
        "Vincent#ra_in01" => vincent_ra_in01,
        "Window#ra_temple" => window_ra_temple,
        "gyoin1#rachel" => gyoin1_rachel,
        "hidden1#rachel" => hidden1_rachel,
        "ice_boss#broad" => ice_boss_broad,
        "ice_boss#on" => ice_boss_on,
        "imir1#rachel" => imir1_rachel,
        "imir2#rachel" => imir2_rachel,
        "imir3#rachel" => imir3_rachel,
        "imir3#rachel2" => imir3_rachel2,
        "key1#rachel" => key1_rachel,
        "nemma01" => nemma01,
        "out1#rachel" => out1_rachel,
        "saint1#rachel" => saint1_rachel,
        "zawa00" => zawa00,
        "zawa01" => zawa01,
        "zawa02" => zawa02,
        "zawa03" => zawa03,
        "zawa04" => zawa04,
    }
    events {
        "#cave_vos::OnInit" => cave_vos_oninit,
        "#cave_vos::OnTimer10800000" => cave_vos_ontimer10800000,
        "#cave_vos::OnTimer3600000" => cave_vos_ontimer3600000,
        "#cave_vos::OnTimer7200000" => cave_vos_ontimer7200000,
        "#ice_4f_1::OnInit" => ice_4f_1_oninit,
        "#ice_4f_1::OnTouch_" => ice_4f_1_ontouch,
        "#ice_4f_2::OnInit" => ice_4f_2_oninit,
        "#ice_4f_2::OnTouch_" => ice_4f_2_ontouch,
        "#ice_4f_3::OnInit" => ice_4f_3_oninit,
        "#ice_4f_3::OnTouch_" => ice_4f_3_ontouch,
        "#ice_4f_4::OnInit" => ice_4f_4_oninit,
        "#ice_4f_4::OnTouch_" => ice_4f_4_ontouch,
        "#ice_sec::OnStart" => ice_sec_onstart,
        "#ice_sec::OnTimer60000" => ice_sec_ontimer60000,
        "#rachel33::OnTouch_" => rachel33_ontouch,
        "#raevent1::OnTouch_" => raevent1_ontouch,
        "#ratrace1::OnTouch_" => ratrace1_ontouch,
        "Bloody Spot::OnTouch" => bloody_spot_ontouch,
        "High Priestess Niren#r2::OnEnable" => high_priestess_niren_r2_onenable,
        "High Priestess Niren#r2::OnInit" => high_priestess_niren_r2_oninit,
        "High Priestess Niren#r2::OnTimer120000" => high_priestess_niren_r2_ontimer120000,
        "High Priestess Niren#ra::OnEnable" => high_priestess_niren_ra_onenable,
        "High Priestess Niren#ra::OnInit" => high_priestess_niren_ra_oninit,
        "High Priestess Niren#ra::OnTimer120000" => high_priestess_niren_ra_ontimer120000,
        "Man Stuck in Ice#cave::OnMyMobDead" => man_stuck_in_ice_cave_onmymobdead,
        "Man Stuck in Ice#cave::OnTouch" => man_stuck_in_ice_cave_ontouch,
        "Man Stuck in Ice#cave::OnTouchNPC" => man_stuck_in_ice_cave_ontouchnpc,
        "Mohadian::OnTouch_" => mohadian_ontouch,
        "Seeking Follower#rachel::OnTouch" => seeking_follower_rachel_ontouch,
        "Temple Entrance#ra_tem::OnTouch" => temple_entrance_ra_tem_ontouch,
        "gyoin1#rachel::OnTouch" => gyoin1_rachel_ontouch,
        "hidden1#rachel::OnTouch" => hidden1_rachel_ontouch,
        "ice_boss#broad::OnStart" => ice_boss_broad_onstart,
        "ice_boss#broad::OnStop" => ice_boss_broad_onstop,
        "ice_boss#broad::OnTimer10000" => ice_boss_broad_ontimer10000,
        "ice_boss#broad::OnTimer13000" => ice_boss_broad_ontimer13000,
        "ice_boss#broad::OnTimer16000" => ice_boss_broad_ontimer16000,
        "ice_boss#broad::OnTimer19000" => ice_boss_broad_ontimer19000,
        "ice_boss#broad::OnTimer2000" => ice_boss_broad_ontimer2000,
        "ice_boss#broad::OnTimer21000" => ice_boss_broad_ontimer21000,
        "ice_boss#broad::OnTimer8000" => ice_boss_broad_ontimer8000,
        "ice_boss#on::OnMyMobDead" => ice_boss_on_onmymobdead,
        "ice_boss#on::OnStart" => ice_boss_on_onstart,
        "ice_boss#on::OnStartTimer" => ice_boss_on_onstarttimer,
        "ice_boss#on::OnStopTimer" => ice_boss_on_onstoptimer,
        "ice_boss#on::OnTimer7200000" => ice_boss_on_ontimer7200000,
        "imir1#rachel::OnTouch" => imir1_rachel_ontouch,
        "imir2#rachel::OnTouch" => imir2_rachel_ontouch,
        "imir3#rachel2::OnTouch" => imir3_rachel2_ontouch,
        "imir3#rachel::OnTouch" => imir3_rachel_ontouch,
        "key1#rachel::OnTouch" => key1_rachel_ontouch,
        "nemma01::OnTouch_" => nemma01_ontouch,
        "out1#rachel::OnTouch" => out1_rachel_ontouch,
        "saint1#rachel::OnTouch" => saint1_rachel_ontouch,
        "zawa00::OnTouch" => zawa00_ontouch,
        "zawa01::OnTouch" => zawa01_ontouch,
        "zawa02::OnTouch" => zawa02_ontouch,
        "zawa03::OnTouch" => zawa03_ontouch,
        "zawa04::OnTouch" => zawa04_ontouch,
    }
}
