// Generated by tools/scripts-import/convert_sdk2.py from npc/pre-re/quests/collection/quest_pecopeco.txt. Hand-maintained from here on: edit this file directly.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn gregor_pecopeco_hunt_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ctx.call(Function::CheckQuest, vec![Val::from(60101)])? != -1 {
        if ctx.call(Function::CheckQuest, vec![Val::from(60101), ctx.constant("HUNTING")?])? != 2 {
            ctx.lines_as("Gregor", args!["Have you finished hunting the 50 Peco Pecos?"])?;
            ctx.next()?;
            'b1: {
                let subject1 = Val::from(runtime::select_values(ctx, &[Val::from("Yes:No:I want to quit")])?);
                let mut matched1 = false;
                let no_case1 = !subject1.loosely_equals(&Val::from(1))
                    && !subject1.loosely_equals(&Val::from(2))
                    && !subject1.loosely_equals(&Val::from(3));
                if !matched1 && subject1.loosely_equals(&Val::from(1)) {
                    matched1 = true;
                }
                if matched1 {
                    ctx.lines_as("Gregor", args!["Hmm, I don't think you've hunted 50 yet..."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                if !matched1 && subject1.loosely_equals(&Val::from(2)) {
                    matched1 = true;
                }
                if matched1 {
                    ctx.lines_as("Gregor", args!["Please hurry and kill 50 of those tasty err pesky Peco Pecos."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                if !matched1 && subject1.loosely_equals(&Val::from(3)) {
                    matched1 = true;
                }
                if matched1 {
                    ctx.lines_as(
                        "Gregor",
                        args![
                            "Are you sure that you want to stop hunting?",
                            "Any progress that you've made will be erased"
                        ],
                    )?;
                    ctx.next()?;
                    'b2: {
                        let subject2 = Val::from(runtime::select_values(ctx, &[Val::from("Yes:No")])?);
                        let mut matched2 = false;
                        let no_case2 = !subject2.loosely_equals(&Val::from(1)) && !subject2.loosely_equals(&Val::from(2));
                        if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                            matched2 = true;
                        }
                        if matched2 {
                            ctx.lines_as("Gregor", args!["Ok then, well come back here if you change your mind."])?;
                            ctx.call(Function::EraseQuest, vec![Val::from(60101)])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                            matched2 = true;
                        }
                        if matched2 {
                            ctx.lines_as("Gregor", args!["Please hurry and kill 50 of those tasty err pesky Peco Pecos."])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                    }
                }
            }
        } else {
            ctx.lines_as("Gregor", args!["Oh thank you so much!", "I think that I can rest easily now."])?;
            ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
            ctx.call(Function::EraseQuest, vec![Val::from(60101)])?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    if ctx.call(Function::CheckQuest, vec![Val::from(60102)])? != -1 {
        if ctx.call(Function::CheckQuest, vec![Val::from(60102), ctx.constant("HUNTING")?])? != 2 {
            ctx.lines_as("Gregor", args!["Have you finished hunting the 50 Peco Pecos?"])?;
            ctx.next()?;
            'b3: {
                let subject3 = Val::from(runtime::select_values(ctx, &[Val::from("Yes:No:I want to quit")])?);
                let mut matched3 = false;
                let no_case3 = !subject3.loosely_equals(&Val::from(1))
                    && !subject3.loosely_equals(&Val::from(2))
                    && !subject3.loosely_equals(&Val::from(3));
                if !matched3 && subject3.loosely_equals(&Val::from(1)) {
                    matched3 = true;
                }
                if matched3 {
                    ctx.lines_as("Gregor", args!["Hmm, I don't think you've hunted 100 yet..."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                if !matched3 && subject3.loosely_equals(&Val::from(2)) {
                    matched3 = true;
                }
                if matched3 {
                    ctx.lines_as(
                        "Gregor",
                        args!["Please hurry and kill 100 of those tasty err pesky Peco Pecos."],
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                if !matched3 && subject3.loosely_equals(&Val::from(3)) {
                    matched3 = true;
                }
                if matched3 {
                    ctx.lines_as(
                        "Gregor",
                        args![
                            "Are you sure that you want to stop hunting?",
                            "Any progress that you've made will be erased"
                        ],
                    )?;
                    ctx.next()?;
                    'b4: {
                        let subject4 = Val::from(runtime::select_values(ctx, &[Val::from("Yes:No")])?);
                        let mut matched4 = false;
                        let no_case4 = !subject4.loosely_equals(&Val::from(1)) && !subject4.loosely_equals(&Val::from(2));
                        if !matched4 && subject4.loosely_equals(&Val::from(1)) {
                            matched4 = true;
                        }
                        if matched4 {
                            ctx.lines_as("Gregor", args!["Ok then, well come back here if you change your mind."])?;
                            ctx.call(Function::EraseQuest, vec![Val::from(60102)])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched4 && subject4.loosely_equals(&Val::from(2)) {
                            matched4 = true;
                        }
                        if matched4 {
                            ctx.lines_as(
                                "Gregor",
                                args!["Please hurry and kill 100 of those tasty err pesky Peco Pecos."],
                            )?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                    }
                }
            }
        } else {
            ctx.lines_as("Gregor", args!["Oh thank you so much!", "I think that I can rest easily now."])?;
            ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
            ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
            ctx.call(Function::EraseQuest, vec![Val::from(60102)])?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    if ctx.call(Function::CheckQuest, vec![Val::from(60103)])? != -1 {
        if ctx.call(Function::CheckQuest, vec![Val::from(60103), ctx.constant("HUNTING")?])? != 2 {
            ctx.lines_as("Gregor", args!["Have you finished hunting the 150 Peco Pecos?"])?;
            ctx.next()?;
            'b5: {
                let subject5 = Val::from(runtime::select_values(ctx, &[Val::from("Yes:No:I want to quit")])?);
                let mut matched5 = false;
                let no_case5 = !subject5.loosely_equals(&Val::from(1))
                    && !subject5.loosely_equals(&Val::from(2))
                    && !subject5.loosely_equals(&Val::from(3));
                if !matched5 && subject5.loosely_equals(&Val::from(1)) {
                    matched5 = true;
                }
                if matched5 {
                    ctx.lines_as("Gregor", args!["Hmm, I don't think you've hunted 150 yet..."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                if !matched5 && subject5.loosely_equals(&Val::from(2)) {
                    matched5 = true;
                }
                if matched5 {
                    ctx.lines_as(
                        "Gregor",
                        args!["Please hurry and kill 150 of those tasty err pesky Peco Pecos."],
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                if !matched5 && subject5.loosely_equals(&Val::from(3)) {
                    matched5 = true;
                }
                if matched5 {
                    ctx.lines_as(
                        "Gregor",
                        args![
                            "Are you sure that you want to stop hunting?",
                            "Any progress that you've made will be erased"
                        ],
                    )?;
                    ctx.next()?;
                    'b6: {
                        let subject6 = Val::from(runtime::select_values(ctx, &[Val::from("Yes:No")])?);
                        let mut matched6 = false;
                        let no_case6 = !subject6.loosely_equals(&Val::from(1)) && !subject6.loosely_equals(&Val::from(2));
                        if !matched6 && subject6.loosely_equals(&Val::from(1)) {
                            matched6 = true;
                        }
                        if matched6 {
                            ctx.lines_as("Gregor", args!["Ok then, well come back here if you change your mind."])?;
                            ctx.call(Function::EraseQuest, vec![Val::from(60103)])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched6 && subject6.loosely_equals(&Val::from(2)) {
                            matched6 = true;
                        }
                        if matched6 {
                            ctx.lines_as(
                                "Gregor",
                                args!["Please hurry and kill 150 of those tasty err pesky Peco Pecos."],
                            )?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                    }
                }
            }
        } else {
            ctx.lines_as("Gregor", args!["Oh thank you so much!", "I think that I can rest easily now."])?;
            ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
            ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
            ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
            ctx.call(Function::EraseQuest, vec![Val::from(60103)])?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    if ctx.var("BaseLevel").get()?.number()? > 9 {
        if ctx.var("BaseLevel").get()?.number()? < 31 {
            ctx.lines_as(
                "Gregor",
                args![
                    "Peco Pecos are fascinating.",
                    "I am still doing my, uh, research...",
                    "But now it is of a different nature."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Gregor",
                args![
                    "You see I've been uh, ''researching''",
                    "these animals by collecting their",
                    "Bill of Birds but lately they seem",
                    "to have become hostile towards me."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as("Gregor", args!["Can you do me a favor please?"])?;
            ctx.next()?;
            'b7: {
                let subject7 = Val::from(runtime::select_values(ctx, &[Val::from("What kind of favor?:No")])?);
                let mut matched7 = false;
                let no_case7 = !subject7.loosely_equals(&Val::from(1)) && !subject7.loosely_equals(&Val::from(2));
                if !matched7 && subject7.loosely_equals(&Val::from(1)) {
                    matched7 = true;
                }
                if matched7 {
                    ctx.lines_as(
                        "Gregor",
                        args!["I am so afraid that these Peco Pecos will hurt me for my, uh, researching activities."],
                    )?;
                    ctx.next()?;
                    ctx.lines_as(
                        "Gregor",
                        args![
                            "Can you help protect me by killing them?",
                            "I think I'll feel safer...",
                            "Please..."
                        ],
                    )?;
                    ctx.next()?;
                    'b8: {
                        let subject8 = Val::from(runtime::select_values(
                            ctx,
                            &[Val::from("Gather Items:Hunt Peco Pecos:Cancel")],
                        )?);
                        let mut matched8 = false;
                        let no_case8 = !subject8.loosely_equals(&Val::from(1))
                            && !subject8.loosely_equals(&Val::from(2))
                            && !subject8.loosely_equals(&Val::from(3));
                        if !matched8 && subject8.loosely_equals(&Val::from(1)) {
                            matched8 = true;
                        }
                        if matched8 {
                            ctx.lines_as(
                                "Gregor",
                                args!["I need some ^FF0000Bill of Birds^000000 for my, uh, research..."],
                            )?;
                            ctx.next()?;
                            'b9: {
                                let subject9 = Val::from(runtime::select_values(
                                    ctx,
                                    &[Val::from("I have some Bill of Birds:What did you need?")],
                                )?);
                                let mut matched9 = false;
                                let no_case9 = !subject9.loosely_equals(&Val::from(1)) && !subject9.loosely_equals(&Val::from(2));
                                if !matched9 && subject9.loosely_equals(&Val::from(1)) {
                                    matched9 = true;
                                }
                                if matched9 {
                                    if ctx.call(Function::CountItem, vec![Val::from(925)])?.number()? > 24 {
                                        ctx.lines_as("Gregor", args!["Thank you so much."])?;
                                        ctx.call(Function::DelItem, vec![Val::from(925), Val::from(25)])?;
                                        ctx.call(Function::GetExperience, vec![Val::from(4000), Val::from(2000)])?;
                                        ctx.next()?;
                                        ctx.lines_as("Gregor", args!["This is gonna be delicious!"])?;
                                        ctx.close_window()?;
                                        return Err(Stop::End);
                                    } else {
                                        ctx.lines_as("Gregor", args!["It doesn't look like you have enough."])?;
                                        ctx.next()?;
                                        ctx.lines_as(
                                            "Gregor",
                                            args!["Can you help me out and bring me ^FF000025 Bill of Birds^000000?"],
                                        )?;
                                        ctx.close_window()?;
                                        return Err(Stop::End);
                                    }
                                }
                                if !matched9 && subject9.loosely_equals(&Val::from(2)) {
                                    matched9 = true;
                                }
                                if matched9 {
                                    ctx.lines_as(
                                        "Gregor",
                                        args!["Can you help me out and bring me ^FF000025 Bill of Birds^000000?"],
                                    )?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                            }
                        }
                        if !matched8 && subject8.loosely_equals(&Val::from(2)) {
                            matched8 = true;
                        }
                        if matched8 {
                            ctx.lines_as(
                                "Gregor",
                                args![
                                    "Ah, ok I think you can help me out by hunting some Peco Pecos.",
                                    "How many would you like to hunt?"
                                ],
                            )?;
                            ctx.next()?;
                            'b10: {
                                let subject10 = Val::from(runtime::select_values(
                                    ctx,
                                    &[Val::from("50 Peco Pecos:100 Peco Pecos:150 Peco Pecos")],
                                )?);
                                let mut matched10 = false;
                                let no_case10 = !subject10.loosely_equals(&Val::from(1))
                                    && !subject10.loosely_equals(&Val::from(2))
                                    && !subject10.loosely_equals(&Val::from(3));
                                if !matched10 && subject10.loosely_equals(&Val::from(1)) {
                                    matched10 = true;
                                }
                                if matched10 {
                                    ctx.lines_as(
                                        "Gregor",
                                        args!["Come back when you've finished your task and I will give you a small reward."],
                                    )?;
                                    ctx.call(Function::SetQuest, vec![Val::from(60101)])?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                                if !matched10 && subject10.loosely_equals(&Val::from(2)) {
                                    matched10 = true;
                                }
                                if matched10 {
                                    ctx.lines_as(
                                        "Gregor",
                                        args!["Come back when you've finished your task and I will give you a small reward."],
                                    )?;
                                    ctx.call(Function::SetQuest, vec![Val::from(60102)])?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                                if !matched10 && subject10.loosely_equals(&Val::from(3)) {
                                    matched10 = true;
                                }
                                if matched10 {
                                    ctx.lines_as(
                                        "Gregor",
                                        args!["Come back when you've finished your task and I will give you a small reward."],
                                    )?;
                                    ctx.call(Function::SetQuest, vec![Val::from(60103)])?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                            }
                        }
                        if !matched8 && subject8.loosely_equals(&Val::from(3)) {
                            matched8 = true;
                        }
                        if matched8 {
                            ctx.lines_as("Gregor", args!["If you change your mind, please come back."])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                    }
                }
                if !matched7 && subject7.loosely_equals(&Val::from(2)) {
                    matched7 = true;
                }
                if matched7 {
                    ctx.lines_as("Gregor", args!["If you change your mind, please come back."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        } else {
            ctx.lines_as("Gregor", args!["Hmmm... you seem to be too strong to be fighting over here."])?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    } else {
        ctx.lines_as("Gregor", args!["Hi there."])?;
        ctx.next()?;
        ctx.lines_as("Gregor", args!["Those picky's over there seem to be about your speed."])?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    Ok(Val::from(0))
}

pub fn gregor_pecopeco_hunt(ctx: &Ctx) -> Script {
    gregor_pecopeco_hunt_body(ctx, Vec::new()).map(|_| ())
}
