// Generated by tools/scripts-import/convert_sdk2.py from npc/jobs/2-2a/Professor.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn scholar_valkyrie_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_karma_d = Val::from(0);
    if (ctx.var("advjob").get()? == 0 || ctx.var("Upper").get()? != 1) {
        l_karma_d = ctx.call(Function::Rand, vec![Val::from(1), Val::from(10)])?;
        if l_karma_d.clone().number()? > 4 {
            ctx.lines_as("Scholar", args!["Congratulations.", "Honor to the warriors!"])?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        ctx.lines_as(
            "Scholar",
            args![
                "It takes a lifetime...",
                "Literally a lifetime",
                "to amass the knowledge",
                "necessary to become",
                "a Scholar..."
            ],
        )?;
        ctx.next()?;
        ctx.lines_as(
            "Scholar",
            args![
                "It's overwhelming.",
                "The more you learn, the",
                "more you discover what",
                "else you don't know.",
                "There's no end to the",
                "process of learning..."
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    } else {
        if ((ctx.var("advjob").get()?.loosely_equals(&ctx.constant("JOB_PROFESSOR")?)
            && ctx.var("Class").get()?.loosely_equals(&ctx.constant("JOB_MAGE_HIGH")?))
            && ctx.var("JobLevel").get()?.number()? > 39)
        {
            ctx.lines_as(
                "Scholar",
                args![
                    "Midgard doesn't",
                    "have enough Scholars to",
                    "help usher in a new age",
                    "of prosperity. The",
                    "world needs you..."
                ],
            )?;
            ctx.next()?;
            ctx.lines_as(
                "Scholar",
                args![
                    "Will you take this",
                    "awesome responsibility?",
                    "Will you serve Midgard",
                    "as a Scholar?"
                ],
            )?;
            ctx.next()?;
            if Val::from(runtime::select_values(ctx, &[Val::from("No.:Yes.")])?) == 1 {
                ctx.lines_as(
                    "Scholar",
                    args!["When you're ready,", "feel free to come back.", "Honor to the warriors!"],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            if ctx.var("SkillPoint").get()?.is_true() {
                ctx.lines_as(
                    "Scholar",
                    args![
                        "It is still possible for you to learn more skills. Please use",
                        "all of your remaining Skill Points before returning to me."
                    ],
                )?;
                ctx.close_window()?;
                return Err(Stop::End);
            }
            ctx.call(Function::JobChange, vec![ctx.constant("JOB_PROFESSOR")?])?;
            ctx.var("advjob").set(Val::from(0))?;
            ctx.lines_as(
                "Scholar",
                args![
                    "Congratulations!",
                    "As a Professor, I hope",
                    "that you will take an",
                    "active part in bringing",
                    "the light of knowledge",
                    "where there is darkness."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    ctx.lines_as("Scholar", args!["Welcome", "to Valhalla,", "the Hall of Honor."])?;
    ctx.next()?;
    ctx.lines_as(
        "Scholar",
        args![
            "Please make",
            "yourself comfortable",
            "while you are here.",
            "Honor to the warriors!"
        ],
    )?;
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn scholar_valkyrie(ctx: &Ctx) -> Script {
    scholar_valkyrie_body(ctx, Vec::new()).map(|_| ())
}
