#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "#Charm Stone Admintt01" => charm_stone_admintt01,
        "#cooltime_thana" => cooltime_thana,
        "#gateto_thanatos" => gateto_thanatos,
        "#sommon_thanatos" => sommon_thanatos,
        "#thanatos_seal" => thanatos_seal,
        "#tteffect01" => tteffect01,
        "#tteffect02" => tteffect02,
        "#tteffect03" => tteffect03,
        "#tteffect04" => tteffect04,
        "#tteffect05" => tteffect05,
        "3rdf_warp#tt" => s_3rdf_warp_tt,
        "Bloody Knight Statue#tt" => bloody_knight_statue_tt,
        "Blue Angel Statue#tt" => blue_angel_statue_tt,
        "Brilliant Statue#tt3" => brilliant_statue_tt3,
        "Brilliant Statue#tt4" => brilliant_statue_tt4,
        "Dark Devil Statue#tt" => dark_devil_statue_tt,
        "Entrance Guide" => entrance_guide,
        "Gold Religious Statue#tt" => gold_religious_statue_tt,
        "Green Wiseman Statue#tt" => green_wiseman_statue_tt,
        "Guide" => guide,
        "Guide#reward" => guide_reward,
        "Memory Seal#tt1" => memory_seal_tt1,
        "Memory Seal#tt5" => memory_seal_tt5,
        "Rune Device#tt1" => rune_device_tt1,
        "Rune Device#tt2" => rune_device_tt2,
        "Shining Crystal#tt_b1" => shining_crystal_tt_b1,
        "Shining Crystal#tt_g1" => shining_crystal_tt_g1,
        "Shining Crystal#tt_r1" => shining_crystal_tt_r1,
        "Shining Crystal#tt_y1" => shining_crystal_tt_y1,
        "Splendid Sword#tt5" => splendid_sword_tt5,
        "Tower Keeper" => tower_keeper,
        "to 7th Floor" => to_7th_floor,
    }
    events {
        "#Charm Stone Admintt01::OnEnable" => charm_stone_admintt01_onenable,
        "#Charm Stone Admintt01::OnInit" => charm_stone_admintt01_oninit,
        "#Charm Stone Admintt01::OnTimer1000" => charm_stone_admintt01_ontimer1000,
        "#Charm Stone Admintt01::OnTimer1200000" => charm_stone_admintt01_ontimer1200000,
        "#Charm Stone Admintt01::OnTimer1800000" => charm_stone_admintt01_ontimer1800000,
        "#Charm Stone Admintt01::OnTimer2400000" => charm_stone_admintt01_ontimer2400000,
        "#Charm Stone Admintt01::OnTimer600000" => charm_stone_admintt01_ontimer600000,
        "#cooltime_thana::OnEnable" => cooltime_thana_onenable,
        "#cooltime_thana::OnInit" => cooltime_thana_oninit,
        "#cooltime_thana::OnStop" => cooltime_thana_onstop,
        "#cooltime_thana::OnTimer16000" => cooltime_thana_ontimer16000,
        "#cooltime_thana::OnTimer26000" => cooltime_thana_ontimer26000,
        "#cooltime_thana::OnTimer3000" => cooltime_thana_ontimer3000,
        "#cooltime_thana::OnTimer31000" => cooltime_thana_ontimer31000,
        "#cooltime_thana::OnTimer32000" => cooltime_thana_ontimer32000,
        "#cooltime_thana::OnTimer33000" => cooltime_thana_ontimer33000,
        "#cooltime_thana::OnTimer34000" => cooltime_thana_ontimer34000,
        "#cooltime_thana::OnTimer35000" => cooltime_thana_ontimer35000,
        "#cooltime_thana::OnTimer36000" => cooltime_thana_ontimer36000,
        "#cooltime_thana::OnTimer37000" => cooltime_thana_ontimer37000,
        "#cooltime_thana::OnTimer6000" => cooltime_thana_ontimer6000,
        "#cooltime_thana::OnTimer7200000" => cooltime_thana_ontimer7200000,
        "#gateto_thanatos::OnEnable" => gateto_thanatos_onenable,
        "#gateto_thanatos::OnInit" => gateto_thanatos_oninit,
        "#gateto_thanatos::OnOn2" => gateto_thanatos_onon2,
        "#gateto_thanatos::OnTimer1000" => gateto_thanatos_ontimer1000,
        "#gateto_thanatos::OnTimer3000" => gateto_thanatos_ontimer3000,
        "#gateto_thanatos::OnTimer5000" => gateto_thanatos_ontimer5000,
        "#gateto_thanatos::OnTimer6000" => gateto_thanatos_ontimer6000,
        "#gateto_thanatos::OnTouch_" => gateto_thanatos_ontouch,
        "#sommon_thanatos::OnEnable" => sommon_thanatos_onenable,
        "#sommon_thanatos::OnMyMobDead" => sommon_thanatos_onmymobdead,
        "#thanatos_seal::OnDisable" => thanatos_seal_ondisable,
        "#thanatos_seal::OnEnable" => thanatos_seal_onenable,
        "#thanatos_seal::OnTimer1000" => thanatos_seal_ontimer1000,
        "#thanatos_seal::OnTimer10000" => thanatos_seal_ontimer10000,
        "#thanatos_seal::OnTimer13000" => thanatos_seal_ontimer13000,
        "#thanatos_seal::OnTimer16000" => thanatos_seal_ontimer16000,
        "#thanatos_seal::OnTimer4000" => thanatos_seal_ontimer4000,
        "#thanatos_seal::OnTimer7000" => thanatos_seal_ontimer7000,
        "#thanatos_seal::OnTouch_" => thanatos_seal_ontouch,
        "#tteffect01::OnEnable" => tteffect01_onenable,
        "#tteffect01::OnStop" => tteffect01_onstop,
        "#tteffect01::OnTimer1000" => tteffect01_ontimer1000,
        "#tteffect01::OnTimer1500" => tteffect01_ontimer1500,
        "#tteffect01::OnTimer2000" => tteffect01_ontimer2000,
        "#tteffect01::OnTimer2500" => tteffect01_ontimer2500,
        "#tteffect01::OnTimer3000" => tteffect01_ontimer3000,
        "#tteffect01::OnTimer500" => tteffect01_ontimer500,
        "#tteffect02::OnEnable" => tteffect02_onenable,
        "#tteffect02::OnStop" => tteffect02_onstop,
        "#tteffect02::OnTimer1000" => tteffect02_ontimer1000,
        "#tteffect02::OnTimer1500" => tteffect02_ontimer1500,
        "#tteffect02::OnTimer2000" => tteffect02_ontimer2000,
        "#tteffect02::OnTimer2500" => tteffect02_ontimer2500,
        "#tteffect02::OnTimer3000" => tteffect02_ontimer3000,
        "#tteffect02::OnTimer500" => tteffect02_ontimer500,
        "#tteffect03::OnEnable" => tteffect03_onenable,
        "#tteffect03::OnStop" => tteffect03_onstop,
        "#tteffect03::OnTimer1000" => tteffect03_ontimer1000,
        "#tteffect03::OnTimer1500" => tteffect03_ontimer1500,
        "#tteffect03::OnTimer2000" => tteffect03_ontimer2000,
        "#tteffect03::OnTimer2500" => tteffect03_ontimer2500,
        "#tteffect03::OnTimer3000" => tteffect03_ontimer3000,
        "#tteffect03::OnTimer500" => tteffect03_ontimer500,
        "#tteffect04::OnEnable" => tteffect04_onenable,
        "#tteffect04::OnStop" => tteffect04_onstop,
        "#tteffect04::OnTimer1000" => tteffect04_ontimer1000,
        "#tteffect04::OnTimer1500" => tteffect04_ontimer1500,
        "#tteffect04::OnTimer2000" => tteffect04_ontimer2000,
        "#tteffect04::OnTimer2500" => tteffect04_ontimer2500,
        "#tteffect04::OnTimer3000" => tteffect04_ontimer3000,
        "#tteffect04::OnTimer500" => tteffect04_ontimer500,
        "#tteffect05::OnEnable" => tteffect05_onenable,
        "#tteffect05::OnStop" => tteffect05_onstop,
        "#tteffect05::OnTimer1000" => tteffect05_ontimer1000,
        "#tteffect05::OnTimer1500" => tteffect05_ontimer1500,
        "#tteffect05::OnTimer2000" => tteffect05_ontimer2000,
        "#tteffect05::OnTimer2500" => tteffect05_ontimer2500,
        "#tteffect05::OnTimer3000" => tteffect05_ontimer3000,
        "#tteffect05::OnTimer500" => tteffect05_ontimer500,
        "3rdf_warp#tt::OnEnable" => s_3rdf_warp_tt_onenable,
        "3rdf_warp#tt::OnInit" => s_3rdf_warp_tt_oninit,
        "3rdf_warp#tt::OnTimer30000" => s_3rdf_warp_tt_ontimer30000,
        "3rdf_warp#tt::OnTouch_" => s_3rdf_warp_tt_ontouch,
        "Brilliant Statue#tt3::OnTouch_" => brilliant_statue_tt3_ontouch,
        "Brilliant Statue#tt4::OnTouch_" => brilliant_statue_tt4_ontouch,
        "Memory Seal#tt1::OnDisable" => memory_seal_tt1_ondisable,
        "Memory Seal#tt1::OnEnable" => memory_seal_tt1_onenable,
        "Memory Seal#tt1::OnMyMobDead" => memory_seal_tt1_onmymobdead,
        "Memory Seal#tt1::OnTouch_" => memory_seal_tt1_ontouch,
        "Memory Seal#tt5::OnDisable" => memory_seal_tt5_ondisable,
        "Memory Seal#tt5::OnEnable" => memory_seal_tt5_onenable,
        "Memory Seal#tt5::OnInit" => memory_seal_tt5_oninit,
        "Rune Device#tt1::OnTouch_" => rune_device_tt1_ontouch,
        "Rune Device#tt2::OnTouch_" => rune_device_tt2_ontouch,
        "Shining Crystal#tt_b1::OnDisable" => shining_crystal_tt_b1_ondisable,
        "Shining Crystal#tt_b1::OnEnable" => shining_crystal_tt_b1_onenable,
        "Shining Crystal#tt_b1::OnInit" => shining_crystal_tt_b1_oninit,
        "Shining Crystal#tt_g1::OnDisable" => shining_crystal_tt_g1_ondisable,
        "Shining Crystal#tt_g1::OnEnable" => shining_crystal_tt_g1_onenable,
        "Shining Crystal#tt_g1::OnInit" => shining_crystal_tt_g1_oninit,
        "Shining Crystal#tt_r1::OnDisable" => shining_crystal_tt_r1_ondisable,
        "Shining Crystal#tt_r1::OnEnable" => shining_crystal_tt_r1_onenable,
        "Shining Crystal#tt_r1::OnInit" => shining_crystal_tt_r1_oninit,
        "Shining Crystal#tt_y1::OnDisable" => shining_crystal_tt_y1_ondisable,
        "Shining Crystal#tt_y1::OnEnable" => shining_crystal_tt_y1_onenable,
        "Shining Crystal#tt_y1::OnInit" => shining_crystal_tt_y1_oninit,
        "Splendid Sword#tt5::OnTouch_" => splendid_sword_tt5_ontouch,
        "Tower Keeper::OnTouch_" => tower_keeper_ontouch,
        "to 7th Floor::OnTouch" => to_7th_floor_ontouch,
    }
}
