#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod part_01;
mod part_02;

pub use part_01::*;
pub use part_02::*;

script_sdk_2::script_module! {
    npcs {
        "Crusader" => crusader,
        "Man in Anguish_" => man_in_anguish,
        "Monster Summon#cr0" => monster_summon_cr0,
        "Monster Summon#cr1" => monster_summon_cr1,
        "Monster Summon#cr2" => monster_summon_cr2,
        "Monster Summon#cr3" => monster_summon_cr3,
        "Monster Summon#cr4" => monster_summon_cr4,
        "Monster Summon#cr4-a" => monster_summon_cr4_a,
        "Monster Summon#cr6" => monster_summon_cr6,
        "Patron Knight#2" => patron_knight_2,
        "Patron Knight_" => patron_knight,
        "Senior Crusader_" => senior_crusader,
        "Summoner#cr1" => summoner_cr1,
        "Summoner#cr2" => summoner_cr2,
        "Summoner#cr3" => summoner_cr3,
        "Summoner#cr4" => summoner_cr4,
        "Waiting Room#cr1" => waiting_room_cr1,
        "Zombie Guide" => zombie_guide,
    }
    events {
        "Monster Summon#cr0::OnDead" => monster_summon_cr0_ondead,
        "Monster Summon#cr0::OnEnd" => monster_summon_cr0_onend,
        "Monster Summon#cr0::OnInit" => monster_summon_cr0_oninit,
        "Monster Summon#cr0::OnMonster1" => monster_summon_cr0_onmonster1,
        "Monster Summon#cr0::OnMonster2" => monster_summon_cr0_onmonster2,
        "Monster Summon#cr0::OnMonster3" => monster_summon_cr0_onmonster3,
        "Monster Summon#cr0::OnReset" => monster_summon_cr0_onreset,
        "Monster Summon#cr0::OnStart" => monster_summon_cr0_onstart,
        "Monster Summon#cr1::OnEnd" => monster_summon_cr1_onend,
        "Monster Summon#cr1::OnInit" => monster_summon_cr1_oninit,
        "Monster Summon#cr1::OnStart" => monster_summon_cr1_onstart,
        "Monster Summon#cr1::OnTouch_" => monster_summon_cr1_ontouch,
        "Monster Summon#cr2::OnEnd" => monster_summon_cr2_onend,
        "Monster Summon#cr2::OnInit" => monster_summon_cr2_oninit,
        "Monster Summon#cr2::OnStart" => monster_summon_cr2_onstart,
        "Monster Summon#cr2::OnTouch_" => monster_summon_cr2_ontouch,
        "Monster Summon#cr3::OnEnd" => monster_summon_cr3_onend,
        "Monster Summon#cr3::OnInit" => monster_summon_cr3_oninit,
        "Monster Summon#cr3::OnStart" => monster_summon_cr3_onstart,
        "Monster Summon#cr3::OnTouch_" => monster_summon_cr3_ontouch,
        "Monster Summon#cr4-a::OnDead" => monster_summon_cr4_a_ondead,
        "Monster Summon#cr4::OnDead" => monster_summon_cr4_ondead,
        "Monster Summon#cr4::OnEnd" => monster_summon_cr4_onend,
        "Monster Summon#cr4::OnInit" => monster_summon_cr4_oninit,
        "Monster Summon#cr4::OnReset" => monster_summon_cr4_onreset,
        "Monster Summon#cr4::OnStart" => monster_summon_cr4_onstart,
        "Monster Summon#cr4::OnTouch_" => monster_summon_cr4_ontouch,
        "Monster Summon#cr6::OnEnd" => monster_summon_cr6_onend,
        "Monster Summon#cr6::OnInit" => monster_summon_cr6_oninit,
        "Monster Summon#cr6::OnStart" => monster_summon_cr6_onstart,
        "Monster Summon#cr6::OnStop" => monster_summon_cr6_onstop,
        "Monster Summon#cr6::OnTimer241000" => monster_summon_cr6_ontimer241000,
        "Summoner#cr1::OnDead" => summoner_cr1_ondead,
        "Summoner#cr1::OnEnd" => summoner_cr1_onend,
        "Summoner#cr1::OnInit" => summoner_cr1_oninit,
        "Summoner#cr1::OnReset" => summoner_cr1_onreset,
        "Summoner#cr1::OnStart" => summoner_cr1_onstart,
        "Summoner#cr1::OnTimer300000" => summoner_cr1_ontimer300000,
        "Summoner#cr1::OnTimer300500" => summoner_cr1_ontimer300500,
        "Summoner#cr1::OnTimer301000" => summoner_cr1_ontimer301000,
        "Summoner#cr2::OnDead" => summoner_cr2_ondead,
        "Summoner#cr2::OnEnd" => summoner_cr2_onend,
        "Summoner#cr2::OnInit" => summoner_cr2_oninit,
        "Summoner#cr2::OnReset" => summoner_cr2_onreset,
        "Summoner#cr2::OnStart" => summoner_cr2_onstart,
        "Summoner#cr2::OnTimer345000" => summoner_cr2_ontimer345000,
        "Summoner#cr2::OnTimer345500" => summoner_cr2_ontimer345500,
        "Summoner#cr2::OnTimer346000" => summoner_cr2_ontimer346000,
        "Summoner#cr3::OnDead" => summoner_cr3_ondead,
        "Summoner#cr3::OnEnd" => summoner_cr3_onend,
        "Summoner#cr3::OnInit" => summoner_cr3_oninit,
        "Summoner#cr3::OnReset" => summoner_cr3_onreset,
        "Summoner#cr3::OnStart" => summoner_cr3_onstart,
        "Summoner#cr3::OnTimer345000" => summoner_cr3_ontimer345000,
        "Summoner#cr3::OnTimer345500" => summoner_cr3_ontimer345500,
        "Summoner#cr3::OnTimer346000" => summoner_cr3_ontimer346000,
        "Summoner#cr4::OnDead" => summoner_cr4_ondead,
        "Summoner#cr4::OnEnd" => summoner_cr4_onend,
        "Summoner#cr4::OnInit" => summoner_cr4_oninit,
        "Summoner#cr4::OnReset" => summoner_cr4_onreset,
        "Summoner#cr4::OnStart" => summoner_cr4_onstart,
        "Summoner#cr4::OnTimer345000" => summoner_cr4_ontimer345000,
        "Summoner#cr4::OnTimer345500" => summoner_cr4_ontimer345500,
        "Summoner#cr4::OnTimer346000" => summoner_cr4_ontimer346000,
        "Waiting Room#cr1::OnInit" => waiting_room_cr1_oninit,
        "Waiting Room#cr1::OnStart" => waiting_room_cr1_onstart,
        "Waiting Room#cr1::OnStartArena" => waiting_room_cr1_onstartarena,
        "Zombie Guide::OnTouch_" => zombie_guide_ontouch,
    }
}
