#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "#race_timer1-1" => race_timer1_1,
        "#race_timer2-1" => race_timer2_1,
        "#race_timer2-2" => race_timer2_2,
        "#race_timer2-3" => race_timer2_3,
        "Absent Minded Man#single" => absent_minded_man_single,
        "Blacksmith Guildsman#dou" => blacksmith_guildsman_dou,
        "Blacksmith Guildsman#sin" => blacksmith_guildsman_sin,
        "Drunkard#single" => drunkard_single,
        "Eccentric Scholar#double" => eccentric_scholar_double,
        "Eckar Ellebird#single" => eckar_ellebird_single,
        "Eckar Erenes#double" => eckar_erenes_double,
        "Ei'felle#repay01" => ei_felle_repay01,
        "Eocatt#decoy01" => eocatt_decoy01,
        "Exit Guide#double" => exit_guide_double,
        "Exit Guide#single" => exit_guide_single,
        "Game Guide#double" => game_guide_double,
        "Game Guide#single" => game_guide_single,
        "Luk_1" => luk_1,
        "Luk_2" => luk_2,
        "Medal Distributor#medal" => medal_distributor_medal,
        "Medal Distributor#single" => medal_distributor_single,
        "Monster Race Manager" => monster_race_manager,
        "Mudie#dummy01" => mudie_dummy01,
        "Race Progress Timer" => race_progress_timer,
        "Runner_main" => runner_main,
        "Ticket Helper#2" => ticket_helper_2,
        "Ticket Helper#single" => ticket_helper_single,
        "Tire_1" => tire_1,
        "TrapGlobal#race02" => trapglobal_race02,
        "Valiant Knight#double" => valiant_knight_double,
        "Wayne" => wayne,
        "mob1#main" => mob1_main,
        "starting_1" => starting_1,
        "starting_2" => starting_2,
    }
    events {
        "#race_timer1-1::OnEnable" => race_timer1_1_onenable,
        "#race_timer1-1::OnInit" => race_timer1_1_oninit,
        "#race_timer1-1::OnTimer10000" => race_timer1_1_ontimer10000,
        "#race_timer1-1::OnTimer210000" => race_timer1_1_ontimer210000,
        "#race_timer1-1::OnTimer270000" => race_timer1_1_ontimer270000,
        "#race_timer1-1::OnTimer272000" => race_timer1_1_ontimer272000,
        "#race_timer1-1::OnTimer30000" => race_timer1_1_ontimer30000,
        "#race_timer1-1::OnTimer330000" => race_timer1_1_ontimer330000,
        "#race_timer1-1::OnTimer90000" => race_timer1_1_ontimer90000,
        "#race_timer2-1::OnEnable" => race_timer2_1_onenable,
        "#race_timer2-1::OnInit" => race_timer2_1_oninit,
        "#race_timer2-1::OnTimer10000" => race_timer2_1_ontimer10000,
        "#race_timer2-1::OnTimer210000" => race_timer2_1_ontimer210000,
        "#race_timer2-1::OnTimer270000" => race_timer2_1_ontimer270000,
        "#race_timer2-1::OnTimer272000" => race_timer2_1_ontimer272000,
        "#race_timer2-1::OnTimer30000" => race_timer2_1_ontimer30000,
        "#race_timer2-1::OnTimer330000" => race_timer2_1_ontimer330000,
        "#race_timer2-1::OnTimer90000" => race_timer2_1_ontimer90000,
        "#race_timer2-2::OnEnable" => race_timer2_2_onenable,
        "#race_timer2-2::OnInit" => race_timer2_2_oninit,
        "#race_timer2-2::OnTimer120000" => race_timer2_2_ontimer120000,
        "#race_timer2-2::OnTimer122000" => race_timer2_2_ontimer122000,
        "#race_timer2-2::OnTimer240000" => race_timer2_2_ontimer240000,
        "#race_timer2-2::OnTimer242000" => race_timer2_2_ontimer242000,
        "#race_timer2-2::OnTimer300000" => race_timer2_2_ontimer300000,
        "#race_timer2-2::OnTimer5000" => race_timer2_2_ontimer5000,
        "#race_timer2-2::OnTimer7000" => race_timer2_2_ontimer7000,
        "#race_timer2-3::OnEnable" => race_timer2_3_onenable,
        "#race_timer2-3::OnInit" => race_timer2_3_oninit,
        "#race_timer2-3::OnTimer12000" => race_timer2_3_ontimer12000,
        "#race_timer2-3::OnTimer15000" => race_timer2_3_ontimer15000,
        "#race_timer2-3::OnTimer240000" => race_timer2_3_ontimer240000,
        "#race_timer2-3::OnTimer243000" => race_timer2_3_ontimer243000,
        "#race_timer2-3::OnTimer246000" => race_timer2_3_ontimer246000,
        "#race_timer2-3::OnTimer249000" => race_timer2_3_ontimer249000,
        "#race_timer2-3::OnTimer252000" => race_timer2_3_ontimer252000,
        "#race_timer2-3::OnTimer3000" => race_timer2_3_ontimer3000,
        "#race_timer2-3::OnTimer300000" => race_timer2_3_ontimer300000,
        "#race_timer2-3::OnTimer6000" => race_timer2_3_ontimer6000,
        "#race_timer2-3::OnTimer9000" => race_timer2_3_ontimer9000,
        "Eckar Ellebird#single::OnDisable" => eckar_ellebird_single_ondisable,
        "Eckar Ellebird#single::OnEnable" => eckar_ellebird_single_onenable,
        "Eckar Erenes#double::OnDisable" => eckar_erenes_double_ondisable,
        "Eckar Erenes#double::OnEnable" => eckar_erenes_double_onenable,
        "Luk_1::OnInit" => luk_1_oninit,
        "Luk_1::OnTouchNPC" => luk_1_ontouchnpc,
        "Luk_2::OnInit" => luk_2_oninit,
        "Luk_2::OnTouchNPC" => luk_2_ontouchnpc,
        "Medal Distributor#medal::OnInit" => medal_distributor_medal_oninit,
        "Medal Distributor#single::OnEnable" => medal_distributor_single_onenable,
        "Medal Distributor#single::OnInit" => medal_distributor_single_oninit,
        "Medal Distributor#single::OnTimer1000" => medal_distributor_single_ontimer1000,
        "Medal Distributor#single::OnTimer10000" => medal_distributor_single_ontimer10000,
        "Medal Distributor#single::OnTimer13000" => medal_distributor_single_ontimer13000,
        "Medal Distributor#single::OnTimer240000" => medal_distributor_single_ontimer240000,
        "Medal Distributor#single::OnTimer243000" => medal_distributor_single_ontimer243000,
        "Medal Distributor#single::OnTimer246000" => medal_distributor_single_ontimer246000,
        "Medal Distributor#single::OnTimer249000" => medal_distributor_single_ontimer249000,
        "Medal Distributor#single::OnTimer252000" => medal_distributor_single_ontimer252000,
        "Medal Distributor#single::OnTimer300000" => medal_distributor_single_ontimer300000,
        "Medal Distributor#single::OnTimer342000" => medal_distributor_single_ontimer342000,
        "Medal Distributor#single::OnTimer4000" => medal_distributor_single_ontimer4000,
        "Medal Distributor#single::OnTimer7000" => medal_distributor_single_ontimer7000,
        "Race Progress Timer::OnDisable" => race_progress_timer_ondisable,
        "Race Progress Timer::OnEnable" => race_progress_timer_onenable,
        "Race Progress Timer::OnInit" => race_progress_timer_oninit,
        "Race Progress Timer::OnTimer1000" => race_progress_timer_ontimer1000,
        "Race Progress Timer::OnTimer10000" => race_progress_timer_ontimer10000,
        "Race Progress Timer::OnTimer120000" => race_progress_timer_ontimer120000,
        "Race Progress Timer::OnTimer123000" => race_progress_timer_ontimer123000,
        "Race Progress Timer::OnTimer240000" => race_progress_timer_ontimer240000,
        "Race Progress Timer::OnTimer243000" => race_progress_timer_ontimer243000,
        "Race Progress Timer::OnTimer300000" => race_progress_timer_ontimer300000,
        "Race Progress Timer::OnTimer7000" => race_progress_timer_ontimer7000,
        "Runner_main::OnDisable" => runner_main_ondisable,
        "Runner_main::OnEnable" => runner_main_onenable,
        "Runner_main::OnInit" => runner_main_oninit,
        "Runner_main::OnTouchNPC" => runner_main_ontouchnpc,
        "Ticket Helper#2::OnInit" => ticket_helper_2_oninit,
        "Ticket Helper#single::OnInit" => ticket_helper_single_oninit,
        "Tire_1::OnInit" => tire_1_oninit,
        "Tire_1::OnTouchNPC" => tire_1_ontouchnpc,
        "TrapGlobal#race02::OnDisable" => trapglobal_race02_ondisable,
        "TrapGlobal#race02::OnEnable" => trapglobal_race02_onenable,
        "TrapGlobal#race02::OnInit" => trapglobal_race02_oninit,
        "mob1#main::OnDisable" => mob1_main_ondisable,
        "mob1#main::OnEnable" => mob1_main_onenable,
        "mob1#main::OnInit" => mob1_main_oninit,
        "mob1#main::OnMyMobDead" => mob1_main_onmymobdead,
        "mob1#main::OnTouchNPC" => mob1_main_ontouchnpc,
        "starting_1::OnInit" => starting_1_oninit,
        "starting_1::OnTouchNPC" => starting_1_ontouchnpc,
        "starting_2::OnDisable" => starting_2_ondisable,
        "starting_2::OnInit" => starting_2_oninit,
        "starting_2::OnTouchNPC" => starting_2_ontouchnpc,
    }
}
