#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;

script_sdk_2::script_module! {
    npcs {
        "Broadcast#tt_main" => broadcast_tt_main,
        "DSwitch#tt_main" => dswitch_tt_main,
        "Expert Mode Record" => expert_mode_record,
        "Flasher#tt_main" => flasher_tt_main,
        "Guide#TBT_n1" => guide_tbt_n1,
        "Hall of Honor#tt" => hall_of_honor_tt,
        "Hall of Honor#tt2" => hall_of_honor_tt2,
        "Helper#tt_main" => helper_tt_main,
        "Kafra Staff#tt" => kafra_staff_tt,
        "LogTrap#tt_main" => logtrap_tt_main,
        "Master#tt_main" => master_tt_main,
        "MountManager_turbo" => mountmanager_turbo,
        "NMaker1#tt_main" => nmaker1_tt_main,
        "NMaker3#tt_main" => nmaker3_tt_main,
        "NMaker4#tt_main" => nmaker4_tt_main,
        "NoUnfair#tt_main" => nounfair_tt_main,
        "Normal Mode Record#tt" => normal_mode_record_tt,
        "Point Exchange Helper" => point_exchange_helper,
        "Point Manager#tt" => point_manager_tt,
        "Point#tt_main" => point_tt_main,
        "SandTrap#tt_main" => sandtrap_tt_main,
        "Sign#TBT" => sign_tbt,
        "SnakeHunt#tt_main" => snakehunt_tt_main,
        "Solo Mode#tt" => solo_mode_tt,
        "Trap#tt_main" => trap_tt_main,
        "Turbo Track Guide" => turbo_track_guide,
        "Turbo Track Guide#Entran" => turbo_track_guide_entran,
        "TurboHint_1#tt_main" => turbohint_1_tt_main,
        "TurboHint_2#tt_main" => turbohint_2_tt_main,
        "TurboHint_3#tt_main" => turbohint_3_tt_main,
        "TurboHint_4#tt_main" => turbohint_4_tt_main,
        "TurboTrap#tt_main" => turbotrap_tt_main,
        "TurboTrap_2#tt_main" => turbotrap_2_tt_main,
        "WHelper#tt_main" => whelper_tt_main,
        "WaterTrap#tt_main" => watertrap_tt_main,
        "bing_1#tt_main" => bing_1_tt_main,
        "bing_2#tt_main" => bing_2_tt_main,
        "cos#tt_main" => cos_tt_main,
        "cos_end#tt_main" => cos_end_tt_main,
        "cos_end2#tt_main" => cos_end2_tt_main,
        "cos_end3#tt_main" => cos_end3_tt_main,
        "en_turbo" => en_turbo,
        "entrance#tt_main" => entrance_tt_main,
        "snake01#tt_main" => snake01_tt_main,
        "snake02#tt_main" => snake02_tt_main,
        "snake03#tt_main" => snake03_tt_main,
        "snake04#tt_main" => snake04_tt_main,
        "warp#tt_main" => warp_tt_main,
    }
    events {
        "Broadcast#tt_main::OnEnable" => broadcast_tt_main_onenable,
        "Broadcast#tt_main::OnInit" => broadcast_tt_main_oninit,
        "Broadcast#tt_main::OnTimer10000" => broadcast_tt_main_ontimer10000,
        "Broadcast#tt_main::OnTimer15000" => broadcast_tt_main_ontimer15000,
        "Broadcast#tt_main::OnTimer17000" => broadcast_tt_main_ontimer17000,
        "Broadcast#tt_main::OnTimer2000" => broadcast_tt_main_ontimer2000,
        "Broadcast#tt_main::OnTimer27000" => broadcast_tt_main_ontimer27000,
        "Broadcast#tt_main::OnTimer37000" => broadcast_tt_main_ontimer37000,
        "Broadcast#tt_main::OnTimer42000" => broadcast_tt_main_ontimer42000,
        "Broadcast#tt_main::OnTimer43000" => broadcast_tt_main_ontimer43000,
        "Broadcast#tt_main::OnTimer44000" => broadcast_tt_main_ontimer44000,
        "Broadcast#tt_main::OnTimer45000" => broadcast_tt_main_ontimer45000,
        "Broadcast#tt_main::OnTimer46000" => broadcast_tt_main_ontimer46000,
        "Broadcast#tt_main::OnTimer47000" => broadcast_tt_main_ontimer47000,
        "Broadcast#tt_main::OnTimer49000" => broadcast_tt_main_ontimer49000,
        "Broadcast#tt_main::OnTimer50000" => broadcast_tt_main_ontimer50000,
        "Broadcast#tt_main::OnTimer57000" => broadcast_tt_main_ontimer57000,
        "Broadcast#tt_main::OnTimer7000" => broadcast_tt_main_ontimer7000,
        "DSwitch#tt_main::OnTouch_" => dswitch_tt_main_ontouch,
        "Flasher#tt_main::OnInit" => flasher_tt_main_oninit,
        "Flasher#tt_main::OnTouch_" => flasher_tt_main_ontouch,
        "Guide#TBT_n1::OnEnable" => guide_tbt_n1_onenable,
        "Guide#TBT_n1::OnInit" => guide_tbt_n1_oninit,
        "Guide#TBT_n1::OnTimer12000" => guide_tbt_n1_ontimer12000,
        "Guide#TBT_n1::OnTimer16000" => guide_tbt_n1_ontimer16000,
        "Guide#TBT_n1::OnTimer20000" => guide_tbt_n1_ontimer20000,
        "Guide#TBT_n1::OnTimer24000" => guide_tbt_n1_ontimer24000,
        "Guide#TBT_n1::OnTimer28000" => guide_tbt_n1_ontimer28000,
        "Guide#TBT_n1::OnTimer32000" => guide_tbt_n1_ontimer32000,
        "Guide#TBT_n1::OnTimer36000" => guide_tbt_n1_ontimer36000,
        "Guide#TBT_n1::OnTimer4000" => guide_tbt_n1_ontimer4000,
        "Guide#TBT_n1::OnTimer40000" => guide_tbt_n1_ontimer40000,
        "Guide#TBT_n1::OnTimer44000" => guide_tbt_n1_ontimer44000,
        "Guide#TBT_n1::OnTimer48000" => guide_tbt_n1_ontimer48000,
        "Guide#TBT_n1::OnTimer52000" => guide_tbt_n1_ontimer52000,
        "Guide#TBT_n1::OnTimer56000" => guide_tbt_n1_ontimer56000,
        "Guide#TBT_n1::OnTimer60000" => guide_tbt_n1_ontimer60000,
        "Guide#TBT_n1::OnTimer8000" => guide_tbt_n1_ontimer8000,
        "LogTrap#tt_main::OnTouch_" => logtrap_tt_main_ontouch,
        "Master#tt_main::OnDisable" => master_tt_main_ondisable,
        "Master#tt_main::OnEnable" => master_tt_main_onenable,
        "Master#tt_main::OnInit" => master_tt_main_oninit,
        "Master#tt_main::OnTimer11000" => master_tt_main_ontimer11000,
        "Master#tt_main::OnTimer13000" => master_tt_main_ontimer13000,
        "Master#tt_main::OnTimer143000" => master_tt_main_ontimer143000,
        "Master#tt_main::OnTimer15000" => master_tt_main_ontimer15000,
        "Master#tt_main::OnTimer17000" => master_tt_main_ontimer17000,
        "Master#tt_main::OnTimer18000" => master_tt_main_ontimer18000,
        "Master#tt_main::OnTimer19000" => master_tt_main_ontimer19000,
        "Master#tt_main::OnTimer20000" => master_tt_main_ontimer20000,
        "Master#tt_main::OnTimer203000" => master_tt_main_ontimer203000,
        "Master#tt_main::OnTimer21000" => master_tt_main_ontimer21000,
        "Master#tt_main::OnTimer22000" => master_tt_main_ontimer22000,
        "Master#tt_main::OnTimer23000" => master_tt_main_ontimer23000,
        "Master#tt_main::OnTimer263000" => master_tt_main_ontimer263000,
        "Master#tt_main::OnTimer30000" => master_tt_main_ontimer30000,
        "Master#tt_main::OnTimer323000" => master_tt_main_ontimer323000,
        "Master#tt_main::OnTimer383000" => master_tt_main_ontimer383000,
        "Master#tt_main::OnTimer443000" => master_tt_main_ontimer443000,
        "Master#tt_main::OnTimer503000" => master_tt_main_ontimer503000,
        "Master#tt_main::OnTimer563000" => master_tt_main_ontimer563000,
        "Master#tt_main::OnTimer623000" => master_tt_main_ontimer623000,
        "Master#tt_main::OnTimer683000" => master_tt_main_ontimer683000,
        "Master#tt_main::OnTimer7000" => master_tt_main_ontimer7000,
        "Master#tt_main::OnTimer743000" => master_tt_main_ontimer743000,
        "Master#tt_main::OnTimer803000" => master_tt_main_ontimer803000,
        "Master#tt_main::OnTimer83000" => master_tt_main_ontimer83000,
        "Master#tt_main::OnTimer863000" => master_tt_main_ontimer863000,
        "Master#tt_main::OnTimer893000" => master_tt_main_ontimer893000,
        "Master#tt_main::OnTimer9000" => master_tt_main_ontimer9000,
        "Master#tt_main::OnTimer903000" => master_tt_main_ontimer903000,
        "Master#tt_main::OnTimer913000" => master_tt_main_ontimer913000,
        "Master#tt_main::OnTimer918000" => master_tt_main_ontimer918000,
        "Master#tt_main::OnTimer919000" => master_tt_main_ontimer919000,
        "Master#tt_main::OnTimer920000" => master_tt_main_ontimer920000,
        "Master#tt_main::OnTimer921000" => master_tt_main_ontimer921000,
        "Master#tt_main::OnTimer922000" => master_tt_main_ontimer922000,
        "Master#tt_main::OnTimer923000" => master_tt_main_ontimer923000,
        "Master#tt_main::OnTimer925000" => master_tt_main_ontimer925000,
        "Master#tt_main::OnTimer927000" => master_tt_main_ontimer927000,
        "NMaker1#tt_main::OnInit" => nmaker1_tt_main_oninit,
        "NMaker1#tt_main::OnTouch_" => nmaker1_tt_main_ontouch,
        "NMaker3#tt_main::OnInit" => nmaker3_tt_main_oninit,
        "NMaker3#tt_main::OnTouch_" => nmaker3_tt_main_ontouch,
        "NMaker4#tt_main::OnInit" => nmaker4_tt_main_oninit,
        "NMaker4#tt_main::OnTouch_" => nmaker4_tt_main_ontouch,
        "NoUnfair#tt_main::OnTouch_" => nounfair_tt_main_ontouch,
        "Point#tt_main::OnInit" => point_tt_main_oninit,
        "Point#tt_main::OnTouch_" => point_tt_main_ontouch,
        "SandTrap#tt_main::OnTouch_" => sandtrap_tt_main_ontouch,
        "SnakeHunt#tt_main::OnEnable" => snakehunt_tt_main_onenable,
        "SnakeHunt#tt_main::OnReset" => snakehunt_tt_main_onreset,
        "Trap#tt_main::OnTouch_" => trap_tt_main_ontouch,
        "Turbo Track Guide::OnEnd_e16" => turbo_track_guide_onend_e16,
        "Turbo Track Guide::OnEnd_e4" => turbo_track_guide_onend_e4,
        "Turbo Track Guide::OnEnd_e8" => turbo_track_guide_onend_e8,
        "Turbo Track Guide::OnEnd_n1" => turbo_track_guide_onend_n1,
        "Turbo Track Guide::OnEnd_n16" => turbo_track_guide_onend_n16,
        "Turbo Track Guide::OnEnd_n4" => turbo_track_guide_onend_n4,
        "Turbo Track Guide::OnEnd_n8" => turbo_track_guide_onend_n8,
        "Turbo Track Guide::OnInit" => turbo_track_guide_oninit,
        "Turbo Track Guide::OnNew_Top1" => turbo_track_guide_onnew_top1,
        "Turbo Track Guide::OnNew_Top2" => turbo_track_guide_onnew_top2,
        "Turbo Track Guide::OnNew_Top3" => turbo_track_guide_onnew_top3,
        "Turbo Track Guide::OnNew_Top4" => turbo_track_guide_onnew_top4,
        "Turbo Track Guide::OnNew_Top5" => turbo_track_guide_onnew_top5,
        "Turbo Track Guide::OnWin_e16" => turbo_track_guide_onwin_e16,
        "Turbo Track Guide::OnWin_e4" => turbo_track_guide_onwin_e4,
        "Turbo Track Guide::OnWin_e8" => turbo_track_guide_onwin_e8,
        "Turbo Track Guide::OnWin_n16" => turbo_track_guide_onwin_n16,
        "Turbo Track Guide::OnWin_n4" => turbo_track_guide_onwin_n4,
        "Turbo Track Guide::OnWin_n8" => turbo_track_guide_onwin_n8,
        "TurboHint_1#tt_main::OnTouch_" => turbohint_1_tt_main_ontouch,
        "TurboHint_2#tt_main::OnTouch_" => turbohint_2_tt_main_ontouch,
        "TurboHint_3#tt_main::OnTouch_" => turbohint_3_tt_main_ontouch,
        "TurboHint_4#tt_main::OnTouch_" => turbohint_4_tt_main_ontouch,
        "TurboTrap#tt_main::OnTouch_" => turbotrap_tt_main_ontouch,
        "TurboTrap_2#tt_main::OnTouch_" => turbotrap_2_tt_main_ontouch,
        "WHelper#tt_main::OnEnable" => whelper_tt_main_onenable,
        "WHelper#tt_main::OnInit" => whelper_tt_main_oninit,
        "WHelper#tt_main::OnTimer12000" => whelper_tt_main_ontimer12000,
        "WHelper#tt_main::OnTimer16000" => whelper_tt_main_ontimer16000,
        "WHelper#tt_main::OnTimer20000" => whelper_tt_main_ontimer20000,
        "WHelper#tt_main::OnTimer24000" => whelper_tt_main_ontimer24000,
        "WHelper#tt_main::OnTimer25000" => whelper_tt_main_ontimer25000,
        "WHelper#tt_main::OnTimer28000" => whelper_tt_main_ontimer28000,
        "WHelper#tt_main::OnTimer30000" => whelper_tt_main_ontimer30000,
        "WHelper#tt_main::OnTimer32000" => whelper_tt_main_ontimer32000,
        "WHelper#tt_main::OnTimer35000" => whelper_tt_main_ontimer35000,
        "WHelper#tt_main::OnTimer36000" => whelper_tt_main_ontimer36000,
        "WHelper#tt_main::OnTimer4000" => whelper_tt_main_ontimer4000,
        "WHelper#tt_main::OnTimer40000" => whelper_tt_main_ontimer40000,
        "WHelper#tt_main::OnTimer44000" => whelper_tt_main_ontimer44000,
        "WHelper#tt_main::OnTimer45000" => whelper_tt_main_ontimer45000,
        "WHelper#tt_main::OnTimer48000" => whelper_tt_main_ontimer48000,
        "WHelper#tt_main::OnTimer50000" => whelper_tt_main_ontimer50000,
        "WHelper#tt_main::OnTimer52000" => whelper_tt_main_ontimer52000,
        "WHelper#tt_main::OnTimer55000" => whelper_tt_main_ontimer55000,
        "WHelper#tt_main::OnTimer58000" => whelper_tt_main_ontimer58000,
        "WHelper#tt_main::OnTimer60000" => whelper_tt_main_ontimer60000,
        "WHelper#tt_main::OnTimer65000" => whelper_tt_main_ontimer65000,
        "WHelper#tt_main::OnTimer70000" => whelper_tt_main_ontimer70000,
        "WHelper#tt_main::OnTimer71000" => whelper_tt_main_ontimer71000,
        "WHelper#tt_main::OnTimer8000" => whelper_tt_main_ontimer8000,
        "WaterTrap#tt_main::OnTouch_" => watertrap_tt_main_ontouch,
        "bing_1#tt_main::OnTouch_" => bing_1_tt_main_ontouch,
        "bing_2#tt_main::OnInit" => bing_2_tt_main_oninit,
        "bing_2#tt_main::OnTouch_" => bing_2_tt_main_ontouch,
        "cos#tt_main::OnTouch_" => cos_tt_main_ontouch,
        "cos_end#tt_main::OnInit" => cos_end_tt_main_oninit,
        "cos_end#tt_main::OnTouch_" => cos_end_tt_main_ontouch,
        "cos_end2#tt_main::OnInit" => cos_end2_tt_main_oninit,
        "cos_end2#tt_main::OnTouch_" => cos_end2_tt_main_ontouch,
        "cos_end3#tt_main::OnInit" => cos_end3_tt_main_oninit,
        "cos_end3#tt_main::OnTouch_" => cos_end3_tt_main_ontouch,
        "en_turbo::OnTouch_" => en_turbo_ontouch,
        "entrance#tt_main::OnEnable" => entrance_tt_main_onenable,
        "entrance#tt_main::OnInit" => entrance_tt_main_oninit,
        "entrance#tt_main::OnStartArena" => entrance_tt_main_onstartarena,
        "snake01#tt_main::OnTouch_" => snake01_tt_main_ontouch,
        "snake02#tt_main::OnTouch_" => snake02_tt_main_ontouch,
        "snake03#tt_main::OnTouch_" => snake03_tt_main_ontouch,
        "snake04#tt_main::OnTouch_" => snake04_tt_main_ontouch,
        "warp#tt_main::OnTouch_" => warp_tt_main_ontouch,
    }
}
