pub mod alchemist;
pub mod bard;
pub mod dancer;

script_sdk_2::script_module! {
    npcs {
        "Aile#da" => dancer::aile_da,
        "Alchemist Guildsman#am" => alchemist::alchemist_guildsman_am,
        "Backdancer#1" => dancer::backdancer_1,
        "Backdancer#2" => dancer::backdancer_2,
        "Backdancer#3" => dancer::backdancer_3,
        "Backdancer#4" => dancer::backdancer_4,
        "Bijou#da" => dancer::bijou_da,
        "Bijou#dance_timer" => dancer::bijou_dance_timer,
        "Bor Robin#1" => dancer::bor_robin_1,
        "Chief Researcher#am" => alchemist::chief_researcher_am,
        "Experiment Expert#am" => alchemist::experiment_expert_am,
        "Fastidious Alchemist#am" => alchemist::fastidious_alchemist_am,
        "Master Alchemist#am" => alchemist::master_alchemist_am,
        "Sonotora#1" => dancer::sonotora_1,
        "Studying Man#am" => alchemist::studying_man_am,
        "Waiting Room#click" => dancer::waiting_room_click,
        "Waiting Room#dance" => dancer::waiting_room_dance,
        "Wandering Bard" => bard::wandering_bard,
        "dance#poring" => dancer::dance_poring,
        "dance#return" => dancer::dance_return,
        "dance#return#2" => dancer::dance_return_2,
        "dance#return#3" => dancer::dance_return_3,
        "dancestep" => dancer::dancestep,
    }
    events {
        "Backdancer#1::OnOmg" => dancer::backdancer_1_onomg,
        "Backdancer#1::OnSmile" => dancer::backdancer_1_onsmile,
        "Backdancer#2::OnOmg" => dancer::backdancer_2_onomg,
        "Backdancer#2::OnSmile" => dancer::backdancer_2_onsmile,
        "Backdancer#3::OnOmg" => dancer::backdancer_3_onomg,
        "Backdancer#3::OnSmile" => dancer::backdancer_3_onsmile,
        "Backdancer#4::OnOmg" => dancer::backdancer_4_onomg,
        "Backdancer#4::OnSmile" => dancer::backdancer_4_onsmile,
        "Bijou#dance_timer::OnDisable" => dancer::bijou_dance_timer_ondisable,
        "Bijou#dance_timer::OnEnable" => dancer::bijou_dance_timer_onenable,
        "Bijou#dance_timer::OnTimer11000" => dancer::bijou_dance_timer_ontimer11000,
        "Bijou#dance_timer::OnTimer12000" => dancer::bijou_dance_timer_ontimer12000,
        "Bijou#dance_timer::OnTimer15000" => dancer::bijou_dance_timer_ontimer15000,
        "Bijou#dance_timer::OnTimer16000" => dancer::bijou_dance_timer_ontimer16000,
        "Bijou#dance_timer::OnTimer19000" => dancer::bijou_dance_timer_ontimer19000,
        "Bijou#dance_timer::OnTimer2000" => dancer::bijou_dance_timer_ontimer2000,
        "Bijou#dance_timer::OnTimer20000" => dancer::bijou_dance_timer_ontimer20000,
        "Bijou#dance_timer::OnTimer23000" => dancer::bijou_dance_timer_ontimer23000,
        "Bijou#dance_timer::OnTimer23500" => dancer::bijou_dance_timer_ontimer23500,
        "Bijou#dance_timer::OnTimer27000" => dancer::bijou_dance_timer_ontimer27000,
        "Bijou#dance_timer::OnTimer28500" => dancer::bijou_dance_timer_ontimer28500,
        "Bijou#dance_timer::OnTimer30000" => dancer::bijou_dance_timer_ontimer30000,
        "Bijou#dance_timer::OnTimer34000" => dancer::bijou_dance_timer_ontimer34000,
        "Bijou#dance_timer::OnTimer35000" => dancer::bijou_dance_timer_ontimer35000,
        "Bijou#dance_timer::OnTimer38500" => dancer::bijou_dance_timer_ontimer38500,
        "Bijou#dance_timer::OnTimer40000" => dancer::bijou_dance_timer_ontimer40000,
        "Bijou#dance_timer::OnTimer43000" => dancer::bijou_dance_timer_ontimer43000,
        "Bijou#dance_timer::OnTimer49000" => dancer::bijou_dance_timer_ontimer49000,
        "Bijou#dance_timer::OnTimer5000" => dancer::bijou_dance_timer_ontimer5000,
        "Bijou#dance_timer::OnTimer50000" => dancer::bijou_dance_timer_ontimer50000,
        "Bijou#dance_timer::OnTimer53000" => dancer::bijou_dance_timer_ontimer53000,
        "Bijou#dance_timer::OnTimer54000" => dancer::bijou_dance_timer_ontimer54000,
        "Bijou#dance_timer::OnTimer60000" => dancer::bijou_dance_timer_ontimer60000,
        "Bijou#dance_timer::OnTimer61000" => dancer::bijou_dance_timer_ontimer61000,
        "Bijou#dance_timer::OnTimer66000" => dancer::bijou_dance_timer_ontimer66000,
        "Bijou#dance_timer::OnTimer67000" => dancer::bijou_dance_timer_ontimer67000,
        "Bijou#dance_timer::OnTimer69000" => dancer::bijou_dance_timer_ontimer69000,
        "Bijou#dance_timer::OnTimer7000" => dancer::bijou_dance_timer_ontimer7000,
        "Bijou#dance_timer::OnTimer70000" => dancer::bijou_dance_timer_ontimer70000,
        "Bijou#dance_timer::OnTimer74000" => dancer::bijou_dance_timer_ontimer74000,
        "Bijou#dance_timer::OnTimer75000" => dancer::bijou_dance_timer_ontimer75000,
        "Bijou#dance_timer::OnTimer8000" => dancer::bijou_dance_timer_ontimer8000,
        "Bijou#dance_timer::OnTimer80000" => dancer::bijou_dance_timer_ontimer80000,
        "Bijou#dance_timer::OnTimer81000" => dancer::bijou_dance_timer_ontimer81000,
        "Bijou#dance_timer::OnTimer82000" => dancer::bijou_dance_timer_ontimer82000,
        "Bijou#dance_timer::OnTimer89000" => dancer::bijou_dance_timer_ontimer89000,
        "Waiting Room#dance::OnEnable" => dancer::waiting_room_dance_onenable,
        "Waiting Room#dance::OnInit" => dancer::waiting_room_dance_oninit,
        "Waiting Room#dance::OnStartArena" => dancer::waiting_room_dance_onstartarena,
        "dance#poring::OnDisable" => dancer::dance_poring_ondisable,
        "dance#poring::OnEnable" => dancer::dance_poring_onenable,
        "dance#poring::OnMyMobDead" => dancer::dance_poring_onmymobdead,
        "dance#return#2::OnDisable" => dancer::dance_return_2_ondisable,
        "dance#return#2::OnEnable" => dancer::dance_return_2_onenable,
        "dance#return#2::OnTouch_" => dancer::dance_return_2_ontouch,
        "dance#return#3::OnDisable" => dancer::dance_return_3_ondisable,
        "dance#return#3::OnEnable" => dancer::dance_return_3_onenable,
        "dance#return#3::OnTouch_" => dancer::dance_return_3_ontouch,
        "dance#return::OnDisable" => dancer::dance_return_ondisable,
        "dance#return::OnEnable" => dancer::dance_return_onenable,
        "dance#return::OnTouch_" => dancer::dance_return_ontouch,
        "dancestep::OnTouch_" => dancer::dancestep_ontouch,
    }
}
