// Generated by tools/scripts-import/convert_sdk2.py from npc/quests/first_class/tu_ma_th01.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn trace_of_battle_1_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThere are signs that show",
            "that some violent scuffle",
            "might have occurred here,",
            "but you can't tell what had",
            "happened exactly...^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 5 && l_class_thief.clone().is_true())
            || (l_class_mage.clone().is_true() && ctx.var("tu_magician01").get()?.number()? < 8))
        {
            ctx.lines(args![
                "^3355FFYou find traces of poison",
                "used in a battle. You sense",
                "its potency and decide not",
                "to get too close to it.^000000"
            ])?;
            if l_class_mage.clone().is_true() {
                ctx.call(Function::NpcSpecialEffect, vec![ctx.constant("EF_VENOMDUST2")?])?;
            }
        } else {
            if (ctx.var("tu_thief01").get()? == 5 && l_class_thief.clone().is_true()) {
                ctx.lines(args![
                    "^3355FFYou find traces of poison",
                    "used in a battle. A feeling",
                    "of acute dizziness overcomes",
                    "you after examining the scene.^000000"
                ])?;
                ctx.var("tu_thief01").set(Val::from(6))?;
                ctx.call(
                    Function::StartStatus,
                    vec![ctx.constant("SC_POISON")?, Val::from(60000), Val::from(0)],
                )?;
                ctx.call(Function::NpcSpecialEffect, vec![ctx.constant("EF_VENOMDUST2")?])?;
            } else {
                if (ctx.var("tu_thief01").get()? == 6 && l_class_thief.clone().is_true()) {
                    ctx.lines(args![
                        "^3355FFYou find traces of poison",
                        "used in a battle. A feeling",
                        "of acute dizziness overcomes",
                        "you after examining the scene.^000000"
                    ])?;
                    ctx.call(
                        Function::StartStatus,
                        vec![ctx.constant("SC_POISON")?, Val::from(60000), Val::from(0)],
                    )?;
                    ctx.call(Function::NpcSpecialEffect, vec![ctx.constant("EF_VENOMDUST2")?])?;
                } else {
                    if (ctx.var("tu_thief01").get()? == 7 && l_class_thief.clone().is_true()) {
                        ctx.lines(args![
                            "^3355FFYou find traces of poison",
                            "used in a battle. You sense",
                            "its potency and decide not",
                            "to get too close to it.^000000"
                        ])?;
                    } else {
                        if ((l_class_thief.clone().is_true() && ctx.var("tu_thief01").get()? == 8)
                            || (l_class_mage.clone().is_true() && ctx.var("tu_magician01").get()? == 8))
                        {
                            ctx.lines(args![
                                "^3355FFThere are traces of a battle",
                                "that seem to be leading in",
                                "different directions. From the",
                                "peculiar smell that permeates",
                                "the area, it seems that some",
                                "kind of lethal poison was used.^000000"
                            ])?;
                            ctx.next()?;
                            ctx.lines(args![
                                "^3355FFStill...",
                                "The trail of this",
                                "battle decidedly",
                                "heads southward.^000000"
                            ])?;
                            if ctx.var("tu_magician01").get()? == 8 {
                                ctx.var("tu_magician01").set(Val::from(9))?;
                            } else {
                                ctx.var("tu_thief01").set(Val::from(9))?;
                            }
                        } else {
                            ctx.lines(args!["^3355FFYou find signs of", "a heated pursuit", "that head south."])?;
                        }
                    }
                }
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_1(ctx: &Ctx) -> Script {
    trace_of_battle_1_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_2_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThere are signs that show",
            "that some violent scuffle",
            "might have occurred here,",
            "but you can't tell what had",
            "happened exactly...^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 9 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 9 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that many people",
                "have traveled through",
                "this particular area.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 9 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 9 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFYou've found traces",
                    "of the pursuit which",
                    "continue eastward.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 9 {
                    ctx.var("tu_magician01").set(Val::from(10))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(10))?;
                }
            } else {
                ctx.lines(args!["^3355FFThese traces of", "the pursuit lead", "towards the east.^000000"])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_2(ctx: &Ctx) -> Script {
    trace_of_battle_2_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_3_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 10 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 10 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that many people",
                "have traveled through",
                "this particular area.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 10 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 10 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFYou examine these traces",
                    "and notice that one set of",
                    "footprints looks almost too",
                    "pronounced, as if it had been",
                    "made for somebody to find.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 10 {
                    ctx.var("tu_magician01").set(Val::from(11))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(11))?;
                }
            } else {
                ctx.lines(args!["^3355FFIt's a very", "strange looking", "set of footprints.^000000"])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_3(ctx: &Ctx) -> Script {
    trace_of_battle_3_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_4_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThere are signs that show",
            "that some violent scuffle",
            "might have occurred here,",
            "but you can't tell what had",
            "happened exactly...^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 11 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 11 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that many people",
                "have traveled through",
                "this particular area.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 11 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 11 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFFrom these traces,",
                    "you see that another",
                    "set of footprints has",
                    "been added. It looks like",
                    "someone else got involved.",
                    "These prints are distinctly",
                    "clearer and much smaller.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 11 {
                    ctx.var("tu_magician01").set(Val::from(12))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(12))?;
                }
            } else {
                ctx.lines(args![
                    "^3355FFFrom these traces,",
                    "you see that another",
                    "person has gotten involved",
                    "in this heated scuffle.^000000"
                ])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_4(ctx: &Ctx) -> Script {
    trace_of_battle_4_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_5_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 12 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 12 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that many people",
                "have traveled through",
                "this particular area.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 12 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 12 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFThe traces of the battle",
                    "now split and head towards",
                    "the north and south. However,^000000"
                ])?;
                if ctx.call(Function::CountItem, vec![Val::from(506)])? == 0 {
                    ctx.mes(
                        "^3355FFthere is a puddle of strong poison that you must neutralize before you can investigate this scene.^000000",
                    )?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
                ctx.mes(
                    "^3355FFthere is a puddle of strong poison that you must neutralize before you can investigate this scene.^000000",
                )?;
                ctx.next()?;
                ctx.lines(args![
                    "^3355FFFortunately, you can",
                    "temporarily nullify the",
                    "poison by using one",
                    "of your Green Potions.^000000"
                ])?;
                ctx.next()?;
                'b1: {
                    let subject1 = Val::from(runtime::select_values(ctx, &[Val::from("Use Green Potion.:Don't use it.")])?);
                    let mut matched1 = false;
                    let no_case1 = !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2));
                    if !matched1 && subject1.loosely_equals(&Val::from(1)) {
                        matched1 = true;
                    }
                    if matched1 {
                        ctx.lines(args![
                            "^3355FFThe poison weakens",
                            "and some of it evaporates,",
                            "revealing a piece of cloth that",
                            "was hidden in that puddle.^000000"
                        ])?;
                        ctx.next()?;
                        'b2: {
                            let subject2 = Val::from(runtime::select_values(ctx, &[Val::from("Don't investigate.:Investigate.")])?);
                            let mut matched2 = false;
                            let no_case2 = !subject2.loosely_equals(&Val::from(1)) && !subject2.loosely_equals(&Val::from(2));
                            if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                                matched2 = true;
                            }
                            if matched2 {
                                ctx.lines_as(
                                    ctx.call(Function::StrCharInfo, vec![Val::from(0)])?,
                                    args!["A piece of cloth", "is nothing to be", "concerned about."],
                                )?;
                                ctx.close_window()?;
                                return Err(Stop::End);
                            }
                            if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                                matched2 = true;
                            }
                            if matched2 {
                                ctx.lines_as(
                                    ctx.call(Function::StrCharInfo, vec![Val::from(0)])?,
                                    args![
                                        "Hey... There's",
                                        "blood on this cloth",
                                        "and some writing on",
                                        "it that I can't recognize.",
                                        "Hopefully, this'll provide",
                                        "some sort of clue to all this?"
                                    ],
                                )?;
                                if ctx.var("tu_thief01").get()? == 12 {
                                    ctx.var("tu_thief01").set(Val::from(13))?;
                                } else {
                                    ctx.var("tu_magician01").set(Val::from(13))?;
                                }
                                ctx.next()?;
                                ctx.lines(args![
                                    "^3355FFYou take the piece",
                                    "of cloth from the puddle",
                                    "of poison and keep it with you.^000000"
                                ])?;
                                ctx.close_window()?;
                                return Err(Stop::End);
                            }
                        }
                    }
                    if !matched1 && subject1.loosely_equals(&Val::from(2)) {
                        matched1 = true;
                    }
                    if matched1 {
                        ctx.lines_as(
                            ctx.call(Function::StrCharInfo, vec![Val::from(0)])?,
                            args![
                                "Hmm...",
                                "It'll probably be",
                                "faster if I follow this",
                                "trail, rather than stop to",
                                "investigate this scene."
                            ],
                        )?;
                        ctx.close_window()?;
                        return Err(Stop::End);
                    }
                }
            } else {
                ctx.lines(args![
                    "^3355FFYou can't find",
                    "anything else here,",
                    "aside from the traces",
                    "that split and lead both",
                    "northward and southward.^000000"
                ])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_5(ctx: &Ctx) -> Script {
    trace_of_battle_5_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_6_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 13 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 13 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that many people",
                "have traveled through",
                "this particular area.^000000"
            ])?;
        } else {
            ctx.lines(args![
                "^3355FFThese footprints",
                "look like they're",
                "heading towards the",
                "north from the south.",
                "But you can't really",
                "be sure just yet.^000000"
            ])?;
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_6(ctx: &Ctx) -> Script {
    trace_of_battle_6_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_7_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 13 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 13 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that many people",
                "have traveled through",
                "this particular area.^000000"
            ])?;
        } else {
            ctx.lines(args![
                "^3355FFThe trail here looks pretty",
                "muddled, since it looks like",
                "they battled here for quite a",
                "while. But the footprints are",
                "definitely heading south.^000000"
            ])?;
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_7(ctx: &Ctx) -> Script {
    trace_of_battle_7_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_8_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 13 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 13 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are two",
                "distinct sets of",
                "footprints in this",
                "area, but they don't",
                "hold any significance",
                "right about now.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 13 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 13 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFAround here, it",
                    "looks like there are",
                    "only two sets of footprints.",
                    "What happened to the other",
                    "set that you found earlier?^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 13 {
                    ctx.var("tu_magician01").set(Val::from(14))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(14))?;
                }
            } else {
                ctx.lines(args![
                    "^3355FFFrom the evidence",
                    "that you've found here,",
                    "it looks like the battle",
                    "involves only two people",
                    "from this point onward.^000000"
                ])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_8(ctx: &Ctx) -> Script {
    trace_of_battle_8_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_9_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 14 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 14 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFTraces of some",
                "sort of battle are",
                "scattered all over",
                "this particular area.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 14 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 14 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFYou follow the trail",
                    "and although traces from",
                    "the north and southeast mix",
                    "together, it looks like the battle continues towards the east.",
                    "But you should check this",
                    "spot a little bit more...^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 14 {
                    ctx.var("tu_magician01").set(Val::from(15))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(15))?;
                }
            } else {
                if ((ctx.var("tu_thief01").get()? == 15 && l_class_thief.clone().is_true())
                    || (ctx.var("tu_magician01").get()? == 15 && l_class_mage.clone().is_true()))
                {
                    if ctx.call(Function::Rand, vec![Val::from(1), Val::from(10)])? == 7 {
                        ctx.lines(args![
                            "^3355FFAfter investigating this",
                            "area more thoroughly,",
                            "you find another piece of",
                            "cloth stained with blood.",
                            "You decide to keep it with",
                            "you, hoping that it will",
                            "provide more clues.^000000"
                        ])?;
                        if ctx.var("tu_magician01").get()? == 15 {
                            ctx.var("tu_magician01").set(Val::from(16))?;
                        } else {
                            ctx.var("tu_thief01").set(Val::from(16))?;
                        }
                    } else {
                        ctx.lines(args![
                            "^3355FFYou don't find anything,",
                            "but you still can't shake",
                            "the feeling that there is",
                            "some important clue that",
                            "you have to find here. It won't hurt to keep investigating here.^000000"
                        ])?;
                    }
                } else {
                    ctx.lines(args![
                        "^3355FFYou better continue",
                        "following this trail",
                        "which leads westward.^000000"
                    ])?;
                }
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_9(ctx: &Ctx) -> Script {
    trace_of_battle_9_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_10_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 16 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 16 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "showing that a lot",
                "of people were in",
                "this area earlier.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 16 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 16 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFThe lead set of footprints,",
                    "probably belonging to the one",
                    "who was being pursued, look",
                    "more erratic, as if exhaustion",
                    "and desperation were setting in. These traces lead to the west.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 16 {
                    ctx.var("tu_magician01").set(Val::from(17))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(17))?;
                }
            } else {
                ctx.lines(args!["^3355FFThe trail from", "this point heads", "towards the west.^000000"])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_10(ctx: &Ctx) -> Script {
    trace_of_battle_10_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_11_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 17 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 17 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "showing that a lot",
                "of people were in",
                "this area earlier.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 17 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 17 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFFollowing the",
                    "trail, you see signs",
                    "that blood was spilled",
                    "in this area. It looks like",
                    "someone was injured",
                    "pretty badly around here.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 17 {
                    ctx.var("tu_magician01").set(Val::from(18))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(18))?;
                }
            } else {
                ctx.lines(args![
                    "^3355FFSince someone involved",
                    "in this conflict was bleeding,",
                    "further traces of this pursuit",
                    "might be easier to find now.^000000"
                ])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_11(ctx: &Ctx) -> Script {
    trace_of_battle_11_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_12_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 18 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 18 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "showing that a lot",
                "of people were in",
                "this area earlier.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 18 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 18 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFThese traces lead",
                    "northward and it looks",
                    "like whoever is doing",
                    "the chasing is getting",
                    "much closer to his prey.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 18 {
                    ctx.var("tu_magician01").set(Val::from(19))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(19))?;
                }
            } else {
                ctx.lines(args![
                    "^3355FFThe trail of this",
                    "pursuit now leads",
                    "towards the north.^000000"
                ])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_12(ctx: &Ctx) -> Script {
    trace_of_battle_12_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_13_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if (ctx.var("tu_thief01").get()?.number()? < 19 && l_class_thief.clone().is_true()) {
            ctx.lines(args![
                "^3355FFThere are signs",
                "showing that a lot",
                "of people were in",
                "this area earlier.^000000"
            ])?;
        } else {
            if (ctx.var("tu_magician01").get()?.number()? < 19 && l_class_mage.clone().is_true()) {
                ctx.mes("A large group of people seem to have gone by.")?;
            } else {
                if ((ctx.var("tu_thief01").get()? == 19 && l_class_thief.clone().is_true())
                    || (ctx.var("tu_magician01").get()? == 19 && l_class_mage.clone().is_true()))
                {
                    ctx.lines(args![
                        "^3355FFJudging from these",
                        "traces, it looks like",
                        "even more people have",
                        "joined the battle which",
                        "now seems to be leading",
                        "in the southwest direction.^000000"
                    ])?;
                    if ctx.var("tu_magician01").get()? == 19 {
                        ctx.var("tu_magician01").set(Val::from(20))?;
                    } else {
                        ctx.var("tu_thief01").set(Val::from(20))?;
                    }
                } else {
                    ctx.lines(args![
                        "^3355FFIt looks like",
                        "the battle heads",
                        "towards the southwest",
                        "from this particular point.^000000"
                    ])?;
                }
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_13(ctx: &Ctx) -> Script {
    trace_of_battle_13_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_14_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 20 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 20 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "showing that a lot",
                "of people were in",
                "this area earlier.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 20 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 20 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFIn this area, it looks",
                    "like even more people",
                    "joined in this battle and",
                    "the pursuit clearly heads",
                    "towards the south.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 20 {
                    ctx.var("tu_magician01").set(Val::from(21))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(21))?;
                }
            } else {
                ctx.lines(args!["^3355FFThe trail of", "this battle heads", "towards the south.^000000"])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_14(ctx: &Ctx) -> Script {
    trace_of_battle_14_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_15_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if (ctx.var("tu_thief01").get()?.number()? < 21 && l_class_thief.clone().is_true()) {
            ctx.lines(args![
                "^3355FFThere are signs",
                "showing that a lot",
                "of people were in",
                "this area earlier.^000000"
            ])?;
        } else {
            if (ctx.var("tu_magician01").get()?.number()? < 21 && l_class_mage.clone().is_true()) {
                ctx.mes("A large group of people seem to have gone by.")?;
            } else {
                if ((ctx.var("tu_thief01").get()? == 21 && l_class_thief.clone().is_true())
                    || (ctx.var("tu_magician01").get()? == 21 && l_class_mage.clone().is_true()))
                {
                    ctx.lines(args![
                        "^3355FFThis area is clearly",
                        "marked with signs",
                        "of a violent battle, with",
                        "traces of poison strewn",
                        "all over the ground.^000000"
                    ])?;
                    ctx.next()?;
                    'b1: {
                        let subject1 = Val::from(runtime::select_values(
                            ctx,
                            &[Val::from("Continue following the traces.:Further investigate the area.")],
                        )?);
                        let mut matched1 = false;
                        let no_case1 = !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2));
                        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
                            matched1 = true;
                        }
                        if matched1 {
                            ctx.lines(args![
                                "^3355FFYou examine the",
                                "trail, but can't really",
                                "discern the direction",
                                "in which the battle",
                                "continues...^000000"
                            ])?;
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
                            matched1 = true;
                        }
                        if matched1 {
                            ctx.lines(args![
                                "^3355FFYou find a bunch of",
                                "traps that use different",
                                "kinds of poison. The ones",
                                "that have been set off are",
                                "mixed with the ones which",
                                "haven't been triggered.^000000"
                            ])?;
                            if ctx.var("tu_thief01").get()? == 21 {
                                ctx.var("tu_thief01").set(Val::from(22))?;
                            } else {
                                ctx.var("tu_magician01").set(Val::from(22))?;
                            }
                            ctx.close_window()?;
                            return Err(Stop::End);
                        }
                    }
                } else {
                    if ((ctx.var("tu_thief01").get()? == 22 && l_class_thief.clone().is_true())
                        || (ctx.var("tu_magician01").get()? == 22 && l_class_mage.clone().is_true()))
                    {
                        if ctx.call(Function::Rand, vec![Val::from(1), Val::from(3)])? == 3 {
                            ctx.lines(args![
                                "^3355FFOne trap in particular",
                                "stands out to you more",
                                "than the rest. Perhaps",
                                "you should pour some",
                                "Green Potion on it to",
                                "neutralize it first.^000000"
                            ])?;
                            ctx.next()?;
                            'b2: {
                                let subject2 = Val::from(runtime::select_values(
                                    ctx,
                                    &[Val::from("Pour Green Potion.:Don't use Green Potion.")],
                                )?);
                                let mut matched2 = false;
                                let no_case2 = !subject2.loosely_equals(&Val::from(1)) && !subject2.loosely_equals(&Val::from(2));
                                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                                    matched2 = true;
                                }
                                if matched2 {
                                    if ctx.call(Function::CountItem, vec![Val::from(506)])?.number()? < 1 {
                                        ctx.lines(args![
                                            "^3355FFUnfortunately, you",
                                            "don't have a Green",
                                            "Potion that you can",
                                            "use to pour on this trap...^000000"
                                        ])?;
                                        ctx.close_window()?;
                                        return Err(Stop::End);
                                    } else {
                                        ctx.lines(args![
                                            "^3355FFPouring that",
                                            "Green Potion didn't",
                                            "really make anything",
                                            "happen. Perhaps you",
                                            "should try something else.^000000"
                                        ])?;
                                        ctx.call(Function::DelItem, vec![Val::from(506), Val::from(1)])?;
                                        if ctx.var("tu_thief01").get()? == 22 {
                                            ctx.var("tu_thief01").set(Val::from(23))?;
                                        } else {
                                            ctx.var("tu_magician01").set(Val::from(23))?;
                                        }
                                        ctx.close_window()?;
                                        return Err(Stop::End);
                                    }
                                }
                                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                                    matched2 = true;
                                }
                                if matched2 {
                                    ctx.lines_as(
                                        ctx.call(Function::StrCharInfo, vec![Val::from(0)])?,
                                        args!["I guess...", "I'll try investigating", "this area a little more?"],
                                    )?;
                                    ctx.close_window()?;
                                    return Err(Stop::End);
                                }
                            }
                        } else {
                            ctx.lines(args![
                                "^3355FFBy sheer accident,",
                                "you set off one of",
                                "the traps in the area.^000000"
                            ])?;
                            ctx.call(
                                Function::StartStatus,
                                vec![ctx.constant("SC_POISON")?, Val::from(60000), Val::from(0)],
                            )?;
                            ctx.call(Function::NpcSpecialEffect, vec![ctx.constant("EF_VENOMDUST2")?])?;
                            ctx.call(Function::PercentHeal, vec![Val::from(-30), Val::from(0)])?;
                        }
                    } else {
                        if ((ctx.var("tu_thief01").get()? == 23 && l_class_thief.clone().is_true())
                            || (ctx.var("tu_magician01").get()? == 23 && l_class_mage.clone().is_true()))
                        {
                            if (ctx.call(Function::CountItem, vec![Val::from(511)])?.number()? > 0
                                && ctx.call(Function::CountItem, vec![Val::from(716)])?.number()? > 0)
                            {
                                ctx.lines(args![
                                    "^3355FFYou try grinding",
                                    "a Green Herb and",
                                    "sprinkling it on the",
                                    "trap and then place",
                                    "a Red Gemstone on it.",
                                    "The gem glows and",
                                    "slowly melts away...^000000"
                                ])?;
                                ctx.next()?;
                                ctx.lines(args![
                                    "^3355FFAlthough you don't",
                                    "fully understand the",
                                    "science of using poisons",
                                    "or antidotes, you managed",
                                    "to successfully dismantle",
                                    "the trap. Now you can safely",
                                    "check what might be inside.^000000"
                                ])?;
                                ctx.call(Function::DelItem, vec![Val::from(511), Val::from(1)])?;
                                ctx.call(Function::DelItem, vec![Val::from(716), Val::from(1)])?;
                                if ctx.var("tu_thief01").get()? == 23 {
                                    ctx.var("tu_thief01").set(Val::from(24))?;
                                } else {
                                    ctx.var("tu_magician01").set(Val::from(24))?;
                                }
                            } else {
                                if ctx.call(Function::CountItem, vec![Val::from(511)])?.number()? > 0 {
                                    ctx.lines(args![
                                        "^3355FFYou should try to",
                                        "dismantle this trap",
                                        "by using other catalysts",
                                        "related to the curing or",
                                        "use of poison. You do have",
                                        "a Green Herb on you, so you",
                                        "try sprinkling it on the trap.^000000"
                                    ])?;
                                    ctx.next()?;
                                    ctx.lines(args![
                                        "^3355FFHowever, nothing",
                                        "happens. It seems that",
                                        "you need another catalyst",
                                        "in addition to the Green Herb",
                                        "that you have in order to",
                                        "dismantle this trap.^000000"
                                    ])?;
                                } else {
                                    if ctx.call(Function::CountItem, vec![Val::from(716)])?.number()? > 0 {
                                        ctx.lines(args![
                                            "^3355FFYou should try to",
                                            "dismantle this trap",
                                            "by using other catalysts",
                                            "related to the curing or use",
                                            "of poison. You do have a",
                                            "Red Gemstone, so you grind",
                                            "it and sprinkle it on the trap.^000000"
                                        ])?;
                                        ctx.next()?;
                                        ctx.lines(args![
                                            "^3355FFHowever, nothing",
                                            "happens. It seems that",
                                            "you need another catalyst to",
                                            "use with the Red Gemstone",
                                            "that you have in order to",
                                            "dismantle this trap.^000000"
                                        ])?;
                                    } else {
                                        ctx.lines(args![
                                            "^3355FFYou should try to",
                                            "dismantle this trap",
                                            "by using other catalysts",
                                            "related to the curing or",
                                            "use of poison. But what",
                                            "items should you bring?^000000"
                                        ])?;
                                    }
                                }
                            }
                        } else {
                            if ((ctx.var("tu_thief01").get()? == 24 && l_class_thief.clone().is_true())
                                || (ctx.var("tu_magician01").get()? == 24 && l_class_mage.clone().is_true()))
                            {
                                ctx.lines(args![
                                    "^3355FFInside the dismantled",
                                    "trap, you find another",
                                    "piece of strange cloth",
                                    "that's stained with blood.",
                                    "You take it with you in",
                                    "hopes that it provides",
                                    "some kind of evidence.^000000"
                                ])?;
                                if ctx.var("tu_thief01").get()? == 24 {
                                    ctx.var("tu_thief01").set(Val::from(25))?;
                                } else {
                                    ctx.var("tu_magician01").set(Val::from(25))?;
                                }
                            } else {
                                ctx.lines(args![
                                    "^3355FFYou examine the area",
                                    "a little further and guess",
                                    "that the battle might head",
                                    "towards the south.^000000"
                                ])?;
                            }
                        }
                    }
                }
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_15(ctx: &Ctx) -> Script {
    trace_of_battle_15_body(ctx, Vec::new()).map(|_| ())
}

fn trace_of_battle_16_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_class_mage = Val::from(0);
    let mut l_class_thief = Val::from(0);
    l_class_thief = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_THIEF")?));
    l_class_mage = Val::from(ctx.var("BaseClass").get()?.loosely_equals(&ctx.constant("JOB_MAGE")?));
    if ((l_class_thief.clone() == 0 && l_class_mage.clone() == 0)
        || runtime::op(&ctx.call(Function::EaClass, vec![])?, "&", &ctx.constant("EAJL_BABY")?)?.is_true())
    {
        ctx.lines(args![
            "^3355FFThese look like",
            "traces of some kind",
            "of pursuit or battle, but",
            "you can't really tell for sure.^000000"
        ])?;
    } else {
        if ((ctx.var("tu_thief01").get()?.number()? < 25 && l_class_thief.clone().is_true())
            || (ctx.var("tu_magician01").get()?.number()? < 25 && l_class_mage.clone().is_true()))
        {
            ctx.lines(args![
                "^3355FFThere are signs",
                "that a large group",
                "of people have been in",
                "this area for some reason.^000000"
            ])?;
        } else {
            if ((ctx.var("tu_thief01").get()? == 25 && l_class_thief.clone().is_true())
                || (ctx.var("tu_magician01").get()? == 25 && l_class_mage.clone().is_true()))
            {
                ctx.lines(args![
                    "^3355FFThese traces lead",
                    "to the edge of the cliff.",
                    "marking the end of the trail.",
                    "Apparently, the one who was",
                    "being chased met his fate here.^000000"
                ])?;
                ctx.next()?;
                ctx.lines(args![
                    "^3355FFThere are many footprints",
                    "leading to the edge of the",
                    "cliff and all of them leave",
                    "this scene, save for the set",
                    "of footprints that distinctly",
                    "belong to the person who",
                    "was pursued all this time...^3355FF"
                ])?;
                ctx.next()?;
                ctx.lines(args![
                    "^3355FFIt looks like you've",
                    "learned all that you can",
                    "from this investigation. You",
                    "better return and report your",
                    "findings to Yierhan soon.^000000"
                ])?;
                if ctx.var("tu_magician01").get()? == 25 {
                    ctx.var("tu_magician01").set(Val::from(26))?;
                } else {
                    ctx.var("tu_thief01").set(Val::from(26))?;
                }
            } else {
                ctx.lines(args![
                    "^3355FFThis is the end",
                    "of the trail. There",
                    "aren't any more traces",
                    "of the battle left to find.^000000"
                ])?;
            }
        }
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn trace_of_battle_16(ctx: &Ctx) -> Script {
    trace_of_battle_16_body(ctx, Vec::new()).map(|_| ())
}
