pub mod guides;
pub mod other;

script_sdk_2::script_module! {
    npcs {
        "Adventurer#um" => guides::guides_umbala::adventurer_um,
        "Amatsu Guide#ama" => guides::guides_amatsu::amatsu_guide_ama,
        "Brasilis Guide" => guides::guides_brasilis::brasilis_guide,
        "Bulletin Board#08" => other::bulletin_boards::bulletin_board_08,
        "Bulletin Board#10" => other::bulletin_boards::bulletin_board_10,
        "Bulletin Board#16" => other::bulletin_boards::bulletin_board_16,
        "Bulletin Board#19" => other::bulletin_boards::bulletin_board_19,
        "Bulletin Board#20" => other::bulletin_boards::bulletin_board_20,
        "Bulletin Board#21" => other::bulletin_boards::bulletin_board_21,
        "Bulletin Board#23" => other::bulletin_boards::bulletin_board_23,
        "Bulletin Board#24" => other::bulletin_boards::bulletin_board_24,
        "Bulletin Board#27" => other::bulletin_boards::bulletin_board_27,
        "Bulletin Board#3" => other::bulletin_boards::bulletin_board_3,
        "Bulletin Board#5" => other::bulletin_boards::bulletin_board_5,
        "Comodo Guide#2cmd" => guides::guides_comodo::comodo_guide_2cmd,
        "Comodo Guide#cmd" => guides::guides_comodo::comodo_guide_cmd,
        "Fight Square Reception#8" => other::pvp::fight_square_reception_8,
        "Fight Square Reception#n" => other::pvp::fight_square_reception_n,
        "Guide Man#2ama" => guides::guides_amatsu::guide_man_2ama,
        "Guide#2cmd" => guides::guides_comodo::guide_2cmd,
        "Guide#2pay" => guides::guides_payon::guide_2pay,
        "Guide#4ein" => guides::guides_einbroch::guide_4ein,
        "Guide#alb" => guides::guides_alberta::guide_alb,
        "Guide#ein" => guides::guides_einbroch::guide_ein,
        "Guide#gef" => guides::guides_geffen::guide_gef,
        "Guide#iz" => guides::guides_izlude::guide_iz,
        "Guide#lhz" => guides::guides_lighthalzen::guide_lhz,
        "Guide#moc" => guides::guides_morroc::guide_moc,
        "Guide#pay" => guides::guides_payon::guide_pay,
        "Guide#prt" => guides::guides_prontera::guide_prt,
        "Hugel Guide Granny#huge" => guides::guides_hugel::hugel_guide_granny_huge,
        "Hypnotist#2" => other::resetskill::hypnotist_2,
        "Juno Guide#yuno" => guides::guides_juno::juno_guide_yuno,
        "Kunlun Guide#gon" => guides::guides_gonryun::kunlun_guide_gon,
        "Moscovia Guide#mosk" => guides::guides_moscovia::moscovia_guide_mosk,
        "Noi#ayo" => guides::guides_ayothaya::noi_ayo,
        "Rachel Guide" => guides::guides_rachel::rachel_guide,
        "Representative#lou" => guides::guides_louyang::representative_lou,
        "Roaming Man#nif" => guides::guides_niflheim::roaming_man_nif,
        "Sign#Iz1" => other::msg_boards::sign_iz1,
        "Sign#Iz2" => other::msg_boards::sign_iz2,
        "Soldier#2alde" => guides::guides_aldebaran::soldier_2alde,
        "Soldier#BA" => guides::guides_louyang::soldier_ba,
        "Soldier#alde" => guides::guides_aldebaran::soldier_alde,
        "Veins Guide#1" => guides::guides_veins::veins_guide_1,
    }
    events {
        "Fight Square Reception#8::OnInit" => other::pvp::fight_square_reception_8_oninit,
        "Fight Square Reception#n::OnInit" => other::pvp::fight_square_reception_n_oninit,
    }
}
