#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod part_01;
mod part_02;
mod part_03;
mod part_04;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;

script_sdk_2::script_module! {
    npcs {
        "#Gate_manager_main" => gate_manager_main,
        "#Maze_Manager_main" => maze_manager_main,
        "#event_start01_main" => event_start01_main,
        "#gd_main_mobctrl" => gd_main_mobctrl,
        "#gdtimer01_main" => gdtimer01_main,
        "#gdtimer02_main" => gdtimer02_main,
        "#getspells_main" => getspells_main,
        "#gq_miromob2_main" => gq_miromob2_main,
        "#main_cages" => main_cages,
        "#main_stone01" => main_stone01,
        "#main_stone02" => main_stone02,
        "#main_stone03" => main_stone03,
        "#miro_bf_main" => miro_bf_main,
        "#miro_rf_main" => miro_rf_main,
        "#miro_yf_main" => miro_yf_main,
        "#nm_switch_main" => nm_switch_main,
        "#nmsommain_jin01" => nmsommain_jin01,
        "#nmsommain_jin02" => nmsommain_jin02,
        "#nmsommain_jin03" => nmsommain_jin03,
        "#okolnir_main" => okolnir_main,
        "#okolnir_main_time01" => okolnir_main_time01,
        "#piamette_main" => piamette_main_l1220,
        "#to_agit_main_gate" => to_agit_main_gate,
        "Bloody Hunter#main_all" => bloody_hunter_main_all,
        "Gate01#gq_main" => gate01_gq_main,
        "Guard of Shadow#main_all" => guard_of_shadow_main_all,
        "Guide#gq_main" => guide_gq_main,
        "Piamette#main" => piamette_main,
        "Temple Keeper#main_all" => temple_keeper_main_all,
        "Wish Maiden#gq_main" => wish_maiden_gq_main,
        "Wish Maiden#main_boss" => wish_maiden_main_boss,
        "Wish Maiden#main_gift" => wish_maiden_main_gift,
        "windpath01_main" => windpath01_main,
        "windpaths_main" => windpaths_main,
    }
    events {
        "#Gate_manager_main::OnMyMobDead" => gate_manager_main_onmymobdead,
        "#Maze_Manager_main::OnDisable" => maze_manager_main_ondisable,
        "#Maze_Manager_main::OnEnable" => maze_manager_main_onenable,
        "#Maze_Manager_main::OnInit" => maze_manager_main_oninit,
        "#Maze_Manager_main::OnTimer1000" => maze_manager_main_ontimer1000,
        "#Maze_Manager_main::OnTimer120000" => maze_manager_main_ontimer120000,
        "#Maze_Manager_main::OnTimer121000" => maze_manager_main_ontimer121000,
        "#Maze_Manager_main::OnTimer123000" => maze_manager_main_ontimer123000,
        "#Maze_Manager_main::OnTimer2000" => maze_manager_main_ontimer2000,
        "#Maze_Manager_main::OnTimer240000" => maze_manager_main_ontimer240000,
        "#Maze_Manager_main::OnTimer241000" => maze_manager_main_ontimer241000,
        "#Maze_Manager_main::OnTimer242000" => maze_manager_main_ontimer242000,
        "#Maze_Manager_main::OnTimer3000" => maze_manager_main_ontimer3000,
        "#Maze_Manager_main::OnTimer360000" => maze_manager_main_ontimer360000,
        "#event_start01_main::OnDisable" => event_start01_main_ondisable,
        "#event_start01_main::OnEnable" => event_start01_main_onenable,
        "#event_start01_main::OnInit" => event_start01_main_oninit,
        "#event_start01_main::OnTimer10000" => event_start01_main_ontimer10000,
        "#event_start01_main::OnTimer14000" => event_start01_main_ontimer14000,
        "#event_start01_main::OnTimer2000" => event_start01_main_ontimer2000,
        "#event_start01_main::OnTimer6000" => event_start01_main_ontimer6000,
        "#event_start01_main::OnTouch_" => event_start01_main_ontouch,
        "#gd_main_mobctrl::OnEnable" => gd_main_mobctrl_onenable,
        "#gd_main_mobctrl::OnMyMobDead" => gd_main_mobctrl_onmymobdead,
        "#gd_main_mobctrl::OnReset" => gd_main_mobctrl_onreset,
        "#gdtimer01_main::OnEnable" => gdtimer01_main_onenable,
        "#gdtimer01_main::OnStop" => gdtimer01_main_onstop,
        "#gdtimer01_main::OnTimer1000" => gdtimer01_main_ontimer1000,
        "#gdtimer01_main::OnTimer10000" => gdtimer01_main_ontimer10000,
        "#gdtimer01_main::OnTimer20000" => gdtimer01_main_ontimer20000,
        "#gdtimer01_main::OnTimer30000" => gdtimer01_main_ontimer30000,
        "#gdtimer01_main::OnTimer40000" => gdtimer01_main_ontimer40000,
        "#gdtimer01_main::OnTimer50000" => gdtimer01_main_ontimer50000,
        "#gdtimer01_main::OnTimer60000" => gdtimer01_main_ontimer60000,
        "#gdtimer01_main::OnTimer70000" => gdtimer01_main_ontimer70000,
        "#gdtimer01_main::OnTimer75000" => gdtimer01_main_ontimer75000,
        "#gdtimer01_main::OnTimer76000" => gdtimer01_main_ontimer76000,
        "#gdtimer01_main::OnTimer80000" => gdtimer01_main_ontimer80000,
        "#gdtimer02_main::OnEnable" => gdtimer02_main_onenable,
        "#gdtimer02_main::OnMyMobDead" => gdtimer02_main_onmymobdead,
        "#gdtimer02_main::OnReset" => gdtimer02_main_onreset,
        "#gdtimer02_main::OnStop" => gdtimer02_main_onstop,
        "#gdtimer02_main::OnTimer112000" => gdtimer02_main_ontimer112000,
        "#gdtimer02_main::OnTimer113000" => gdtimer02_main_ontimer113000,
        "#gdtimer02_main::OnTimer12000" => gdtimer02_main_ontimer12000,
        "#gdtimer02_main::OnTimer4000" => gdtimer02_main_ontimer4000,
        "#gdtimer02_main::OnTimer8000" => gdtimer02_main_ontimer8000,
        "#getspells_main::OnDisable" => getspells_main_ondisable,
        "#getspells_main::OnEnable" => getspells_main_onenable,
        "#getspells_main::OnInit" => getspells_main_oninit,
        "#getspells_main::OnTouch_" => getspells_main_ontouch,
        "#gq_miromob2_main::OnEnable" => gq_miromob2_main_onenable,
        "#gq_miromob2_main::OnMyMobDead" => gq_miromob2_main_onmymobdead,
        "#gq_miromob2_main::OnReset" => gq_miromob2_main_onreset,
        "#gq_miromob2_main::OnTimer1000" => gq_miromob2_main_ontimer1000,
        "#gq_miromob2_main::OnTimer6000" => gq_miromob2_main_ontimer6000,
        "#main_cages::OnInit" => main_cages_oninit,
        "#main_cages::OnTouch_" => main_cages_ontouch,
        "#main_stone01::OnEnable" => main_stone01_onenable,
        "#main_stone01::OnMyMobDead" => main_stone01_onmymobdead,
        "#main_stone01::OnReset" => main_stone01_onreset,
        "#main_stone02::OnEnable" => main_stone02_onenable,
        "#main_stone02::OnMyMobDead" => main_stone02_onmymobdead,
        "#main_stone02::OnReset" => main_stone02_onreset,
        "#main_stone03::OnEnable" => main_stone03_onenable,
        "#main_stone03::OnMyMobDead" => main_stone03_onmymobdead,
        "#main_stone03::OnReset" => main_stone03_onreset,
        "#miro_bf_main::OnDisable" => miro_bf_main_ondisable,
        "#miro_bf_main::OnEnable" => miro_bf_main_onenable,
        "#miro_bf_main::OnMyMobDead" => miro_bf_main_onmymobdead,
        "#miro_rf_main::OnDisable" => miro_rf_main_ondisable,
        "#miro_rf_main::OnEnable" => miro_rf_main_onenable,
        "#miro_rf_main::OnMyMobDead" => miro_rf_main_onmymobdead,
        "#miro_yf_main::OnDisable" => miro_yf_main_ondisable,
        "#miro_yf_main::OnEnable" => miro_yf_main_onenable,
        "#miro_yf_main::OnMyMobDead" => miro_yf_main_onmymobdead,
        "#nm_switch_main::OnDisable" => nm_switch_main_ondisable,
        "#nm_switch_main::OnEnable" => nm_switch_main_onenable,
        "#nm_switch_main::OnInit" => nm_switch_main_oninit,
        "#nm_switch_main::OnTimer1000" => nm_switch_main_ontimer1000,
        "#nm_switch_main::OnTimer10000" => nm_switch_main_ontimer10000,
        "#nm_switch_main::OnTimer190000" => nm_switch_main_ontimer190000,
        "#nm_switch_main::OnTimer370000" => nm_switch_main_ontimer370000,
        "#nm_switch_main::OnTimer4000" => nm_switch_main_ontimer4000,
        "#nm_switch_main::OnTimer9000" => nm_switch_main_ontimer9000,
        "#nm_switch_main::OnTouch_" => nm_switch_main_ontouch,
        "#nmsommain_jin01::OnDisable" => nmsommain_jin01_ondisable,
        "#nmsommain_jin01::OnEnable" => nmsommain_jin01_onenable,
        "#nmsommain_jin01::OnMyMobDead" => nmsommain_jin01_onmymobdead,
        "#nmsommain_jin01::OnTimer120000" => nmsommain_jin01_ontimer120000,
        "#nmsommain_jin01::OnTimer180000" => nmsommain_jin01_ontimer180000,
        "#nmsommain_jin01::OnTimer25000" => nmsommain_jin01_ontimer25000,
        "#nmsommain_jin01::OnTimer5000" => nmsommain_jin01_ontimer5000,
        "#nmsommain_jin01::OnTimer55000" => nmsommain_jin01_ontimer55000,
        "#nmsommain_jin01::OnTimer85000" => nmsommain_jin01_ontimer85000,
        "#nmsommain_jin02::OnDisable" => nmsommain_jin02_ondisable,
        "#nmsommain_jin02::OnEnable" => nmsommain_jin02_onenable,
        "#nmsommain_jin02::OnMyMobDead" => nmsommain_jin02_onmymobdead,
        "#nmsommain_jin02::OnTimer120000" => nmsommain_jin02_ontimer120000,
        "#nmsommain_jin02::OnTimer180000" => nmsommain_jin02_ontimer180000,
        "#nmsommain_jin02::OnTimer25000" => nmsommain_jin02_ontimer25000,
        "#nmsommain_jin02::OnTimer5000" => nmsommain_jin02_ontimer5000,
        "#nmsommain_jin02::OnTimer55000" => nmsommain_jin02_ontimer55000,
        "#nmsommain_jin02::OnTimer85000" => nmsommain_jin02_ontimer85000,
        "#nmsommain_jin03::OnDisable" => nmsommain_jin03_ondisable,
        "#nmsommain_jin03::OnEnable" => nmsommain_jin03_onenable,
        "#nmsommain_jin03::OnMyMobDead" => nmsommain_jin03_onmymobdead,
        "#nmsommain_jin03::OnTimer120000" => nmsommain_jin03_ontimer120000,
        "#nmsommain_jin03::OnTimer240000" => nmsommain_jin03_ontimer240000,
        "#nmsommain_jin03::OnTimer360000" => nmsommain_jin03_ontimer360000,
        "#nmsommain_jin03::OnTimer5000" => nmsommain_jin03_ontimer5000,
        "#okolnir_main::OnDisable" => okolnir_main_ondisable,
        "#okolnir_main::OnEnable" => okolnir_main_onenable,
        "#okolnir_main::OnStop" => okolnir_main_onstop,
        "#okolnir_main::OnTimer1000" => okolnir_main_ontimer1000,
        "#okolnir_main::OnTimer1800000" => okolnir_main_ontimer1800000,
        "#okolnir_main::OnTimer2400000" => okolnir_main_ontimer2400000,
        "#okolnir_main::OnTimer3000000" => okolnir_main_ontimer3000000,
        "#okolnir_main::OnTimer3300000" => okolnir_main_ontimer3300000,
        "#okolnir_main::OnTimer3360000" => okolnir_main_ontimer3360000,
        "#okolnir_main::OnTimer3420000" => okolnir_main_ontimer3420000,
        "#okolnir_main::OnTimer3480000" => okolnir_main_ontimer3480000,
        "#okolnir_main::OnTimer3540000" => okolnir_main_ontimer3540000,
        "#okolnir_main::OnTimer3600000" => okolnir_main_ontimer3600000,
        "#okolnir_main::OnTimer3605000" => okolnir_main_ontimer3605000,
        "#okolnir_main::OnTimer3608000" => okolnir_main_ontimer3608000,
        "#okolnir_main::OnTimer3610000" => okolnir_main_ontimer3610000,
        "#okolnir_main::OnTimer3611000" => okolnir_main_ontimer3611000,
        "#okolnir_main_time01::OnEnable" => okolnir_main_time01_onenable,
        "#okolnir_main_time01::OnInit" => okolnir_main_time01_oninit,
        "#okolnir_main_time01::OnReset" => okolnir_main_time01_onreset,
        "#okolnir_main_time01::OnTimer3600000" => okolnir_main_time01_ontimer3600000,
        "#piamette_main::OnEnable" => piamette_main_l1220_onenable,
        "#piamette_main::OnMyMobDead" => piamette_main_l1220_onmymobdead,
        "#piamette_main::OnReset" => piamette_main_l1220_onreset,
        "#piamette_main::OnTimer1000" => piamette_main_l1220_ontimer1000,
        "#piamette_main::OnTimer5000" => piamette_main_l1220_ontimer5000,
        "#to_agit_main_gate::OnInit" => to_agit_main_gate_oninit,
        "#to_agit_main_gate::OnTouch_" => to_agit_main_gate_ontouch,
        "Bloody Hunter#main_all::OnDisable" => bloody_hunter_main_all_ondisable,
        "Bloody Hunter#main_all::OnInit" => bloody_hunter_main_all_oninit,
        "Bloody Hunter#main_all::OnMyMobDead" => bloody_hunter_main_all_onmymobdead,
        "Bloody Hunter#main_all::OnTouch_" => bloody_hunter_main_all_ontouch,
        "Gate01#gq_main::OnDisable" => gate01_gq_main_ondisable,
        "Gate01#gq_main::OnEnable" => gate01_gq_main_onenable,
        "Gate01#gq_main::OnInit" => gate01_gq_main_oninit,
        "Gate01#gq_main::OnTouch_" => gate01_gq_main_ontouch,
        "Guard of Shadow#main_all::OnDisable" => guard_of_shadow_main_all_ondisable,
        "Guard of Shadow#main_all::OnInit" => guard_of_shadow_main_all_oninit,
        "Guard of Shadow#main_all::OnMyMobDead" => guard_of_shadow_main_all_onmymobdead,
        "Guard of Shadow#main_all::OnTouch_" => guard_of_shadow_main_all_ontouch,
        "Guide#gq_main::OnInit" => guide_gq_main_oninit,
        "Piamette#main::OnInit" => piamette_main_oninit,
        "Temple Keeper#main_all::OnDisable" => temple_keeper_main_all_ondisable,
        "Temple Keeper#main_all::OnInit" => temple_keeper_main_all_oninit,
        "Temple Keeper#main_all::OnMyMobDead" => temple_keeper_main_all_onmymobdead,
        "Temple Keeper#main_all::OnTouch_" => temple_keeper_main_all_ontouch,
        "Wish Maiden#gq_main::OnInit" => wish_maiden_gq_main_oninit,
        "Wish Maiden#main_boss::OnDisable" => wish_maiden_main_boss_ondisable,
        "Wish Maiden#main_boss::OnFight" => wish_maiden_main_boss_onfight,
        "Wish Maiden#main_boss::OnInit" => wish_maiden_main_boss_oninit,
        "Wish Maiden#main_boss::OnMyMobDead" => wish_maiden_main_boss_onmymobdead,
        "Wish Maiden#main_boss::OnTimer1000" => wish_maiden_main_boss_ontimer1000,
        "Wish Maiden#main_boss::OnTimer4000" => wish_maiden_main_boss_ontimer4000,
        "Wish Maiden#main_boss::OnTimer5000" => wish_maiden_main_boss_ontimer5000,
        "Wish Maiden#main_gift::OnDisable" => wish_maiden_main_gift_ondisable,
        "Wish Maiden#main_gift::OnEnable" => wish_maiden_main_gift_onenable,
        "Wish Maiden#main_gift::OnInit" => wish_maiden_main_gift_oninit,
        "Wish Maiden#main_gift::OnTimer280000" => wish_maiden_main_gift_ontimer280000,
        "Wish Maiden#main_gift::OnTimer290000" => wish_maiden_main_gift_ontimer290000,
        "Wish Maiden#main_gift::OnTimer300000" => wish_maiden_main_gift_ontimer300000,
        "windpath01_main::OnTouch_" => windpath01_main_ontouch,
        "windpaths_main::OnInit" => windpaths_main_oninit,
        "windpaths_main::OnTouch_" => windpaths_main_ontouch,
    }
}
