#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod part_10;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;
pub use part_08::*;
pub use part_09::*;
pub use part_10::*;

script_sdk_2::script_module! {
    npcs {
        "#LyozienSwitch" => lyozienswitch,
        "#Sneak" => sneak,
        "#bully1" => bully1,
        "#bully2" => bully2,
        "#flashback1" => flashback1,
        "#flashback2" => flashback2,
        "#kiz01-1" => kiz01_1,
        "#kiz02-1" => kiz02_1,
        "#kiz03" => kiz03,
        "#kiz03-1" => kiz03_1,
        "#kiz04" => kiz04,
        "#kiz05" => kiz05,
        "#kiz06" => kiz06,
        "#kiz07" => kiz07,
        "#kiz08" => kiz08,
        "#kiz09" => kiz09,
        "#kiz10" => kiz10,
        "#li_Man" => li_man,
        "#li_Varmunt" => li_varmunt,
        "#li_bird" => li_bird,
        "#li_bother" => li_bother,
        "#li_door" => li_door,
        "#li_end" => li_end,
        "#li_researcher" => li_researcher,
        "#li_toend" => li_toend,
        "#packidentity" => packidentity,
        "A File#li-1" => a_file_li_1,
        "A Fine Gentleman" => a_fine_gentleman,
        "A Neat Gentleman" => a_neat_gentleman,
        "Area 1-5" => area_1_5,
        "Area 1-7" => area_1_7,
        "Area 3-2" => area_3_2,
        "Area 3-3" => area_3_3,
        "Area 6-1" => area_6_1,
        "Barrel#cube" => barrel_cube,
        "Bed#cube" => bed_cube,
        "Book#lhz" => book_lhz,
        "Box#cube1" => box_cube1,
        "Broken Machine" => broken_machine,
        "Bundle of Files#cube" => bundle_of_files_cube,
        "Cabinet#cube" => cabinet_cube,
        "Chemicals#cube" => chemicals_cube,
        "Chest#cube" => chest_cube,
        "Crippled Girl#li_tre" => crippled_girl_li_tre,
        "Desk#cube" => desk_cube,
        "Digotz" => digotz,
        "Dismal Guy" => dismal_guy,
        "Door#cube" => door_cube,
        "Door#sneak" => door_sneak,
        "Drawer#cube" => drawer_cube,
        "Eavesdrop" => eavesdrop,
        "Elder#lhz" => elder_lhz,
        "Esuna Trigger" => esuna_trigger,
        "Exit1#lt" => exit1_lt,
        "Experiment Tube#cube" => experiment_tube_cube,
        "File Search Engine" => file_search_engine,
        "File#li" => file_li,
        "Fishbone" => fishbone,
        "Goblet#cube" => goblet_cube,
        "Guard" => guard,
        "Guard#lhz01" => guard_lhz01,
        "Guard#lhz02" => guard_lhz02,
        "Kafra Employee#l1" => kafra_employee_l1,
        "Kafra Employee#l2" => kafra_employee_l2,
        "Laboratory Guard#reken" => laboratory_guard_reken,
        "Law Enforcement" => law_enforcement,
        "Mad Scientist#li" => mad_scientist_li,
        "Maintenance Guy" => maintenance_guy,
        "Maku" => maku,
        "Man#Lyozien" => man_lyozien,
        "Mr. President" => mr_president,
        "Mysterious Woman" => mysterious_woman,
        "Old Man#reken" => old_man_reken,
        "Ordinary Man" => ordinary_man,
        "Passionate Student" => passionate_student,
        "Picture#cube" => picture_cube,
        "Power Generator#cube" => power_generator_cube,
        "Rekenber Guidebook#li" => rekenber_guidebook_li,
        "Representative#li_01" => representative_li_01,
        "Representative#li_02" => representative_li_02,
        "Researcher#1" => researcher_1,
        "Researcher#2" => researcher_2,
        "Scamp" => scamp,
        "Secretary Slierre#li" => secretary_slierre_li,
        "Secretary#1" => secretary_1,
        "Secretary#2" => secretary_2,
        "Status Light#cube" => status_light_cube,
        "Student" => student,
        "Suspicious Guy#lhz_01" => suspicious_guy_lhz_01,
        "Suspicious Guy#lhz_02" => suspicious_guy_lhz_02,
        "Suspicious Guy#lhz_03" => suspicious_guy_lhz_03,
        "Switch" => switch,
        "Timer_Sneak" => timer_sneak,
        "Wounded Man" => wounded_man,
        "Wounded Man Switch" => wounded_man_switch,
        "Young Man#reken" => young_man_reken,
        "boss" => boss,
    }
    events {
        "#Sneak::OnTouch_" => sneak_ontouch,
        "#bully1::OnEnter" => bully1_onenter,
        "#bully1::OnInit" => bully1_oninit,
        "#bully1::OnMyMobDead" => bully1_onmymobdead,
        "#bully1::OnReset" => bully1_onreset,
        "#bully1::OnTimer120000" => bully1_ontimer120000,
        "#bully2::OnEnter" => bully2_onenter,
        "#bully2::OnInit" => bully2_oninit,
        "#bully2::OnMyMobDead" => bully2_onmymobdead,
        "#bully2::OnReset" => bully2_onreset,
        "#bully2::OnTimer120000" => bully2_ontimer120000,
        "#flashback1::OnTouch_" => flashback1_ontouch,
        "#flashback2::OnTouch_" => flashback2_ontouch,
        "#kiz01-1::OnTouch_" => kiz01_1_ontouch,
        "#kiz02-1::OnTouch_" => kiz02_1_ontouch,
        "#kiz03-1::OnTouch_" => kiz03_1_ontouch,
        "#kiz03::OnTouch_" => kiz03_ontouch,
        "#kiz04::OnTouch_" => kiz04_ontouch,
        "#kiz05::OnTouch_" => kiz05_ontouch,
        "#kiz06::OnTouch_" => kiz06_ontouch,
        "#kiz07::OnTouch_" => kiz07_ontouch,
        "#kiz08::OnTouch_" => kiz08_ontouch,
        "#kiz09::OnTouch_" => kiz09_ontouch,
        "#kiz10::OnTouch_" => kiz10_ontouch,
        "#li_bird::OnTouch_" => li_bird_ontouch,
        "#li_bother::OnTouch_" => li_bother_ontouch,
        "#li_door::OnTouch_" => li_door_ontouch,
        "#li_end::OnTouch_" => li_end_ontouch,
        "#li_toend::OnTouch_" => li_toend_ontouch,
        "#packidentity::OnEnter" => packidentity_onenter,
        "#packidentity::OnInit" => packidentity_oninit,
        "#packidentity::OnTimer120000" => packidentity_ontimer120000,
        "#packidentity::OnTouch_" => packidentity_ontouch,
        "A Fine Gentleman::OnInit" => a_fine_gentleman_oninit,
        "A Neat Gentleman::OnInit" => a_neat_gentleman_oninit,
        "Eavesdrop::OnTouch_" => eavesdrop_ontouch,
        "Esuna Trigger::OnTouch_" => esuna_trigger_ontouch,
        "Exit1#lt::OnTouch_" => exit1_lt_ontouch,
        "Law Enforcement::OnEnable" => law_enforcement_onenable,
        "Law Enforcement::OnMyMobDead" => law_enforcement_onmymobdead,
        "Law Enforcement::OnTimer220000" => law_enforcement_ontimer220000,
        "Man#Lyozien::OnEnter" => man_lyozien_onenter,
        "Man#Lyozien::OnStop" => man_lyozien_onstop,
        "Mysterious Woman::OnInit" => mysterious_woman_oninit,
        "Secretary#2::OnInit" => secretary_2_oninit,
        "Suspicious Guy#lhz_01::OnTouch_" => suspicious_guy_lhz_01_ontouch,
        "Suspicious Guy#lhz_02::OnInit" => suspicious_guy_lhz_02_oninit,
        "Suspicious Guy#lhz_02::OnTouch_" => suspicious_guy_lhz_02_ontouch,
        "Suspicious Guy#lhz_03::OnInit" => suspicious_guy_lhz_03_oninit,
        "Suspicious Guy#lhz_03::OnTouch_" => suspicious_guy_lhz_03_ontouch,
        "Switch::OnTouch_" => switch_ontouch,
        "Timer_Sneak::OnEnter" => timer_sneak_onenter,
        "Timer_Sneak::OnInit" => timer_sneak_oninit,
        "Timer_Sneak::OnTimer180000" => timer_sneak_ontimer180000,
        "Timer_Sneak::OnTimer190000" => timer_sneak_ontimer190000,
        "Timer_Sneak::OnTouch_" => timer_sneak_ontouch,
        "Wounded Man Switch::OnTouch_" => wounded_man_switch_ontouch,
        "Wounded Man::OnInit" => wounded_man_oninit,
    }
}
