// Generated by tools/scripts-import/convert_sdk2.py from npc/events/nguild/nguild_guardians.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val};

#[derive(Clone, Copy, Debug)]
enum GuardianN01Step {
    Start,
    OnAgitInit,
    OnGuardianDied,
}

fn guardian_n01_run(ctx: &Ctx, mut step: GuardianN01Step, args: Vec<Val>) -> Result<Val, Stop> {
    'machine: loop {
        match step {
            GuardianN01Step::Start => {
                step = GuardianN01Step::OnAgitInit;
                continue 'machine;
            }
            GuardianN01Step::OnAgitInit => {
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(10)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(18),
                            Val::from(219),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(0),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(11)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(117),
                            Val::from(42),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(1),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(12)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(207),
                            Val::from(153),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(2),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(13)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(68),
                            Val::from(70),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(3),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(14)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(187),
                            Val::from(140),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(4),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(15)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(62),
                            Val::from(204),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(5),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(16)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(113),
                            Val::from(100),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(6),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_alde"), Val::from(17)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_alde"),
                            Val::from(211),
                            Val::from(174),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N01::OnGuardianDied"),
                            Val::from(7),
                        ],
                    )?;
                }
                return Err(Stop::End);
            }
            GuardianN01Step::OnGuardianDied => {
                ctx.call(
                    Function::MapAnnounce,
                    vec![Val::from("nguild_alde"), Val::from("A Guardian Has Fallen"), Val::from(17)],
                )?;
                return Err(Stop::End);
            }
        }
    }
}

pub fn guardian_n01(ctx: &Ctx) -> Script {
    guardian_n01_run(ctx, GuardianN01Step::Start, Vec::new()).map(|_| ())
}

pub fn guardian_n01_onagitinit(ctx: &Ctx) -> Script {
    guardian_n01_run(ctx, GuardianN01Step::OnAgitInit, Vec::new()).map(|_| ())
}

pub fn guardian_n01_onguardiandied(ctx: &Ctx) -> Script {
    guardian_n01_run(ctx, GuardianN01Step::OnGuardianDied, Vec::new()).map(|_| ())
}

#[derive(Clone, Copy, Debug)]
enum GuardianN02Step {
    Start,
    OnAgitInit,
    OnGuardianDied,
}

fn guardian_n02_run(ctx: &Ctx, mut step: GuardianN02Step, args: Vec<Val>) -> Result<Val, Stop> {
    'machine: loop {
        match step {
            GuardianN02Step::Start => {
                step = GuardianN02Step::OnAgitInit;
                continue 'machine;
            }
            GuardianN02Step::OnAgitInit => {
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(10)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(30),
                            Val::from(178),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(0),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(11)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(64),
                            Val::from(180),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(1),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(12)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(61),
                            Val::from(25),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(2),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(13)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(61),
                            Val::from(44),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(3),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(14)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(189),
                            Val::from(43),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(4),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(15)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(51),
                            Val::from(192),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(5),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(16)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(49),
                            Val::from(67),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(6),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_gef"), Val::from(17)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_gef"),
                            Val::from(181),
                            Val::from(14),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N02::OnGuardianDied"),
                            Val::from(7),
                        ],
                    )?;
                }
                return Err(Stop::End);
            }
            GuardianN02Step::OnGuardianDied => {
                ctx.call(
                    Function::MapAnnounce,
                    vec![Val::from("nguild_gef"), Val::from("A Guardian Has Fallen"), Val::from(17)],
                )?;
                return Err(Stop::End);
            }
        }
    }
}

pub fn guardian_n02(ctx: &Ctx) -> Script {
    guardian_n02_run(ctx, GuardianN02Step::Start, Vec::new()).map(|_| ())
}

pub fn guardian_n02_onagitinit(ctx: &Ctx) -> Script {
    guardian_n02_run(ctx, GuardianN02Step::OnAgitInit, Vec::new()).map(|_| ())
}

pub fn guardian_n02_onguardiandied(ctx: &Ctx) -> Script {
    guardian_n02_run(ctx, GuardianN02Step::OnGuardianDied, Vec::new()).map(|_| ())
}

#[derive(Clone, Copy, Debug)]
enum GuardianN03Step {
    Start,
    OnAgitInit,
    OnGuardianDied,
}

fn guardian_n03_run(ctx: &Ctx, mut step: GuardianN03Step, args: Vec<Val>) -> Result<Val, Stop> {
    'machine: loop {
        match step {
            GuardianN03Step::Start => {
                step = GuardianN03Step::OnAgitInit;
                continue 'machine;
            }
            GuardianN03Step::OnAgitInit => {
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(10)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(210),
                            Val::from(120),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(0),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(11)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(69),
                            Val::from(26),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(1),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(12)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(23),
                            Val::from(141),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(2),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(13)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(224),
                            Val::from(87),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(3),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(14)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(81),
                            Val::from(45),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(4),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(15)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(214),
                            Val::from(53),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(5),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(16)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(69),
                            Val::from(26),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(6),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_pay"), Val::from(17)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_pay"),
                            Val::from(23),
                            Val::from(141),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N03::OnGuardianDied"),
                            Val::from(7),
                        ],
                    )?;
                }
                return Err(Stop::End);
            }
            GuardianN03Step::OnGuardianDied => {
                ctx.call(
                    Function::MapAnnounce,
                    vec![Val::from("nguild_pay"), Val::from("A Guardian Has Fallen"), Val::from(17)],
                )?;
                return Err(Stop::End);
            }
        }
    }
}

pub fn guardian_n03(ctx: &Ctx) -> Script {
    guardian_n03_run(ctx, GuardianN03Step::Start, Vec::new()).map(|_| ())
}

pub fn guardian_n03_onagitinit(ctx: &Ctx) -> Script {
    guardian_n03_run(ctx, GuardianN03Step::OnAgitInit, Vec::new()).map(|_| ())
}

pub fn guardian_n03_onguardiandied(ctx: &Ctx) -> Script {
    guardian_n03_run(ctx, GuardianN03Step::OnGuardianDied, Vec::new()).map(|_| ())
}

#[derive(Clone, Copy, Debug)]
enum GuardianN04Step {
    Start,
    OnAgitInit,
    OnGuardianDied,
}

fn guardian_n04_run(ctx: &Ctx, mut step: GuardianN04Step, args: Vec<Val>) -> Result<Val, Stop> {
    'machine: loop {
        match step {
            GuardianN04Step::Start => {
                step = GuardianN04Step::OnAgitInit;
                continue 'machine;
            }
            GuardianN04Step::OnAgitInit => {
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(10)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(196),
                            Val::from(92),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(0),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(11)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(113),
                            Val::from(200),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(1),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(12)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(111),
                            Val::from(186),
                            Val::from("Soldier Guardian"),
                            Val::from(1287),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(2),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(13)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(76),
                            Val::from(202),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(3),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(14)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(90),
                            Val::from(26),
                            Val::from("Archer Guardian"),
                            Val::from(1285),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(4),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(15)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(58),
                            Val::from(59),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(5),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(16)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(112),
                            Val::from(200),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(6),
                        ],
                    )?;
                }
                if ctx.call(Function::GetCastleData, vec![Val::from("nguild_prt"), Val::from(17)])? == 1 {
                    ctx.call(
                        Function::Guardian,
                        vec![
                            Val::from("nguild_prt"),
                            Val::from(101),
                            Val::from(194),
                            Val::from("Knight Guardian"),
                            Val::from(1286),
                            Val::from("Guardian_N04::OnGuardianDied"),
                            Val::from(7),
                        ],
                    )?;
                }
                return Err(Stop::End);
            }
            GuardianN04Step::OnGuardianDied => {
                ctx.call(
                    Function::MapAnnounce,
                    vec![Val::from("nguild_prt"), Val::from("A Guardian Has Fallen"), Val::from(17)],
                )?;
                return Err(Stop::End);
            }
        }
    }
}

pub fn guardian_n04(ctx: &Ctx) -> Script {
    guardian_n04_run(ctx, GuardianN04Step::Start, Vec::new()).map(|_| ())
}

pub fn guardian_n04_onagitinit(ctx: &Ctx) -> Script {
    guardian_n04_run(ctx, GuardianN04Step::OnAgitInit, Vec::new()).map(|_| ())
}

pub fn guardian_n04_onguardiandied(ctx: &Ctx) -> Script {
    guardian_n04_run(ctx, GuardianN04Step::OnGuardianDied, Vec::new()).map(|_| ())
}
