// Generated by tools/scripts-import/convert_sdk2.py from npc/events/nguild/nguild_warper.txt. Hand-maintained from here on: edit this file directly.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn cita_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.lines_as(
        "Cita",
        args![((Val::from("Hello, ") + ctx.call(Function::StrCharInfo, vec![Val::from(0)])?) + Val::from(". Can I help you?"))],
    )?;
    ctx.next()?;
    if Val::from(runtime::select_values(
        ctx,
        &[Val::from("Warp me to Prontera!"), Val::from("Cancel")],
    )?) == 1
    {
        ctx.call(
            Function::Warp,
            vec![
                Val::from("prontera"),
                Val::from(155),
                (Val::from(177) + ctx.call(Function::Rand, vec![Val::from(5)])?),
            ],
        )?;
    } else {
        ctx.lines_as("Cita", args!["Ok."])?;
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn cita(ctx: &Ctx) -> Script {
    cita_body(ctx, Vec::new()).map(|_| ())
}
