#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;

pub use part_01::*;
pub use part_02::*;

script_sdk_2::script_module! {
    npcs {
        "#aroom_ingate_wop" => aroom_ingate_wop,
        "#aroom_outgate_wop" => aroom_outgate_wop,
        "#droom_ingate_wop" => droom_ingate_wop,
        "#droom_outgate_wop" => droom_outgate_wop,
        "#wop_angellium1" => wop_angellium1,
        "#wop_angellium2" => wop_angellium2,
        "#wop_devillium1" => wop_devillium1,
        "#wop_devillium2" => wop_devillium2,
        "#wop_ex_1" => wop_ex_1,
        "#wop_ex_2" => wop_ex_2,
        "#wop_master" => wop_master,
        "#wop_warp_a" => wop_warp_a,
        "#wop_warp_d" => wop_warp_d,
        "#wop_warp_rtry" => wop_warp_rtry,
        "Angeling Guardian#wop_da" => angeling_guardian_wop_da,
        "Angeling Side Poring#wpa" => angeling_side_poring_wpa,
        "Deviling Guardian#wop_dd" => deviling_guardian_wop_dd,
        "Deviling Side Marin#wpd" => deviling_side_marin_wpd,
        "Deviruchi#wop_endmaster" => deviruchi_wop_endmaster,
        "Mr. Doppel#wop_team_a" => mr_doppel_wop_team_a,
        "Mr. Doppel#wop_team_d" => mr_doppel_wop_team_d,
        "Poring Vending Machine#w" => poring_vending_machine_w,
        "Poring War Recruiter#wop" => poring_war_recruiter_wop,
        "Poring#wop_door_a" => poring_wop_door_a,
        "Poring#wop_door_all" => poring_wop_door_all,
        "Poring#wop_door_d" => poring_wop_door_d,
        "Sweet Devi#wop" => sweet_devi_wop,
    }
    events {
        "#aroom_ingate_wop::OnDisable" => aroom_ingate_wop_ondisable,
        "#aroom_ingate_wop::OnEnable" => aroom_ingate_wop_onenable,
        "#aroom_ingate_wop::OnInit" => aroom_ingate_wop_oninit,
        "#aroom_ingate_wop::OnTouch_" => aroom_ingate_wop_ontouch,
        "#aroom_outgate_wop::OnDisable" => aroom_outgate_wop_ondisable,
        "#aroom_outgate_wop::OnEnable" => aroom_outgate_wop_onenable,
        "#aroom_outgate_wop::OnInit" => aroom_outgate_wop_oninit,
        "#aroom_outgate_wop::OnTouch_" => aroom_outgate_wop_ontouch,
        "#droom_ingate_wop::OnDisable" => droom_ingate_wop_ondisable,
        "#droom_ingate_wop::OnEnable" => droom_ingate_wop_onenable,
        "#droom_ingate_wop::OnInit" => droom_ingate_wop_oninit,
        "#droom_ingate_wop::OnTouch_" => droom_ingate_wop_ontouch,
        "#droom_outgate_wop::OnDisable" => droom_outgate_wop_ondisable,
        "#droom_outgate_wop::OnEnable" => droom_outgate_wop_onenable,
        "#droom_outgate_wop::OnInit" => droom_outgate_wop_oninit,
        "#droom_outgate_wop::OnTouch_" => droom_outgate_wop_ontouch,
        "#wop_angellium1::OnAngelingSpawn" => wop_angellium1_onangelingspawn,
        "#wop_angellium1::OnMyMobDead" => wop_angellium1_onmymobdead,
        "#wop_angellium1::OnReset" => wop_angellium1_onreset,
        "#wop_angellium1::OnTimer120000" => wop_angellium1_ontimer120000,
        "#wop_angellium2::OnAngelingSpawn" => wop_angellium2_onangelingspawn,
        "#wop_angellium2::OnMyMobDead" => wop_angellium2_onmymobdead,
        "#wop_angellium2::OnReset" => wop_angellium2_onreset,
        "#wop_angellium2::OnTimer120000" => wop_angellium2_ontimer120000,
        "#wop_devillium1::OnDevilingSpawn" => wop_devillium1_ondevilingspawn,
        "#wop_devillium1::OnMyMobDead" => wop_devillium1_onmymobdead,
        "#wop_devillium1::OnReset" => wop_devillium1_onreset,
        "#wop_devillium1::OnTimer120000" => wop_devillium1_ontimer120000,
        "#wop_devillium2::OnMyMobDead" => wop_devillium2_onmymobdead,
        "#wop_devillium2::OnReset" => wop_devillium2_onreset,
        "#wop_devillium2::OnTimer120000" => wop_devillium2_ontimer120000,
        "#wop_devillium2::OndevilingSpawn" => wop_devillium2_ondevilingspawn,
        "#wop_ex_1::OnTouch" => wop_ex_1_ontouch,
        "#wop_ex_2::OnTouch" => wop_ex_2_ontouch,
        "#wop_master::OnAngelingEnd" => wop_master_onangelingend,
        "#wop_master::OnAngelingWarn" => wop_master_onangelingwarn,
        "#wop_master::OnAngelingWin" => wop_master_onangelingwin,
        "#wop_master::OnDevilingEnd" => wop_master_ondevilingend,
        "#wop_master::OnDevilingWarn" => wop_master_ondevilingwarn,
        "#wop_master::OnDevilingWin" => wop_master_ondevilingwin,
        "#wop_master::OnReset" => wop_master_onreset,
        "#wop_master::OnStart" => wop_master_onstart,
        "#wop_master::OnStop" => wop_master_onstop,
        "#wop_master::OnTimer100000" => wop_master_ontimer100000,
        "#wop_master::OnTimer12000" => wop_master_ontimer12000,
        "#wop_master::OnTimer32000" => wop_master_ontimer32000,
        "#wop_master::OnTimer5000" => wop_master_ontimer5000,
        "#wop_master::OnTimer62000" => wop_master_ontimer62000,
        "#wop_master::OnTimer70000" => wop_master_ontimer70000,
        "#wop_master::OnTimer700000" => wop_master_ontimer700000,
        "#wop_master::OnTimer703000" => wop_master_ontimer703000,
        "#wop_master::OnTimer75000" => wop_master_ontimer75000,
        "#wop_master::OnTimer8000" => wop_master_ontimer8000,
        "#wop_master::OnTimer80000" => wop_master_ontimer80000,
        "#wop_master::OnTimer85000" => wop_master_ontimer85000,
        "#wop_master::OnTimer90000" => wop_master_ontimer90000,
        "#wop_master::OnTimer95000" => wop_master_ontimer95000,
        "#wop_warp_a::OnDisable" => wop_warp_a_ondisable,
        "#wop_warp_a::OnEnable" => wop_warp_a_onenable,
        "#wop_warp_a::OnInit" => wop_warp_a_oninit,
        "#wop_warp_a::OnTouch_" => wop_warp_a_ontouch,
        "#wop_warp_d::OnDisable" => wop_warp_d_ondisable,
        "#wop_warp_d::OnEnable" => wop_warp_d_onenable,
        "#wop_warp_d::OnInit" => wop_warp_d_oninit,
        "#wop_warp_d::OnTouch_" => wop_warp_d_ontouch,
        "#wop_warp_rtry::OnDisable" => wop_warp_rtry_ondisable,
        "#wop_warp_rtry::OnEnable" => wop_warp_rtry_onenable,
        "#wop_warp_rtry::OnInit" => wop_warp_rtry_oninit,
        "#wop_warp_rtry::OnReady" => wop_warp_rtry_onready,
        "#wop_warp_rtry::OnStop" => wop_warp_rtry_onstop,
        "#wop_warp_rtry::OnTimer3000" => wop_warp_rtry_ontimer3000,
        "#wop_warp_rtry::OnTimer33000" => wop_warp_rtry_ontimer33000,
        "#wop_warp_rtry::OnTimer58000" => wop_warp_rtry_ontimer58000,
        "#wop_warp_rtry::OnTimer60000" => wop_warp_rtry_ontimer60000,
        "#wop_warp_rtry::OnTimer61000" => wop_warp_rtry_ontimer61000,
        "#wop_warp_rtry::OnTimer65000" => wop_warp_rtry_ontimer65000,
        "#wop_warp_rtry::OnTouch" => wop_warp_rtry_ontouch,
        "Angeling Guardian#wop_da::OnInit" => angeling_guardian_wop_da_oninit,
        "Deviling Guardian#wop_dd::OnInit" => deviling_guardian_wop_dd_oninit,
        "Deviruchi#wop_endmaster::OnDisable" => deviruchi_wop_endmaster_ondisable,
        "Deviruchi#wop_endmaster::OnEnable" => deviruchi_wop_endmaster_onenable,
        "Deviruchi#wop_endmaster::OnInit" => deviruchi_wop_endmaster_oninit,
        "Deviruchi#wop_endmaster::OnTimer3000" => deviruchi_wop_endmaster_ontimer3000,
        "Deviruchi#wop_endmaster::OnTimer5000" => deviruchi_wop_endmaster_ontimer5000,
        "Deviruchi#wop_endmaster::OnTimer65000" => deviruchi_wop_endmaster_ontimer65000,
        "Deviruchi#wop_endmaster::OnTimer68000" => deviruchi_wop_endmaster_ontimer68000,
        "Deviruchi#wop_endmaster::OnTimer68100" => deviruchi_wop_endmaster_ontimer68100,
        "Mr. Doppel#wop_team_a::OnDisable" => mr_doppel_wop_team_a_ondisable,
        "Mr. Doppel#wop_team_a::OnEnable" => mr_doppel_wop_team_a_onenable,
        "Mr. Doppel#wop_team_a::OnInit" => mr_doppel_wop_team_a_oninit,
        "Mr. Doppel#wop_team_d::OnDisable" => mr_doppel_wop_team_d_ondisable,
        "Mr. Doppel#wop_team_d::OnEnable" => mr_doppel_wop_team_d_onenable,
        "Mr. Doppel#wop_team_d::OnInit" => mr_doppel_wop_team_d_oninit,
        "Poring#wop_door_a::OnAngelingStart" => poring_wop_door_a_onangelingstart,
        "Poring#wop_door_a::OnDisable" => poring_wop_door_a_ondisable,
        "Poring#wop_door_a::OnEnable" => poring_wop_door_a_onenable,
        "Poring#wop_door_a::OnInit" => poring_wop_door_a_oninit,
        "Poring#wop_door_a::OnStartArena" => poring_wop_door_a_onstartarena,
        "Poring#wop_door_a::OnStop" => poring_wop_door_a_onstop,
        "Poring#wop_door_a::OnTimer1000" => poring_wop_door_a_ontimer1000,
        "Poring#wop_door_a::OnTimer13000" => poring_wop_door_a_ontimer13000,
        "Poring#wop_door_a::OnTimer20000" => poring_wop_door_a_ontimer20000,
        "Poring#wop_door_a::OnTimer30000" => poring_wop_door_a_ontimer30000,
        "Poring#wop_door_a::OnTimer4000" => poring_wop_door_a_ontimer4000,
        "Poring#wop_door_a::OnTimer40000" => poring_wop_door_a_ontimer40000,
        "Poring#wop_door_a::OnTimer50000" => poring_wop_door_a_ontimer50000,
        "Poring#wop_door_a::OnTimer55000" => poring_wop_door_a_ontimer55000,
        "Poring#wop_door_a::OnTimer55100" => poring_wop_door_a_ontimer55100,
        "Poring#wop_door_a::OnTimer58000" => poring_wop_door_a_ontimer58000,
        "Poring#wop_door_a::OnTimer8000" => poring_wop_door_a_ontimer8000,
        "Poring#wop_door_all::OnDisable" => poring_wop_door_all_ondisable,
        "Poring#wop_door_all::OnEnable" => poring_wop_door_all_onenable,
        "Poring#wop_door_all::OnInit" => poring_wop_door_all_oninit,
        "Poring#wop_door_all::OnStartArena" => poring_wop_door_all_onstartarena,
        "Poring#wop_door_d::OnDevilingStart" => poring_wop_door_d_ondevilingstart,
        "Poring#wop_door_d::OnDisable" => poring_wop_door_d_ondisable,
        "Poring#wop_door_d::OnEnable" => poring_wop_door_d_onenable,
        "Poring#wop_door_d::OnInit" => poring_wop_door_d_oninit,
        "Poring#wop_door_d::OnStartArena" => poring_wop_door_d_onstartarena,
        "Poring#wop_door_d::OnStop" => poring_wop_door_d_onstop,
        "Poring#wop_door_d::OnTimer1000" => poring_wop_door_d_ontimer1000,
        "Poring#wop_door_d::OnTimer13000" => poring_wop_door_d_ontimer13000,
        "Poring#wop_door_d::OnTimer20000" => poring_wop_door_d_ontimer20000,
        "Poring#wop_door_d::OnTimer30000" => poring_wop_door_d_ontimer30000,
        "Poring#wop_door_d::OnTimer4000" => poring_wop_door_d_ontimer4000,
        "Poring#wop_door_d::OnTimer40000" => poring_wop_door_d_ontimer40000,
        "Poring#wop_door_d::OnTimer50000" => poring_wop_door_d_ontimer50000,
        "Poring#wop_door_d::OnTimer55000" => poring_wop_door_d_ontimer55000,
        "Poring#wop_door_d::OnTimer55100" => poring_wop_door_d_ontimer55100,
        "Poring#wop_door_d::OnTimer58000" => poring_wop_door_d_ontimer58000,
        "Poring#wop_door_d::OnTimer8000" => poring_wop_door_d_ontimer8000,
        "Sweet Devi#wop::OnInit" => sweet_devi_wop_oninit,
        "Sweet Devi#wop::OnPCDieEvent" => sweet_devi_wop_onpcdieevent,
        "Sweet Devi#wop::OnPCKillEvent" => sweet_devi_wop_onpckillevent,
        "Sweet Devi#wop::OnPCLogoutEvent" => sweet_devi_wop_onpclogoutevent,
    }
}
