#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "#crazy4u" => crazy4u,
        "#horri" => horri,
        "#mimir_camera" => mimir_camera,
        "#never" => never,
        "Annette#li_party" => annette_li_party,
        "Arthur#zen16" => arthur_zen16,
        "Avetis#zen10" => avetis_zen10,
        "Bad Drunk#12" => bad_drunk_12,
        "Bad Drunk#amano06" => bad_drunk_amano06,
        "Bank Clerk#1" => bank_clerk_1,
        "Bankri Kun#kagun" => bankri_kun_kagun,
        "Banquet Staff" => banquet_staff,
        "Bartender#12" => bartender_12,
        "Bartender#amano07" => bartender_amano07,
        "Beggar#lhz_02" => beggar_lhz_02,
        "Ben Allen#zen11" => ben_allen_zen11,
        "Berru#lhz_01" => berru_lhz_01,
        "Blackboard#li" => blackboard_li,
        "Bodger#zen5" => bodger_zen5,
        "Cenku Dekdam#delic" => cenku_dekdam_delic,
        "Christopher Michael#zen" => christopher_michael_zen,
        "Citizen#amano03" => citizen_amano03,
        "Citizen#amano04" => citizen_amano04,
        "Citizen#amano09" => citizen_amano09,
        "City Girl#amano05" => city_girl_amano05,
        "Collins#zen1" => collins_zen1,
        "Cool Event Manager" => cool_event_manager,
        "Cool Event Staff#Cesuna" => cool_event_staff_cesuna,
        "Cool Event Staff#Saera" => cool_event_staff_saera,
        "Customer#amano10" => customer_amano10,
        "Customer#amano11" => customer_amano11,
        "Customer#amano12" => customer_amano12,
        "Customer#amano13" => customer_amano13,
        "Dan Song#zen2" => dan_song_zen2,
        "Delna#li_reken" => delna_li_reken,
        "Diana#npc" => diana_npc,
        "Dowbow Ryuei#ryusei" => dowbow_ryuei_ryusei,
        "Drunken Man#amano01" => drunken_man_amano01,
        "Drunken Man#amano02" => drunken_man_amano02,
        "Eiya#iaiai" => eiya_iaiai,
        "Ellette#tre" => ellette_tre,
        "Elmer Keays#li_03" => elmer_keays_li_03,
        "Enoz#oz" => enoz_oz,
        "Event Planner" => event_planner,
        "Gopal#zen4" => gopal_zen4,
        "Gracie#5" => gracie_5,
        "Greedy Looking Man#li_01" => greedy_looking_man_li_01,
        "Grinnel#zen6" => grinnel_zen6,
        "Guard#01" => guard_01,
        "Guide#lt0" => guide_lt0,
        "Guide#lt1" => guide_lt1,
        "Guide#lt2" => guide_lt2,
        "Haggar#zen1" => haggar_zen1,
        "Hanccet#li_party" => hanccet_li_party,
        "Harp#zen8" => harp_zen8,
        "Healthy Looking Guy#hol" => healthy_looking_guy_hol,
        "Helen#zen6" => helen_zen6,
        "Hinkley#06" => hinkley_06,
        "Hotel Employee#zen1" => hotel_employee_zen1,
        "Hotel Employee#zen2" => hotel_employee_zen2,
        "Hotel Employee#zen3" => hotel_employee_zen3,
        "Hotel Employee#zen4" => hotel_employee_zen4,
        "Housemaid Brenda#li" => housemaid_brenda_li,
        "Housemaid Jane#li_house1" => housemaid_jane_li_house1,
        "Jade#zen2" => jade_zen2,
        "Janice#zen03" => janice_zen03,
        "Jay#li_house" => jay_li_house,
        "Jiwon#zen5" => jiwon_zen5,
        "Jorje#zero" => jorje_zero,
        "Jorjerro#fhero" => jorjerro_fhero,
        "Joshua#aya" => joshua_aya,
        "Joyce#zen" => joyce_zen,
        "Kariya#li_01" => kariya_li_01,
        "Kejulle Rekenber#reken" => kejulle_rekenber_reken,
        "Kemp#zen13" => kemp_zen13,
        "Kimmy#zen3" => kimmy_zen3,
        "Klaubis#zen3" => klaubis_zen3,
        "Kosit#zen1" => kosit_zen1,
        "Lab Staff#amano08" => lab_staff_amano08,
        "Laqumet#li_02" => laqumet_li_02,
        "Leekal#lackee" => leekal_lackee,
        "Leimi#mimir" => leimi_mimir,
        "Loudmouth" => loudmouth,
        "Luccet#li_party" => luccet_li_party,
        "Lucius#zen5" => lucius_zen5,
        "Maggie#05" => maggie_05,
        "Maivi#zen1" => maivi_zen1,
        "Mareth#seram" => mareth_seram,
        "Margie Keays#li_02" => margie_keays_li_02,
        "Martial Artist#1" => martial_artist_1,
        "Mauro#zen3" => mauro_zen3,
        "Mazwon#minus1" => mazwon_minus1,
        "Mereth#erem" => mereth_erem,
        "Merpi#zen2" => merpi_zen2,
        "Millette#05" => millette_05,
        "Ninjose#nina" => ninjose_nina,
        "Noama#amano" => noama_amano,
        "Nun#light" => nun_light,
        "Officer Guo#06" => officer_guo_06,
        "Oyoung#zen14" => oyoung_zen14,
        "Regenschirm Guard#40" => regenschirm_guard_40,
        "Rekenber Employee#li" => rekenber_employee_li,
        "Rekenber Employee#li_2" => rekenber_employee_li_2,
        "Rekenber Guard Drew#li" => rekenber_guard_drew_li,
        "Rekenber Guard Tan#li" => rekenber_guard_tan_li,
        "Rekenber Guard#li01" => rekenber_guard_li01,
        "Rekenber Guard#li02" => rekenber_guard_li02,
        "Rekenber Guard#li03" => rekenber_guard_li03,
        "Repairman#li_01" => repairman_li_01,
        "Reuben#lhz_02" => reuben_lhz_02,
        "Rocky#li_house" => rocky_li_house,
        "Ruth#zen4" => ruth_zen4,
        "Safwat Fahmy" => safwat_fahmy,
        "Sameer#zen15" => sameer_zen15,
        "Samnang#zen2" => samnang_zen2,
        "Scientist#li_01" => scientist_li_01,
        "Scientist#li_02" => scientist_li_02,
        "Scientist#li_03" => scientist_li_03,
        "Sefith#li_01" => sefith_li_01,
        "Sergei#zen1" => sergei_zen1,
        "Shayna#li" => shayna_li,
        "Shengwen#zen7" => shengwen_zen7,
        "Shop Assistant#cobo" => shop_assistant_cobo,
        "Sigmund#zen3" => sigmund_zen3,
        "Sopheap#zen1" => sopheap_zen1,
        "Srinivas#zen4" => srinivas_zen4,
        "Sung#A" => sung_a,
        "Tadem#zen6" => tadem_zen6,
        "Tanoue#zen04" => tanoue_zen04,
        "Togii#07" => togii_07,
        "Vergil#zen4" => vergil_zen4,
        "Victor Perfecto#zen9" => victor_perfecto_zen9,
        "Villagomez#li_01" => villagomez_li_01,
        "Wallace#zen2" => wallace_zen2,
    }
    events {
        "#mimir_camera::OnTouch_" => mimir_camera_ontouch,
        "Beggar#lhz_02::OnTouch_" => beggar_lhz_02_ontouch,
        "Jorje#zero::OnTouch_" => jorje_zero_ontouch,
        "Rekenber Guard#li02::OnTouch_" => rekenber_guard_li02_ontouch,
        "Rekenber Guard#li03::OnTouch_" => rekenber_guard_li03_ontouch,
    }
}
