#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "Antonio junior#rg" => antonio_junior_rg,
        "Aragham Junior#rg" => aragham_junior_rg,
        "Hermanthorn Jr#rg" => hermanthorn_jr_rg,
        "Hollgrehenn junior#rg" => hollgrehenn_junior_rg,
        "Mr. Smith#rg" => mr_smith_rg,
        "Rogue Guildsman#rg" => rogue_guildsman_rg,
        "Thug#rg" => thug_rg,
        "Warp#1" => warp_1,
        "Warp#2" => warp_2,
        "Warp#3" => warp_3,
        "gen_ro#1" => gen_ro_1,
        "gen_ro#2" => gen_ro_2,
        "gen_ro#3" => gen_ro_3,
        "gen_ro#4" => gen_ro_4,
        "he_to_rogue#rg" => he_to_rogue_rg,
        "mob_rogue#1" => mob_rogue_1,
        "mob_rogue#10" => mob_rogue_10,
        "mob_rogue#11" => mob_rogue_11,
        "mob_rogue#12" => mob_rogue_12,
        "mob_rogue#13" => mob_rogue_13,
        "mob_rogue#14" => mob_rogue_14,
        "mob_rogue#15" => mob_rogue_15,
        "mob_rogue#16" => mob_rogue_16,
        "mob_rogue#2" => mob_rogue_2,
        "mob_rogue#3" => mob_rogue_3,
        "mob_rogue#4" => mob_rogue_4,
        "mob_rogue#5" => mob_rogue_5,
        "mob_rogue#6" => mob_rogue_6,
        "mob_rogue#7" => mob_rogue_7,
        "mob_rogue#8" => mob_rogue_8,
        "mob_rogue#9" => mob_rogue_9,
        "oneway_to_gu" => oneway_to_gu,
        "quest_out" => quest_out,
        "resetter#rogue" => resetter_rogue,
        "switch#rogreset" => switch_rogreset,
    }
    events {
        "Warp#1::OnTouch_" => warp_1_ontouch,
        "Warp#2::OnTouch_" => warp_2_ontouch,
        "Warp#3::OnTouch_" => warp_3_ontouch,
        "gen_ro#1::OnDisable" => gen_ro_1_ondisable,
        "gen_ro#1::OnMyMobDead" => gen_ro_1_onmymobdead,
        "gen_ro#1::OnTouch_" => gen_ro_1_ontouch,
        "gen_ro#2::OnDisable" => gen_ro_2_ondisable,
        "gen_ro#2::OnMyMobDead" => gen_ro_2_onmymobdead,
        "gen_ro#2::OnTouch_" => gen_ro_2_ontouch,
        "gen_ro#3::OnDisable" => gen_ro_3_ondisable,
        "gen_ro#3::OnMyMobDead" => gen_ro_3_onmymobdead,
        "gen_ro#3::OnTouch_" => gen_ro_3_ontouch,
        "gen_ro#4::OnDisable" => gen_ro_4_ondisable,
        "gen_ro#4::OnMyMobDead" => gen_ro_4_onmymobdead,
        "gen_ro#4::OnTouch_" => gen_ro_4_ontouch,
        "he_to_rogue#rg::OnTouch_" => he_to_rogue_rg_ontouch,
        "mob_rogue#10::OnDisable" => mob_rogue_10_ondisable,
        "mob_rogue#10::OnMyMobDead" => mob_rogue_10_onmymobdead,
        "mob_rogue#10::OnTouch_" => mob_rogue_10_ontouch,
        "mob_rogue#11::OnTouch_" => mob_rogue_11_ontouch,
        "mob_rogue#12::OnDisable" => mob_rogue_12_ondisable,
        "mob_rogue#12::OnMyMobDead" => mob_rogue_12_onmymobdead,
        "mob_rogue#12::OnTouch_" => mob_rogue_12_ontouch,
        "mob_rogue#13::OnDisable" => mob_rogue_13_ondisable,
        "mob_rogue#13::OnMyMobDead" => mob_rogue_13_onmymobdead,
        "mob_rogue#13::OnTouch_" => mob_rogue_13_ontouch,
        "mob_rogue#14::OnTouch_" => mob_rogue_14_ontouch,
        "mob_rogue#15::OnDisable" => mob_rogue_15_ondisable,
        "mob_rogue#15::OnMyMobDead" => mob_rogue_15_onmymobdead,
        "mob_rogue#15::OnTouch_" => mob_rogue_15_ontouch,
        "mob_rogue#16::OnTouch_" => mob_rogue_16_ontouch,
        "mob_rogue#1::OnDisable" => mob_rogue_1_ondisable,
        "mob_rogue#1::OnMyMobDead" => mob_rogue_1_onmymobdead,
        "mob_rogue#1::OnTouch_" => mob_rogue_1_ontouch,
        "mob_rogue#2::OnDisable" => mob_rogue_2_ondisable,
        "mob_rogue#2::OnMyMobDead" => mob_rogue_2_onmymobdead,
        "mob_rogue#2::OnTouch_" => mob_rogue_2_ontouch,
        "mob_rogue#3::OnDisable" => mob_rogue_3_ondisable,
        "mob_rogue#3::OnMyMobDead" => mob_rogue_3_onmymobdead,
        "mob_rogue#3::OnTouch_" => mob_rogue_3_ontouch,
        "mob_rogue#4::OnDisable" => mob_rogue_4_ondisable,
        "mob_rogue#4::OnMyMobDead" => mob_rogue_4_onmymobdead,
        "mob_rogue#4::OnTouch_" => mob_rogue_4_ontouch,
        "mob_rogue#5::OnDisable" => mob_rogue_5_ondisable,
        "mob_rogue#5::OnMyMobDead" => mob_rogue_5_onmymobdead,
        "mob_rogue#5::OnTouch_" => mob_rogue_5_ontouch,
        "mob_rogue#6::OnDisable" => mob_rogue_6_ondisable,
        "mob_rogue#6::OnMyMobDead" => mob_rogue_6_onmymobdead,
        "mob_rogue#6::OnTouch_" => mob_rogue_6_ontouch,
        "mob_rogue#7::OnDisable" => mob_rogue_7_ondisable,
        "mob_rogue#7::OnMyMobDead" => mob_rogue_7_onmymobdead,
        "mob_rogue#7::OnTouch_" => mob_rogue_7_ontouch,
        "mob_rogue#8::OnDisable" => mob_rogue_8_ondisable,
        "mob_rogue#8::OnMyMobDead" => mob_rogue_8_onmymobdead,
        "mob_rogue#8::OnTouch_" => mob_rogue_8_ontouch,
        "mob_rogue#9::OnDisable" => mob_rogue_9_ondisable,
        "mob_rogue#9::OnMyMobDead" => mob_rogue_9_onmymobdead,
        "mob_rogue#9::OnTouch_" => mob_rogue_9_ontouch,
        "oneway_to_gu::OnTouch_" => oneway_to_gu_ontouch,
        "quest_out::OnTouch_" => quest_out_ontouch,
        "resetter#rogue::OnEnable" => resetter_rogue_onenable,
        "resetter#rogue::OnInit" => resetter_rogue_oninit,
        "resetter#rogue::OnTimer500000" => resetter_rogue_ontimer500000,
    }
}
