#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;

script_sdk_2::script_module! {
    npcs {
        "Abduction_trigger" => abduction_trigger,
        "Allysia" => allysia,
        "Apple Box#khp1" => apple_box_khp1,
        "Beautiful Lady#kh1" => beautiful_lady_kh1,
        "Beautiful Lady#kh6" => beautiful_lady_kh6,
        "Beautiful lady#kh2" => beautiful_lady_kh2,
        "Bed#khr" => bed_khr,
        "Big Door#BigDoorKHQ1" => big_door_bigdoorkhq1,
        "Big Door#BigDoorKHQ2" => big_door_bigdoorkhq2,
        "Big Door#BigDoorKHQ3" => big_door_bigdoorkhq3,
        "Big Door#BigDoorKHQ4" => big_door_bigdoorkhq4,
        "Big Door#BigDoorKHQ5" => big_door_bigdoorkhq5,
        "Big_Door_1_Warp" => big_door_1_warp,
        "Big_Door_2_Warp" => big_door_2_warp,
        "Big_Door_3_Warp" => big_door_3_warp,
        "Big_Door_4_Warp" => big_door_4_warp,
        "Big_Door_5_Warp" => big_door_5_warp,
        "Book#kh1" => book_kh1,
        "Bookshelf#khp1" => bookshelf_khp1,
        "Bookshelf#khr" => bookshelf_khr,
        "Box#kh1" => box_kh1,
        "Box#khp1" => box_khp1,
        "Box#khp2" => box_khp2,
        "Calabash#khp1" => calabash_khp1,
        "Cookie Basket#kh" => cookie_basket_kh,
        "Cottage Keeper#kh" => cottage_keeper_kh,
        "Cute Student#kh" => cute_student_kh,
        "Desk#khp1" => desk_khp1,
        "Desk#khr3" => desk_khr3,
        "Door#kh1" => door_kh1,
        "Door#kh2" => door_kh2,
        "Drawer#khp1" => drawer_khp1,
        "Elly" => elly,
        "Entrance Device#khd2" => entrance_device_khd2,
        "Factory B Area Door" => factory_b_area_door,
        "Flower Vase#kh1" => flower_vase_kh1,
        "Grave#kh" => grave_kh,
        "Hanie#kh1" => hanie_kh1,
        "Heavy Door" => heavy_door,
        "Heavy Door#kh1" => heavy_door_kh1,
        "Kiehl#Copy" => kiehl_copy,
        "Kiehl#Original" => kiehl_original,
        "KiehlRoom" => kiehlroom,
        "Kiehl_Room_Exit" => kiehl_room_exit,
        "Kiehl_Room_Trap" => kiehl_room_trap,
        "Kiehl_Room_Warp" => kiehl_room_warp,
        "Kiel Hyre#kh" => kiel_hyre_kh,
        "Lady#kh" => lady_kh,
        "Letter#kh" => letter_kh,
        "Little Kid#kh" => little_kid_kh,
        "Map#khp1" => map_khp1,
        "Mechanical Device#kh" => mechanical_device_kh,
        "Medicine Chest#khp1" => medicine_chest_khp1,
        "Mitchell#KiehlRoom" => mitchell_kiehlroom,
        "Mysterious Woman#kh" => mysterious_woman_kh,
        "Odd Grandma" => odd_grandma,
        "Old Fisherman" => old_fisherman,
        "Old Lady#kh" => old_lady_kh,
        "Pool#khp1" => pool_khp1,
        "Pot#khp1" => pot_khp1,
        "Pub Master#kh" => pub_master_kh,
        "Receiver#kh" => receiver_kh,
        "Robots#kh1" => robots_kh1,
        "Robots#kh2" => robots_kh2,
        "Rosimmir_Entrance" => rosimmir_entrance,
        "Security Guard#1" => security_guard_1,
        "Shelf#khr" => shelf_khr,
        "Signboard#kh" => signboard_kh,
        "Steward#kh" => steward_kh,
        "Student#kha" => student_kha,
        "Student#khb" => student_khb,
        "Sword Hilt#kh" => sword_hilt_kh,
        "Table#khr2" => table_khr2,
        "Test Tube" => test_tube,
        "Test Tube#khp2" => test_tube_khp2,
        "Vicious Dog#khp1" => vicious_dog_khp1,
        "Wall#kh" => wall_kh,
        "Windmill Owner#kh" => windmill_owner_kh,
        "Windmill Owner's Helper" => windmill_owner_s_helper,
        "Window#kh" => window_kh,
        "Window#kh2" => window_kh2,
        "Wooden Board#kh" => wooden_board_kh,
    }
    events {
        "Abduction_trigger::OnTouch" => abduction_trigger_ontouch,
        "Big_Door_1_Warp::OnEnable" => big_door_1_warp_onenable,
        "Big_Door_1_Warp::OnInit" => big_door_1_warp_oninit,
        "Big_Door_1_Warp::OnTimer30000" => big_door_1_warp_ontimer30000,
        "Big_Door_1_Warp::OnTouch_" => big_door_1_warp_ontouch,
        "Big_Door_2_Warp::OnEnable" => big_door_2_warp_onenable,
        "Big_Door_2_Warp::OnInit" => big_door_2_warp_oninit,
        "Big_Door_2_Warp::OnTimer30000" => big_door_2_warp_ontimer30000,
        "Big_Door_2_Warp::OnTouch_" => big_door_2_warp_ontouch,
        "Big_Door_3_Warp::OnEnable" => big_door_3_warp_onenable,
        "Big_Door_3_Warp::OnInit" => big_door_3_warp_oninit,
        "Big_Door_3_Warp::OnTimer30000" => big_door_3_warp_ontimer30000,
        "Big_Door_3_Warp::OnTouch_" => big_door_3_warp_ontouch,
        "Big_Door_4_Warp::OnEnable" => big_door_4_warp_onenable,
        "Big_Door_4_Warp::OnInit" => big_door_4_warp_oninit,
        "Big_Door_4_Warp::OnTimer30000" => big_door_4_warp_ontimer30000,
        "Big_Door_4_Warp::OnTouch_" => big_door_4_warp_ontouch,
        "Big_Door_5_Warp::OnEnable" => big_door_5_warp_onenable,
        "Big_Door_5_Warp::OnInit" => big_door_5_warp_oninit,
        "Big_Door_5_Warp::OnTimer30000" => big_door_5_warp_ontimer30000,
        "Big_Door_5_Warp::OnTouch_" => big_door_5_warp_ontouch,
        "Factory B Area Door::OnTouch" => factory_b_area_door_ontouch,
        "Kiehl#Copy::OnInit" => kiehl_copy_oninit,
        "Kiehl#Original::OnTimer1000" => kiehl_original_ontimer1000,
        "Kiehl#Original::OnTimer120000" => kiehl_original_ontimer120000,
        "Kiehl#Original::OnTimer150000" => kiehl_original_ontimer150000,
        "Kiehl#Original::OnTimer160000" => kiehl_original_ontimer160000,
        "Kiehl#Original::OnTimer170000" => kiehl_original_ontimer170000,
        "Kiehl#Original::OnTimer175000" => kiehl_original_ontimer175000,
        "Kiehl#Original::OnTimer176000" => kiehl_original_ontimer176000,
        "Kiehl#Original::OnTimer177000" => kiehl_original_ontimer177000,
        "Kiehl#Original::OnTimer178000" => kiehl_original_ontimer178000,
        "Kiehl#Original::OnTimer179000" => kiehl_original_ontimer179000,
        "Kiehl#Original::OnTimer180000" => kiehl_original_ontimer180000,
        "Kiehl#Original::OnTimer60000" => kiehl_original_ontimer60000,
        "KiehlRoom::OnKiehlDead" => kiehlroom_onkiehldead,
        "KiehlRoom::OnKiehlMobDead" => kiehlroom_onkiehlmobdead,
        "KiehlRoom::OnReset" => kiehlroom_onreset,
        "Kiehl_Room_Exit::OnEnable" => kiehl_room_exit_onenable,
        "Kiehl_Room_Exit::OnInit" => kiehl_room_exit_oninit,
        "Kiehl_Room_Exit::OnTouch_" => kiehl_room_exit_ontouch,
        "Kiehl_Room_Trap::OnGlobalTimerOff" => kiehl_room_trap_onglobaltimeroff,
        "Kiehl_Room_Trap::OnTimer1200000" => kiehl_room_trap_ontimer1200000,
        "Kiehl_Room_Trap::OnTimer300000" => kiehl_room_trap_ontimer300000,
        "Kiehl_Room_Trap::OnTimer600000" => kiehl_room_trap_ontimer600000,
        "Kiehl_Room_Trap::OnTimer900000" => kiehl_room_trap_ontimer900000,
        "Kiehl_Room_Trap::OnTouch" => kiehl_room_trap_ontouch,
        "Kiehl_Room_Warp::OnEnable" => kiehl_room_warp_onenable,
        "Kiehl_Room_Warp::OnInit" => kiehl_room_warp_oninit,
        "Kiehl_Room_Warp::OnTimer30000" => kiehl_room_warp_ontimer30000,
        "Kiehl_Room_Warp::OnTouch_" => kiehl_room_warp_ontouch,
        "Letter#kh::OnTouch" => letter_kh_ontouch,
        "Mitchell#KiehlRoom::OnInit" => mitchell_kiehlroom_oninit,
        "Mysterious Woman#kh::OnTouch" => mysterious_woman_kh_ontouch,
        "Pub Master#kh::OnTouch" => pub_master_kh_ontouch,
        "Receiver#kh::OnMyMobDead" => receiver_kh_onmymobdead,
        "Robots#kh1::OnMyMobDead" => robots_kh1_onmymobdead,
        "Rosimmir_Entrance::OnTouch_" => rosimmir_entrance_ontouch,
        "Student#kha::OnTouch_" => student_kha_ontouch,
        "Vicious Dog#khp1::OnTouch" => vicious_dog_khp1_ontouch,
    }
}
