#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "#3room_barmunt" => s_3room_barmunt,
        "#barmunt_fire" => barmunt_fire,
        "#barmunt_living" => barmunt_living,
        "#barmut_onna" => barmut_onna,
        "#barmut_room1" => barmut_room1,
        "#barmut_room2" => barmut_room2,
        "#bpast_1_1" => bpast_1_1,
        "#garas_catch" => garas_catch,
        "#garas_eff" => garas_eff,
        "#garas_f_yume" => garas_f_yume,
        "#garas_path" => garas_path,
        "Alchemist" => alchemist,
        "Assistant#moc_ex1" => assistant_moc_ex1,
        "Book-Touching Man#garas" => book_touching_man_garas,
        "Cave Settler#f_cave1" => cave_settler_f_cave1,
        "Cave Settler#f_cave4" => cave_settler_f_cave4,
        "Cave Settler#f_cave6" => cave_settler_f_cave6,
        "Cave Settler#f_cave7" => cave_settler_f_cave7,
        "Cave Settler#g1" => cave_settler_g1,
        "Cave Settler#m_cave2" => cave_settler_m_cave2,
        "Cave Settler#m_cave3" => cave_settler_m_cave3,
        "Chief Balrog" => chief_balrog,
        "Continental Guard#01" => continental_guard_01,
        "Continental Messenger#00" => continental_messenger_00,
        "Continental Official" => continental_official,
        "Dog#garas" => dog_garas,
        "Female Researcher#bpast" => female_researcher_bpast,
        "Girl#moc_ex002" => girl_moc_ex002,
        "Grotesque Man#zid1" => grotesque_man_zid1,
        "Grotesque Man#zid2" => grotesque_man_zid2,
        "Grotesque Woman#eva1" => grotesque_woman_eva1,
        "Grotesque Woman#eva2" => grotesque_woman_eva2,
        "Group of Evil#edq" => group_of_evil_edq,
        "Hot Bestseller Corner" => hot_bestseller_corner,
        "Jaeda#garas1" => jaeda_garas1,
        "Library Curator#garas" => library_curator_garas,
        "Library Master#garas" => library_master_garas,
        "Library Part-Timer#garas" => library_part_timer_garas,
        "Monsterous Man#zid" => monsterous_man_zid,
        "Morocc GlobalVar Admin" => morocc_globalvar_admin,
        "Morocc Timer#edq" => morocc_timer_edq,
        "Old News Scrapbook" => old_news_scrapbook,
        "Reading Girl#moc_girl1" => reading_girl_moc_girl1,
        "Researcher#bpast_2_1" => researcher_bpast_2_1,
        "Researcher#bpast_2_2" => researcher_bpast_2_2,
        "Satan Broadcast#edq" => satan_broadcast_edq,
        "Satan Summon#edq" => satan_summon_edq,
        "Suspicious Man#oliver_h" => suspicious_man_oliver_h,
        "Time-Space Gap#edq" => time_space_gap_edq,
        "William" => william,
        "Worn-out Book#garas" => worn_out_book_garas,
    }
    events {
        "#3room_barmunt::OnTouch" => s_3room_barmunt_ontouch,
        "#barmunt_living::OnTouch" => barmunt_living_ontouch,
        "#barmut_onna::OnInit" => barmut_onna_oninit,
        "#barmut_room1::OnTouch" => barmut_room1_ontouch,
        "#bpast_1_1::OnTouch" => bpast_1_1_ontouch,
        "#garas_catch::OnTouch" => garas_catch_ontouch,
        "#garas_f_yume::OnTouch" => garas_f_yume_ontouch,
        "#garas_path::OnTouch" => garas_path_ontouch,
        "Cave Settler#g1::OnTouch" => cave_settler_g1_ontouch,
        "Continental Guard#01::OnTouch" => continental_guard_01_ontouch,
        "Continental Messenger#00::OnTouch_" => continental_messenger_00_ontouch,
        "Group of Evil#edq::OnEnable" => group_of_evil_edq_onenable,
        "Jaeda#garas1::OnInit" => jaeda_garas1_oninit,
        "Morocc Timer#edq::OnTouch_" => morocc_timer_edq_ontouch,
        "Satan Broadcast#edq::OnDisable" => satan_broadcast_edq_ondisable,
        "Satan Broadcast#edq::OnEnable" => satan_broadcast_edq_onenable,
        "Satan Broadcast#edq::OnInit" => satan_broadcast_edq_oninit,
        "Satan Broadcast#edq::OnTimer15000" => satan_broadcast_edq_ontimer15000,
        "Satan Broadcast#edq::OnTimer25000" => satan_broadcast_edq_ontimer25000,
        "Satan Broadcast#edq::OnTimer5000" => satan_broadcast_edq_ontimer5000,
        "Satan Summon#edq::OnDisable" => satan_summon_edq_ondisable,
        "Satan Summon#edq::OnEnable" => satan_summon_edq_onenable,
        "Satan Summon#edq::OnInit" => satan_summon_edq_oninit,
        "Satan Summon#edq::OnMyMobDead" => satan_summon_edq_onmymobdead,
        "Satan Summon#edq::OnTimer5400000" => satan_summon_edq_ontimer5400000,
        "Satan Summon#edq::OnTimer5415000" => satan_summon_edq_ontimer5415000,
        "Time-Space Gap#edq::OnDisable" => time_space_gap_edq_ondisable,
        "Time-Space Gap#edq::OnEnable" => time_space_gap_edq_onenable,
        "Time-Space Gap#edq::OnInit" => time_space_gap_edq_oninit,
        "Time-Space Gap#edq::OnTimer1800000" => time_space_gap_edq_ontimer1800000,
        "Time-Space Gap#edq::OnTimer21600000" => time_space_gap_edq_ontimer21600000,
    }
}
