// Generated by tools/scripts-import/convert_sdk2.py from npc/events/nguild/nguild_ev_agit.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, runtime};

pub fn f_agitbreak(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_castle_s = Val::from("");
    let mut l_defence = Val::from(0);
    let mut l_economy = Val::from(0);
    let mut l_gid = Val::from(0);
    let mut l_i = Val::from(0);
    let mut l_map_s = Val::from("");
    l_map_s = runtime::arg(&args, 0, Val::from(0));
    l_castle_s = runtime::arg(&args, 1, Val::from(0));
    l_gid = ctx.call(Function::GetCharacterId, vec![Val::from(2)])?;
    if l_gid.clone().number()? <= 0 {
        return Ok(Val::from(0));
    }
    l_economy = (ctx
        .call(Function::GetCastleData, vec![l_map_s.clone(), Val::from(2)])?
        .try_sub(Val::from(5))?);
    if l_economy.clone().number()? < 0 {
        l_economy = Val::from(0);
    }
    ctx.call(Function::SetCastleData, vec![l_map_s.clone(), Val::from(2), l_economy.clone()])?;
    l_defence = (ctx
        .call(Function::GetCastleData, vec![l_map_s.clone(), Val::from(3)])?
        .try_sub(Val::from(5))?);
    if l_defence.clone().number()? < 0 {
        l_defence = Val::from(0);
    }
    ctx.call(Function::SetCastleData, vec![l_map_s.clone(), Val::from(3), l_defence.clone()])?;
    ctx.call(Function::SetCastleData, vec![l_map_s.clone(), Val::from(1), l_gid.clone()])?;
    ctx.call(
        Function::MapAnnounce,
        vec![
            l_map_s.clone(),
            Val::from("The emperium has been destroyed."),
            ctx.constant("BC_MAP")?,
            Val::from(52479),
        ],
    )?;
    ctx.call(
        Function::Announce,
        vec![
            ((((Val::from("The [") + ctx.call(Function::GetCastleName, vec![l_map_s.clone()])?)
                + Val::from("] castle has been conquered by the ["))
                + ctx.call(Function::GetGuildInfo, vec![l_gid.clone(), Val::from(0)])?)
                + Val::from("] guild.")),
            ctx.constant("BC_ALL")?,
        ],
    )?;
    ctx.call(Function::DoNpcEvent, vec![(Val::from("::OnRecvCastle") + l_castle_s.clone())])?;
    ctx.call(Function::DisableNpc, vec![(Val::from("Kafra Staff#") + l_castle_s.clone())])?;
    l_i = Val::from(4);
    'l1: loop {
        if !(l_i.clone().number()? <= 9) {
            break 'l1;
        }
        'b1: {
            ctx.call(Function::SetCastleData, vec![l_map_s.clone(), l_i.clone(), Val::from(0)])?;
        }
        l_i = (l_i.clone() + Val::from(1));
    }
    if ctx.call(Function::GetGuildSkillLevel, vec![l_gid.clone(), Val::from(10002)])? == 0 {
        l_i = Val::from(10);
        'l2: loop {
            if !(l_i.clone().number()? <= 17) {
                break 'l2;
            }
            'b2: {
                ctx.call(Function::SetCastleData, vec![l_map_s.clone(), l_i.clone(), Val::from(0)])?;
            }
            l_i = (l_i.clone() + Val::from(1));
        }
    }
    return Ok(Val::from(0));
}

pub fn f_agitend(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_castle_s = Val::from("");
    let mut l_map_s = Val::from("");
    l_map_s = runtime::arg(&args, 0, Val::from(0));
    l_castle_s = runtime::arg(&args, 1, Val::from(0));
    ctx.call(Function::GvgOff, vec![l_map_s.clone()])?;
    if ctx.call(Function::GetCastleData, vec![l_map_s.clone(), Val::from(1)])? == 0 {
        return Ok(Val::from(0));
    }
    ctx.call(
        Function::MapRespawnGuildId,
        vec![
            l_map_s.clone(),
            ctx.call(Function::GetCastleData, vec![l_map_s.clone(), Val::from(1)])?,
            Val::from(4),
        ],
    )?;
    ctx.call(
        Function::KillMonster,
        vec![
            l_map_s.clone(),
            ((Val::from("Agit_") + l_castle_s.clone()) + Val::from("::OnAgitBreak")),
        ],
    )?;
    return Err(Stop::End);
}

pub fn f_agitstart(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_castle_s = Val::from("");
    let mut l_empx = Val::from(0);
    let mut l_empy = Val::from(0);
    let mut l_map_s = Val::from("");
    l_map_s = runtime::arg(&args, 0, Val::from(0));
    l_castle_s = runtime::arg(&args, 1, Val::from(0));
    l_empx = runtime::arg(&args, 2, Val::from(0));
    l_empy = runtime::arg(&args, 3, Val::from(0));
    ctx.call(
        Function::MapRespawnGuildId,
        vec![
            l_map_s.clone(),
            ctx.call(Function::GetCastleData, vec![l_map_s.clone(), Val::from(1)])?,
            Val::from(2),
        ],
    )?;
    ctx.call(
        Function::Monster,
        vec![
            l_map_s.clone(),
            l_empx.clone(),
            l_empy.clone(),
            Val::from("Emperium"),
            Val::from(1288),
            Val::from(1),
            ((Val::from("Agit_") + l_castle_s.clone()) + Val::from("::OnAgitBreak")),
        ],
    )?;
    ctx.call(Function::GvgOn, vec![l_map_s.clone()])?;
    if ctx.call(Function::GetCastleData, vec![l_map_s.clone(), Val::from(1)])? != 0 {
        return Ok(Val::from(0));
    }
    return Err(Stop::End);
}

pub fn f_guildbreak(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_castle_s = Val::from("");
    let mut l_map_s = Val::from("");
    l_map_s = runtime::arg(&args, 0, Val::from(0));
    l_castle_s = runtime::arg(&args, 1, Val::from(0));
    ctx.call(Function::KillMonster, vec![l_map_s.clone(), Val::from("All")])?;
    ctx.call(
        Function::Announce,
        vec![
            ((Val::from("Guild Base [") + ctx.call(Function::GetCastleName, vec![l_map_s.clone()])?) + Val::from("] has been abandoned.")),
            Val::from(0),
        ],
    )?;
    ctx.call(Function::DisableNpc, vec![(Val::from("Kafra Staff#") + l_castle_s.clone())])?;
    ctx.call(Function::SetCastleData, vec![l_map_s.clone(), Val::from(0), Val::from(0)])?;
    return Ok(Val::from(0));
}
