// Generated by tools/scripts-import/convert_sdk2.py from npc/other/gm_npcs.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, runtime};

pub fn f_gm_npc(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_error = Val::from(0);
    let mut l_input = Val::from(0);
    let mut l_inputstr_s = Val::from("");
    let mut l_map_s = Val::from("");
    let mut l_x = Val::from(0);
    let mut l_y = Val::from(0);
    if ctx.call(Function::GetGmLevel, vec![])?.number()? < 99 {
        let position = ctx
            .call(Function::GetMapXy, vec![ctx.constant("BL_NPC")?])?
            .into_array()
            .ok_or_else(|| Stop::Error("Invalid position".into()))?;
        l_map_s = position[0].clone();
        l_x = position[1].clone();
        l_y = position[2].clone();
        return Err(Stop::End);
    }
    if !(Val::from(args.len() as i32).is_true()) {
        return Ok(Val::from(0));
    }
    if runtime::arg(&args, 1, Val::from(0)) == 0 {
        if runtime::arg(&args, 3, Val::from(0)).is_true() {
            l_error = {
                let (input, status) = runtime::input_number(
                    ctx,
                    Some(runtime::arg(&args, 2, Val::from(0)).number()?),
                    Some(runtime::arg(&args, 3, Val::from(0)).number()?),
                )?;
                l_input = input;
                Val::from(status)
            };
            if l_error.clone().is_true() {
                return Ok(Val::from(-2));
            }
        } else {
            let (input, status) = runtime::input_number(ctx, None, None)?;
            l_input = input;
        }
        if l_input.clone() == 0 {
            return Ok(Val::from(-1));
        } else {
            return Ok((if l_input.clone().loosely_equals(&runtime::arg(&args, 0, Val::from(0))) {
                Val::from(1)
            } else {
                Val::from(0)
            }));
        }
    } else {
        let (input, status) = runtime::input_text(ctx, None, None)?;
        l_inputstr_s = input;
        return Ok((if l_inputstr_s.clone().loosely_equals(&runtime::arg(&args, 0, Val::from(0))) {
            Val::from(1)
        } else {
            Val::from(0)
        }));
    }
}
