// Generated by tools/scripts-import/convert_sdk2.py from npc/pre-re/jobs/1-1/merchant.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

pub fn f_merckafra(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ((ctx.var("job_merchant_q").get()? == 6 || ctx.var("job_merchant_q").get()? == 5)
        && (ctx.var("job_merchant_q2").get()? == 8 || ctx.var("job_merchant_q2").get()? == 7))
    {
        ctx.lines_as(
            "Kafra Employee",
            args!["Oh hello~", "Um, is there", "some special reason", "as to why you're here?"],
        )?;
        ctx.close_window()?;
        ctx.call(Function::Cutin, vec![Val::from(""), Val::from(255)])?;
        return Err(Stop::End);
    } else {
        if (ctx.var("job_merchant_q").get()? == 4 || ctx.var("job_merchant_q").get()? == 3) {
            ctx.lines_as(
                "Kafra Employee",
                args![
                    "A delivery from",
                    "the Merchant Guild?",
                    "Oh, yes, please set",
                    "it down right over there..."
                ],
            )?;
            if ((ctx.call(Function::CountItem, vec![Val::from(1081)])? == 1 || ctx.call(Function::CountItem, vec![Val::from(1082)])? == 1)
                || ctx.call(Function::CountItem, vec![Val::from(1091)])? == 1)
            {
                ctx.lines(args!["You must be really tired", "after carrying it for so long!"])?;
            } else {
                ctx.lines(args!["W-wait. Didn't you bring it?", "Where's the package?"])?;
                ctx.close_window()?;
                ctx.call(Function::Cutin, vec![Val::from(""), Val::from(255)])?;
                return Err(Stop::End);
            }
            ctx.next()?;
            ctx.lines_as("Kafra Employee", args!["Now, let me check", "the serial number..."])?;
            if (ctx.var("job_merchant_q2").get()? == 7 && ctx.call(Function::CountItem, vec![Val::from(1081)])? != 0) {
                ctx.lines(args![
                    "3318702. Right, this is",
                    "the one we ordered. Oh,",
                    "and don't forget this receipt!"
                ])?;
                ctx.call(Function::DelItem, vec![Val::from(1081), Val::from(1)])?;
                ctx.call(Function::GetItem, vec![Val::from(1079), Val::from(1)])?;
            } else {
                if (ctx.var("job_merchant_q2").get()? == 8 && ctx.call(Function::CountItem, vec![Val::from(1082)])? != 0) {
                    ctx.lines(args![
                        "3543625. Right, this is",
                        "the one we ordered. Oh,",
                        "and don't forget this receipt!"
                    ])?;
                    ctx.call(Function::DelItem, vec![Val::from(1082), Val::from(1)])?;
                    ctx.call(Function::GetItem, vec![Val::from(1080), Val::from(1)])?;
                } else {
                    ctx.lines(args!["Mmmm? Hold on. This is", "the wrong package. What we"])?;
                    if ctx.var("job_merchant_q2").get()? == 7 {
                        ctx.mes("ordered had the serial number 3318702. I'm sure it's not this.")?;
                    } else {
                        if ctx.var("job_merchant_q2").get()? == 8 {
                            ctx.mes("ordered had the serial number 3543625. I'm sure it's not this.")?;
                        } else {
                            ctx.mes("ordered had the serial number 3318702 or 3543625.")?;
                        }
                    }
                    ctx.close_window()?;
                    ctx.call(Function::Cutin, vec![Val::from(""), Val::from(255)])?;
                    return Err(Stop::End);
                }
            }
            if ctx.var("job_merchant_q").get()? == 4 {
                ctx.var("job_merchant_q").set(Val::from(6))?;
            } else {
                if ctx.var("job_merchant_q").get()? == 3 {
                    ctx.var("job_merchant_q").set(Val::from(5))?;
                }
            }
            ctx.next()?;
            if (ctx.call(Function::CountItem, vec![Val::from(1072)])? != 0 && ctx.var("quest_alb_01").get()? == 0) {
                let choice = runtime::select_values(ctx, &[Val::from("This is from Chief Mahnsoo of the Merchant Guild...")])?;
                ctx.var("@menu").set(choice)?;
                ctx.call(Function::DelItem, vec![Val::from(1072), Val::from(1)])?;
                ctx.var("quest_alb_01").set(Val::from(1))?;
                ctx.lines_as(
                    "Kafra Employee",
                    args![
                        "Oh~! A letter from",
                        "Mahnsoo! Thank you",
                        "so much, I've been dying",
                        "to hear from him. How is",
                        "he doing, is he alright?",
                        "I can't wait to read it..."
                    ],
                )?;
                ctx.next()?;
                ctx.lines_as(
                    "Kafra Employee",
                    args![
                        "Oh, thank you for",
                        "going through all the",
                        "trouble of delivering all",
                        "of this. This isn't anything",
                        "special, but please take it.",
                        "Well, see you again~"
                    ],
                )?;
                ctx.call(Function::GetItem, vec![Val::from(513), Val::from(3)])?;
            } else {
                ctx.lines_as(
                    "Kafra Employee",
                    args!["Thanks again", "for going through", "all of that trouble~"],
                )?;
            }
            ctx.close_window()?;
            ctx.call(Function::Cutin, vec![Val::from(""), Val::from(255)])?;
            return Err(Stop::End);
        }
    }
    return Ok(Val::from(0));
}
