pub mod nguild_dunsw;
pub mod nguild_ev_agit;
pub mod nguild_flags;
pub mod nguild_guardians;
pub mod nguild_kafras;
pub mod nguild_managers;
pub mod nguild_treas;
pub mod nguild_warper;

script_sdk_2::script_module! {
    npcs {
        "Agit_N01" => nguild_ev_agit::agit_n01,
        "Agit_N02" => nguild_ev_agit::agit_n02,
        "Agit_N03" => nguild_ev_agit::agit_n03,
        "Agit_N04" => nguild_ev_agit::agit_n04,
        "Cita" => nguild_warper::cita,
        "Dundar" => nguild_managers::dundar,
        "Frolo" => nguild_managers::frolo,
        "Guardian_N01" => nguild_guardians::guardian_n01,
        "Guardian_N02" => nguild_guardians::guardian_n02,
        "Guardian_N03" => nguild_guardians::guardian_n03,
        "Guardian_N04" => nguild_guardians::guardian_n04,
        "Kafra Service#N01" => nguild_kafras::kafra_service_n01,
        "Kafra Service#N02" => nguild_kafras::kafra_service_n02,
        "Kafra Service#N03" => nguild_kafras::kafra_service_n03,
        "Kafra Service#N04" => nguild_kafras::kafra_service_n04,
        "Leiber" => nguild_managers::leiber,
        "NGuild Aldebaran#a1-1" => nguild_flags::nguild_aldebaran_a1_1,
        "NGuild Aldebaran#a1-6" => nguild_flags::nguild_aldebaran_a1_6,
        "NGuild Geffen#g1-1" => nguild_flags::nguild_geffen_g1_1,
        "NGuild Geffen#g1-6" => nguild_flags::nguild_geffen_g1_6,
        "NGuild Payon#f1-1" => nguild_flags::nguild_payon_f1_1,
        "NGuild Payon#f1-6" => nguild_flags::nguild_payon_f1_6,
        "NGuild Prontera#p1-1" => nguild_flags::nguild_prontera_p1_1,
        "NGuild Prontera#p1-7" => nguild_flags::nguild_prontera_p1_7,
        "Novice Castles" => nguild_warper::novice_castles,
        "Switch#DunN01" => nguild_dunsw::switch_dunn01,
        "Switch#DunN02" => nguild_dunsw::switch_dunn02,
        "Switch#DunN03" => nguild_dunsw::switch_dunn03,
        "Switch#DunN04" => nguild_dunsw::switch_dunn04,
        "Switch#TresN01" => nguild_treas::switch_tresn01,
        "Switch#TresN02" => nguild_treas::switch_tresn02,
        "Switch#TresN03" => nguild_treas::switch_tresn03,
        "Switch#TresN04" => nguild_treas::switch_tresn04,
        "Thefton" => nguild_managers::thefton,
        "TreasSpawn" => nguild_ev_agit::treasspawn,
        "Treasure_N01" => nguild_treas::treasure_n01,
        "Treasure_N02" => nguild_treas::treasure_n02,
        "Treasure_N03" => nguild_treas::treasure_n03,
        "Treasure_N04" => nguild_treas::treasure_n04,
    }
    events {
        "Agit_N01::OnAgitBreak" => nguild_ev_agit::agit_n01_onagitbreak,
        "Agit_N01::OnAgitEliminate" => nguild_ev_agit::agit_n01_onagiteliminate,
        "Agit_N01::OnAgitEnd" => nguild_ev_agit::agit_n01_onagitend,
        "Agit_N01::OnAgitStart" => nguild_ev_agit::agit_n01_onagitstart,
        "Agit_N01::OnGuildBreak" => nguild_ev_agit::agit_n01_onguildbreak,
        "Agit_N01::OnInterIfInitOnce" => nguild_ev_agit::agit_n01_oninterifinitonce,
        "Agit_N01::OnRecvCastleN01" => nguild_ev_agit::agit_n01_onrecvcastlen01,
        "Agit_N02::OnAgitBreak" => nguild_ev_agit::agit_n02_onagitbreak,
        "Agit_N02::OnAgitEliminate" => nguild_ev_agit::agit_n02_onagiteliminate,
        "Agit_N02::OnAgitEnd" => nguild_ev_agit::agit_n02_onagitend,
        "Agit_N02::OnAgitStart" => nguild_ev_agit::agit_n02_onagitstart,
        "Agit_N02::OnGuildBreak" => nguild_ev_agit::agit_n02_onguildbreak,
        "Agit_N02::OnInterIfInitOnce" => nguild_ev_agit::agit_n02_oninterifinitonce,
        "Agit_N02::OnRecvCastleN02" => nguild_ev_agit::agit_n02_onrecvcastlen02,
        "Agit_N03::OnAgitBreak" => nguild_ev_agit::agit_n03_onagitbreak,
        "Agit_N03::OnAgitEliminate" => nguild_ev_agit::agit_n03_onagiteliminate,
        "Agit_N03::OnAgitEnd" => nguild_ev_agit::agit_n03_onagitend,
        "Agit_N03::OnAgitStart" => nguild_ev_agit::agit_n03_onagitstart,
        "Agit_N03::OnGuildBreak" => nguild_ev_agit::agit_n03_onguildbreak,
        "Agit_N03::OnInterIfInitOnce" => nguild_ev_agit::agit_n03_oninterifinitonce,
        "Agit_N03::OnRecvCastleN03" => nguild_ev_agit::agit_n03_onrecvcastlen03,
        "Agit_N04::OnAgitBreak" => nguild_ev_agit::agit_n04_onagitbreak,
        "Agit_N04::OnAgitEliminate" => nguild_ev_agit::agit_n04_onagiteliminate,
        "Agit_N04::OnAgitEnd" => nguild_ev_agit::agit_n04_onagitend,
        "Agit_N04::OnAgitStart" => nguild_ev_agit::agit_n04_onagitstart,
        "Agit_N04::OnGuildBreak" => nguild_ev_agit::agit_n04_onguildbreak,
        "Agit_N04::OnInterIfInitOnce" => nguild_ev_agit::agit_n04_oninterifinitonce,
        "Agit_N04::OnRecvCastleN04" => nguild_ev_agit::agit_n04_onrecvcastlen04,
        "Guardian_N01::OnAgitInit" => nguild_guardians::guardian_n01_onagitinit,
        "Guardian_N01::OnGuardianDied" => nguild_guardians::guardian_n01_onguardiandied,
        "Guardian_N02::OnAgitInit" => nguild_guardians::guardian_n02_onagitinit,
        "Guardian_N02::OnGuardianDied" => nguild_guardians::guardian_n02_onguardiandied,
        "Guardian_N03::OnAgitInit" => nguild_guardians::guardian_n03_onagitinit,
        "Guardian_N03::OnGuardianDied" => nguild_guardians::guardian_n03_onguardiandied,
        "Guardian_N04::OnAgitInit" => nguild_guardians::guardian_n04_onagitinit,
        "Guardian_N04::OnGuardianDied" => nguild_guardians::guardian_n04_onguardiandied,
        "Kafra Service#N01::OnRecvCastleN01" => nguild_kafras::kafra_service_n01_onrecvcastlen01,
        "Kafra Service#N02::OnRecvCastleN02" => nguild_kafras::kafra_service_n02_onrecvcastlen02,
        "Kafra Service#N03::OnRecvCastleN03" => nguild_kafras::kafra_service_n03_onrecvcastlen03,
        "Kafra Service#N04::OnRecvCastleN04" => nguild_kafras::kafra_service_n04_onrecvcastlen04,
        "NGuild Aldebaran#a1-1::OnRecvCastleN01" => nguild_flags::nguild_aldebaran_a1_1_onrecvcastlen01,
        "NGuild Aldebaran#a1-6::OnRecvCastleN01" => nguild_flags::nguild_aldebaran_a1_6_onrecvcastlen01,
        "NGuild Geffen#g1-1::OnRecvCastleN02" => nguild_flags::nguild_geffen_g1_1_onrecvcastlen02,
        "NGuild Geffen#g1-6::OnRecvCastleN02" => nguild_flags::nguild_geffen_g1_6_onrecvcastlen02,
        "NGuild Payon#f1-1::OnRecvCastleN03" => nguild_flags::nguild_payon_f1_1_onrecvcastlen03,
        "NGuild Payon#f1-6::OnRecvCastleN03" => nguild_flags::nguild_payon_f1_6_onrecvcastlen03,
        "NGuild Prontera#p1-1::OnRecvCastleN04" => nguild_flags::nguild_prontera_p1_1_onrecvcastlen04,
        "NGuild Prontera#p1-7::OnRecvCastleN04" => nguild_flags::nguild_prontera_p1_7_onrecvcastlen04,
        "TreasSpawn::OnClock0005" => nguild_ev_agit::treasspawn_onclock0005,
        "Treasure_N01::OnDied" => nguild_treas::treasure_n01_ondied,
        "Treasure_N01::OnInit" => nguild_treas::treasure_n01_oninit,
        "Treasure_N01::OnRecvCastleN01" => nguild_treas::treasure_n01_onrecvcastlen01,
        "Treasure_N02::OnDied" => nguild_treas::treasure_n02_ondied,
        "Treasure_N02::OnInit" => nguild_treas::treasure_n02_oninit,
        "Treasure_N02::OnRecvCastleN02" => nguild_treas::treasure_n02_onrecvcastlen02,
        "Treasure_N03::OnDied" => nguild_treas::treasure_n03_ondied,
        "Treasure_N03::OnInit" => nguild_treas::treasure_n03_oninit,
        "Treasure_N03::OnRecvCastleN03" => nguild_treas::treasure_n03_onrecvcastlen03,
        "Treasure_N04::OnDied" => nguild_treas::treasure_n04_ondied,
        "Treasure_N04::OnInit" => nguild_treas::treasure_n04_oninit,
        "Treasure_N04::OnRecvCastleN04" => nguild_treas::treasure_n04_onrecvcastlen04,
    }
}
