#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod part_10;
mod part_11;
mod part_12;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;
pub use part_08::*;
pub use part_09::*;
pub use part_10::*;
pub use part_11::*;
pub use part_12::*;

script_sdk_2::script_module! {
    npcs {
        "#dandelion_duplicates" => dandelion_duplicates,
        "#env_clear" => env_clear,
        "#ep13bs" => ep13bs,
        "#evt_lumis" => evt_lumis,
        "#moc2_b1_gate" => moc2_b1_gate,
        "#moc2_event01" => moc2_event01,
        "#moc2_event_on" => moc2_event_on,
        "#moc2_talkevent01" => moc2_talkevent01,
        "#monster_master" => monster_master,
        "#room1_warp13" => room1_warp13,
        "#room1timer" => room1timer,
        "#room2_1_warp" => room2_1_warp,
        "#room2_2_warp" => room2_2_warp,
        "#room2timer" => room2timer,
        "#timer_alba01" => timer_alba01,
        "Alberto#ep13bs" => alberto_ep13bs,
        "Alliance Manager#prt_" => alliance_manager_prt,
        "Alliance Manager#ra" => alliance_manager_ra,
        "Allied Manager#gm" => allied_manager_gm,
        "Bar Master#moc2_01" => bar_master_moc2_01,
        "Botanist#ep13" => botanist_ep13,
        "Botanist#ep13_1" => botanist_ep13_1,
        "Breeder Taab#ep13_alba" => breeder_taab_ep13_alba,
        "Camp Guard Captain#man1" => camp_guard_captain_man1,
        "Camp Guard#man1" => camp_guard_man1,
        "Cat Paw Agent" => cat_paw_agent,
        "Cat Paw Mining Agent" => cat_paw_mining_agent,
        "Command Timer#edq" => command_timer_edq,
        "Cooking Soldier#ep13bs" => cooking_soldier_ep13bs,
        "Cornus#alba03" => cornus_alba03,
        "Corpse#moc2_dead01" => corpse_moc2_dead01,
        "Crushed Corpse#moc2" => crushed_corpse_moc2,
        "Davi#ep13bs" => davi_ep13bs,
        "Defaria#moc2" => defaria_moc2,
        "Diego#ep13bs_" => diego_ep13bs,
        "Dirt#ep13" => dirt_ep13,
        "Disfigured Corpse#moc2" => disfigured_corpse_moc2,
        "Dismembered Corpse#moc2" => dismembered_corpse_moc2,
        "Expedition Messenger" => expedition_messenger,
        "Expedition Messenger#2" => expedition_messenger_2,
        "Expedition Messenger#3" => expedition_messenger_3,
        "Expedition Scout#1" => expedition_scout_1,
        "Ferocious Gorurug" => ferocious_gorurug,
        "Fluffy Gyaruk" => fluffy_gyaruk,
        "Frozen Tree#evt_lumis" => frozen_tree_evt_lumis,
        "Gerard#ep13bs" => gerard_ep13bs,
        "Gerhart" => gerhart,
        "Guard#ep13_1-1" => guard_ep13_1_1,
        "Guard#ep13_1-3" => guard_ep13_1_3,
        "Guard#ep13_1-5" => guard_ep13_1_5,
        "Guard#ep13_1-7" => guard_ep13_1_7,
        "Guard#ep13_1-9" => guard_ep13_1_9,
        "Guide#ep13_1" => guide_ep13_1,
        "Hansenne#ep131_rhea03" => hansenne_ep131_rhea03,
        "Hansenne#ep131_rhea07" => hansenne_ep131_rhea07,
        "Head of the Alliance#moo" => head_of_the_alliance_moo,
        "Heap of Earth#mao2_01" => heap_of_earth_mao2_01,
        "Henry Clifford" => henry_clifford,
        "Hibba Agip" => hibba_agip,
        "Hillsrion#alba01" => hillsrion_alba01,
        "Hue#ep131_rhea02" => hue_ep131_rhea02,
        "Hue#ep131_rhea06" => hue_ep131_rhea06,
        "Idle Knight#dan_08" => idle_knight_dan_08,
        "Instructor Igrid" => instructor_igrid,
        "Instructor#ep13bs" => instructor_ep13bs,
        "Jan#ep13bs" => jan_ep13bs,
        "Laur_" => laur,
        "Lucas#ep13bs" => lucas_ep13bs,
        "Man#moc2_crazyR01" => man_moc2_crazyr01,
        "Manager#moc2_finder" => manager_moc2_finder,
        "Marian#ep13bs" => marian_ep13bs,
        "Member of Alliance#1" => member_of_alliance_1,
        "Member of Alliance#2" => member_of_alliance_2,
        "Member of Alliance#3" => member_of_alliance_3,
        "Member of Alliance#4" => member_of_alliance_4,
        "Member of Alliance#5" => member_of_alliance_5,
        "Member of Alliance#6" => member_of_alliance_6,
        "Member of Alliance#7" => member_of_alliance_7,
        "Member of Alliance#8" => member_of_alliance_8,
        "Member of Alliance#prt_" => member_of_alliance_prt,
        "Monster Scholar#ep13" => monster_scholar_ep13,
        "Mr. Kidd#ep13_dan01" => mr_kidd_ep13_dan01,
        "Mr. Kidd#moc_extra01" => mr_kidd_moc_extra01,
        "Munkenro#1" => munkenro_1,
        "Munkenro#2" => munkenro_2,
        "Mutated Corpse#moc2" => mutated_corpse_moc2,
        "Mutilated Corpse#moc2" => mutilated_corpse_moc2,
        "Mysterious Rock#0" => mysterious_rock_0,
        "Nuria" => nuria,
        "Officer A" => officer_a,
        "Officer B" => officer_b,
        "Otto#ep13bs" => otto_ep13bs,
        "Piece of crack#sec" => piece_of_crack_sec,
        "Post#ep13bs1" => post_ep13bs1,
        "Post#ep13bs2" => post_ep13bs2,
        "Promotional Staff#alde" => promotional_staff_alde,
        "Promotional Staff#gef" => promotional_staff_gef,
        "Promotional Staff#prt" => promotional_staff_prt,
        "PromotionalStaff_izlude" => promotionalstaff_izlude,
        "Pursuit Party Leader#1" => pursuit_party_leader_1,
        "Rayan#moc_room2_2" => rayan_moc_room2_2,
        "Receptionist Brink#ep13b" => receptionist_brink_ep13b,
        "Recruiter for the Brave_" => recruiter_for_the_brave,
        "Research Official#ep131" => research_official_ep131,
        "Rift Guard#1" => rift_guard_1,
        "Rift Guard#2" => rift_guard_2,
        "Rift Guard#3" => rift_guard_3,
        "Rift Guard#4" => rift_guard_4,
        "Rin#moc_room2_1" => rin_moc_room2_1,
        "Rin#moc_room2_2" => rin_moc_room2_2,
        "Ryosen#ep131_rhea01" => ryosen_ep131_rhea01,
        "Ryosen#ep131_rhea05" => ryosen_ep131_rhea05,
        "School of Fish#1" => school_of_fish_1,
        "Sharp-Looking Boy#dan_07" => sharp_looking_boy_dan_07,
        "Sikaiz#1" => sikaiz_1,
        "Small Fairy#spl" => small_fairy_spl,
        "Sorcerer#ep13bs" => sorcerer_ep13bs,
        "Staff Officer Abidal" => staff_officer_abidal,
        "Tao#dan_09" => tao_dan_09,
        "Tatacho#alba02" => tatacho_alba02,
        "Time-Space Gap Guard" => time_space_gap_guard,
        "Traces#mao2_object02" => traces_mao2_object02,
        "Traces#mao2_object03" => traces_mao2_object03,
        "Tree Giant#man" => tree_giant_man,
        "Tree#ep13bs1" => tree_ep13bs1,
        "Valdes#moc_master_1" => valdes_moc_master_1,
        "Wet Firewood#moc2" => wet_firewood_moc2,
        "ep13_man_fild01_mon_edq" => ep13_man_fild01_mon_edq,
        "ep13_man_fild03_mon_edq" => ep13_man_fild03_mon_edq,
        "ep13_spl_fild02_mon_edq" => ep13_spl_fild02_mon_edq,
        "ep13_spl_fild03_mon_edq" => ep13_spl_fild03_mon_edq,
        "que_job01#01" => que_job01_01,
        "que_job01#04" => que_job01_04,
        "que_job01#room1_out" => que_job01_room1_out,
        "que_job01#room2_1_out" => que_job01_room2_1_out,
        "que_job01#room2_2_out" => que_job01_room2_2_out,
        "que_job01#room_1" => que_job01_room_1,
        "que_job01#room_2" => que_job01_room_2,
    }
    events {
        "#dandelion_duplicates::OnDisable" => dandelion_duplicates_ondisable,
        "#dandelion_duplicates::OnEnable" => dandelion_duplicates_onenable,
        "#dandelion_duplicates::OnInit" => dandelion_duplicates_oninit,
        "#env_clear::OnTouch" => env_clear_ontouch,
        "#ep13bs::OnTouch_" => ep13bs_ontouch,
        "#evt_lumis::OnTouch_" => evt_lumis_ontouch,
        "#moc2_b1_gate::OnTouch" => moc2_b1_gate_ontouch,
        "#moc2_event01::OnDisable" => moc2_event01_ondisable,
        "#moc2_event01::OnEnable" => moc2_event01_onenable,
        "#moc2_event01::OnInit" => moc2_event01_oninit,
        "#moc2_event01::OnTouch_" => moc2_event01_ontouch,
        "#moc2_event_on::OnDisable" => moc2_event_on_ondisable,
        "#moc2_event_on::OnEnable" => moc2_event_on_onenable,
        "#moc2_event_on::OnStop" => moc2_event_on_onstop,
        "#moc2_event_on::OnTimer300000" => moc2_event_on_ontimer300000,
        "#moc2_event_on::OnTimer303000" => moc2_event_on_ontimer303000,
        "#moc2_event_on::OnTimer306000" => moc2_event_on_ontimer306000,
        "#moc2_event_on::OnTimer307000" => moc2_event_on_ontimer307000,
        "#moc2_event_on::OnTimer308000" => moc2_event_on_ontimer308000,
        "#moc2_event_on::OnTouch_" => moc2_event_on_ontouch,
        "#moc2_talkevent01::OnTouch" => moc2_talkevent01_ontouch,
        "#monster_master::OnEnable" => monster_master_onenable,
        "#monster_master::OnMyMobDead" => monster_master_onmymobdead,
        "#monster_master::OnStop" => monster_master_onstop,
        "#monster_master::OnTimer3600000" => monster_master_ontimer3600000,
        "#monster_master::OnTimer3960000" => monster_master_ontimer3960000,
        "#room1_warp13::OnDisable" => room1_warp13_ondisable,
        "#room1_warp13::OnEnable" => room1_warp13_onenable,
        "#room1_warp13::OnInit" => room1_warp13_oninit,
        "#room1_warp13::OnTouch_" => room1_warp13_ontouch,
        "#room1timer::OnEnable" => room1timer_onenable,
        "#room1timer::OnStop" => room1timer_onstop,
        "#room1timer::OnTimer240000" => room1timer_ontimer240000,
        "#room1timer::OnTimer245000" => room1timer_ontimer245000,
        "#room1timer::OnTimer250000" => room1timer_ontimer250000,
        "#room2_1_warp::OnDisable" => room2_1_warp_ondisable,
        "#room2_1_warp::OnEnable" => room2_1_warp_onenable,
        "#room2_1_warp::OnInit" => room2_1_warp_oninit,
        "#room2_1_warp::OnTouch_" => room2_1_warp_ontouch,
        "#room2_2_warp::OnDisable" => room2_2_warp_ondisable,
        "#room2_2_warp::OnEnable" => room2_2_warp_onenable,
        "#room2_2_warp::OnInit" => room2_2_warp_oninit,
        "#room2_2_warp::OnTouch_" => room2_2_warp_ontouch,
        "#room2timer::OnEnable" => room2timer_onenable,
        "#room2timer::OnStop" => room2timer_onstop,
        "#room2timer::OnTimer240000" => room2timer_ontimer240000,
        "#room2timer::OnTimer245000" => room2timer_ontimer245000,
        "#room2timer::OnTimer250000" => room2timer_ontimer250000,
        "#timer_alba01::OnEnable" => timer_alba01_onenable,
        "#timer_alba01::OnInit" => timer_alba01_oninit,
        "#timer_alba01::OnStop" => timer_alba01_onstop,
        "#timer_alba01::OnTimer1000" => timer_alba01_ontimer1000,
        "#timer_alba01::OnTimer180000" => timer_alba01_ontimer180000,
        "#timer_alba01::OnTimer360000" => timer_alba01_ontimer360000,
        "#timer_alba01::OnTimer600000" => timer_alba01_ontimer600000,
        "#timer_alba01::OnTimer7800000" => timer_alba01_ontimer7800000,
        "Botanist#ep13_1::OnInit" => botanist_ep13_1_oninit,
        "Command Timer#edq::OnDisable" => command_timer_edq_ondisable,
        "Command Timer#edq::OnEnable" => command_timer_edq_onenable,
        "Command Timer#edq::OnInit" => command_timer_edq_oninit,
        "Command Timer#edq::OnTimer3600000" => command_timer_edq_ontimer3600000,
        "Cornus#alba03::OnDisable" => cornus_alba03_ondisable,
        "Cornus#alba03::OnEnable" => cornus_alba03_onenable,
        "Cornus#alba03::OnTouch" => cornus_alba03_ontouch,
        "Corpse#moc2_dead01::OnCall" => corpse_moc2_dead01_oncall,
        "Corpse#moc2_dead01::OnDisable" => corpse_moc2_dead01_ondisable,
        "Corpse#moc2_dead01::OnEnable" => corpse_moc2_dead01_onenable,
        "Corpse#moc2_dead01::OnInit" => corpse_moc2_dead01_oninit,
        "Corpse#moc2_dead01::OnMyMobDead" => corpse_moc2_dead01_onmymobdead,
        "Corpse#moc2_dead01::OnReset" => corpse_moc2_dead01_onreset,
        "Corpse#moc2_dead01::OnTimer10000" => corpse_moc2_dead01_ontimer10000,
        "Corpse#moc2_dead01::OnTimer11000" => corpse_moc2_dead01_ontimer11000,
        "Corpse#moc2_dead01::OnTimer4000" => corpse_moc2_dead01_ontimer4000,
        "Corpse#moc2_dead01::OnTimer7000" => corpse_moc2_dead01_ontimer7000,
        "Expedition Messenger#2::OnDisable" => expedition_messenger_2_ondisable,
        "Expedition Messenger#2::OnEnable" => expedition_messenger_2_onenable,
        "Expedition Messenger#2::OnInit" => expedition_messenger_2_oninit,
        "Expedition Messenger#2::Ongo" => expedition_messenger_2_ongo,
        "Expedition Messenger#3::OnDisable" => expedition_messenger_3_ondisable,
        "Expedition Messenger#3::OnEnable" => expedition_messenger_3_onenable,
        "Expedition Messenger#3::OnInit" => expedition_messenger_3_oninit,
        "Expedition Messenger::OnInit" => expedition_messenger_oninit,
        "Guard#ep13_1-1::OnTouch" => guard_ep13_1_1_ontouch,
        "Guard#ep13_1-3::OnTouch" => guard_ep13_1_3_ontouch,
        "Guard#ep13_1-5::OnTouch" => guard_ep13_1_5_ontouch,
        "Guard#ep13_1-7::OnTouch" => guard_ep13_1_7_ontouch,
        "Hansenne#ep131_rhea07::OnDisable" => hansenne_ep131_rhea07_ondisable,
        "Hansenne#ep131_rhea07::OnEnable" => hansenne_ep131_rhea07_onenable,
        "Hansenne#ep131_rhea07::OnInit" => hansenne_ep131_rhea07_oninit,
        "Hansenne#ep131_rhea07::OnTimer300000" => hansenne_ep131_rhea07_ontimer300000,
        "Head of the Alliance#moo::OnDisable" => head_of_the_alliance_moo_ondisable,
        "Head of the Alliance#moo::OnEnable" => head_of_the_alliance_moo_onenable,
        "Head of the Alliance#moo::OnInit" => head_of_the_alliance_moo_oninit,
        "Head of the Alliance#moo::OnMyMobDead" => head_of_the_alliance_moo_onmymobdead,
        "Head of the Alliance#moo::OnReset" => head_of_the_alliance_moo_onreset,
        "Head of the Alliance#moo::OnTimer900000" => head_of_the_alliance_moo_ontimer900000,
        "Heap of Earth#mao2_01::OnTouch" => heap_of_earth_mao2_01_ontouch,
        "Hillsrion#alba01::OnDisable" => hillsrion_alba01_ondisable,
        "Hillsrion#alba01::OnEnable" => hillsrion_alba01_onenable,
        "Hillsrion#alba01::OnTouch" => hillsrion_alba01_ontouch,
        "Hue#ep131_rhea06::OnDisable" => hue_ep131_rhea06_ondisable,
        "Hue#ep131_rhea06::OnEnable" => hue_ep131_rhea06_onenable,
        "Hue#ep131_rhea06::OnInit" => hue_ep131_rhea06_oninit,
        "Hue#ep131_rhea06::OnTimer300000" => hue_ep131_rhea06_ontimer300000,
        "Mr. Kidd#ep13_dan01::OnInit" => mr_kidd_ep13_dan01_oninit,
        "Mr. Kidd#moc_extra01::OnDisable" => mr_kidd_moc_extra01_ondisable,
        "Mr. Kidd#moc_extra01::OnEnable" => mr_kidd_moc_extra01_onenable,
        "Mr. Kidd#moc_extra01::OnInit" => mr_kidd_moc_extra01_oninit,
        "Mysterious Rock#0::OnTimer120000" => mysterious_rock_0_ontimer120000,
        "Rayan#moc_room2_2::OnDisable" => rayan_moc_room2_2_ondisable,
        "Rayan#moc_room2_2::OnEnable" => rayan_moc_room2_2_onenable,
        "Rayan#moc_room2_2::OnInit" => rayan_moc_room2_2_oninit,
        "Research Official#ep131::OnCall" => research_official_ep131_oncall,
        "Research Official#ep131::OnDisable" => research_official_ep131_ondisable,
        "Research Official#ep131::OnEnable" => research_official_ep131_onenable,
        "Research Official#ep131::OnInit" => research_official_ep131_oninit,
        "Research Official#ep131::OnMeet" => research_official_ep131_onmeet,
        "Research Official#ep131::OnMyMobDead" => research_official_ep131_onmymobdead,
        "Research Official#ep131::OnTimer300000" => research_official_ep131_ontimer300000,
        "Research Official#ep131::OnTouch_" => research_official_ep131_ontouch,
        "Rin#moc_room2_2::OnDisable" => rin_moc_room2_2_ondisable,
        "Rin#moc_room2_2::OnEnable" => rin_moc_room2_2_onenable,
        "Rin#moc_room2_2::OnInit" => rin_moc_room2_2_oninit,
        "Ryosen#ep131_rhea05::OnDisable" => ryosen_ep131_rhea05_ondisable,
        "Ryosen#ep131_rhea05::OnEnable" => ryosen_ep131_rhea05_onenable,
        "Ryosen#ep131_rhea05::OnInit" => ryosen_ep131_rhea05_oninit,
        "Ryosen#ep131_rhea05::OnTimer300000" => ryosen_ep131_rhea05_ontimer300000,
        "Tatacho#alba02::OnDisable" => tatacho_alba02_ondisable,
        "Tatacho#alba02::OnEnable" => tatacho_alba02_onenable,
        "Tatacho#alba02::OnTouch" => tatacho_alba02_ontouch,
        "Valdes#moc_master_1::OnDisable" => valdes_moc_master_1_ondisable,
        "Valdes#moc_master_1::OnEnable" => valdes_moc_master_1_onenable,
        "Valdes#moc_master_1::OnInit" => valdes_moc_master_1_oninit,
        "ep13_man_fild01_mon_edq::OnDisable" => ep13_man_fild01_mon_edq_ondisable,
        "ep13_man_fild01_mon_edq::OnEnable" => ep13_man_fild01_mon_edq_onenable,
        "ep13_man_fild01_mon_edq::OnInit" => ep13_man_fild01_mon_edq_oninit,
        "ep13_man_fild01_mon_edq::OnMyMobDead" => ep13_man_fild01_mon_edq_onmymobdead,
        "ep13_man_fild01_mon_edq::OnTimer600000" => ep13_man_fild01_mon_edq_ontimer600000,
        "ep13_man_fild03_mon_edq::OnDisable" => ep13_man_fild03_mon_edq_ondisable,
        "ep13_man_fild03_mon_edq::OnEnable" => ep13_man_fild03_mon_edq_onenable,
        "ep13_man_fild03_mon_edq::OnInit" => ep13_man_fild03_mon_edq_oninit,
        "ep13_man_fild03_mon_edq::OnMyMobDead" => ep13_man_fild03_mon_edq_onmymobdead,
        "ep13_man_fild03_mon_edq::OnTimer600000" => ep13_man_fild03_mon_edq_ontimer600000,
        "ep13_spl_fild02_mon_edq::OnDisable" => ep13_spl_fild02_mon_edq_ondisable,
        "ep13_spl_fild02_mon_edq::OnEnable" => ep13_spl_fild02_mon_edq_onenable,
        "ep13_spl_fild02_mon_edq::OnInit" => ep13_spl_fild02_mon_edq_oninit,
        "ep13_spl_fild02_mon_edq::OnMyMobDead" => ep13_spl_fild02_mon_edq_onmymobdead,
        "ep13_spl_fild02_mon_edq::OnTimer600000" => ep13_spl_fild02_mon_edq_ontimer600000,
        "ep13_spl_fild03_mon_edq::OnDisable" => ep13_spl_fild03_mon_edq_ondisable,
        "ep13_spl_fild03_mon_edq::OnEnable" => ep13_spl_fild03_mon_edq_onenable,
        "ep13_spl_fild03_mon_edq::OnInit" => ep13_spl_fild03_mon_edq_oninit,
        "ep13_spl_fild03_mon_edq::OnMyMobDead" => ep13_spl_fild03_mon_edq_onmymobdead,
        "ep13_spl_fild03_mon_edq::OnTimer600000" => ep13_spl_fild03_mon_edq_ontimer600000,
        "que_job01#01::OnTouch_" => que_job01_01_ontouch,
        "que_job01#04::OnTouch_" => que_job01_04_ontouch,
        "que_job01#room1_out::OnTouch_" => que_job01_room1_out_ontouch,
        "que_job01#room2_1_out::OnTouch_" => que_job01_room2_1_out_ontouch,
        "que_job01#room2_2_out::OnTouch_" => que_job01_room2_2_out_ontouch,
        "que_job01#room_1::OnInit" => que_job01_room_1_oninit,
        "que_job01#room_1::OnReset" => que_job01_room_1_onreset,
        "que_job01#room_1::OnTouch_" => que_job01_room_1_ontouch,
        "que_job01#room_2::OnInit" => que_job01_room_2_oninit,
        "que_job01#room_2::OnReset" => que_job01_room_2_onreset,
        "que_job01#room_2::OnTouch_" => que_job01_room_2_ontouch,
    }
}
