// Generated by tools/scripts-import/convert_sdk2.py from npc/pre-re/guides/guides_lighthalzen.txt. Delete this line to stop the generator from overwriting the file.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn guide_lhz_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_compass_check = Val::from(0);
    let mut l_loop1 = Val::from(0);
    let mut l_loop2 = Val::from(0);
    let mut l_wait_button_chk = Val::from(0);
    ctx.call(Function::Cutin, vec![Val::from("ein_soldier"), Val::from(2)])?;
    ctx.lines_as(
        "Lighthalzen Guide",
        args![
            "Welcome to Lighthalzen,",
            "the Corporation City-State.",
            "If you need any guidance",
            "around the city, feel free",
            "to ask me and I'll do my",
            "very best to help you."
        ],
    )?;
    l_loop1 = Val::from(1);
    'l1: loop {
        if !(l_loop1.clone().is_true()) {
            break 'l1;
        }
        'b1: {
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(
                    ctx,
                    &[Val::from("City Guide:Remove Marks from Mini-Map:Notice.:Cancel")],
                )?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1))
                    && !subject2.loosely_equals(&Val::from(2))
                    && !subject2.loosely_equals(&Val::from(3))
                    && !subject2.loosely_equals(&Val::from(4));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as(
                        "Lighthalzen Guide",
                        args![
                            "Please be aware that I'm",
                            "in charge of providing info",
                            "regarding the West District",
                            "of Lighthalzen. Now, please",
                            "select the location that you'd",
                            "like to learn more about."
                        ],
                    )?;
                    if l_compass_check.clone() == 0 {
                        ctx.next()?;
                        ctx.lines_as(
                            "Lighthalzen Guide",
                            args!["But before that,", "would you like me", "to mark locations", "on your Mini-Map?"],
                        )?;
                        ctx.next()?;
                        if Val::from(runtime::select_values(ctx, &[Val::from("Yes.:No.")])?) == 1 {
                            l_compass_check = Val::from(1);
                        }
                    }
                    l_loop2 = Val::from(1);
                    'l3: loop {
                        if !(l_loop2.clone().is_true()) {
                            break 'l3;
                        }
                        'b3: {
                            if l_wait_button_chk.clone() == 0 {
                                l_wait_button_chk = Val::from(1);
                            } else {
                                ctx.next()?;
                            }
                            'b4: {
                                let subject4 = Val::from(runtime::select_values(
                                    ctx,
                                    &[Val::from(
                                        "^FF0000Rekenber Corporation^000000:Train Station:Police Station:Bank:Hotel:Airport:Merchant Guild:Jewelry Shop:Weapon Shop:Departement Store:Cancel",
                                    )],
                                )?);
                                let mut matched4 = false;
                                let no_case4 = !subject4.loosely_equals(&Val::from(1))
                                    && !subject4.loosely_equals(&Val::from(2))
                                    && !subject4.loosely_equals(&Val::from(3))
                                    && !subject4.loosely_equals(&Val::from(4))
                                    && !subject4.loosely_equals(&Val::from(5))
                                    && !subject4.loosely_equals(&Val::from(6))
                                    && !subject4.loosely_equals(&Val::from(7))
                                    && !subject4.loosely_equals(&Val::from(8))
                                    && !subject4.loosely_equals(&Val::from(9))
                                    && !subject4.loosely_equals(&Val::from(10))
                                    && !subject4.loosely_equals(&Val::from(11));
                                if !matched4 && subject4.loosely_equals(&Val::from(1)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "Rekenber Corporation,",
                                            "the largest company in",
                                            "the Schwarzwald Republic,",
                                            "in located in northwestern",
                                            "Lighthalzen. You can't miss",
                                            "the headquarters building."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(102), Val::from(247), Val::from(2), Val::from(16711680)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(2)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "The Train Station is",
                                            "located in the center of",
                                            "the city, where we have",
                                            "a direct railroad to Einbroch."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(233), Val::from(164), Val::from(3), Val::from(16711935)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(3)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "Our Police Station is just",
                                            "north of the city's center.",
                                            "Please don't hesitate to report",
                                            "any suspicious persons and",
                                            "activity, or if you have any",
                                            "problems whatsoever."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(236), Val::from(276), Val::from(4), Val::from(10092543)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(4)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "The Bank is located",
                                            "just opposite to the",
                                            "Lighthalzen Police Station,",
                                            "which is a pretty good idea",
                                            "when I think about it, actually. ^FFFFFFspacer^000000"
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(198), Val::from(257), Val::from(5), Val::from(255)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(5)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "Our Hotel is located in",
                                            "the middle of the South Plaza.",
                                            "Due to its quality services and",
                                            "luxurious accomodations, this",
                                            "hotel is extremely popular."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(159), Val::from(133), Val::from(6), Val::from(65280)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(6)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "The Airport is to the far",
                                            "west of the Central Promenade.",
                                            "You can travel anywhere within",
                                            "the Schwarzwald Republic by",
                                            "riding on one of the Airships."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(267), Val::from(75), Val::from(7), Val::from(65280)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(7)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args!["The Merchant Guild can be", "found in the southwestern", "part of Lighthalzen."],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(74), Val::from(53), Val::from(8), Val::from(16751103)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(8)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args!["The Jewelry Shop is", "located just west of", "the South Plaza."],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(93), Val::from(110), Val::from(9), Val::from(16750848)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(9)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "The Weapon Shop is",
                                            "located at the end of",
                                            "the Central Promenade.",
                                            "It's at least worth a look",
                                            "if you're serious about",
                                            "adventuring around here."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(196), Val::from(46), Val::from(10), Val::from(3342387)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(10)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "The Department Store is",
                                            "located in the middle of",
                                            "Lighthalzen and is the biggest",
                                            "and most convenient place for",
                                            "shopping for almost everything."
                                        ],
                                    )?;
                                    if l_compass_check.clone().is_true() {
                                        ctx.call(
                                            Function::ViewPoint,
                                            vec![Val::from(1), Val::from(199), Val::from(163), Val::from(11), Val::from(16776960)],
                                        )?;
                                    }
                                    break 'b4;
                                }
                                if !matched4 && subject4.loosely_equals(&Val::from(11)) {
                                    matched4 = true;
                                }
                                if matched4 {
                                    ctx.lines_as(
                                        "Lighthalzen Guide",
                                        args![
                                            "Please ask me to ''Remove",
                                            "Marks from Mini-Map'' if you",
                                            "no longer wish to have the",
                                            "location marks displayed",
                                            "on your Mini-Map."
                                        ],
                                    )?;
                                    l_loop2 = Val::from(0);
                                }
                            }
                        }
                    }
                    break 'b2;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(102), Val::from(247), Val::from(2), Val::from(16711680)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(233), Val::from(164), Val::from(3), Val::from(16711935)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(236), Val::from(276), Val::from(4), Val::from(10092543)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(198), Val::from(257), Val::from(5), Val::from(255)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(159), Val::from(133), Val::from(6), Val::from(65280)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(267), Val::from(75), Val::from(7), Val::from(65280)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(74), Val::from(53), Val::from(8), Val::from(16751103)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(93), Val::from(110), Val::from(9), Val::from(16750848)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(196), Val::from(46), Val::from(10), Val::from(3342387)],
                    )?;
                    ctx.call(
                        Function::ViewPoint,
                        vec![Val::from(2), Val::from(199), Val::from(163), Val::from(11), Val::from(16776960)],
                    )?;
                    l_compass_check = Val::from(0);
                    break 'b2;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as(
                        "Lighthalzen Guide",
                        args![
                            "Advances in sorcery and",
                            "technology have allowed",
                            "us to update our information",
                            "system, enabling up to mark",
                            "locations on your Mini-Map",
                            "for easier navigation."
                        ],
                    )?;
                    ctx.next()?;
                    ctx.lines_as(
                        "Lighthalzen Guide",
                        args![
                            "Your Mini-Map is located",
                            "in the upper right corner",
                            "of the screen. If you can't",
                            "see it, press the Ctrl + Tab",
                            "keys or click the ''Map'' button in your Basic Info Window."
                        ],
                    )?;
                    ctx.next()?;
                    ctx.lines_as(
                        "Lighthalzen Guide",
                        args![
                            "On your Mini-Map,",
                            "click on the ''+'' and ''-''",
                            "symbols to zoom in and",
                            "our of your Mini-Map. We",
                            "hope you enjoy your travels",
                            "here in Lighthalzen."
                        ],
                    )?;
                    break 'b2;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(4)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as(
                        "Lighthalzen Guide",
                        args![
                            "Lighthalzen is divided",
                            "into the East and West",
                            "districts by a railroad that",
                            "runs right through the middle.",
                            "There are always guards on",
                            "watch to protect the peace."
                        ],
                    )?;
                    ctx.next()?;
                    ctx.lines_as(
                        "Lighthalzen Guide",
                        args![
                            "Please don't hesitate",
                            "to report any suspicious",
                            "activity or persons to us.",
                            "We hope that you enjoy",
                            "our fair city, adventurer."
                        ],
                    )?;
                    ctx.close_window()?;
                    l_loop1 = Val::from(0);
                }
            }
        }
    }
    ctx.call(Function::Cutin, vec![Val::from("ein_soldier"), Val::from(255)])?;
    return Err(Stop::End);
}

pub fn guide_lhz(ctx: &Ctx) -> Script {
    guide_lhz_body(ctx, Vec::new()).map(|_| ())
}
