// Generated by tools/scripts-import/convert_sdk2.py from npc/pre-re/guides/guides_gonryun.txt. Hand-maintained from here on: edit this file directly.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn kunlun_guide_gon_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    ctx.lines_as(
        "He Yuen Zhe",
        args![
            "Ni Hao!",
            "Welcome to Kunlun~",
            "Take a walk around and experience",
            "the ancient history and tradition",
            "of our breath taking city."
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "He Yuen Zhe",
        args![
            "I am responsible for helping you",
            "with any questions you may have.",
            "Please feel free to ask me anything."
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from(
                "Residence of the Chief:Tool Dealer:Weapon Dealer:Armor Dealer:Wine Maker",
            )],
        )?);
        let mut matched1 = false;
        let no_case1 = !subject1.loosely_equals(&Val::from(1))
            && !subject1.loosely_equals(&Val::from(2))
            && !subject1.loosely_equals(&Val::from(3))
            && !subject1.loosely_equals(&Val::from(4))
            && !subject1.loosely_equals(&Val::from(5));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.call(
                Function::ViewPoint,
                vec![Val::from(1), Val::from(109), Val::from(131), Val::from(0), Val::from(16724821)],
            )?;
            ctx.lines_as(
                "He Yuen Zhe",
                args![
                    "Please follow your minimap, and head over to the ^FF3355+^000000 mark.",
                    "There, you'll get to the residence of the Chief. Enjoy your stay in lovely Kunlun!",
                    "Xie Xie!"
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.call(
                Function::ViewPoint,
                vec![Val::from(1), Val::from(147), Val::from(82), Val::from(1), Val::from(13525760)],
            )?;
            ctx.lines_as(
                "He Yuen Zhe",
                args![
                    "Please follow your minimap, and head over to the ^CE6300+^000000 mark.",
                    "There, you'll get to the Tool Dealer. Enjoy your stay in lovely Kunlun!",
                    "Xie Xie!"
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.call(
                Function::ViewPoint,
                vec![Val::from(1), Val::from(174), Val::from(104), Val::from(2), Val::from(5635891)],
            )?;
            ctx.lines_as(
                "He Yuen Zhe",
                args![
                    "Please follow your minimap, and head over to the ^55FF33+^000000 mark.",
                    "There, you'll get to the Weapon Dealer. Enjoy your stay in lovely Kunlun!",
                    "Xie Xie!"
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(4)) {
            matched1 = true;
        }
        if matched1 {
            ctx.call(
                Function::ViewPoint,
                vec![Val::from(1), Val::from(173), Val::from(84), Val::from(3), Val::from(3364351)],
            )?;
            ctx.lines_as(
                "He Yuen Zhe",
                args![
                    "Please follow your minimap, and head over to the ^3355FF+^000000 mark.",
                    "There, you'll get to the Armor Dealer. Enjoy your stay in lovely Kunlun!",
                    "Xie Xie!"
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(5)) {
            matched1 = true;
        }
        if matched1 {
            ctx.call(
                Function::ViewPoint,
                vec![Val::from(1), Val::from(215), Val::from(114), Val::from(3), Val::from(13461961)],
            )?;
            ctx.lines_as(
                "He Yuen Zhe",
                args![
                    "Please follow your minimap, and head over to the ^CD69C9+^000000 mark.",
                    "There, you'll get to the Wine Maker. Enjoy your stay in lovely Kunlun!",
                    "Xie Xie!"
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn kunlun_guide_gon(ctx: &Ctx) -> Script {
    kunlun_guide_gon_body(ctx, Vec::new()).map(|_| ())
}
