// Generated by tools/scripts-import/convert_sdk2.py from npc/merchants/milk_trader.txt. Hand-maintained from here on: edit this file directly.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn milk_vendor_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    let mut l_bottles = Val::from(0);
    let mut l_total_cost = Val::from(0);
    let mut l_total_weight = Val::from(0);
    if ctx.call(Function::CheckWeight, vec![Val::from(1201), Val::from(1)])? == 0 {
        ctx.lines(args![
            "^3355FFJust a minute!",
            "I can't offer any of my",
            "services to you because",
            "you're carrying too much",
            "stuff. Put your extra items in",
            "Kafra Storage and come again~"
        ])?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as(
        "Milk Vendor",
        args![
            "Hey, hey...",
            "If you bring me",
            "1 Empty Bottle and",
            "15 Zeny, I'll exchange",
            "them for 1 Milk. How",
            "does that sound?"
        ],
    )?;
    ctx.next()?;
    if Val::from(runtime::select_values(ctx, &[Val::from("Exchange all empty bottles.:Cancel")])?) == 1 {
        if ctx.call(Function::CountItem, vec![Val::from(713)])?.number()? <= 0 {
            ctx.lines_as(
                "Milk Vendor",
                args![
                    "Hey...",
                    "You don't have",
                    "any Empty Bottles.",
                    "I can't really give you",
                    "this milk any other",
                    "way, you know..."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        l_bottles = ctx.call(Function::CountItem, vec![Val::from(713)])?;
        l_total_weight = (l_bottles.clone().try_mul(Val::from(50))?);
        l_total_cost = (l_bottles.clone().try_mul(Val::from(15))?);
        if runtime::op(&ctx.var("Zeny").get()?, "<", &l_total_cost.clone())?.is_true() {
            ctx.lines_as(
                "Milk Vendor",
                args![
                    "Oh, whoa~!",
                    "You don't have enough",
                    "zeny to exchange all",
                    "these Empty Bottles for",
                    "Milk. You need to have",
                    ((Val::from("at least ") + l_total_cost.clone()) + Val::from(" zeny."))
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if runtime::op(
            &(ctx.var("MaxWeight").get()?.try_sub(ctx.var("Weight").get()?)?),
            "<",
            &l_total_weight.clone(),
        )?
        .is_true()
        {
            ctx.lines_as(
                "Milk Vendor",
                args![
                    "Hmm...",
                    "Would you make",
                    "a little more room",
                    "in your inventory",
                    "before I give you",
                    "all of this milk?"
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        ctx.var("Zeny").set((ctx.var("Zeny").get()?.try_sub(l_total_cost.clone())?))?;
        ctx.call(Function::DelItem, vec![Val::from(713), l_bottles.clone()])?;
        ctx.call(Function::GetItem, vec![Val::from(519), l_bottles.clone()])?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.close_window()?;
    return Err(Stop::End);
}

pub fn milk_vendor(ctx: &Ctx) -> Script {
    milk_vendor_body(ctx, Vec::new()).map(|_| ())
}
