// Generated by tools/scripts-import/convert_sdk2.py from npc/merchants/novice_exchange.txt. Hand-maintained from here on: edit this file directly.
#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

use script_sdk_2::{Ctx, Function, Script, Stop, Val, args, runtime};

fn merchant_pron_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ((ctx.var("MaxWeight").get()?.try_sub(ctx.var("Weight").get()?)?).number()? < 6301
        || ctx.call(Function::CheckWeight, vec![Val::from(1201), Val::from(1)])? == 0)
    {
        ctx.lines_as(
            "Merchant",
            args![
                "Haha!",
                "What are you, superhuman?",
                "You're carrying so much stuff!",
                "You better put some of that",
                "into Kafra Storage~"
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as(
        "Merchant",
        args![
            "Good day!",
            "Have you collected any",
            "items like Shells or Fluff?",
            "What about Jellopies? Oh yeah,",
            "I need those for something."
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Merchant",
        args![
            "Of course, I won't ask you",
            "to give me that stuff for free. What about if I trade a Red Potion for 5 Shells, 10 Fluff,",
            "or 10 Jellopies?"
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from("Sure!:I think it's a rip-off!:No, thanks.")],
        )?);
        let mut matched1 = false;
        let no_case1 =
            !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2)) && !subject1.loosely_equals(&Val::from(3));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["So which item do", "you want to bring me?", "Shells, Fluffs, or Jellopies?"],
            )?;
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(ctx, &[Val::from("Shells:Jellopies:Fluff:Cancel")])?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1))
                    && !subject2.loosely_equals(&Val::from(2))
                    && !subject2.loosely_equals(&Val::from(3))
                    && !subject2.loosely_equals(&Val::from(4));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(935), Val::from(5)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(909), Val::from(10)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(914), Val::from(10)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(4)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as("Merchant", args!["Sure~", "No problem."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "A rip-off...?",
                    "If you check the market value",
                    "of the items being traded, I'm actually the one getting",
                    "ripped off here."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["Alright,", "no problem.", "But come back to me", "if you change your mind."],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn merchant_pron(ctx: &Ctx) -> Script {
    merchant_pron_body(ctx, Vec::new()).map(|_| ())
}

fn merchant_morocc_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ((ctx.var("MaxWeight").get()?.try_sub(ctx.var("Weight").get()?)?).number()? < 6301
        || ctx.call(Function::CheckWeight, vec![Val::from(1201), Val::from(1)])? == 0)
    {
        ctx.lines_as(
            "Merchant",
            args![
                "Haha!",
                "What are you, superhuman?",
                "You're carrying so much stuff!",
                "You better put some of that",
                "into Kafra Storage~"
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as(
        "Merchant",
        args![
            "Good day!",
            "Have you collected any",
            "Shells or Feathers of Bird?",
            "What about Jellopies? Oh yeah,",
            "I need those for something."
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Merchant",
        args![
            "Of course, I won't ask you",
            "to give me that stuff for free. What about if I trade a Red Potion for 5 Shells, 7 Feathers of Bird",
            "or 10 Jellopies?"
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from("Sure!:I think it's a rip-off!:No, thanks.")],
        )?);
        let mut matched1 = false;
        let no_case1 =
            !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2)) && !subject1.loosely_equals(&Val::from(3));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "So which item do",
                    "you want to bring me?",
                    "Shells, Feathers of Birds,",
                    "or Jellopies?"
                ],
            )?;
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(
                    ctx,
                    &[Val::from("Shells:Feathers of Birds:Jellopies:Cancel")],
                )?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1))
                    && !subject2.loosely_equals(&Val::from(2))
                    && !subject2.loosely_equals(&Val::from(3))
                    && !subject2.loosely_equals(&Val::from(4));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(935), Val::from(5)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(916), Val::from(7)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(909), Val::from(10)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(4)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as("Merchant", args!["Sure~", "No problem."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "A rip-off...?",
                    "If you check the market value",
                    "of the items being traded, I'm actually the one getting",
                    "ripped off here."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["Alright,", "no problem.", "But come back to me", "if you change your mind."],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn merchant_morocc(ctx: &Ctx) -> Script {
    merchant_morocc_body(ctx, Vec::new()).map(|_| ())
}

fn merchant_pay_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ((ctx.var("MaxWeight").get()?.try_sub(ctx.var("Weight").get()?)?).number()? < 6301
        || ctx.call(Function::CheckWeight, vec![Val::from(1201), Val::from(1)])? == 0)
    {
        ctx.lines_as(
            "Merchant",
            args![
                "Haha!",
                "What are you, superhuman?",
                "You're carrying so much stuff!",
                "You better put some of that",
                "into Kafra Storage~"
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as(
        "Merchant",
        args![
            "Good day!",
            "Have you collected",
            "items like Tree Roots?",
            "What about Jellopies? Oh yeah,",
            "I need those for something."
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Merchant",
        args![
            "Of course, I won't ask you",
            "to give me that stuff for free. What about if I trade a Red Potion for 6 Tree Roots or 10 Jellopies?"
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from("Sure!:I think it's a rip-off!:No, thanks.")],
        )?);
        let mut matched1 = false;
        let no_case1 =
            !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2)) && !subject1.loosely_equals(&Val::from(3));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["So which item do", "you want to bring me?", "Tree Roots, or Jellopies?"],
            )?;
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(ctx, &[Val::from("Tree Roots:Jellopies:Cancel")])?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1))
                    && !subject2.loosely_equals(&Val::from(2))
                    && !subject2.loosely_equals(&Val::from(3));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(902), Val::from(6)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(909), Val::from(10)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as("Merchant", args!["Sure~", "No problem."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "A rip-off...?",
                    "If you check the market value",
                    "of the items being traded, I'm actually the one getting",
                    "ripped off here."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["Alright,", "no problem.", "But come back to me", "if you change your mind."],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn merchant_pay(ctx: &Ctx) -> Script {
    merchant_pay_body(ctx, Vec::new()).map(|_| ())
}

fn merchant_alde_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ((ctx.var("MaxWeight").get()?.try_sub(ctx.var("Weight").get()?)?).number()? < 6301
        || ctx.call(Function::CheckWeight, vec![Val::from(1201), Val::from(1)])? == 0)
    {
        ctx.lines_as(
            "Merchant",
            args![
                "Haha!",
                "What are you, superhuman?",
                "You're carrying so much stuff!",
                "You better put some of that",
                "into Kafra Storage~"
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as(
        "Merchant",
        args![
            "Good day!",
            "Have you collected any",
            "Worm Peelings or Feather of Birds?",
            "How about Jellopies? Oh yeah,",
            "I need those for something."
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Merchant",
        args![
            "Of course, I won't ask you",
            "to give me that stuff for free. What about if I trade a Red Potion for 1 Worm Peeling, 7 Feather of Birds, or 10 Jellopies?"
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from("Sure!:I think it's a rip-off!:No, thanks.")],
        )?);
        let mut matched1 = false;
        let no_case1 =
            !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2)) && !subject1.loosely_equals(&Val::from(3));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "So which item do",
                    "you want to bring me?",
                    "Feathers of Birds?",
                    "Worm Peelings?",
                    "Or Jellopies?"
                ],
            )?;
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(
                    ctx,
                    &[Val::from("Worm Peelings:Feathers of Birds:Jellopies:Cancel")],
                )?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1))
                    && !subject2.loosely_equals(&Val::from(2))
                    && !subject2.loosely_equals(&Val::from(3))
                    && !subject2.loosely_equals(&Val::from(4));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(955), Val::from(1)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(916), Val::from(7)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(909), Val::from(10)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(4)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as("Merchant", args!["Sure~", "No problem."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "A rip-off...?",
                    "If you check the market value",
                    "of the items being traded, I'm actually the one getting",
                    "ripped off here."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["Alright,", "no problem.", "But come back to me", "if you change your mind."],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn merchant_alde(ctx: &Ctx) -> Script {
    merchant_alde_body(ctx, Vec::new()).map(|_| ())
}

fn merchant_geff_body(ctx: &Ctx, args: Vec<Val>) -> Result<Val, Stop> {
    if ((ctx.var("MaxWeight").get()?.try_sub(ctx.var("Weight").get()?)?).number()? < 6301
        || ctx.call(Function::CheckWeight, vec![Val::from(1201), Val::from(1)])? == 0)
    {
        ctx.lines_as(
            "Merchant",
            args![
                "Haha!",
                "What are you, superhuman?",
                "You're carrying so much stuff!",
                "You better put some of that",
                "into Kafra Storage~"
            ],
        )?;
        ctx.close_window()?;
        return Err(Stop::End);
    }
    ctx.lines_as(
        "Merchant",
        args![
            "Good day!",
            "Have you collected any",
            "items like Shells or Chrysalises?",
            "What about Jellopies? Oh yeah,",
            "I need those for something."
        ],
    )?;
    ctx.next()?;
    ctx.lines_as(
        "Merchant",
        args![
            "Of course, I won't ask you",
            "to give me that stuff for free. What about if I trade a Red Potion for 5 Shells or 6 Chrysalises, or 10 Jellopies?"
        ],
    )?;
    ctx.next()?;
    'b1: {
        let subject1 = Val::from(runtime::select_values(
            ctx,
            &[Val::from("Sure!:I think it's a rip-off!:No, thanks.")],
        )?);
        let mut matched1 = false;
        let no_case1 =
            !subject1.loosely_equals(&Val::from(1)) && !subject1.loosely_equals(&Val::from(2)) && !subject1.loosely_equals(&Val::from(3));
        if !matched1 && subject1.loosely_equals(&Val::from(1)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["So which item do", "you want to bring me?", "Shells, Chrysalises, or Jellopies?"],
            )?;
            ctx.next()?;
            'b2: {
                let subject2 = Val::from(runtime::select_values(
                    ctx,
                    &[Val::from("Shells:Chrysalises:Jellopies:Cancel")],
                )?);
                let mut matched2 = false;
                let no_case2 = !subject2.loosely_equals(&Val::from(1))
                    && !subject2.loosely_equals(&Val::from(2))
                    && !subject2.loosely_equals(&Val::from(3))
                    && !subject2.loosely_equals(&Val::from(4));
                if !matched2 && subject2.loosely_equals(&Val::from(1)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(935), Val::from(5)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(2)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(915), Val::from(6)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(3)) {
                    matched2 = true;
                }
                if matched2 {
                    shared::merchants_novice_exchange::f_potexchange(ctx, vec![Val::from(909), Val::from(10)])?;
                }
                if !matched2 && subject2.loosely_equals(&Val::from(4)) {
                    matched2 = true;
                }
                if matched2 {
                    ctx.lines_as("Merchant", args!["Sure~", "No problem."])?;
                    ctx.close_window()?;
                    return Err(Stop::End);
                }
            }
        }
        if !matched1 && subject1.loosely_equals(&Val::from(2)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args![
                    "A rip-off...?",
                    "If you check the market value",
                    "of the items being traded, I'm actually the one getting",
                    "ripped off here."
                ],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
        if !matched1 && subject1.loosely_equals(&Val::from(3)) {
            matched1 = true;
        }
        if matched1 {
            ctx.lines_as(
                "Merchant",
                args!["Alright,", "no problem.", "But come back to me", "if you change your mind."],
            )?;
            ctx.close_window()?;
            return Err(Stop::End);
        }
    }
    Ok(Val::from(0))
}

pub fn merchant_geff(ctx: &Ctx) -> Script {
    merchant_geff_body(ctx, Vec::new()).map(|_| ())
}
