#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;

script_sdk_2::script_module! {
    npcs {
        "#Colonel1" => colonel1,
        "#Colonel2" => colonel2,
        "#buki_vol" => buki_vol,
        "#sita_vol" => sita_vol,
        "#totcamp" => totcamp,
        "#tov_1" => tov_1,
        "#tov_2" => tov_2,
        "#vol_study1" => vol_study1,
        "#volbq" => volbq,
        "#volroom" => volroom,
        "#whoau" => whoau,
        "????#sch1" => sch1,
        "????#sch2" => sch2,
        "????#sch3" => sch3,
        "Aitra#vol" => aitra_vol,
        "Arunafeltz Figure" => arunafeltz_figure,
        "Arunafeltz Figure#sch" => arunafeltz_figure_sch,
        "Bard Trigger#sch" => bard_trigger_sch,
        "Bard#sch" => bard_sch,
        "Bartender#ve" => bartender_ve,
        "Bookshelf#vol" => bookshelf_vol,
        "Camel#camelcc1" => camel_camelcc1,
        "Cheerful Dancer#sch1" => cheerful_dancer_sch1,
        "Cheerful Dancer#sch2" => cheerful_dancer_sch2,
        "Cheerful Dancer#sch3" => cheerful_dancer_sch3,
        "Colonel Vito#1" => colonel_vito_1,
        "Colonel Vito#2" => colonel_vito_2,
        "Colonel Vito#3" => colonel_vito_3,
        "Control Panel#vol" => control_panel_vol,
        "Corporate Figure" => corporate_figure,
        "Corporate Figure#sch" => corporate_figure_sch,
        "Dance Instructor#sch" => dance_instructor_sch,
        "Drawer#vol1" => drawer_vol1,
        "Drawer#vol3" => drawer_vol3,
        "Drunken Lady#1" => drunken_lady_1,
        "Drunken Lady#2" => drunken_lady_2,
        "Drunken Man#vol" => drunken_man_vol,
        "Dummy#1" => dummy_1,
        "Employee#sch" => employee_sch,
        "Extra Story Patch" => extra_story_patch,
        "Factory Manager" => factory_manager,
        "Factory Worker#ve1" => factory_worker_ve1,
        "Factory Worker#ve2" => factory_worker_ve2,
        "Female Customer#ve1" => female_customer_ve1,
        "Female Follower#vol" => female_follower_vol,
        "Flower Vase#vol" => flower_vase_vol,
        "Goddess Statue#vol1" => goddess_statue_vol1,
        "Guant Prisoner#sch" => guant_prisoner_sch,
        "Guard#goto" => guard_goto,
        "Guard#vol" => guard_vol,
        "Guardian#vol_7" => guardian_vol_7,
        "High Priest#vol" => high_priest_vol,
        "Hot Land Surface#1" => hot_land_surface_1,
        "Hot Land Surface#2" => hot_land_surface_2,
        "Hot Land Surface#3" => hot_land_surface_3,
        "Hotel Manager#sch" => hotel_manager_sch,
        "Ivory" => ivory,
        "Jesse#sch" => jesse_sch,
        "Kid#camelcamel" => kid_camelcamel,
        "Kid#sch" => kid_sch,
        "Ladder#vol1" => ladder_vol1,
        "Little Curdie" => little_curdie,
        "Lockenlock" => lockenlock,
        "Male Customer#ve2" => male_customer_ve2,
        "Mature Looking Dancer#s1" => mature_looking_dancer_s1,
        "Mature Looking Dancer#s2" => mature_looking_dancer_s2,
        "Mature Looking Dancer#s3" => mature_looking_dancer_s3,
        "Prison Ward#sch" => prison_ward_sch,
        "Public Security Officer" => public_security_officer,
        "Rachel Guard#vol1" => rachel_guard_vol1,
        "Rachel Guard#vol1_1" => rachel_guard_vol1_1,
        "Rachel Guard#vol2" => rachel_guard_vol2,
        "Rachel Guard#vol2_1" => rachel_guard_vol2_1,
        "Sahedi#vol" => sahedi_vol,
        "Saraman" => saraman,
        "Silk Sand Camel" => silk_sand_camel,
        "Soldier#vol1" => soldier_vol1,
        "Soldier#vol2" => soldier_vol2,
        "Strange Old Man#ve" => strange_old_man_ve,
        "Thin-Faced Bard#sch" => thin_faced_bard_sch,
        "Thor Volcano Soldier#vo1" => thor_volcano_soldier_vo1,
        "Thor Volcano Soldier#vo2" => thor_volcano_soldier_vo2,
        "Thor Volcano Soldier#vo3" => thor_volcano_soldier_vo3,
        "Thor Volcano Soldier#vo4" => thor_volcano_soldier_vo4,
        "Thor Volcano Soldier#vo5" => thor_volcano_soldier_vo5,
        "Thor Volcano Soldier#vo6" => thor_volcano_soldier_vo6,
        "Thor Volcano Soldier#vo7" => thor_volcano_soldier_vo7,
        "Thor Volcano Soldier#vo8" => thor_volcano_soldier_vo8,
        "Thor Volcano Soldier#vo9" => thor_volcano_soldier_vo9,
        "Towner#vol" => towner_vol,
        "Upset Looking Bard#sch" => upset_looking_bard_sch,
        "Wall Closet#vol" => wall_closet_vol,
        "WincingOldMan_veins" => wincingoldman_veins,
        "Young Dancer#sch1" => young_dancer_sch1,
        "Young Dancer#sch2" => young_dancer_sch2,
        "Young Dancer#sch3" => young_dancer_sch3,
        "Young Man#sch" => young_man_sch,
        "Young Man#sch2" => young_man_sch2,
        "Young Town Native" => young_town_native,
        "Young Woman#sch" => young_woman_sch,
        "path_vol1" => path_vol1,
        "path_vol1#2" => path_vol1_2,
        "path_vol1#3" => path_vol1_3,
        "vol_time" => vol_time,
        "vol_time2" => vol_time2,
    }
    events {
        "#Colonel1::OnTouch" => colonel1_ontouch,
        "#Colonel2::OnTouch" => colonel2_ontouch,
        "#buki_vol::OnTouch" => buki_vol_ontouch,
        "#sita_vol::OnTouch" => sita_vol_ontouch,
        "#totcamp::OnTouch_" => totcamp_ontouch,
        "#tov_1::OnTouch_" => tov_1_ontouch,
        "#tov_2::OnTouch_" => tov_2_ontouch,
        "#vol_study1::OnTouch" => vol_study1_ontouch,
        "#volbq::OnTouch" => volbq_ontouch,
        "#volroom::OnTouch" => volroom_ontouch,
        "#whoau::OnTouch_" => whoau_ontouch,
        "????#sch1::OnInit" => sch1_oninit,
        "????#sch2::OnInit" => sch2_oninit,
        "????#sch3::OnInit" => sch3_oninit,
        "Aitra#vol::OnInit" => aitra_vol_oninit,
        "Arunafeltz Figure::OnInit" => arunafeltz_figure_oninit,
        "Bard Trigger#sch::OnTouch" => bard_trigger_sch_ontouch,
        "Colonel Vito#1::OnInit" => colonel_vito_1_oninit,
        "Colonel Vito#2::OnInit" => colonel_vito_2_oninit,
        "Corporate Figure::OnInit" => corporate_figure_oninit,
        "Hotel Manager#sch::OnTouch" => hotel_manager_sch_ontouch,
        "Jesse#sch::OnInit" => jesse_sch_oninit,
        "Rachel Guard#vol1::OnInit" => rachel_guard_vol1_oninit,
        "Rachel Guard#vol1::OnTouch" => rachel_guard_vol1_ontouch,
        "Rachel Guard#vol1_1::OnInit" => rachel_guard_vol1_1_oninit,
        "Rachel Guard#vol2::OnInit" => rachel_guard_vol2_oninit,
        "Rachel Guard#vol2::OnTouch" => rachel_guard_vol2_ontouch,
        "Rachel Guard#vol2_1::OnInit" => rachel_guard_vol2_1_oninit,
        "path_vol1#2::OnTouch" => path_vol1_2_ontouch,
        "path_vol1#3::OnTouch" => path_vol1_3_ontouch,
        "path_vol1::OnTouch" => path_vol1_ontouch,
        "vol_time2::OnEnable" => vol_time2_onenable,
        "vol_time2::OnInit" => vol_time2_oninit,
        "vol_time2::OnTimer30000" => vol_time2_ontimer30000,
        "vol_time::OnEnable" => vol_time_onenable,
        "vol_time::OnInit" => vol_time_oninit,
        "vol_time::OnTimer10000" => vol_time_ontimer10000,
        "vol_time::OnTimer15000" => vol_time_ontimer15000,
        "vol_time::OnTimer20000" => vol_time_ontimer20000,
        "vol_time::OnTimer30000" => vol_time_ontimer30000,
        "vol_time::OnTimer35000" => vol_time_ontimer35000,
        "vol_time::OnTimer40000" => vol_time_ontimer40000,
        "vol_time::OnTimer45000" => vol_time_ontimer45000,
        "vol_time::OnTimer50000" => vol_time_ontimer50000,
        "vol_time::OnTimer55000" => vol_time_ontimer55000,
    }
}
