#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;

script_sdk_2::script_module! {
    npcs {
        "2f_callmon_pattern" => s_2f_callmon_pattern,
        "2f_callmon_pattern_c" => s_2f_callmon_pattern_c,
        "Ancient Hero's Soul#1F" => ancient_hero_s_soul_1f,
        "Ancient Hero's Soul#2F" => ancient_hero_s_soul_2f,
        "Bobbing Torch#SS" => bobbing_torch_ss,
        "Friar Patrick#edq" => friar_patrick_edq,
        "Grave of Baphomet#edq" => grave_of_baphomet_edq,
        "Gravestone#" => gravestone,
        "Gravestone#SS1" => gravestone_ss1,
        "Gravestone#SS2" => gravestone_ss2,
        "Magical Seal#SS" => magical_seal_ss,
        "Rust Blackhand#edq" => rust_blackhand_edq,
        "The Main Altar#ss" => the_main_altar_ss,
        "control_baphomet" => control_baphomet,
        "ins_1f_spawn_mobs" => ins_1f_spawn_mobs,
        "ins_2f_enter" => ins_2f_enter,
        "ins_2f_enter_broad" => ins_2f_enter_broad,
        "ins_2f_hero_broad" => ins_2f_hero_broad,
        "ins_2f_hero_broad2" => ins_2f_hero_broad2,
        "ins_2f_hero_pattern" => ins_2f_hero_pattern,
        "ins_2f_hero_pattern_c" => ins_2f_hero_pattern_c,
        "ins_bapho_to_2f" => ins_bapho_to_2f,
        "ins_baphomet_1f_timer" => ins_baphomet_1f_timer,
        "ins_baphomet_lotto" => ins_baphomet_lotto,
        "ins_baphomet_lotto2" => ins_baphomet_lotto2,
        "ins_baphomet_lotto3" => ins_baphomet_lotto3,
        "slave_down" => slave_down,
        "slave_left" => slave_left,
        "slave_right" => slave_right,
    }
    events {
        "2f_callmon_pattern::OnDisable" => s_2f_callmon_pattern_ondisable,
        "2f_callmon_pattern::OnEnable" => s_2f_callmon_pattern_onenable,
        "2f_callmon_pattern::OnInstanceInit" => s_2f_callmon_pattern_oninstanceinit,
        "2f_callmon_pattern::OnTimer300000" => s_2f_callmon_pattern_ontimer300000,
        "2f_callmon_pattern_c::OnDisable" => s_2f_callmon_pattern_c_ondisable,
        "2f_callmon_pattern_c::OnEnable" => s_2f_callmon_pattern_c_onenable,
        "2f_callmon_pattern_c::OnInstanceInit" => s_2f_callmon_pattern_c_oninstanceinit,
        "2f_callmon_pattern_c::OnTimer3600000" => s_2f_callmon_pattern_c_ontimer3600000,
        "2f_callmon_pattern_c::Ongo" => s_2f_callmon_pattern_c_ongo,
        "Ancient Hero's Soul#1F::OnInstanceInit" => ancient_hero_s_soul_1f_oninstanceinit,
        "Ancient Hero's Soul#2F::OnInstanceInit" => ancient_hero_s_soul_2f_oninstanceinit,
        "Bobbing Torch#SS::OnInstanceInit" => bobbing_torch_ss_oninstanceinit,
        "Gravestone#::OnInstanceInit" => gravestone_oninstanceinit,
        "Gravestone#::OnTouch" => gravestone_ontouch,
        "Magical Seal#SS::OnInstanceInit" => magical_seal_ss_oninstanceinit,
        "control_baphomet::OnDisable" => control_baphomet_ondisable,
        "control_baphomet::OnEnable" => control_baphomet_onenable,
        "control_baphomet::OnInstanceInit" => control_baphomet_oninstanceinit,
        "control_baphomet::OnMyMobDead" => control_baphomet_onmymobdead,
        "ins_1f_spawn_mobs::OnInstanceInit" => ins_1f_spawn_mobs_oninstanceinit,
        "ins_2f_enter::OnTouch_" => ins_2f_enter_ontouch,
        "ins_2f_enter_broad::OnDisable" => ins_2f_enter_broad_ondisable,
        "ins_2f_enter_broad::OnEnable" => ins_2f_enter_broad_onenable,
        "ins_2f_enter_broad::OnInstanceInit" => ins_2f_enter_broad_oninstanceinit,
        "ins_2f_enter_broad::OnTimer10000" => ins_2f_enter_broad_ontimer10000,
        "ins_2f_enter_broad::OnTimer13000" => ins_2f_enter_broad_ontimer13000,
        "ins_2f_enter_broad::OnTimer16000" => ins_2f_enter_broad_ontimer16000,
        "ins_2f_enter_broad::OnTimer18000" => ins_2f_enter_broad_ontimer18000,
        "ins_2f_hero_broad2::OnDisable" => ins_2f_hero_broad2_ondisable,
        "ins_2f_hero_broad2::OnEnable" => ins_2f_hero_broad2_onenable,
        "ins_2f_hero_broad2::OnInstanceInit" => ins_2f_hero_broad2_oninstanceinit,
        "ins_2f_hero_broad2::OnTimer11000" => ins_2f_hero_broad2_ontimer11000,
        "ins_2f_hero_broad2::OnTimer13000" => ins_2f_hero_broad2_ontimer13000,
        "ins_2f_hero_broad2::OnTimer16000" => ins_2f_hero_broad2_ontimer16000,
        "ins_2f_hero_broad2::OnTimer19000" => ins_2f_hero_broad2_ontimer19000,
        "ins_2f_hero_broad2::OnTimer22000" => ins_2f_hero_broad2_ontimer22000,
        "ins_2f_hero_broad2::OnTimer26000" => ins_2f_hero_broad2_ontimer26000,
        "ins_2f_hero_broad2::OnTimer8000" => ins_2f_hero_broad2_ontimer8000,
        "ins_2f_hero_broad::OnDisable" => ins_2f_hero_broad_ondisable,
        "ins_2f_hero_broad::OnEnable" => ins_2f_hero_broad_onenable,
        "ins_2f_hero_broad::OnTimer12000" => ins_2f_hero_broad_ontimer12000,
        "ins_2f_hero_broad::OnTimer15000" => ins_2f_hero_broad_ontimer15000,
        "ins_2f_hero_broad::OnTimer17000" => ins_2f_hero_broad_ontimer17000,
        "ins_2f_hero_broad::OnTimer3000" => ins_2f_hero_broad_ontimer3000,
        "ins_2f_hero_broad::OnTimer6000" => ins_2f_hero_broad_ontimer6000,
        "ins_2f_hero_broad::OnTimer9000" => ins_2f_hero_broad_ontimer9000,
        "ins_2f_hero_pattern::OnDisable" => ins_2f_hero_pattern_ondisable,
        "ins_2f_hero_pattern::OnEnable" => ins_2f_hero_pattern_onenable,
        "ins_2f_hero_pattern::OnInstanceInit" => ins_2f_hero_pattern_oninstanceinit,
        "ins_2f_hero_pattern::OnTimer70000" => ins_2f_hero_pattern_ontimer70000,
        "ins_2f_hero_pattern_c::OnDisable" => ins_2f_hero_pattern_c_ondisable,
        "ins_2f_hero_pattern_c::OnEnable" => ins_2f_hero_pattern_c_onenable,
        "ins_2f_hero_pattern_c::OnInstanceInit" => ins_2f_hero_pattern_c_oninstanceinit,
        "ins_2f_hero_pattern_c::OnTimer3600000" => ins_2f_hero_pattern_c_ontimer3600000,
        "ins_2f_hero_pattern_c::OnTimer3605000" => ins_2f_hero_pattern_c_ontimer3605000,
        "ins_2f_hero_pattern_c::Ongo" => ins_2f_hero_pattern_c_ongo,
        "ins_bapho_to_2f::OnInstanceInit" => ins_bapho_to_2f_oninstanceinit,
        "ins_bapho_to_2f::OnTouch" => ins_bapho_to_2f_ontouch,
        "ins_baphomet_1f_timer::OnDisable" => ins_baphomet_1f_timer_ondisable,
        "ins_baphomet_1f_timer::OnEnable" => ins_baphomet_1f_timer_onenable,
        "ins_baphomet_1f_timer::OnInstanceInit" => ins_baphomet_1f_timer_oninstanceinit,
        "ins_baphomet_1f_timer::OnTimer1800000" => ins_baphomet_1f_timer_ontimer1800000,
        "ins_baphomet_1f_timer::OnTimer2400000" => ins_baphomet_1f_timer_ontimer2400000,
        "ins_baphomet_1f_timer::OnTimer3000000" => ins_baphomet_1f_timer_ontimer3000000,
        "ins_baphomet_1f_timer::OnTimer3050000" => ins_baphomet_1f_timer_ontimer3050000,
        "ins_baphomet_1f_timer::OnTimer3100000" => ins_baphomet_1f_timer_ontimer3100000,
        "ins_baphomet_1f_timer::OnTimer3500000" => ins_baphomet_1f_timer_ontimer3500000,
        "ins_baphomet_lotto2::OnEnable" => ins_baphomet_lotto2_onenable,
        "ins_baphomet_lotto3::OnDisable" => ins_baphomet_lotto3_ondisable,
        "ins_baphomet_lotto3::OnEnable" => ins_baphomet_lotto3_onenable,
        "ins_baphomet_lotto3::OnMyMobDead" => ins_baphomet_lotto3_onmymobdead,
        "ins_baphomet_lotto::OnInstanceInit" => ins_baphomet_lotto_oninstanceinit,
        "slave_down::OnTouch_" => slave_down_ontouch,
        "slave_left::OnTouch_" => slave_left_ontouch,
        "slave_right::OnTouch_" => slave_right_ontouch,
    }
}
