#![allow(
    unused_imports,
    unused_labels,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_variables,
    unreachable_code
)]

mod common;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;

pub use part_01::*;
pub use part_02::*;
pub use part_03::*;
pub use part_04::*;
pub use part_05::*;
pub use part_06::*;
pub use part_07::*;
pub use part_08::*;
pub use part_09::*;

script_sdk_2::script_module! {
    npcs {
        "#book_russia" => book_russia,
        "#bowl" => bowl,
        "#findship" => findship,
        "#mos_sq" => mos_sq,
        "#nowinterplz" => nowinterplz,
        "#rus27" => rus27,
        "#swan_inn" => swan_inn,
        "1#rus27" => s_1_rus27,
        "A Lady#mos10" => a_lady_mos10,
        "A Lady#mos11" => a_lady_mos11,
        "A Lady#mos5" => a_lady_mos5,
        "A Lady#mos6" => a_lady_mos6,
        "A Little Boy#mos16" => a_little_boy_mos16,
        "A Little Boy#mos4" => a_little_boy_mos4,
        "A Little Boy#mos7" => a_little_boy_mos7,
        "A Little Girl#mos1" => a_little_girl_mos1,
        "A Man#mos13" => a_man_mos13,
        "A Man#mos15" => a_man_mos15,
        "A Man#mos9" => a_man_mos9,
        "A Middle-Aged Man#mos3" => a_middle_aged_man_mos3,
        "A Young Man#mos12" => a_young_man_mos12,
        "A Young Man#mos14" => a_young_man_mos14,
        "A Young Man#mos2" => a_young_man_mos2,
        "A Young Man#mos8" => a_young_man_mos8,
        "Acorn Dealer#mos" => acorn_dealer_mos,
        "Aged Stranger#npc" => aged_stranger_npc,
        "Anna#mos" => anna_mos,
        "Baba Yaga#rus32" => baba_yaga_rus32,
        "Baba Yaga, the Horrible" => baba_yaga_the_horrible,
        "Baehideun#main" => baehideun_main,
        "Bed#mos1" => bed_mos1,
        "Berbayeff#npc" => berbayeff_npc,
        "Big Squirrel#mos" => big_squirrel_mos,
        "Broom Grandma#rus44" => broom_grandma_rus44,
        "Bubbling Swamp#mos1" => bubbling_swamp_mos1,
        "Bulletin Board#npc" => bulletin_board_npc,
        "Caution#07rus" => caution_07rus,
        "Cow#rus33" => cow_rus33,
        "Csar Alexsay III#npc" => csar_alexsay_iii_npc,
        "Dirty Wall#rus39" => dirty_wall_rus39,
        "Find#ship" => find_ship,
        "Fire pot#mos" => fire_pot_mos,
        "Gallina#mos" => gallina_mos,
        "Ghost Tree#rus45" => ghost_tree_rus45,
        "Gray Wolf#rus03" => gray_wolf_rus03,
        "House Ghost Jar#rus43" => house_ghost_jar_rus43,
        "Irina#edq" => irina_edq,
        "Koshei GlobalVar#admin" => koshei_globalvar_admin,
        "Koshei#rus47" => koshei_rus47,
        "Landlord#mos" => landlord_mos,
        "Larissa#mos_01" => larissa_mos_01,
        "Little Boy#rus09" => little_boy_rus09,
        "Lusalka#07russai_22" => lusalka_07russai_22,
        "Lusalka#rus23" => lusalka_rus23,
        "Marozka#rus31" => marozka_rus31,
        "Mikhail#mos" => mikhail_mos,
        "Momotoro Publisher#rus42" => momotoro_publisher_rus42,
        "Morocc Villager#rus25" => morocc_villager_rus25,
        "Mr. Ibanoff#npc" => mr_ibanoff_npc,
        "Mr. Ibanoff#npc2" => mr_ibanoff_npc2,
        "Mysterious Stone#rus02" => mysterious_stone_rus02,
        "Noisy Coffin#rus36" => noisy_coffin_rus36,
        "Occult Apple Tree#rus29" => occult_apple_tree_rus29,
        "Old Bed#rus38" => old_bed_rus38,
        "Old Treasure Box#rus37" => old_treasure_box_rus37,
        "Old_Wooden_Box#rus40" => old_wooden_box_rus40,
        "Opened Treasure Chest#41" => opened_treasure_chest_41,
        "PTree#rusmain" => ptree_rusmain,
        "Pile of skeletons#Magic" => pile_of_skeletons_magic,
        "Prime Minister Dmitree#m" => prime_minister_dmitree_m,
        "Pub Owner#mos" => pub_owner_mos,
        "Ryubaba#rus08" => ryubaba_rus08,
        "Sage#rus01" => sage_rus01,
        "Shepherdess#rus10" => shepherdess_rus10,
        "Soldier#rus26" => soldier_rus26,
        "Stone Furnace#rus28" => stone_furnace_rus28,
        "The Blacksmith#rus06" => the_blacksmith_rus06,
        "Vassili Grandpapa#rus07" => vassili_grandpapa_rus07,
        "Victor#mos" => victor_mos,
        "Wall#rus04" => wall_rus04,
        "Wanderer#rus24" => wanderer_rus24,
        "Worried Mother#rus19" => worried_mother_rus19,
        "mos_rus#main" => mos_rus_main,
        "rudder#ship" => rudder_ship,
    }
    events {
        "#findship::OnEnable" => findship_onenable,
        "#findship::OnInit" => findship_oninit,
        "#findship::OnTimer300000" => findship_ontimer300000,
        "#findship::OnTouch" => findship_ontouch,
        "#rus27::OnTouch_" => rus27_ontouch,
        "#swan_inn::OnTouch" => swan_inn_ontouch,
        "1#rus27::OnEnable" => s_1_rus27_onenable,
        "1#rus27::OnInit" => s_1_rus27_oninit,
        "1#rus27::OnTimer30000" => s_1_rus27_ontimer30000,
        "1#rus27::OnTouch_" => s_1_rus27_ontouch,
        "Baba Yaga#rus32::OnDisable" => baba_yaga_rus32_ondisable,
        "Baba Yaga#rus32::OnMyMobDead" => baba_yaga_rus32_onmymobdead,
        "Baba Yaga#rus32::OnTimer180000" => baba_yaga_rus32_ontimer180000,
        "Baba Yaga, the Horrible::OnTouch" => baba_yaga_the_horrible_ontouch,
        "Baehideun#main::OnDisable" => baehideun_main_ondisable,
        "Baehideun#main::OnEnable" => baehideun_main_onenable,
        "Baehideun#main::OnInit" => baehideun_main_oninit,
        "Baehideun#main::OnMyMobDead" => baehideun_main_onmymobdead,
        "Baehideun#main::OnTimer300000" => baehideun_main_ontimer300000,
        "Big Squirrel#mos::OnTouch" => big_squirrel_mos_ontouch,
        "Cow#rus33::OnTouch_" => cow_rus33_ontouch,
        "Csar Alexsay III#npc::OnTouch" => csar_alexsay_iii_npc_ontouch,
        "Find#ship::OnTouch" => find_ship_ontouch,
        "Gray Wolf#rus03::OnDisable" => gray_wolf_rus03_ondisable,
        "Gray Wolf#rus03::OnEnable" => gray_wolf_rus03_onenable,
        "Gray Wolf#rus03::OnInit" => gray_wolf_rus03_oninit,
        "Gray Wolf#rus03::OnTimer120000" => gray_wolf_rus03_ontimer120000,
        "House Ghost Jar#rus43::OnDisable" => house_ghost_jar_rus43_ondisable,
        "House Ghost Jar#rus43::OnMyMobDead" => house_ghost_jar_rus43_onmymobdead,
        "House Ghost Jar#rus43::OnTimer180000" => house_ghost_jar_rus43_ontimer180000,
        "Koshei#rus47::OnDisable" => koshei_rus47_ondisable,
        "Koshei#rus47::OnEnable" => koshei_rus47_onenable,
        "Koshei#rus47::OnInit" => koshei_rus47_oninit,
        "Koshei#rus47::OnTimer150000" => koshei_rus47_ontimer150000,
        "Koshei#rus47::OnTimer3000" => koshei_rus47_ontimer3000,
        "Koshei#rus47::OnTimer300000" => koshei_rus47_ontimer300000,
        "Koshei#rus47::OnTimer63000" => koshei_rus47_ontimer63000,
        "Lusalka#07russai_22::OnTouch_" => lusalka_07russai_22_ontouch,
        "Lusalka#rus23::OnDisable" => lusalka_rus23_ondisable,
        "Lusalka#rus23::OnEnable" => lusalka_rus23_onenable,
        "Lusalka#rus23::OnInit" => lusalka_rus23_oninit,
        "Lusalka#rus23::OnTimer300000" => lusalka_rus23_ontimer300000,
        "Mikhail#mos::OnEnable" => mikhail_mos_onenable,
        "Mikhail#mos::OnInit" => mikhail_mos_oninit,
        "Old Treasure Box#rus37::OnCall" => old_treasure_box_rus37_oncall,
        "Old Treasure Box#rus37::OnDisable" => old_treasure_box_rus37_ondisable,
        "Old Treasure Box#rus37::OnMyMobDead" => old_treasure_box_rus37_onmymobdead,
        "Old Treasure Box#rus37::OnTimer180000" => old_treasure_box_rus37_ontimer180000,
        "PTree#rusmain::OnDisable" => ptree_rusmain_ondisable,
        "PTree#rusmain::OnEnable" => ptree_rusmain_onenable,
        "PTree#rusmain::OnTimer60000" => ptree_rusmain_ontimer60000,
        "Pile of skeletons#Magic::OnTouch" => pile_of_skeletons_magic_ontouch,
        "Stone Furnace#rus28::OnInit" => stone_furnace_rus28_oninit,
        "Stone Furnace#rus28::OnMyMobDead" => stone_furnace_rus28_onmymobdead,
        "Stone Furnace#rus28::OnTimer300000" => stone_furnace_rus28_ontimer300000,
        "Wall#rus04::OnDisable" => wall_rus04_ondisable,
        "Wall#rus04::OnEnable" => wall_rus04_onenable,
        "Wall#rus04::OnInit" => wall_rus04_oninit,
        "Wall#rus04::OnMyMobDead" => wall_rus04_onmymobdead,
        "mos_rus#main::OnDisable" => mos_rus_main_ondisable,
        "mos_rus#main::OnEnable" => mos_rus_main_onenable,
        "mos_rus#main::OnInit" => mos_rus_main_oninit,
        "mos_rus#main::OnTimer120000" => mos_rus_main_ontimer120000,
    }
}
